### ISSUE TITLE
Exceptions of tracked dependency calls after upgrade Application Insights from 2.1.3 to 2.3.5

### ISSUE THREAD

**Issue by Yao544303** [microsoft/ApplicationInsights-node.js#1022]
After upgrade the Application Insights from 2.1.3 to 2.3.5, there is exceptions as the screen shot below.
<img width="1102" alt="Screen Shot 2022-10-18 at 10 41 35" src="https://user-images.githubusercontent.com/6713442/196324393-9ed90e98-ba16-4f08-a30d-8007b272a1ee.png">

All the  operation_Id and operation_Name of these exceptions are "". And the request near these exceptions are all success.

I have also check the log in container as below:
`2022-09-23T04:14:40.948894698Z MS_FUNCTION_AZURE_MONITOR_EVENT 2,xxxxxxxxx.azurewebsites.net,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'XXXXXX','roleInstance':'XXXXXX','message':'  TypeError [ERR_INVALID_URL]: Invalid URL: Get XXXXX','category':'Host.Function.Console','hostVersion':'3.13.1.0','hostInstanceId':'XXXXX','level':'Error','levelId':4,'processId':25}",09/23/2022 04:14:40`

I also found a similar issue here: https://github.com/Azure/azure-sdk-for-js/issues/17030
The error messages are same:
` TypeError [ERR_INVALID_URL]: Invalid URL: Azure.Storage.Blob.BlobClient-getProperties
      at onParseError (internal/url.js:258:9)
      at new URL (internal/url.js:334:5)
      at NodeClient.TelemetryClient.trackDependency (C:\_work\repro\node_modules\applicationinsights\Library\TelemetryClient.ts:129:36)
      at C:\_work\repro\node_modules\applicationinsights\AutoCollection\diagnostic-channel\azure-coretracing.sub.ts:33:28       
      at Array.forEach (<anonymous>)
      at C:\_work\repro\node_modules\applicationinsights\AutoCollection\diagnostic-channel\azure-coretracing.sub.ts:27:21       
      at clsBind (C:\_work\repro\node_modules\cls-hooked\context.js:172:17)
      at Function.CorrelationContextManager.runWithContext (C:\_work\repro\node_modules\applicationinsights\AutoCollection\CorrelationContextManager.ts:112:117)
      at OpenTelemetryScopeManagerWrapper.with (C:\_work\repro\node_modules\applicationinsights\AutoCollection\AsyncHooksScopeManager.ts:34:42)
      at subscriber (C:\_work\repro\node_modules\applicationinsights\AutoCollection\diagnostic-channel\azure-coretracing.sub.ts:26:31) {
    input: 'Azure.Storage.Blob.BlobClient-getProperties',
    code: 'ERR_INVALID_URL'`

Base Image
mcr.microsoft.com/azure-functions/node:4-node16-appservice

Dependencies
    "@azure/cosmos": "^3.17.0",
    "@azure/service-bus": "^7.7.0",
    "@azure/storage-queue": "^12.10.0",
    "@citrix/ccauth": "^6.0.1",
    "@sendgrid/mail": "^7.7.0",
    "@slack/web-api": "^6.7.2",
    "applicationinsights": "2.3.5",
    "axios": "^0.27.2",
    "bluebird": "^3.7.2",
    "date-fns": "^2.29.2",
    "ioredis": "^5.2.3",
    "js-base64": "^3.7.2",
    "knex": "^2.3.0",
    "lodash": "^4.17.21",
    "node-fetch": "^2.6.1",
    "objection": "^3.0.1",
    "objection-js-soft-delete": "^3.0.2",
    "redlock": "^4.2.0",
    "tedious": "^15.1.0",
    "uuid": "^9.0.0"

**Comment by hectorhdzg** [comment]
the actual URL could be helpful to understand why it fails to parse it, are you manually calling trackDependency or auto generated telemetry?

**Comment by Yao544303** [comment]
Greetings @hectorhdzg , I do manually calling the trackDependency, any changes in this API?

**Comment by hectorhdzg** [comment]
We updated URL parsing in 2.1.5, you can look at #793, this could cause trouble if native URL library finds the URL format you are sending in "data" parameter to be incorrect

**Comment by Yao544303** [comment]
@hectorhdzg Great!  This is the root cause.
