### ISSUE TITLE
Process CPU not formatted correctly

### ISSUE THREAD

**Issue by ramijarrar** [Microsoft/ApplicationInsights-node.js#103]
Looks like the portal expects a percent but gets a decimal (needs to be multiplied by 100):

![test](https://cloud.githubusercontent.com/assets/9661116/16664977/9654ec22-4493-11e6-864d-5c1349325318.png)

**Comment by ramijarrar** [comment]
Any update on this?

**Comment by OsvaldoRosado** [comment]
Fixed in 0.20
