### ISSUE TITLE
APPINSIGHTS_INSTRUMENTATIONKEY doesn't accept connection string?

### ISSUE THREAD

**Issue by iyerusad** [microsoft/ApplicationInsights-node.js#1052]
**Env:** NodeJs 16, Azure Function v4 via Windows Host, Run-From-Package (ReadOnly) mode, `"applicationinsights": "^2.3.6"`

----

I'm migrating to connecting Application Insights instance using **connection string** as per [Application Insights for NodeJS **ReadMe**](https://github.com/microsoft/ApplicationInsights-node.js#readme).

It seems setting the established environment variable `APPINSIGHTS_INSTRUMENTATIONKEY` with the value of **_connection string_** doesn't work as expected. I believe I started getting 500s with this change. Reverting back to instrumentation key worked as expected.

It was only when I added environment variable `APPLICATIONINSIGHTS_CONNECTION_STRING`, set its value to connection string, and updated my code to use new environment variable that the App Insights seemed to work as expected.

**Is this known behavior?** Previous users of Application Insights may be confused since easiest path seems like updating the established environment variable `APPINSIGHTS_INSTRUMENTATIONKEY` from <ins>instrumentation key</ins> to <ins>connection string</ins>.

**Comment by hectorhdzg** [comment]
@iyerusad you should not be using APPINSIGHTS_INSTRUMENTATIONKEY anymore, we are trying to deprecate that env variable, so using a connection string value there is not supported, is there any specific documentation that you saw that is causing confusion?

**Comment by iyerusad** [comment]
I would suggest the either the [Readme ](https://github.com/microsoft/ApplicationInsights-node.js#readme)or the [linked doc](https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings) includes something to effect of:

> `APPINSIGHTS_INSTRUMENTATIONKEY` does NOT accept connection string. Migrate to new variable `APPLICATIONINSIGHTS_CONNECTION_STRING`. Attempts to use connection string in existing `APPINSIGHTS_INSTRUMENTATIONKEY` environment variable will not work
