### ISSUE TITLE
Automatic dependency collection for @azure/arm- SDKs

### ISSUE THREAD

**Issue by DaniSchenk** [microsoft/ApplicationInsights-node.js#1055]
I'm struggling to enable automatic log collection for @azure/arm SDKs. Currently, I'm using `@azure/arm-keyvault`, `@azure/arm-network` and `@azure/arm-resources`. Is there some extra configuration needed? I thought HTTP logs are collected automatically.

`@microsoft/microsoft-graph-client`, `@azure/cosmos` and lots of other dependency logs are collected flawlessly. I use node 18LTS and tested 16LTS. `applicationinsights`  package version is `2.3.6`

```ts
appInsights
  .setup(configService.get("APPLICATIONINSIGHTS_CONNECTION_STRING"))
  .setDistributedTracingMode(DistributedTracingModes.AI_AND_W3C)
  .setAutoCollectConsole(false, false)
  .setAutoCollectExceptions(true)
  .setAutoCollectPerformance(true, true)
  .setAutoCollectPreAggregatedMetrics(true)
  .setAutoCollectHeartbeat(true)
  .setAutoCollectRequests(true)
  .setAutoCollectDependencies(true)
  .setAutoDependencyCorrelation(true)
  .setUseDiskRetryCaching(true)
  .setInternalLogging(false, true)
  .setSendLiveMetrics(true)
  .start();
````

In this screenshot one can see the missing dependency logs. The health requests takes 3 second and there are no correlated logs for the last 2 seconds, when arm SDKs are making requests. The logs are missing in the transactions list as well. 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/15052050/210841890-76049d7e-d8eb-4aac-a25d-da3e45ec538e.png">

**Comment by hectorhdzg** [comment]
@DaniSchenk we hook in to @azure/core-tracing used by Azure SDK packages, is possible the arm SDKs are not using this one, can you create an issue associated to this one in https://github.com/Azure/azure-sdk-for-js, we need someone in Azure SDK side to take a look at it.

**Comment by JacksonWeber** [comment]
Not related to application insights. Please create another issue in Azure SDK if this is still an issue. Thank you.
