### ISSUE TITLE
[BUG] Correlation context missing from trackTrace

### ISSUE THREAD

**Issue by sanderhahn** [microsoft/ApplicationInsights-node.js#1069]
**Description/Screenshot**

When running Application Insights locally `trackTrace` works fine and `appInsights.getCorrelationContext()` returns a context. However once the app is deployed on Azure the `trackTrace` will store TRACEs without operationId and `appInsights.getCorrelationContext()` returns null. This makes it difficult/impossible to correlate the traces with the operations in the performance view on Azure dashboard.

Running node locally on Windows:
![image](https://user-images.githubusercontent.com/775103/213437163-dcc35975-f237-40d0-9b50-5842354e6c53.png)

Running node on Azure in Linux:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/775103/213437590-6b09681f-af39-4822-9fd3-c2d89e0de2d1.png">

**Note the "0 Traces" because they are not associated with the operation, because the operationId is missing**

The trace is actually stored (without operationId):
<img width="871" alt="image" src="https://user-images.githubusercontent.com/775103/213438075-eb114cb8-0924-4eb0-80b9-be5e8eaea576.png">

**Steps to Reproduce**

 - OS/Browser: Azure App Service running on Linux (Node - 16-lts)
 - SDK Version [e.g. 22]: 2.4.0 
 - How you initialized the SDK:

```js
    const appInsights = require('applicationinsights');
    appInsights.setup(process.env.APPLICATIONINSIGHTS_CONNECTION_STRING).start();
    const appInsightsClient = appInsights.defaultClient;
```

**Expected behavior**

The behavior locally should match the behavior on Azure.

**Additional context**

Is the initialization different because the architecture is different? Have tried setting different configurations, but can't seem to find the root cause of this.

**Comment by hectorhdzg** [comment]
@sanderhahn running in Azure should not affect this in any way, can you provide more details about your app or provide some repro?, can you double check the trace is part of the request scope and check for asynchronous code related to it, if the trace is captured after the incoming request handling is done it could cause this problem.

**Comment by sanderhahn** [comment]
@hectorhdzg Have tried to produce a minimal repo that still shows the problem that I am experiencing. The code is available at: https://github.com/saberthooth/express-azure-appinsights Running locally still works as intended but on Azure the correlation of the trace and exception is missing.

**Comment by hectorhdzg** [comment]
@sanderhahn looks like pm2 is causing some trouble with Azure App Services way of handling the Node.js Apps, I don't know specific details but my understanding is that App Services will host a web app and inside will try to add customer one, I never used pm2 before so not sure how exactly works but removing it and running the serve.js directly solve the problem and telemetry is using correct correlation context in my tests.

**Comment by sanderhahn** [comment]
@hectorhdzg Thank you for your quick response :) Have removed pm2 but it still fails to correlate the `trackTrace` on Azure which still works locally. Thought maybe it has to do with the async handler, but also the non-async handler fails to correlate the operations. Any further help/tips are appreciated...

**Comment by akiarima** [comment]
I think I'm running into this same issue. I'm adding Application Insights to a NestJS app running in a container in a Linux App Service. When running locally, the events from `trackTrace` have the `operation_Name`, `operation_Id` and `operation_ParentId
` properties. After deploying to App Service, the trace events arrive without the properties.

**Comment by sanderhahn** [comment]
@hectorhdzg Have now removed all dependencies and upgraded to Node 18 (see https://github.com/saberthooth/express-azure-appinsights), however it still has the problem... so it seems to be a problem with Express/ApplicationInsights and Azure.

**Comment by sanderhahn** [comment]
@akiarima Thanks that is useful to know :)

**Comment by sanderhahn** [comment]
Also tried running my example on Windows and indeed it works as intended. So the issue/bug is related to running on Azure Linux.

**Comment by sanderhahn** [comment]
Okay think I figured it out... the order is important: first initialize express and then initialize application-insights. Now the traces are correctly associated :) Probably application-insights needs to mock some calls. Thanks for all your help!

```js
const app = express();
app.use(express.json());

appInsights.setup(process.env.APPLICATIONINSIGHTS_CONNECTION_STRING).start();
const appInsightsClient = appInsights.defaultClient;
```

**Comment by akiarima** [comment]
This is still an issue for me. Using exactly the same code in Linux App Service, the traces still arrive without correlation context: https://github.com/saberthooth/express-azure-appinsights

**Comment by gpehartz** [comment]
Same as @akiarima, not working.
