### ISSUE TITLE
node package v0.15.17 contains 34MB .ntvs_analysis.dat file...?

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/ApplicationInsights-node.js#107]
While packaging an update to my VS Code extension that uses application insights, I noticed that the VSIX ballooned from 884KB to 11MB.  After extracting it and having a look, there's a 34MB .ntvs_analysis.dat file under my extension's node_modules\applicationinsights folder.

I went ahead and installed the AI module on its own and that file came down in the same package.
It appears 15.17 was published two weeks ago (according to npmjs.com) but I don't see a corresponding version bump in the package.json file.  The previous version, 15.16, did not contain this file.

Is there a reason this file is included?

**Comment by jeffyoung** [comment]
I should also have mentioned, for a repro, compare the output between these two:

**npm install applicationinsights**

**npm install applicationinsights@0.15.16**

**Comment by kamilszostak** [comment]
Thank you for reporting. I'll publish a fix tomorrow morning.

**Comment by kamilszostak** [comment]
I've just published a new version [v0.15.18](https://github.com/Microsoft/ApplicationInsights-node.js/releases/tag/v0.15.18)
