### ISSUE TITLE
console.log of an object is overflows our application insights logs

### ISSUE THREAD

**Issue by bivas6** [microsoft/ApplicationInsights-node.js#1081]
Hi,

we recently upgrade applicationinsights-NodeJS to 2.4.1, and this print: https://github.com/microsoft/ApplicationInsights-node.js/blob/8b322090f52c2b34c7021a8aed5f7237712fc48f/Library/AuthorizationHandler.ts#L29
overflows our logs.
Can it be removed?

Thanks

**Comment by bivas6** [comment]
@jeremymeng

**Comment by jeremymeng** [comment]
oops sorry for the bug
