### ISSUE TITLE
[Beta] No way to suppress DiagnosticChannel logs

### ISSUE THREAD

**Issue by altinokdarici** [microsoft/ApplicationInsights-node.js#1097]
I see that DiagnosticChannel logs appear in the console as soon as `applicationinsights` imported. It's not possible to set log level before this operation hence no way to get rid of these messages.
 
```
ApplicationInsights:DiagnosticChannel [ 'Subscribed to bunyan events' ]
ApplicationInsights:DiagnosticChannel [ 'Subscribed to console events' ]
ApplicationInsights:DiagnosticChannel [ 'Subscribed to winston events' ]
```

We are using ApplicationInsights@beta in our CLI tool. The console logs are very important for us and we want to keep them under control.

**Comment by hectorhdzg** [comment]
@altinokdarici did you try using env variable to set log level?, this should allow you to set it up before the SDK is initialized, more info [here](https://github.com/microsoft/ApplicationInsights-node.js/tree/beta#self-diagnostics)

**Comment by altinokdarici** [comment]
Thanks @hectorhdzg, I didn't think it's a good practice set env var for this purpose in the app. I was thinking it is more for troubleshooting purposes. Settings env var definitely helped me. 

Thanks for the suggestion and changing the default log level.
