### ISSUE TITLE
Dependency issues for NodeJS v8 support

### ISSUE THREAD

**Issue by FrederikFrederiksenMancofi** [microsoft/ApplicationInsights-node.js#1121]
With the release of a new [@azure/core-rest-pipeline](https://www.npmjs.com/package/@azure/core-rest-pipeline/v/1.10.3) v1.10.3 and its dependence on [@azure/core-util](https://www.npmjs.com/package/@azure/core-util) v.1.3.0 I'm experiencing issues in my NodeJS v8.9.0 environment. The new version of core-util utilizes globalThis, which came with the release of node 12, and it results in the following error:
```
const uuidFunction = typeof ((_a = globalThis === null || globalThis === void 0 ? void 0 : globalThis.crypto) === null || _a === void 0 ? void 0 : _a.randomUUID) === "function"
                     ^
ReferenceError: globalThis is not defined

```

**Comment by tevoinea** [comment]
I hit this issue as well on Node 10. Downgrading to 2.4.0 worked for me (I was only looking for the dependency updates).

**Comment by HesselWellema** [comment]
Same issue. According to azure console the version is v14.20.0

**Comment by JamieMagee** [comment]
Locking `@azure/core-util` to `1.2.0` using [npm overrides][1] is a workaround for us.

[1]: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by hectorhdzg** [comment]
Locking down the dependency version for now, we will look into removing this dependency entirely if possible, will be releasing a new version of this package later today.
