### ISSUE TITLE
[Beta] Azure portal reporting lots of failed requests

### ISSUE THREAD

**Issue by mderriey** [microsoft/ApplicationInsights-node.js#1123]
Hi there 👋

In two separate applications running on Node.js v18, we're using the beta App Insights SDK (3.0.0-beta.4), and seeing a huge number of failed requests reported in the portal, although the applications receive very little traffic.

![image](https://user-images.githubusercontent.com/6102639/232410530-88542a20-b422-4753-a36d-176904db4032.png)

When querying the logs, however, only the "real" requests are surfaced:

![image](https://user-images.githubusercontent.com/6102639/232409424-7b171b06-dffe-43a3-b436-8429ea4a3d18.png)

I've also tried querying all the other "tables", and none of them returns such a big amount of data.

The only other place where I can find those requests is in the Metrics blade, when picking the Application Insights standard metrics namespace:

![image](https://user-images.githubusercontent.com/6102639/232412491-a87a9c43-48d7-4a9a-92ba-b371899ed823.png)

---

Here's how we set up the SDK in the application:

```ts
import { ExpressInstrumentation } from '@opentelemetry/instrumentation-express'
import { GraphQLInstrumentation } from '@opentelemetry/instrumentation-graphql'
import { WinstonInstrumentation } from '@opentelemetry/instrumentation-winston'
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http'
import { Resource } from '@opentelemetry/resources'
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions'
import { ApplicationInsightsClient, ApplicationInsightsConfig } from 'applicationinsights'

// Default attributes set on the OpenTelemetry traces
const resource = Resource.EMPTY
resource.attributes[SemanticResourceAttributes.SERVICE_NAME] = '<system-name>'
resource.attributes[SemanticResourceAttributes.SERVICE_NAMESPACE] = '<application-name>'

const config = new ApplicationInsightsConfig()
config.resource = resource

config.instrumentations.http = { enabled: false }
config.instrumentations.azureSdk = { enabled: true }
config.logInstrumentations.winston = { enabled: true }

const client = new ApplicationInsightsClient(config)

client.getTraceHandler().addInstrumentation(new HttpInstrumentation())
client.getTraceHandler().addInstrumentation(new ExpressInstrumentation())
client.getTraceHandler().addInstrumentation(new WinstonInstrumentation())
client.getTraceHandler().addInstrumentation(new GraphQLInstrumentation())

client.start()
```

On the App Service side, we've made sure that auto instrumentation is **not** set up (i.e. we don't have the `ApplicationInsightsAgent_EXTENSION_VERSION` app setting):

We've confirmed this by going to `https://<app-service-name>.scm.azurewebsites.net/applicationinsights`:

![image](https://user-images.githubusercontent.com/6102639/232411521-7e8ca1a5-9e36-41c7-a19c-27955e45a6fc.png)

We've tried looking in the App Service logs but couldn't find anything.

Any ideas? Please let me know if there are additional troubleshooting steps I can take to get to the bottom of this.

Thanks 😉

**Comment by mderriey** [comment]
I did some research on this today.

I first enabled the built-in HTTP instrumentation and removed the newer version that I had manually added from `@opentelemetry/instrumentation-http`.
This seems to fix the issue.

I then reverted to using the instrumentation directly from the `@opentelemetry/instrumentation-http` package, by replicating the `ignoreOutgoingRequestHook` from [the code in `util.ts`](https://github.com/microsoft/ApplicationInsights-node.js/blob/0bbe5aaccd03089277b674274da96167d3bdac22/src/shared/util/util.ts#L125-L138), and the errors started appearing again.

I wonder if there's an issue with having two instances of the same instrumentation, even if one of them is disabled?

I'd like to control which version of the HTTP instrumentation is used in the app, as it seems this space is moving rather quickly, but if we need to use the built-in one, it's not a blocker for now.

Thanks!

**Comment by mderriey** [comment]
Apologies, in the end, reverting to the built-in HTTP instrumentation didn't make the failed requests go away.

I thought it had for a moment, but that was a mistake on my part.

**Comment by hectorhdzg** [comment]
@mderriey can you try to disable standardMetrics? you can use config.enableAutoCollectStandardMetrics = false; Metrics then would be calculated using ingested data, is possible there is some bug with standardMetrics, we recently updated the logic significantly and those updates should be there in next release, but in the meantime give a try and let me know how it goes

**Comment by mderriey** [comment]
Hey @hectorhdzg, thanks for getting back to me.

Disabling auto-collection of standard metrics using `config.enableAutoCollectStandardMetrics = false` worked 🎉
I deployed the application 10-15 minutes ago and this is what the dashboard looks like:

![image](https://user-images.githubusercontent.com/6102639/233654651-9177006f-bafc-41bf-ba1d-f7437dbbe18e.png)

We'll keep it this way for now.

Can I ask that we leave this issue open until you ship a new beta version that fixes it?
The issue being closed will be a good signal for us to update.

Cheers!

**Comment by mderriey** [comment]
Hey there, I hope you're well.

Is `3.0.0-beta.6` supposed to fix this?
We've upgraded, but haven't yet reenabled `enableAutoCollectStandardMetrics`.

Happy to test it out if you think it should be fixed in the latest version.

Cheers.

**Comment by hectorhdzg** [comment]
@mderriey yes please re enable the feature and let us know if you have any issue

**Comment by mderriey** [comment]
Hi, we've reenabled `enableAutoCollectStandardMetrics`, and don't see a huge number of failed requests coming through the portal when using the `3.0.0-beta.6` SDK.

I think this means you can close this.

**Comment by hectorhdzg** [comment]
@mderriey  Thanks for checking on your side
