### ISSUE TITLE
[BETA] how to use TelemetryClient

### ISSUE THREAD

**Issue by floriankoch** [microsoft/ApplicationInsights-node.js#1147]
I try to use the TelemetryClient and the AvailabilityTelemetry with the BETA Version for this package
The client and types are in `src/shim` , how can this. be used?

(I use this with 2.6.0, does work without Problems)

**Comment by hectorhdzg** [comment]
@floriankoch shim is still work in progress, manual track APIs are still not fully functional in beta version, we will be adding that functionality soon

**Comment by jarpoole** [comment]
Any progress?
