### ISSUE TITLE
No way to set the telemetry context without a Request

### ISSUE THREAD

**Issue by chriskuech** [microsoft/ApplicationInsights-node.js#1156]
I can't find a way to set the `operationId` for a background worker process, or generally any scenario that does not have a `Request` associated with it. The closest appears to be `startOperation`, but there does not seem to be any construct for creating the `SpanContext`. I also can't find any mapping between OpenTelemetry concepts and App Insights concepts if I were to use the `SpanContext`.

How can I create a telemetry operation as a child of a given `operationId`?

**Comment by JacksonWeber** [comment]
@chriskuech The entire SDK is now build on top of OpenTelemetry. However, if you're familiar with OpenTelemetry concepts and don't require the 2.X SDK's API, the best package to use is [Azure Monitor OpenTelemetry](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/monitor/monitor-opentelemetry).

**Comment by chriskuech** [comment]
Thanks @JacksonWeber . I'm no longer using the package to confirm, so feel free to close if this is done
