### ISSUE TITLE
[Beta]  'enableAutoCollectHeartbeat' does not exist on type 'ApplicationInsightsConfig' in 3.0.0-beta.6

### ISSUE THREAD

**Issue by altinokdarici** [microsoft/ApplicationInsights-node.js#1164]
We have been using ^3.0.0-beta.5 for a while with the `config.enableAutoCollectHeartbeat = false;`. I realized that this property has been removed in the latest beta.6 version. 

I was wondering what's the new way of disabling AutoCollectHeartbeat?

cc: @hectorhdzg

**Comment by JacksonWeber** [comment]
Hi @altinokdarici, it's no longer necessary to disable `AutoCollectHeartbeat` as of beta.6 as it's been removed as of #1151.
