### ISSUE TITLE
With Node.JS SDK  I see customDimensions_roleInstance, not cloud_roleInstance

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-node.js#120]
Node.JS SDK writes role instance to device_roleInstance, which becomes customDimensions_roleInstance.
Expected: it should write cloud_roleInstance and cloud_roleName.

**Comment by kamilszostak** [comment]
I implemented a temporary fix #123 and I added a new issue to regenerate all types #122.
