### ISSUE TITLE
[Beta] Module size is too BIG

### ISSUE THREAD

**Issue by fakedob** [microsoft/ApplicationInsights-node.js#1240]
Hey guys, I have noticed that since I started using the beta, our dev environment, runing on Azure functions, started getting its cold start from 2 seconds, to 30+ seconds. Well, I didnt figured it out straight away and it did took me some time to realise that the new Beta depends on few node modules, specifically the `@opentelemetry` (as noted in the docs), that allocates around `36mb`'s os space.
My package.json has only:
```
"dependencies": {
    "@azure/functions": "^4.0.1",
    "applicationinsights": "^3.0.0-beta.10"
  },
```
And my node_modules are already `69.5mb`...

I understand this is still a beta, but are there any ways of reducing the package size, that you are aware? Are there plans to reduce the size, maybe distribute a compiled standalone version or other technique?

Thanks :)

**Comment by paed01** [comment]
Thumbs up for this. Did some evaluation between patches v2.9.2 and v2.9.3 and the increase in size is exponential. Some dependencies should be optional at best.

# v2.9.2

![v2 9 2](https://github.com/microsoft/ApplicationInsights-node.js/assets/4265753/bdcfa97d-081c-4162-9a45-bf954849b3e0)

# v2.9.3

![v2 9 3](https://github.com/microsoft/ApplicationInsights-node.js/assets/4265753/163669b8-513b-4e6c-828b-558cbffabf08)

One culprit seems to be the `@nevware21` packages.

```
npm list @nevware21/ts-async
`-- applicationinsights@2.9.3
  `-- @microsoft/applicationinsights-web-snippet@1.1.0
    `-- @microsoft/applicationinsights-common@3.1.0
      `-- @microsoft/applicationinsights-core-js@3.1.0
        `-- @nevware21/ts-async@0.4.0
```

Considering the extremely slow releases of nodejs apps in Azure Dev Ops, correlating to the number of files, this is getting very annoying.

**Comment by paed01** [comment]
Quite an increase:
https://bundlephobia.com/package/applicationinsights@3.0.0-beta.11

https://bundlephobia.com/package/@azure/functions

**Comment by MSNev** [comment]
We have created the following Application Insights Issue to address the inclusion of these dependencies, as they are not actually needed at runtime, once we rework the inclusion we will publish an updated v1.1.1 version.

- https://github.com/microsoft/ApplicationInsights-JS/issues/2277

**Comment by paed01** [comment]
Much better, now it is back to normal sizes.

# v2.9.4

![v2 9 4](https://github.com/microsoft/ApplicationInsights-node.js/assets/4265753/0a19b7c8-ac8d-4c40-aaed-00ab15a40712)


Thank you.

@fakedob I scanned the directories with [TreeSize free (Windows)](https://www.jam-software.com/treesize_free) after `npm prune --omit=dev`

**Comment by JacksonWeber** [comment]
Closing as the bundle sizes were reduced.
