### ISSUE TITLE
[beta] ETA for when 3.0.0 will be out

### ISSUE THREAD

**Issue by lapa182** [microsoft/ApplicationInsights-node.js#1247]
Hello!

We are using the beta version of the SDK in our Next.js application but we would like to know if there's an ETA of when the plugin will be out of the beta version. Right now there are a lot of warnings that don't impact using it, but impact our logs in the server and the readability of it, so hence this question.

That's all right if there's no ETA, thanks for the hard work in any case!

**Comment by hectorhdzg** [comment]
@lapa182 we are targeting march of next year to have this out of beta. Can you elaborate on the warnings you are seeing?

**Comment by lapa182** [comment]
Hi @hectorhdzg thanks for the reply! The warnings we are getting are the following:

```
ApplicationInsights:@azure/opentelemetry-instrumentation-azure-sdk [
  'Module @azure/core-tracing has been loaded before @azure/opentelemetry-instrumentation-azure-sdk so it might not work, please initialize it before requiring @azure/core-tracing'
]
ApplicationInsights:Invalid metric name: "\ASP.NET Applications(??APP_W3SVC_PROC??)\Request Execution Time". The metric name should be a ASCII string with a length no greater than 255 characters. []
ApplicationInsights:Invalid metric name: "\ASP.NET Applications(??APP_W3SVC_PROC??)\Requests/Sec". The metric name should be a ASCII string with a length no greater than 255 characters. []
ApplicationInsights:Invalid metric name: "\Process(??APP_WIN32_PROC??)\Private Bytes". The metric name should be a ASCII string with a length no greater than 255 characters. []
ApplicationInsights:Invalid metric name: "\Memory\Available Bytes". The metric name should be a ASCII string with a length no greater than 255 characters. []
ApplicationInsights:Invalid metric name: "\Processor(_Total)\% Processor Time". The metric name should be a ASCII string with a length no greater than 255 characters. []
ApplicationInsights:Invalid metric name: "\Process(??APP_WIN32_PROC??)\% Processor Time". The metric name should be a ASCII string with a length no greater than 255 characters. []
```

We are using applicantioninsights-node.js@beta in a Next.js application.

**Comment by hectorhdzg** [comment]
Thanks @lapa182, sorry for late reply, metric name warnings should be gone now, the one related to file protection are interesting ones, are you running your program with some account that have limited permissions in the OS?

**Comment by skhilliard** [comment]
Any update as to when this version will come out of beta?  Thanks!

**Comment by lapa182** [comment]
Sorry for the late reply @hectorhdzg ,the warnings are gone. Quick question regarding beta, I've noticed it's out, because there's a difference in implementation but there's also a package called https://www.npmjs.com/package/@azure/monitor-opentelemetry, which one should we use with OpenTelemetry?

**Comment by JacksonWeber** [comment]
Closing this as Application Insights 3.0.0 SDK was released last week.
