### ISSUE TITLE
connect timeout

### ISSUE THREAD

**Issue by torloneg** [Microsoft/ApplicationInsights-node.js#128]
the service does not have access to Azure Insight.
I get  this error

```
ApplicationInsights:Sender [ { [Error: connect ETIMEDOUT 40.114.241.141:443]
                  (err):     code: 'ETIMEDOUT',
                  (err):     errno: 'ETIMEDOUT',
                  (err):     syscall: 'connect',
                  (err):     address: '40.114.241.141',
                  (err):     port: 443 } ]

```

can set the proxy ??

**Comment by kamilszostak** [comment]
Are you still getting this error? This looks like an IP of AppInsights West Europe endpoint (URL: https://dc.services.visualstudio.com/v2/track). The endpoint is healthy and available, so you should not get timeouts. 

The latest NodeJS SDK version (v.0.16.0) is using https by default - [more](https://github.com/Microsoft/ApplicationInsights-Announcements/issues/14). Is this affecting your network in any way?

**Comment by torloneg** [comment]
yes, I still have the problem.
I think from my machines can not login without setting the proxy

**Comment by kamilszostak** [comment]
The Node.js SDK is using [https.request](https://nodejs.org/api/https.html#https_https_request_options_callback) to send telemetry data. I'm not sure how to set the proxy, but the function takes an `option` parameter. So if it's just a matter of changing  a hostName, port or path you can change the [endpointUrl](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Config.ts#L22) in the Config object.

**Comment by hectoralicea** [comment]
I'm having similar issues.  Our VNET is locked down and any internet access must go through a Corporate Proxy (except for anything thats within Azure itself).  Should I put 40.84.189.107 in my proxy exception list? 
ApplicationInsights:Sender [ { [Error: connect ETIMEDOUT 40.84.189.107:80]
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.84.189.107',
    port: 80 } ]

**Comment by hectoralicea** [comment]
Can I just shutdown ApplicationInsights:Sender on a Resource Group basis?

**Comment by OsvaldoRosado** [comment]
There is documentation here about IPs that must be addressable for Application Insights to work: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-ip-addresses
If these are blocked by your firewall, please add exceptions.

This list may change from time to time. I've opened enhancement #246 to track adding support for specifying an http proxy.
