### ISSUE TITLE
Display console kogs

### ISSUE THREAD

**Issue by olawalejuwonm** [microsoft/ApplicationInsights-node.js#1291]
Can this insight display console.logs from the application?

**Comment by JacksonWeber** [comment]
@olawalejuwonm Yes, absolutely. You can use the `.setAutoCollectConsole(true, true)` configuration option to receive logs telemetry from your `console.log` statements. Note that by default, the SDK will only collect `winston` and `bunyan` third-party logs, so make sure to set the configuration option mentioned above.

**Comment by olawalejuwonm** [comment]
Thank you. Is this an open source tool? Or I need to pay to use it?

**Comment by JacksonWeber** [comment]
@olawalejuwonm I invite you to read our software license for the SDK here: https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/LICENSE. 

If you're looking to collect output telemetry from the SDK in Azure and want to determine pricing structure, that information is available here: https://azure.microsoft.com/en-us/pricing/details/monitor/.
