### ISSUE TITLE
[Beta] - Winston log level not respected by SDK

### ISSUE THREAD

**Issue by mderriey** [microsoft/ApplicationInsights-node.js#1294]
Hi there

We're using the SDK and using the Winston integration.
We noticed, while the Winston logger level is set to info, that we get verbose logs emitted to App Insights.

We think we tracked this down to diagnostic-channel-publishers@1.0.7 not respecting the logger level and using the "max" level possible, in our case silly.

We saw you shipped diagnostic-channel-publishers@1.0.8 which seems to fix this issue.

Happy to open a PR if you agree this should be enough to correct this.

Cheers

**Comment by JacksonWeber** [comment]
@mderriey We're planning to move to an OpenTelemetry instrumentation for Winston soon and move away from the diagnostic-channel-publishers library. This issue should be resolved at that point. Thank you for the heads up!
