### ISSUE TITLE
Importing Application Insights library in ES6 module import format doesn't work

### ISSUE THREAD

**Issue by c-amunir** [microsoft/ApplicationInsights-node.js#1311]
I am trying to import application insights into a project that uses ES6.

I have the following code:

``` javascript
import * as appInsights from 'applicationinsights';

const connectionString = '[CONNECTION_STRING]'
appInsights.setup(connectionString).start();
appInsights.defaultClient.trackEvent({
   name: 'test'
});

appInsights.defaultClient.flush();

export default appInsights;
```

Here's the error I am getting:
``` TypeError: Cannot read properties of undefined (reading 'trackEvent') ```

I am using node.js v18.20.2 (LTS).

I tried to use applicationinsights v3.0.0 but I was getting the same issues as [Issue 1310](https://github.com/microsoft/ApplicationInsights-node.js/issues/1310)

I ended up having to do  2 fixes:
1) Downgrade to applicationinsights v.2.9.5
2) Do the following code snippet:

``` javascript
import {createRequire} from 'module';
const require = createRequire(import.meta.url);

let appInsights = require('applicationinsights');
const connectionString = '[CONNECTION_STRING]';
appInsights.setup(connectionString).start();
appInsights.defaultClient.trackEvent({
   name: 'test'
});

appInsights.defaultClient.flush();

export default appInsights;
```

Optimally, I would be using the ES6 import module and not ``` require ```, as well as be on v3.0.0 of Application Insights. Though being on v2.9.5 is okay as well for the time being while other issues get resolved.

Any guidance would be much appreciated.

Thanks

**Comment by JacksonWeber** [comment]
@c-amunir Thank you for bringing this to my attention. I've tested the 3.0.1 release with import syntax and it should work. Please give the updated package a try and let me know. Thank you!

**Comment by max-holland** [comment]
I've got a similar issue but with trackTrace. Running on version 2.9.5 I have no issues, but running on 3.0.1 I get the following:

```
node_modules/applicationinsights/src/shim/telemetryClient.ts:115
        this._logApi.trackTrace(telemetry);
                     ^


TypeError: Cannot read properties of undefined (reading 'trackTrace')
    at TelemetryClient.trackTrace (node_modules/applicationinsights/src/shim/telemetryClient.ts:115:22)
    at enable (./server/modules/appinsights/index.ts:18:33)
    at app (./server.ts:58:21)
    at run (./server.ts:104:18)
    at Module.69787 (./server.ts:118:3)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at <anonymous> (./webpack/bootstrap:36:1)
    at Function.__webpack_require__.O (./webpack/runtime/chunk%20loaded:23:1)
    at __webpack_require__.x (./webpack/bootstrap:37:1)
    at Function.__webpack_require__.x (./webpack/runtime/startup%20chunk%20dependencies:4:1)

Node.js v20.11.0
A server error has occurred.
node exited with 1 code.
```
The code:
```
// const appInsights = require('applicationinsights'); <-- Also get the same error importing this way.
import * as appInsights from 'applicationinsights';

appInsights.setup(config.get('AppInsightsInstrumentationKey')).setSendLiveMetrics(true).start();

appInsights.defaultClient.context.tags[appInsights.defaultClient.context.keys.cloudRole] = 'app-frontend';
appInsights.defaultClient.trackTrace({
  message: 'App insights activated',
});
```

**Comment by c-amunir** [comment]
Hello @JacksonWeber,

Thanks for the prompt response. the 3.0.1 release did fix the issue with the import syntax.

I appreciate the prompt response!

**Comment by JacksonWeber** [comment]
Closing as the issue was resolved with the latest release.
