### ISSUE TITLE
Invalid metric name: The metric name should be a ASCII string with a length no greater than 255 characters.

### ISSUE THREAD

**Issue by JCBauza** [microsoft/ApplicationInsights-node.js#1315]
I get the following error message:

Invalid metric name: "Global Pongs (snapshot)". The metric name should be a ASCII string with a length no greater than 255 characters. []

However, I believe the string contains only ASCII characters. Tried removing the () and still the same:

Invalid metric name: "Global Pongs Snapshot". The metric name should be a ASCII string with a length no greater than 255 characters. []

This happens when I track a Metric with the following code:
        appInsights.defaultClient.insightsClient().trackMetric({ name: "Global Pongs Snapshot", value: snapshot.length });

Any ideas what could be the issue?

**Comment by JacksonWeber** [comment]
@JCBauza You should be able to resolve this issue by removing any spaces in your metric name. Possibly something like "Global_Pongs_Snapshot". Please let me know if that change works for you. Thanks!

**Comment by JCBauza** [comment]
Thanks, it worked!
