### ISSUE TITLE
@azure/opentelemetry-instrumentation-azure-sdk [   'Module @azure/core-tracing has been loaded before @azure/opentelemetry-instrumentation-azure-sdk so it might not work, please initialize it before requiring @azure/core-tracing' ]

### ISSUE THREAD

**Issue by JCBauza** [microsoft/ApplicationInsights-node.js#1316]
Just upgraded to version 3.0.1 from 2.x.x and I get this warning at the beginning of my output:

@azure/opentelemetry-instrumentation-azure-sdk [
  'Module @azure/core-tracing has been loaded before @azure/opentelemetry-instrumentation-azure-sdk so it might not work, please initialize it before requiring @azure/core-tracing'
]

**Comment by JacksonWeber** [comment]
@JCBauza please refer to https://github.com/microsoft/ApplicationInsights-node.js/issues/1107. Long story short, this warning wont impact functionality. If you want to ignore this, that's also discussed in the discussion I've linked.

**Comment by JCBauza** [comment]
Awesome, good to know. Thanks!
