### ISSUE TITLE
trackTrace no longer working since this week

### ISSUE THREAD

**Issue by ypan0** [microsoft/ApplicationInsights-node.js#1317]
we are using the package on azure function, the package version is 2.7.0
it started not logging any trace log this week, we have tried upgrading to v2.9.5 and v3.0.1, none of them worked
the way we use it is

```
const appInsights = require('applicationinsights');

appInsights.setup().start();

client.trackTrace({
        message,
        properties: customProperties,
        severityLevel
    });
```
any advice? or any thought why it stopped working this week?

**Comment by JacksonWeber** [comment]
@ypan0 There's no reason that `trackTrace` shouldn't work specifically. I'd make sure that the Azure Function isn't exiting before telemetry can be exported first.
