### ISSUE TITLE
TrackEvent no longer reporting Measurements

### ISSUE THREAD

**Issue by JCBauza** [microsoft/ApplicationInsights-node.js#1318]
Hi,

If I do the following:

// Set up some properties and metrics:
var properties = {"name": "SomeRandomName"};
var metrics = {"MetricA": 10, "MetricB": 5};

// Send the event:
instanceClient.trackEvent({name: "TestEvent", properties: properties, measurements: metrics});

I can see the event with the correct name and properties... but the measurements/metrics I pass get completely dropped. My dashboards are coming back empty. Any ideas what changed?

**Comment by JacksonWeber** [comment]
@JCBauza Thank you for reporting this issue. It'll be resolved by https://github.com/microsoft/ApplicationInsights-node.js/pull/1319. For now, using version 2.X SDK or recording related metrics separately should be valid solutions.

**Comment by JCBauza** [comment]
Thank you. Are those metrics going to be related to the event that sends them as before? I’m asking because the properties of the event in my case are used to filter those metrics, or more specifically, I use them as tags and on the graphs the values are grouped by those tags.

**Comment by JacksonWeber** [comment]
@JCBauza Yes, that's correct. They should operate in the same way they have in the past and will be available upon the next release of the Azure Monitor Exporter in the PR mentioned above.

**Comment by JacksonWeber** [comment]
@JCBauza Let me know if this has resolved your issue, thanks!

**Comment by JacksonWeber** [comment]
Closing as fix has been merged. Feel free to reopen if you have follow up questions.
