### ISSUE TITLE
"applicationinsights 3.1.0" is not compatible with the "@azure/functions 4.5.0"

### ISSUE THREAD

**Issue by balasphilip** [microsoft/ApplicationInsights-node.js#1332]
Hello team,

I receive typescript compilation errors when trying to start my function locally. Please see the screenshots with the examples:

<img width="1707" alt="Screenshot at May 22 16-51-14" src="https://github.com/microsoft/ApplicationInsights-node.js/assets/8319467/88005f39-07a4-4a08-b541-5de4855f7d6f">

<img width="410" alt="Screenshot at May 22 16-51-23" src="https://github.com/microsoft/ApplicationInsights-node.js/assets/8319467/b3eff3b0-9657-4338-b867-3e9c173b8000">

<img width="764" alt="Screenshot at May 22 16-55-42" src="https://github.com/microsoft/ApplicationInsights-node.js/assets/8319467/2e74ac1d-75ef-4467-bf14-1f3e54f95385">

**Comment by JacksonWeber** [comment]
This package is not currently compatible with Azure Functions version 4.5.0. We have upstream support in progress in OpenTelemetry, and will update the thread here #1299.

**Comment by balasphilip** [comment]
Thank you for your answer. 

This might be out of scope for this conversation, however, can you maybe point me out where to start if I want distributed tracing for my system? I use Azure Function Apps (HTTP, serviceBusTopic, and serviceBusQueue triggers), and Service Bus with both topics and queues respectively. I use Node.js runtime for Function Apps. 

Documentation seems quite vague to me. There is a lot of information about monitoring, application insights, opentelemetry, etc., however it is hard to say where to start.

So first I tried to add `applicationinsights` npm package (basically the initial topic of this issue).

Then I tried `@azure/monitor-opentelemetry` (from the Docs: "_The Distro enables [automatic](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify#automatic-data-collection) telemetry by including OpenTelemetry instrumentation libraries for collecting traces, metrics, logs, and exceptions, and allows collecting [custom](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify#collect-custom-telemetry) telemetry._"), but it looks to me that it does nothing since basic metrics and logs are being streamed by Function App even without that package. Moreover, I'm not quite sure this distro is suitable for Function Apps.

Then I found [this post](https://stackoverflow.com/questions/71871827/proper-way-of-tracing-distributed-requests-through-azure-function-apps) on StackOverflow which looks like a semi-answered.

So hoping for some helping hand here.

Thanks!

**Comment by hectorhdzg** [comment]
This will be available in next release, related to trace-id not being shared in Service Bus and Azure Functions is better to track separately in https://github.com/Azure/azure-sdk-for-js repo so Azure SDK folks could be involved as well.
