### ISSUE TITLE
Newly Installed version of V2.X On Node 14 Errors with `node:os` import error; Docs Suggest v2.X supports Node 14

### ISSUE THREAD

**Issue by epicstar** [microsoft/ApplicationInsights-node.js#1356]
- **Package Version**: v2.4.2 -v2.9.5 (I also tried 3.1.0)
- **Operating system**: BrightSign OS (offshoot Linux of some sort)
- [x] **nodejs**
    - **version**: 14.17.6
- [ ] **browser**
    - **name/version**: Chromium (Unknown Version) 
- [x] **typescript**
    - **version**: 5.5.2
- Is the bug related to **documentation** in
  - [x] README.md
  - [x] source code documentation
  - [x] SDK API docs on https://docs.microsoft.com

**Describe the bug**

[applicationinsights](https://www.npmjs.com/package/applicationinsights) v2.4.2 to v2.9.5 do not seem to run on Node 14 despite the [README](https://github.com/microsoft/ApplicationInsights-node.js/tree/2.x?tab=readme-ov-file#supported-nodejs-versions) suggesting so.

This is the error I get when running my project running on Node 14.17.6:

```
[ 33.125] [ERROR] [source internal/modules/cjs/loader.js:899]: Uncaught Error: Cannot find module 'node:os'
```

The easy cop-out answer is to just simply update our Node versions on our BrightSign players, but I have 0 control over that as it's a hard technical constraint on BrightSign's side (I can't control what version of Node they have in their OS).

This actually started for me when trying to run @azure/opentelemetry-monitor with the same error. I created an issue then was told to try applicationinsights-nodejs v2: https://github.com/Azure/azure-sdk-for-js/issues/30217#issuecomment-2197674361

So I've tried from v2.9.5 all the way down to v2.4.2, and I still get the same issue. I know that `node:xx` is not a direct dependency of this library. I tried deleting my yarn.lock then `yarn install`ing everything and still got the same error. 

My assumption is that the problem is somewhere around a transitive dependency of the library and yarn getting a version that's too updated. I probably just have to create an version override command, but there's around 22 transitive dependencies, so I'm not exactly sure which one(s) is(are) causing the issue.

If you guys could help me figure this out, that would be cool. Thank you!

**Comment by hectorhdzg** [comment]
@epicstar are you using a bundler in your project?, I can run the latest v2 release(2.9.5) with no issues in Node.js 14.

**Comment by epicstar** [comment]
I'm using webpack 5.92.1

**Comment by epicstar** [comment]
Upon reading more into Brightsign's NodeJS implementation. I'm not exactly sure if they expose the full API of it...

https://brightsign.atlassian.net/wiki/spaces/DOC/pages/370672896/roHtmlWidget#Initialization-Parameters

More likely they use Chromium and have implemented some methods or used existing polyfills to at least get some basic NodeJS working..

I'm still willing to keep at trying to get this library working, but I've actually been stuck on this for 2 weeks which at a business perspective isn't feasible when usually it would take 5 mins to get the library running (RIP me).

I am using the web version of the API instead which works: https://github.com/microsoft/ApplicationInsights-JS

So I'll be using this one in the meantime... Apologies all.

**Comment by epicstar** [comment]
That's fair... We can close it. I think you're right it's something in the bundling process.
