### ISSUE TITLE
Upgrading 3.2.1 > 3.2.2 caused "Cannot find module '@azure/functions'"

### ISSUE THREAD

**Issue by max-holland** [microsoft/ApplicationInsights-node.js#1373]
Upgrading from version 3.2.1 to 3.2.2 causes the bellow issue when we try to compile our code. 

![image](https://github.com/user-attachments/assets/3c4e1761-96b5-495a-9697-c4ecfa60e0aa)

Not sure if it's just our repo running into the issue. Looking at our lock file, it does look like the @azure/functions package has been removed. The only reference to @azure/functions I can see in our lock file is that it's a dependendacy of @azure/monitor-opentelemetry 1.6.0, but looks to have been removed with the upgrade to 1.7.0 .

Any help would be much appreciated :)

**Comment by JacksonWeber** [comment]
@max-holland I haven't been able to run into this issue. 1.7.0 of @azure/monitor-opentelemetry does also have a dependency on the @azure/functions package https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/monitor/monitor-opentelemetry/package.json#L67. We did add a dependency on two versions of @azure/functions to maintain support for the v3 programming model. Maybe this is causing issues with your lock file?

**Comment by max-holland** [comment]
Morning @JacksonWeber, thanks for getting back to me. It looks like it's where it's moved from a dependency in 1.6.0 to a dev dependency in 1.7.0 we no longer get the install.

Here's the open PR with the update: https://github.com/hmcts/opal-frontend/pull/769/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de

**Comment by JacksonWeber** [comment]
@max-holland In any Azure Functions app, @azure/functions package should be a dependency and when developing running `npm i` should pull the needed @azure/functions packages, so typically I wouldn't expect `applicationinsights` to have trouble finding the functions package to use the appropriate types.

I've also tested using the 3.2.2 ApplicationInsights package without any explicit dependency on @azure/functions and haven't run into the same build issues.

Can you give me more information about your project so I can try to determine why you might be getting this issue?

**Comment by max-holland** [comment]
@JacksonWeber So we're running an Angular SSR(18.2.2) application and we are using Yarn(4.4.1) instead of npm. We're using application insights on the expressjs side of things. The previous version of applicationinsights works OK.

Link to the project: https://github.com/hmcts/opal-frontend
Link to the PR with the update: https://github.com/hmcts/opal-frontend/pull/769

I have deleted the node_modules + yarn.lock to do a completely fresh install, and still seem to run into the issue. We haven't done anything non standard to install application insights.

**Comment by JacksonWeber** [comment]
@max-holland the above PR should resolve your issue. It reclassifies @azure/functions as a full dependency in applicationInsights.

**Comment by max-holland** [comment]
@JacksonWeber Nice one, will let you know the outcome once it's available for us to install. Thank you so much for the help :)

**Comment by max-holland** [comment]
Hi @JacksonWeber! Is this looking to be released soon?

**Comment by JacksonWeber** [comment]
@max-holland Releaased as a part of 3.3.0 - https://github.com/microsoft/ApplicationInsights-node.js/releases/tag/3.3.0

**Comment by dominikx96** [comment]
I have a problem with this change using pnpm:
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '@azure/functions@3.5.1' in pnpm-lock.yaml

**Comment by JacksonWeber** [comment]
@dominikx96 Seems like it might be an issue with the update to the dependency since we now import the old @azure/functions version under an aliased name. Have you completely cleared and rebuilt your dependencies after updating to 3.3.0?

**Comment by dominikx96** [comment]
I rebuilt package-lock, the issue was during heroku build so it might be a cache there. I can test clear everything and try again. I don't have similar issues in my macbook.
