### ISSUE TITLE
BUG - Request telemetry is not collected

### ISSUE THREAD

**Issue by zhiyuanliang-ms** [microsoft/ApplicationInsights-node.js#1375]
- Package Name: applicationinsights
- Package Version: 3.2.2
- Node.js Version: 20
- Bug description: No request telemetry when using `applicationinsights` in ESM code

The following cjs code works as expected. I can see live metrics and a custom event in the app insights. More importantly, I can see request telemetry if I sent get request to `localhost:5000` because `AutoCollectRequest` config is enabled by default. ([ref](https://learn.microsoft.com/azure/azure-monitor/app/nodejs#sdk-configuration)).

``` js
const appInsights = require("applicationinsights");

appInsights.setup(connectionString)
    .setSendLiveMetrics(true)
    .start();

appInsights.defaultClient.trackEvent({name: "test"})

const express = require('express');
const app = express();
const port = 5000;


app.get('/', (req, res) => {
  const targetingId = req.headers['targetingid'];
  res.send(`id: ${targetingId}`);
});

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
```

However, if I rewrite the above code in ESM style as below:

``` js
import applicationInsights from "applicationinsights"; // default import (module.default)
applicationInsights.setup(connectionString)
  .setSendLiveMetrics(true)
  .start();

applicationInsights.defaultClient.trackEvent({name: "test"})

import express from 'express';

const app = express();
const port = 5000;

app.get('/', (req, res) => {
  const targetingId = req.headers['targetingid'];
  res.send(`id: ${targetingId}`);
});

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
```
I still can see some of the live metrics (e.g. CPU usage) and the custom event (except for the warning log mentioned in #1324).

**BUT, I CANNOT see any request telemetry** in application insights. After debugging for a while, I found that `applicationinsights` will create a default `TelemetryClient` and while initializing it, `applicationinsights` will call `UseAzureMonitor` method provided by `@azure/monitor-opentelemetry` and it seems like azure monitor is supposed to automatically collect all http request. But it turns out to do nothing when `applicationinsights` is imported in ESM.

I also tested `applicationinsights` v2 (classic version). Everything works as expected in ESM when I used `applicationinsights` 2.9.x. The `applicationinsights` v3 is built on azure opentelemetry monitor. I guess it is the root cause of the bug.

I also noticed that #1354 called out that `applicationinsights` package is incompatible with ESM module system. ESM is the trending of JavaScript world. IMO, ESM scenario is more important than CJS scenario. Could you help investigate this bug? Any clue or information will be appreciated.

**Comment by JacksonWeber** [comment]
@zhiyuanliang-ms This is actually related to a larger issue in OpenTelemetry-JS of loading the @opentelemetry/instrumentation package _before_ the instrumentation libraries that need to be instrumented. The current solution for support auto-instrumentation with OpenTelemetry also fixes the issue with this package. The current solution is documented [here](https://github.com/open-telemetry/opentelemetry-js/blob/main/doc/esm-support.md) in the OpenTelemetry project.

Please let me know if setting the `NODE_OPTIONS` with the appropriate loader hook works for you.

**Comment by JacksonWeber** [comment]
Closing based on the above solution working.

**Comment by olli-quartal** [comment]
Hi @JacksonWeber,

The solution might probably work, or then we just use an older version to avoid hacking with Node experimental features....

However, my point is that for someone coming from outside - just expecting to use a Microsoft product with Microsoft maintained library - such a behavior is extremely unexpected. Normally, you would expect ESM modules to just work. And you would expect such a simple thing as adding logging to a web site just work by following instructions. Now it just fails and you need to spend hours searching what is wrong (first you look at the configurations, then permissions etc.). Finally finding an answer from a bug report that is already closed and there is the link to open telemetry web site.

So to avoid this, there should be a clear and visible warning on the documentation page that this is now the current beavior / limitation for ESM. And here is the link how to hack around it using experimental Node features.
