### ISSUE TITLE
Undeclared dependency “undici”

### ISSUE THREAD

**Issue by CarbonCollins** [microsoft/ApplicationInsights-node.js#1386]
Hi,

i’m using Yarn pnp and after updating the 3.3.0 today O got an error that it could not resolve the “undici” package.

checking the source here it is imported in src/shim/correlationContextManager but is not defined in the package.json file and thus leading to yarn pnp disallowing our build to happen as we don’t allow undefined dependencies in our build.

**Comment by hectorhdzg** [comment]
@CarbonCollins thanks for letting us know, most likely this was added by mistake by some IntelliSense.
