### ISSUE TITLE
`ai.operation.name` not available when deployed to Azure

### ISSUE THREAD

**Issue by lcssanches** [microsoft/ApplicationInsights-node.js#1388]
I have a need to update the operation name in a NodeJS API using express. Our API is using path parameter and we can't get any useful metric from Application Insights dashboard because each request with different ID has a different operation name, hence data is not aggregated correctly.

Locally (docker and node index.js), I can run this successfully, with it replacing what I need in the operation name.

But when this is deployed Azure App Service, neither the envolope or context have the relevant properties.

I am using `2.9.6`.

```js
appInsights.defaultClient.addTelemetryProcessor(applyOperationNamePattern);
/* ... */
function applyOperationNamePattern (envelope, context) {

    console.log({ context, envelope: JSON.stringify(envelope) });

    if (envelope.data.baseType === 'RequestData') {
      const request = context?.['http.ServerRequest'] ?? null;
      const operationName = envelope.tags['ai.operation.name'];

      if (!operationName) {
        operationName = request.originalMethod.toUpperCase() + ' ' + request.originalUrl;
      }

      envelope.tags['ai.operation.name'] = operationName
        .replace(uuidLikeRegex, '[id]')
        .replace(numberRegex, '[id]');

      console.log('operationName', envelope.tags['ai.operation.name']);

    }
    return true;
}
```

**Comment by JacksonWeber** [comment]
Hi @lcssanches I wasn't able to reproduce your issue when testing with a very basic telemetry processor to modify the operation.name in both a local and App Service environment.

If you use a TelemetryProcessor like
```
function applyOperationName (envelope, context) {
    console.log({ context, envelope: JSON.stringify(envelope) });
    envelope.tags['ai.operation.name'] = "test";
    return true;
}
```
In the App Service environment are you still observing no change to the operation name field in your reported telemetry?

**Comment by lcssanches** [comment]
Yes @JacksonWeber, this still isn't working, but now I realize that the issue is that the request telemetry is not going through the processor, they are all `MetricData`, similar to this:

```json
{
  "context": { "correlationContext": null },
  "envelope": {
    "ver": 1,
    "sampleRate": 100,
    "tags": {
      "ai.application.ver": "1.0.0",
      "ai.device.id": "",
      "ai.cloud.roleInstance": "----84a9fd885a2fc7f8204167c0b343b",
      "ai.device.osVersion": "Linux 5.15.158.2-1.cm2",
      "ai.cloud.role": "test-api",
      "ai.device.osArchitecture": "x64",
      "ai.device.osPlatform": "linux",
      "ai.internal.sdkVersion": "alm_node:2.9.6"
    },
    "data": {
      "baseType": "MetricData",
      "baseData": {
        "ver": 2,
        "metrics": [
          {
            "kind": 1,
            "count": 1,
            "max": 5.478770416274695,
            "min": 5.478770416274695,
            "name": "\\\\Process(??APP_WIN32_PROC??)\\\\% Processor Time",
            "stdDev": 0,
            "value": 5.478770416274695
          }
        ],
        "properties": {}
      }
    },
    "iKey": "475a59dd-0000-0000-0000-7d54ceaeffa1",
    "name": "Microsoft.ApplicationInsights.475a59dd0000000000007d54ceaeffa1.Metric",
    "time": "2024-09-25T12:02:13.352Z"
  }
}
```

For what matters, this is the setup code, pretty simple:
```js
  appInsights.setup().start();
  appInsights.defaultClient.addTelemetryProcessor(applyOperationNamePattern);
  console.log('App Insights is enabled');
```

**Comment by JacksonWeber** [comment]
@lcssanches Just to make sure I understand correctly, you're just trying to apply an `ai.operation.name` tag to all of your custom metrics? From my testing I'm able to use the check above for `if (envelope.data.baseType === 'MetricData')` in an App Service environment and apply the `ai.operation.name` tag to custom metrics successfully.

**Comment by lcssanches** [comment]
> @lcssanches Just to make sure I understand correctly, you're just trying to apply an `ai.operation.name` tag to all of your custom metrics? From my testing I'm able to use the check above for `if (envelope.data.baseType === 'MetricData')` in an App Service environment and apply the `ai.operation.name` tag to custom metrics successfully.

No, I want to customize the **request** operation names.

If my express server has a route `/user/:userId/notes/:noteId/pdf`, app insights is create operation names like `GET /user/1111/notes/2222/pdf`, `GET /user/3333/notes/4444/pdf`. What I want is customize the operation name replacing the IDs, in a way that all requests to this endpoint have the same operation name: `GET /user/[id]/notes/[id]/pdf`. Similar to what happens with Net 6+ APIs out of the box.

This is the processor that I executed in my previous test that only showed MetricData
```js
applyOperationNamePattern: function (envelope, context) {
    console.log({ context, envelope: JSON.stringify(envelope) });
    const operationName = envelope.tags['ai.operation.name'];
    if (typeof operationName !== 'string') return true;

    envelope.tags['ai.operation.name'] = operationName
      .replace(uuidLikeRegex, '[id]')
      .replace(numberRegex, '[id]');

    return true;
}
```

**Comment by JacksonWeber** [comment]
@lcssanches I see, I misunderstood what you meant about `MetricData` going through the processor. So, what's really happening is that you have a telemetry processor you _want_ to apply to request telemetry, however, you're finding that only `MetricData` is being processed and therefore the operation.name value remains incorrect on the request telemetry you're receiving.

**Comment by lcssanches** [comment]
@JacksonWeber exactly! 👍

**Comment by JacksonWeber** [comment]
@lcssanches Do you have an example of one of the requests you expect to be collected? I would expect that any telemetry would get passed through that processor before being filtered by your `if` case.

**Comment by lcssanches** [comment]
@JacksonWeber , sure.

Locally I get this `envelope` in the processor function.

```json
{
  "ver": 1,
  "sampleRate": 100,
  "tags": {
    "ai.application.ver": "1.0.0",
    "ai.device.id": "",
    "ai.cloud.roleInstance": "XPS",
    "ai.device.osVersion": "Windows_NT 10.0.22631",
    "ai.cloud.role": "Web",
    "ai.device.osArchitecture": "x64",
    "ai.device.osPlatform": "win32",
    "ai.internal.sdkVersion": "uwm_node:2.9.6",
    "ai.location.ip": "127.0.0.1",
    "ai.session.id": "",
    "ai.user.id": "",
    "ai.user.authUserId": "",
    "ai.operation.name": "GET /test/9b8bb4f8-247e-4427-b668-633d66b29f13/test",
    "ai.operation.parentId": "110b84963e16499b848c81c297b78dd0",
    "ai.operation.id": "110b84963e16499b848c81c297b78dd0"
  },
  "data": {
    "baseType": "RequestData",
    "baseData": {
      "ver": 2,
      "properties": {},
      "id": "|110b84963e16499b848c81c297b78dd0.56957ce5962a4df4.",
      "name": "GET /test/9b8bb4f8-247e-4427-b668-633d66b29f13/test",
      "url": "http://localhost:3333/test/9b8bb4f8-247e-4427-b668-633d66b29f13/test",
      "duration": "00:00:00.016",
      "responseCode": "404",
      "success": false
    }
  },
  "iKey": "475a59dd-34c4-4530-a977-7d54ceaeffa1",
  "name": "Microsoft.ApplicationInsights.475a59dd34c44530a9777d54ceaeffa1.Request",
  "time": "2024-09-30T12:49:03.404Z"
}
```

**Comment by JacksonWeber** [comment]
@lcssanches Oh, is this issue independent of the azure app service environment then? I just want to rule that specific issue out if that's the case to narrow down a root cause.

**Comment by lcssanches** [comment]
@JacksonWeber, I believe this issue is related to Azure.

When I run the application locally using node index.js or within a Docker image (the same one deployed to Azure App Service), I receive all events. However, when deployed to Azure, only the “MetricData” events are processed.

**Comment by JacksonWeber** [comment]
@lcssanches can you give me a bit more information about your app service environment? (Node version, OS, etc.). And just to be clear, are you saying that only `MetricData` is processed through the TelemetryProcessor, or that only `MetricData` is being collected and sent to your Application Insights resource?

**Comment by lcssanches** [comment]
Only MetricData is processed through the TelemetryProcessor, although I see request metrics in Application Insights.

We use docker here, we build from `FROM node:20.11.1-alpine3.19 as build`. The App Service is running on a Linux App Service Plan - IsolatedV2. Our ASE is v3.

This is the envelope I receive when running on Azure, with OS details.
```
envelope: '{"ver":1,"sampleRate":100,"tags":{"ai.application.ver":"1.0.0","ai.device.id":"","ai.cloud.roleInstance":"79ad66bdf9adbc2b9e0ecabde508a81192484a9fd885a2fc7f8204167c0b343b","ai.device.osVersion":"Linux 5.15.158.2-1.cm2","ai.cloud.role":"service-api","ai.device.osArchitecture":"x64","ai.device.osPlatform":"linux","ai.internal.sdkVersion":"alm_node:2.9.6"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"kind":1,"count":1,"max":0,"min":0,"name":"\\\\ASP.NET Applications(??APP_W3SVC_PROC??)\\\\Requests/Sec","stdDev":0,"value":0}],"properties":{}}},"iKey":"475a59dd-34c4-4530-a977-7d54ceaeffa1","name":"Microsoft.ApplicationInsights.475a59dd34c44530a9777d54ceaeffa1.Metric","time":"2024-09-26T14:16:23.216Z"}'

```

**Comment by JacksonWeber** [comment]
@lcssanches Okay, it sounds like the real problem you're having isn't really related to telemetry processors, but is instead an issue with missing telemetry (specifically requests). We can rule out attach failing since you're processing metrics still. Could you add some manual request or dependency tracking to your application and see if those are processed when running in the Azure environment?

**Comment by lcssanches** [comment]
> [@lcssanches](https://github.com/lcssanches) Okay, it sounds like the real problem you're having isn't really related to telemetry processors, but is instead an issue with missing telemetry (specifically requests). We can rule out attach failing since you're processing metrics still. Could you add some manual request or dependency tracking to your application and see if those are processed when running in the Azure environment?

Thanks @JacksonWeber , it seems that the manual track did help, however but it still also auto tracking is still enabled although `setAutoCollectRequests` is `false`.

![Image](https://github.com/user-attachments/assets/31e19e40-e2ed-40e5-996b-008e0f0199cf)

The relevant code is

```js

  appInsights
    .setup()
    .setAutoCollectRequests(false)
    .start();
  appInsights.defaultClient.addTelemetryProcessor(applyOperationNamePattern);


  const app = require('express')();
  app.all('*', (req, res, next) => {
    appInsights.defaultClient.trackNodeHttpRequest({
        request: req,
        response: res,
        properties: {
          trackNodeHttpRequest: true
        }
    });
    next();
  });

```

**Comment by JacksonWeber** [comment]
@lcssanches Could you provide an example of a request in the transaction blade that's being auto-collected when `autoCollectRequests` is set to false? Of course, this setting won't stop the collection of dependency or other telemetry, just incoming requests.

**Comment by lcssanches** [comment]
This is a bit confusing for me.

Looking at the "Transaction Search" blade, I only see the original operation name.
![Image](https://github.com/user-attachments/assets/74b802b3-8c08-453e-b6e7-205c56d078fb)

But in the grouped view it's grouped by operation name:
![Image](https://github.com/user-attachments/assets/b5d923b5-2b40-4485-8b2c-e69450141a82)

This is the request the apparently was capture by the auto collect (or something else)
![Image](https://github.com/user-attachments/assets/dd1d1d10-6b39-4db8-8ca9-938e1c887248)

This is the request the was captured by the manual tracking (the operation names is changed + has a custom property)
![Image](https://github.com/user-attachments/assets/432792e8-3ff4-4b49-b131-e6d9605016bd)

**Comment by lcssanches** [comment]
@JacksonWeber codeless was enabled in Application Insights blade, after disabling it manual track was not needed.

**Comment by JacksonWeber** [comment]
@lcssanches Any manual instrumentation should force the auto-instrumentation agent to back off in App Service. Is your operation name update functional now?

**Comment by lcssanches** [comment]
@JacksonWeber Yes operation name is functional now. However, the auto instrumentation was still recording the requests.
Thanks a lot for your help here.
