### ISSUE TITLE
Requests sent with success false

### ISSUE THREAD

**Issue by mauron85** [microsoft/ApplicationInsights-node.js#1391]
We are using version 2.7.3 of applicationinsights and using enableAutoCollectRequests.

The request are sent to appinsights.

However with success: false eventhough response code is 200.

![image](https://github.com/user-attachments/assets/d301362d-7fdb-4cc8-b666-c9c4f66ebc49)

**Comment by JacksonWeber** [comment]
Hi @mauron85 could you try on the latest version of the 2.x SDK? (2.9.6) and could I see the rest of the properties on your request telemetry?
