### ISSUE TITLE
How to create custom span with SDK 3.3.x as opentelemetry allows ?

### ISSUE THREAD

**Issue by Apokalypt** [microsoft/ApplicationInsights-node.js#1394]
Hi,

We're currently migrating the appinsights 2.x.x SDK to version 3.3.x in order to use opentelemetry. However, we'd like to know if it's possible to use opentelemetry to its full potential, in particular through the creation of custom spans:
```Javascript
const { trace } = require('@opentelemetry/api');
trace.getTracer("test-tracer").startActiveSpan("something", (span) => {
    console.log('Does the parent span is shown ?');
});
```

When I tried to do this, the logs are indeed ingested into the AppInsights interface on Azure, but it seems that the span itself is not displayed and, as a result, the parentId of the logs in the custom span is de-correlated from the rest. Am I doing something wrong, or is it intentional/limitation?

By the way, here is the full piece I'm using :
```Javascript
const appinsights = require('applicationinsights');
appinsights.setup('<my-key>')
    .setAutoDependencyCorrelation(true)
    .setAutoCollectRequests(true)
    .setAutoCollectExceptions(true)
    .setAutoCollectDependencies(true)
    .setUseDiskRetryCaching(true)
    .setSendLiveMetrics(false)
    .setAutoCollectConsole(true, true)
appinsights.start()

const { argv } = require( "node:process" );
const express = require('express');
const { trace } = require('@opentelemetry/api');

const app = express();

app.get('/test-custom', (req, res) => {
    console.log(`GET /test-custom ${req.header('traceparent')}`);

    trace.getTracer("test").startActiveSpan("test-new-span", (span) => {
        console.log('GET /test-custom - Span started');

        res.json(appinsights.getCorrelationContext());
    });
});

let portValue = (process.env.PORT || '3000')
if(parseInt(argv[2]) > 0) {
    portValue = argv[2]
}
port = parseInt(portValue, 10)
port = isNaN(port) ? portValue : port
app.listen(port, () => {
    console.log('Server is running on port 3000');
})
```

**Comment by Apokalypt** [comment]
> @Apokalypt While I'm happy to investigate why the span isn't showing up for you here, it seems like you're interested in taking a full-on OpenTelemetry approach to instrumentation. I'd suggest using the [Azure Monitor OpenTelemetry distro](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/monitor/monitor-opentelemetry) in that case.
> 
> For more information on if the 3.x SDK or the Azure Monitor OpenTelemetry distro is a better fit for you, we have a [migration guide](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-nodejs-migrate?tabs=cleaninstall) as well.

I will take a look but I don't really understand the real benefit behind 😅 Indeed, when I look at the documentation (and the code) I get the impression that appinsights offers the same thing, but with a different interface. So I'm having trouble understanding the difference between the two. 

Is there anything I can do with the Azure Monitor OpenTelemetry distro and not with appinsights?

**Comment by JacksonWeber** [comment]
@Apokalypt the 3.x SDK is just a compatibility layer on top of Azure Monitor OpenTelemetry designed to present a compatible API for those directly upgrading from 2.x that have simple use-cases. The intention is to use 3.x if you have a standard use-case and don't have time to take advantage of the OpenTelemetry benefits at the moment. 
If you understand and work with OpenTelemetry concepts, you'll be better served by the distro, especially as these products develop.

**Comment by Apokalypt** [comment]
> @Apokalypt the 3.x SDK is just a compatibility layer on top of Azure Monitor OpenTelemetry designed to present a compatible API for those directly upgrading from 2.x that have simple use-cases. The intention is to use 3.x if you have a standard use-case and don't have time to take advantage of the OpenTelemetry benefits at the moment. If you understand and work with OpenTelemetry concepts, you'll be better served by the distro, especially as these products develop.

Thanks for this clarification 👍

I just tried to switch to azure monitor and the result is the same : my custom span doesn't not show on Application Insights service on Azure. Do you want me to create an issue on the other repository ?

**Comment by Apokalypt** [comment]
Well... All I had to do was activate my brain and now everything works  🤦
I had forgotten the “span.end()”.

Thx for all your information 👍

(btw, it also works with appinsights)

**Comment by JacksonWeber** [comment]
@Apokalypt Of course, just wanted to get you the product that'd work best for your use-case! If you do plan to stick with the 3.x SDK, I'd appreciate any feedback you have on why you decided to stick with it over the distro.

**Comment by Apokalypt** [comment]
> @Apokalypt Of course, just wanted to get you the product that'd work best for your use-case! If you do plan to stick with the 3.x SDK, I'd appreciate any feedback you have on why you decided to stick with it over the distro.

There are two reasons why, for the time being, we planned to stay with appinsights:
- The company I work for uses a microservices-based architecture. We have dozens of services + azure functions on several environments. Although we intend to switch to OpenTelemetry, some services have been developed using the functions offered by the “TelemetryClient” class. Removing appinsights altogether would mean modifying the logging system for these services.
- appinsights offers a rather practical interface for handling exceptions + auto-collection of consoles.log, error, ... + disk retry

To be perfectly honest, our internal migration discussion isn't over yet. Nevertheless, there's a good chance that it'll happen in two stages: 
1. Switch to appinsights 3.x to facilitate migrations on services
2. Change our logging system to a library like winston, develop exceptions handler, .... then switch to azure-monitor
