### ISSUE TITLE
Broken links about OpenTelemetry in README

### ISSUE THREAD

**Issue by Delapouite** [microsoft/ApplicationInsights-node.js#1396]
Hi.

Currently, in the first paragraph of the README.md:

> This solution is based on OpenTelemetry, to learn more about OpenTelemetry concepts, see the [OpenTelemetry overview](https://github.com/microsoft/ApplicationInsights-node.js/blob/main/opentelemetry-overview.md) or [OpenTelemetry FAQ](https://github.com/microsoft/ApplicationInsights-node.js/blob/main/azure/azure-monitor/faq#opentelemetry).

Both links points to 404 document.

Looking at the Git history, I'm not quite sure where they used to lead.

Thanks.

**Comment by JacksonWeber** [comment]
@Delapouite Thank you for catching this! Links will be checked for correctness and updated.
