### ISSUE TITLE
azure-storage and applicationinsights aren't playing nicely

### ISSUE THREAD

**Issue by ch0p57ickz** [Microsoft/ApplicationInsights-node.js#143]
AppInsights is conflicting with my azure-storage calls. After setting up fiddler, I found appinsights is adding this header to my http requests:
**x-ms-request-source-ikey**

that causes the request to return with this error: 

> HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

If I remove that header and re-play the same request, it succeeds.

Trivial repro:
```js
// (package.json/Dependencies)
{
    "applicationinsights": "^0.17.0",
    "azure-storage": "^1.3.2"
}
```
```js
// After setting proper env-vars...
var azure = require('azure-storage')
require('applicationinsights').setup().start()

azure.createBlobService().createContainerIfNotExists("somecontainer", err => console.error(err))
```
Comment out the 2nd line and the code magically works

**Comment by jeffmcaffer** [comment]
I have the same problem with the same versions on node 6.9.1

Poking a little deeper the replacement of http.request in ClientRequests.js#AutoCollectClientRequests.prototype._initialize (lines 29-39 in the JavaScript) seems to be the culprit.  If you comment out those lines then the problem goes away.  I did not dig deeper.

As you can imagine, this takes quite some time to figure out.  ETA on a fix?

**Comment by SergeyKanzhelev** [comment]
@jeffmcaffer do you have a small repro that we can try?

**Comment by SergeyKanzhelev** [comment]
@jasongin can you please take a look?

**Comment by SergeyKanzhelev** [comment]
It seems that appending a header `x-ms-request-source-ikey` breaks the way request signature is [calculated](https://github.com/Azure/azure-storage-node/blob/b12cd980d4bea4058d4bbb85a583ed7146b60d8f/lib/common/signing/sharedkey.js#L237):

``` node.js
/*
* Constructs the Canonicalized Headers string.
*
* To construct the CanonicalizedHeaders portion of the signature string,
* follow these steps: 1. Retrieve all headers for the resource that begin
* with x-ms-, including the x-ms-date header. 2. Convert each HTTP header
* name to lowercase. 3. Sort the headers lexicographically by header name,
* in ascending order. Each header may appear only once in the
* string. 4. Unfold the string by replacing any breaking white space with a
* single space. 5. Trim any white space around the colon in the header. 6.
* Finally, append a new line character to each canonicalized header in the
* resulting list. Construct the CanonicalizedHeaders string by
* concatenating all headers in this list into a single string.
*
* @param {object} The webresource object.
* @return {string} The canonicalized headers.
*/
```

**Comment by jasongin** [comment]
@SergeyKanzhelev I think this should get fixed by adding an excluded domains feature to the Node.js SDK, just like in the .NET SDK referenced above. But nobody is signed up to do that work, as far as I know.

**Comment by SergeyKanzhelev** [comment]
@kamilszostak @OsvaldoRosado @AlexBulankou can we please prioritize this work as it breaks customer application or revert to the previous version of SDK as a minimum.

**Comment by jeffmcaffer** [comment]
@SergeyKanzhelev there is a simple repro in original post.  Basically start() appinsights and do an Azure blob (any storage likely) call.  

@jasongin adding the excludes list might work but that still means that out of the box AppInsights breaks Azure storage (and perhaps other services, likely ones that use SAS tokens).  If you do have an excludes list, it should, by default, include all the known affected services.

BTW, how is this working with the .net SDK?  Unless that is primed with the Azure services in the exclude list, .net users Storage users will also be broken out of the box.

**Comment by SergeyKanzhelev** [comment]
@jeffmcaffer I think .NET storage SDK is using `SharedKeyLite` [authentication](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Authentication-for-the-Azure-Storage-Services?redirectedfrom=MSDN#a-namesubheading2a-specifying-the-authorization-header)

That's probably why it is not broken - we are still investigating.

@kamilszostak will be looking into adding an exclusion domains list and include azure storage to it by default today/tomorrow. We plan to ship an updated version of SDK this week.

**Comment by jeffwilcox** [comment]
The AWS libraries are probably not affected as their newer signature versions allow you to actually specify which specific headers you've used to compute the signature from. Have not tried verifying though as most of my work is with Azure storage's node libs right now.
