### ISSUE TITLE
After integrating azure app with AppInsights noticed failing dependency call to iisnodestats.azurewebsites.net

### ISSUE THREAD

**Issue by greyepoxy** [Microsoft/ApplicationInsights-node.js#144]
This is almost certainly the wrong place to be asking this question but I am hoping someone can point me in the right direction (no luck searching on my own so far).

So I was successfully able to integrate application insights (with all of the default auto collectors) into my Azure web app. While testing it out I noticed a bunch of failed dependency calls being made to http://iisnodestats.azurewebsites.net:80/.... (seems to occur one to one with server requests).

Any idea what is causing this call to be made? I know that node js in azure uses iisnode to host the node app in iis but from what I can tell this is not part of iisnode and seems to be some kind of external azure monitoring (maybe for the default built in web app tracking?).

Any ideas on how to make azure stop making these calls?

My backup strategy would be to use a Telemetry Processor to disable this from being uploaded.

**Comment by SergeyKanzhelev** [comment]
have you searched over npm packages to check which of them calls into "iisnodestats.azurewebsites.net"? You can probably use telemetry processor to get a callstack and guess who calls into that web site. It looks suspicious.

**Comment by greyepoxy** [comment]
hmm well as far as I can tell none of the node_modules are calling that endpoint.
Not sure if it will help but here is the set of dependencies I am using,
  ```
"dependencies": {
    "applicationinsights": "^0.17.0",
    "azure-storage": "^1.3.2",
    "body-parser": "^1.15.2",
    "data.either": "^1.4.0",
    "data.maybe": "^1.2.2",
    "data.task": "^3.1.1",
    "express": "^4.14.0",
    "fs": "0.0.1-security",
    "immutable": "^3.8.1",
    "node-uuid": "^1.4.7",
    "passport": "^0.3.2",
    "passport-facebook-token": "^3.3.0",
    "path": "^0.12.7",
    "ramda": "^0.22.1",
    "react": "15.3.2",
    "react-addons-pure-render-mixin": "15.3.2",
    "react-dom": "15.3.2",
    "react-redux": "^4.4.5",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0",
    "redux-actions": "^0.12.0",
    "redux-immutablejs": "0.0.8",
    "redux-thunk": "^2.1.0",
    "url-pattern": "^1.0.1"
  }
```

**Comment by greyepoxy** [comment]
Okay I figured it out, if others run into this the cause was the built in Azure web app server diagnostic [Web Server Logging](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-enable-diagnostic-log#a-namewhatisdiagaweb-server-diagnostics-and-application-diagnostics).

I turned if off and the requests stopped.

**Comment by SergeyKanzhelev** [comment]
@davidebbo is it expected to have an `http://iisnodestats.azurewebsites.net:80/` as a dependent call from the node.js application? Is there an official documentation about this endpoint? Should Application Insights node.js SDK recognize it and mark it somehow special way or even filter out?

**Comment by davidebbo** [comment]
@rramachand21 do you know how that works?

@greyepoxy @SergeyKanzhelev can you open issue on https://github.com/tjanczuk/iisnode/ so it's tracked in the right place? Thanks!
