### ISSUE TITLE
Failure in telemetry processor should not fail telemetry delivery

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-node.js#147]
I think this is a wrong behavior:

https://github.com/Microsoft/ApplicationInsights-node.js/blob/1658c428ab5fead3bbbaab8d9034cc9fb0e06969/Library/Client.ts#L296 

``` node.js
            } catch (error) {
                accepted = false;
                Logging.warn("One of telemetry processors failed, telemetry item will not be sent.", error, envelope);
            }
```

**Comment by OsvaldoRosado** [comment]
I think JS SDK has this same behavior. If we change this in one, we should change in the other.
