### ISSUE TITLE
Tracking custom requests

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/ApplicationInsights-node.js#148]
Is it possible to track custom requests using this SDK? I am thinking of something similar to C#'s SDK: 

```C#
public void TrackRequest(string name, DateTimeOffset startTime, TimeSpan duration, string responseCode, bool success)
```
Link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient#Microsoft_ApplicationInsights_TelemetryClient_TrackRequest_System_String_System_DateTimeOffset_System_TimeSpan_System_String_System_Boolean_

The reason I'm asking is that I have an API server which can receive requests via web sockets (not just HTTP), and I would like to track these requests as well.

**Comment by kamilszostak** [comment]
Currently, all requests are auto-collected and the SDK doesn't expose a method to track custom requests. 
The SDK should be extended to auto-collect web sockets requests too. I opened an issue and mark it as a feature request - #154. 

In the meantime, as a workaround, you can call `trackEvent` to log web sockets requests, although they won't show up as requests in the Azure Portal.

**Comment by irakliy81** [comment]
Thank you for the suggestion! - I'll use `trackEvent` for now.

Regarding auto-collection: I'm actually not using any of the auto-collect features and track all telemetry via custom methods. So, for my purposes, having a custom event to track non-http requests would be super helpful.

Thanks again!

**Comment by irakliy81** [comment]
I noticed that in the `Client` class, there is a public `track()` method: https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Client.ts#L239

Could it be used somehow to track custom requests?

**Comment by irakliy81** [comment]
@OsvaldoRosado - quick question: has this been implemented? Or you guys not planning to implement ability to track custom requests?

**Comment by OsvaldoRosado** [comment]
Sorry! Re-reading this I may have closed too early. It looked like a question on how to do this that was resolved by using trackEvent and forked a feature request for auto collection.

We don't today have a trackRequest that can be used without a request object, but it does sound like a fair ask to me. Re-opening with an enhancement tag

To answer your previous question, you can use the plain track method for this, but you must construct the telemetry envelope by hand. This will be easier in the next release as we'll export the classes/types we use within the SDK to handle these data contracts.

**Comment by irakliy81** [comment]
No worries! And thank you for re-opening it. I'll play around with the new SDK once it becomes available.
