### ISSUE TITLE
Is there an example on how to override config properties?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-node.js#155]
I want to control these properties: `maxBatchSize` `maxBatchIntervalMs`. How can I override them?

**Comment by gzepeda** [comment]
Hello Guys, 

Looks like what is needed here is a code snippet on how to do it. Is that correct?

**Comment by OsvaldoRosado** [comment]
I think so

**Comment by OsvaldoRosado** [comment]
There's one example of this now in the readme, for configuring sampling. We should consider documenting the entire configuration object

**Comment by OsvaldoRosado** [comment]
Documentation on all config options is now in the README.
