### ISSUE TITLE
v0.17.1 break authentication in other Azure packages

### ISSUE THREAD

**Issue by kowsheek** [Microsoft/ApplicationInsights-node.js#167]
`applicationinsights@0.17.1` breaks authentication in `azure-storage@1.4.0`. See [this issue](https://github.com/Azure/azure-storage-node/issues/247) for repro steps.

**Comment by kamilszostak** [comment]
It looks like it's the same issue as #143, which was fixed in #156. The fix will be released in 0.17.2.

**Comment by kowsheek** [comment]
Awesome, thanks @kamilszostak!
