### ISSUE TITLE
Periodic ApplicationInsights:Sender Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/ApplicationInsights-node.js#177]
We are using the applicationinsights@0.17.2 NPM in a service and quite frequently get the following error.  Sometimes it will be 2-3 occurrences in a minute, other times the service run for 5-10 minutes with no errors.  It is unclear if the error is in some way fatal.  The service keeps on running and app insights still appear in the portal (though it is unclear if some are missing).  Interestingly these errors do not themselves appear as Exception events.

```
ApplicationInsights:Sender [ { Error: unable to verify the first certificate
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:586:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } ]

```
Thoughts?  Is there a way of suppressing the console output?

**Comment by kamilszostak** [comment]
I added a method to disable console logging - #178. 

I'm not sure what is causing this error. The SDK is sending all telemetry using https and for some reason, your node server cannot verify the AppInsights endpoint certificate. Do you have any more logs?

**Comment by jeffmcaffer** [comment]
No additional logging that I can see.  It is interesting because telemetry is getting through and shows up in the portal.  It would be weird if just some of the messages to AppInsights were having this problem.  

@kamilszostak, do you have a sense of whether this causing data loss or can it be safely ignored (e.g., will the failed request be retried?)

**Comment by jeffwilcox** [comment]
+1, seeing this on my dev box on campus, but intermittent. Not sure how to get more information.

**Comment by OsvaldoRosado** [comment]
Closing this to leave #180 as the primary bug tracking this, as most of the conversation has occurred there.
