### ISSUE TITLE
troubles using addTelemetryProcessor

### ISSUE THREAD

**Issue by camous** [Microsoft/ApplicationInsights-node.js#179]
I'm facing few troubles to filter telemetry sent by my nodejs application.
I'm not interested in health metrics (such CPU, RAM, etc), only events that I send myself.

I could don't care at all, but if I'm scaling out my application in azure, I end up with millions of un-necessary records breaking my quota.
![image](https://cloud.githubusercontent.com/assets/8566299/22283448/a311def0-e2e2-11e6-8d05-96541888b9fe.png)

```
appInsights.client.addTelemetryProcessor((envelope) => {
    fs.appendFile('output.txt', JSON.stringify(envelope.data.baseData), function (err) {

    });
    return true;
});
[...]
test.trackEvent('TEST application insights');
test.trackMetric("opportunityqueue-test",1);
test.trackDependency("track dependency");
test.trackTrace("track trace");
```

if I look into my output.txt, I was expected to see all telemetry (the one I want to keep and the one I don't). But it seems I found only the one I don't care (no reference of my TEST application insights, metrics opportunityqueue-test, etc). So I assumed that the telemetryProcessor was only for out of the box health events, and switch the return true, to return false. And then I got a full black out. I am missing something on how addTelemetryProcess works ?

**Comment by SergeyKanzhelev** [comment]
Will this help?

https://github.com/Microsoft/ApplicationInsights-node.js/blob/dbfe2901037478aefcd0b59001c9044c4fdbc72e/README.md#disabling-auto-collection

``` js
import appInsights = require("applicationinsights");
appInsights.setup("<instrumentation_key>")
    .setAutoCollectRequests(false)
    .setAutoCollectPerformance(false)
    .setAutoCollectExceptions(false)
    // no telemetry will be sent until .start() is called
    .start();
```

**Comment by camous** [comment]
I was so much focus on the addTelemetryProcessor function that I've missed the setup part ... It removed the metrics spam, that's great. however, how I should be able to remove autocollection of dependencies ?

![image](https://cloud.githubusercontent.com/assets/8566299/22639299/9961d85a-ec4d-11e6-945a-5f3c038238cb.png)

here my new initialization of insights client
`appInsights.setup(process.env.CORTEX_AZURE_INSIGHTS_INTRUMENTATION_KEY)
    .setAutoCollectPerformance(false)
    .setAutoCollectRequests(false)
    .start();`

**Comment by camous** [comment]
Ok, now I supposed my question is a duplicate of #157

**Comment by camous** [comment]
I've added a processor for skipping remote dependencies. thanks for the initial direction :)
