### ISSUE TITLE
Double reporting of tracked dependencies?

### ISSUE THREAD

**Issue by tolu** [Microsoft/ApplicationInsights-node.js#184]
First of all, thanks for a truly fantastic product!

I'm using the following code to track dependencies in my express server
```js
app.get('/api/plugs/:id', (req, res, next) => {
  appInsights.client.trackRequest(req, res);
  let requestUrl = `http://my-special-api.no/medium/${req.params.id}/plugs?maxnumber=20`;
  const start = Date.now();
  request(requestUrl, (apiError, apiResponse, body) => {
    const elapsedTime = Date.now() - start;
    const { statusCode, statusMessage } = response;
    const success = !error && statusCode < 400;
    const hostname = url.parse(requestUrl).hostname;
    appInsights.client.trackDependency(
        hostname, 
        requestUrl, 
        elapsedTime, 
        success,
        'HTTP',
        { statusCode, statusMessage }
    );
    // handle response to client
  });
});
```

It all seems to work pretty good with the exception of this resulting in **TWO** calls reported in AI Analytics
![image](https://cloud.githubusercontent.com/assets/658586/22542454/2514686a-e92c-11e6-8bef-a0422de925a2.png)

One call with the data that I reported and one call with port-number added.
Also, the `timestamp`, `duration` and `itemId` all differ between the two calls.

Now, my Application Insights setup looks like this:
```js
if(serverConfig.appInsightsKey){
    appInsights.setup(serverConfig.appInsightsKey)
      .setAutoCollectRequests(false)
      .setAutoCollectPerformance(false)
      .setAutoCollectExceptions(true)
      .start();

    const props = {
      applicationName: 'baldibla',
      applicationVersion: serverConfig.version,
      applicationDate: serverConfig.datetime
    };
    appInsights.client.commonProperties = props;
}
```

So I would hope that all reporting should be handled explicitly by my code in this case.

To try and figure this out I've tried looking at the network traffic with Fiddler4 (but found nothing, how do I do that?) and added console-logging to my local copy of `Sender.js` inside the `applicationinsights` npm package.
This logging only report one call being made to the `/v2/track` endpoint.

The result of this behavior is this graph of requests with dependencies overlay that first caught my attention, with twice as many dependency requests as there are requests to my server (weird).
![image](https://cloud.githubusercontent.com/assets/658586/22542694/6c3fecc2-e92d-11e6-8262-0b2a2bdef5f4.png)

Hopefully this is just an error in my implementation but I'd love to get any and all feedback from you that could explain this situation.

**Comment by kamilszostak** [comment]
With [v0.17.0](https://github.com/Microsoft/ApplicationInsights-node.js/releases/tag/v0.17.0) the SDK is automatically tracking all HTTP dependency calls. So you don't need to manually call `trackDependency`. 

`ItemId` is different for every telemetry item, so it's OK. A `timestamp` might differ slightly, depending on when two `trackDependency` methods were called (one from auto-collection class and one in your code).
I'm wondering why `duration` is different (72ms vs 156ms). 

Fiddler doesn't show node.js requests by default. There is a good blog post on how to fix it - [Use Fiddler with Node.js](https://weblogs.asp.net/dixin/use-fiddler-with-node-js)

**Comment by tolu** [comment]
Ah, I see now!
I did not do my homework on checking out more on the settings than reading the readme.
Added #186 to avoid having other jump to the same (falsy) conclusions.

I think I'll just look further into the weird thing about the `duration` difference.

Seems odd that the diff should be so high, although yours is started after and finishes before mine...
It's not a one time thing either, the result from the following analytics query:
```
dependencies
| where timestamp > ago(12h)
| where name !contains ":80"  
| summarize sum(duration)  
```
set against one where I summarize everything that *does* contain `:80` (~9500 records) gives me (roughly):

* myTotal = 1 194 455ms
* yourTotal = 824 294ms
* diff = ~30%

So that doesn't seem as bad as my first example where it was ~46% (72ms vs 156ms).
Still, it'd be fun to know just what happens in the span of that difference.

Thanks for the all the help!
