### ISSUE TITLE
Not receiving any events

### ISSUE THREAD

**Issue by ancashoria** [Microsoft/ApplicationInsights-node.js#185]
Hi,
I want to setup App Insights for a bot running on https://dev.botframework.com/
There is a field over there where you can input the Instrumentation Key which I did, but I receive no events.

I also setup App Insights for node with this code, but still I receive no events
```
console.log(process.env.APPINSIGHTS_INSTRUMENTATIONKEY); // key is ok
appInsights.setup().start();
const client = appInsights.getClient();
client.trackEvent('custom event', {something: true});
client.trackException(new Error("handled exceptions can be logged with this method"));
client.trackMetric("custom metric", 3);
client.trackTrace("trace message");
```

Help?

**Comment by SergeyKanzhelev** [comment]
Do you see any errors in console?

**Comment by KamilSzostak** [comment]
Please reopen if you're still having this issue.
