### ISSUE TITLE
Data volume is high (the custom event is using over 1 KB per event)

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/ApplicationInsights-node.js#188]
I am using `client.trackEvent()` API in my project. The monthly event count is about 360 K. However, the monthly data volume is about 440 MB. So, the custom event is using over 1 KB per event? It is too high, since I just send about 10 byte data per event. Seems data like client IP, location info or others are also calculated in data volume. Is there a way to reduce the cost of data volume?
![1](https://cloud.githubusercontent.com/assets/1050213/22812137/ef4812f6-ef7d-11e6-8219-fb1c3a1b81fa.jpg)
![2](https://cloud.githubusercontent.com/assets/1050213/22812139/f078f2a8-ef7d-11e6-90cb-aa9307aa2343.jpg)

**Comment by kamilszostak** [comment]
Yes, each event holds your data and some other fields, like timestamp or geo-location data. The schema is common for all AppInsights SDKs, so if you want to suggest a change please open an issue in [ApplicationInsights-Home](https://github.com/Microsoft/ApplicationInsights-home) repo.

If you want to reduce the size and don't want to benefit from those additional fields you can write a custom [telemetry processor](https://github.com/Microsoft/ApplicationInsights-home) and remove them from the event object.

**Comment by SergeyKanzhelev** [comment]
Hi @formulahendry,

First I want to clarify what your are paying for.

The calculation of data size happened based on the size of entire event sent to Application Insights endpoint. Geo information that we extracted from the client IP or client IP itself (if not sent as part of JSON) is not being accounted for.

Envelope includes fields like `time`, `iKey`, 'type' (indicating that this is an `Event`), schema `ver`. So it is not 10 bytes even if we would only count the actual data size, not entire JSON payload. By default we also collect some extra information like `sdkVersion` that sent this event to simplify issues troubleshooting and `roleInstance` - the computer name that sent this event. Also the envelope's schema is not super optimal. (I think node.js SDK has some problems with the default data collection that can be addressed. I'll mentioned those in separate comment. For now you can use @KamilSzostak's recommendation to clean those using telemetry processors.)

Now, the actual question. 440 MB you mentioned fit into the free allowance of 1 Gb. From https://azure.microsoft.com/en-us/pricing/details/application-insights/

>With Basic, you pay based on the volume of telemetry your application sends, with a 1 GB free allowance per month. This free data allowance gives you a great way to try out Application Insights as you get started, and it also allows you to use Application Insights for free on an ongoing basis for debugging and for low-volume applications.

If you'd pay for overage - you'd only pay $1.1 for those events. ($2.3 per Gb / 2). Keep in mind - you just sent 700 K events for free (included into 1Gb). 

Does this price seems unreasonable?

**Comment by SergeyKanzhelev** [comment]
@KamilSzostak I created an issue for schema problems: https://github.com/Microsoft/ApplicationInsights-node.js/issues/189
