### ISSUE TITLE
Custom Event and Metrics

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/ApplicationInsights-node.js#190]
Hi,

I tried the sample ` client.trackEvent("custom event", {customProperty: "custom property value"});` and it works, i see some logs on the server

But If I set my own metrics or event, I don't things on the server.
I see my custom event deeeeeeeeper in ApplicationMap > Call > Something about "Dependency" > My Event.

Is there a best practice to see my custom metrics like ELK Stack ?

**Comment by SergeyKanzhelev** [comment]
@JpEncausse - it seems you haven't tried Application Insights Analytics yet. Here is the [overview](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-analytics) and documentation. I think it will give you what you need - fast and easy access + charts that you can pin to Azure Dashboards.

**Comment by SergeyKanzhelev** [comment]
Closing for now - please re-open if it is not what you needed
