### ISSUE TITLE
Storage SDK Failed with Application In National Cloud

### ISSUE THREAD

**Issue by MS-HerbChung** [Microsoft/ApplicationInsights-node.js#193]
Hi Team,

I found in the issue 143 you already add the core.blob.windows.net into exclude domain list. But national cloud like Azure China, Azure Germany and Azure Gov still get the same issues.

Can you also add it into exclude domain list?

**Comment by SergeyKanzhelev** [comment]
What's the suffixes in those clouds?

**Comment by MS-HerbChung** [comment]
Azure China: blob.core.chinacloudapi.cn
Azure Germany: blob.core.cloudapi.de
Azure Gov: blob.core.usgovcloudapi.net
