### ISSUE TITLE
No custom Events or custom Metrics in the App Insights

### ISSUE THREAD

**Issue by romangusev** [Microsoft/ApplicationInsights-node.js#196]
I have an appropriate environment variable with an instrumentation key in our app. After I run `appInsights.setup().start()` I can see basic data like amount of requests in App Insights.

Also, we have an angular app serving from this Node app. I included the javascript sdk and can see metrics like page load time in the same dashboard.

But my problem is that custom Events and custom Metrics in Nodejs SDK do not show up in the charts. There are no errors or other feedback, so I don't know how to make it work.
 
I have these test lines running to get metrics and I’m pretty sure these lines run many times:
```
client.trackEvent("registeredLogin", {id: "someid", name: "somename" });
client.trackEvent("registeredLogin2", {test: 123});
client.trackMetric("registeredLogin", 1);
```
But I can't find anything in neither the Metrics Explorer nor in the customEvents/customMetrics tables in the Analytics.

In the package.json file I have   `"applicationinsights": "^0.15.11"`.

**Comment by sedouard** [comment]
+1 to this I've noticed this for weeks now!

**Comment by SergeyKanzhelev** [comment]
I've tried this and it works:

``` js
var http = require('http');
var url = require('url');
var sleep = require('system-sleep');    

var appInsights = require("applicationinsights");

process.env['NODE_DEBUG'] = 'net,tls';

appInsights.enableVerboseLogging();

var client = appInsights.getClient("9d3ebb4f-7a11-4fb1-91ac-7ca8a17627eb");
client.config.maxBatchSize  = 1;

    console.log("test");
    client.trackEvent("test");

    client.trackEvent("registeredLogin", {id: "someid", name: "somename" });
    client.trackEvent("registeredLogin2", {test: 123});
    client.trackMetric("registeredLogin", 1);

    sleep(300);
```

Here is the output:

```
ApplicationInsights:Sender [ { host: 'dc.services.visualstudio.com',
    port: null,
    path: '/v2/track',
    method: 'POST',
    headers:
     { 'Content-Type': 'application/x-json-stream',
       'Content-Encoding': 'gzip',
       'Content-Length': 375 } } ]
ApplicationInsights:Sender [ { host: 'dc.services.visualstudio.com',
    port: null,
    path: '/v2/track',
    method: 'POST',
    headers:
     { 'Content-Type': 'application/x-json-stream',
       'Content-Encoding': 'gzip',
       'Content-Length': 398 } } ]
ApplicationInsights:Sender [ { host: 'dc.services.visualstudio.com',
    port: null,
    path: '/v2/track',
    method: 'POST',
    headers:
     { 'Content-Type': 'application/x-json-stream',
       'Content-Encoding': 'gzip',
       'Content-Length': 390 } } ]
ApplicationInsights:Sender [ { host: 'dc.services.visualstudio.com',
    port: null,
    path: '/v2/track',
    method: 'POST',
    headers:
     { 'Content-Type': 'application/x-json-stream',
       'Content-Encoding': 'gzip',
       'Content-Length': 430 } } ]
ApplicationInsights:Sender [ '{"itemsReceived":1,"itemsAccepted":1,"errors":[]}' ]
ApplicationInsights:Sender [ '{"itemsReceived":1,"itemsAccepted":1,"errors":[]}' ]
ApplicationInsights:Sender [ '{"itemsReceived":1,"itemsAccepted":1,"errors":[]}' ]
ApplicationInsights:Sender [ '{"itemsReceived":1,"itemsAccepted":1,"errors":[]}' ]
```

Can you also please try to add this logging and see what server response is.

**Comment by romangusev** [comment]
Got this:
```
ApplicationInsights:Sender [ { host: 'dc.services.visualstudio.com',
    port: null,
    path: '/v2/track',
    method: 'POST',
    headers: 
     { 'Content-Type': 'application/x-json-stream',
       'Content-Encoding': 'gzip',
       'Content-Length': 6545 } } ]
ApplicationInsights:Sender [ '<head><title>Document Moved</title></head>\n<body><h1>Object Moved</h1>This document may be found <a HREF="https://dc.services.visualstudio.com/v2/track">here</a></body>' ]
```

**Comment by SergeyKanzhelev** [comment]
Upgrade to latest version of node.js. Error saying that you need to use `https`, not `http`

**Comment by SergeyKanzhelev** [comment]
Or set it manually by `client.config.endpointUrl = "https://dc.services.visualstudio.com/v2/track";`

**Comment by sedouard** [comment]
=-| You mean by default previous versions used http?? That's dangerous for privacy.

**Comment by SergeyKanzhelev** [comment]
=) now we do better

**Comment by romangusev** [comment]
Thanks, that works now.

Also I have noticed that when I specify this config.endpointUrl it sends my custom events fine. But for the default metrics which appinsights sends automatically I still can see this errors.

My app is using https on azure. Why iappinsights still sends the request with http?

**Comment by SergeyKanzhelev** [comment]
This line will set it for your own client only

**Comment by romangusev** [comment]
I have updated SDK to the latest 0.18.0 and it works fine now with no errors. Even without client.config.endpointURL. 
So I think the problem existed just in old releases. I had 0.15.something.
My fault.
Thanks Sergey for the help.
