### ISSUE TITLE
Collect system metrics

### ISSUE THREAD

**Issue by scsouthw** [Microsoft/ApplicationInsights-node.js#20]
I just realized the `require("os");` module provides a way to track cpu/memory/network. 

https://nodejs.org/api/os.html

The application insights user interface now supports custom metrics so the idea here is to collect custom metrics to capture system performance. This will be exposed similar to `appInsights.trackAllHttpServerRequets`, maybe `appInsights.trackSystemMetrics()` and it will capture aggregate metrics at a configurable interval.

**Comment by mrmckeb** [comment]
When do you think the next release will be ready? This is a great module, and I'm looking forward to the future.

**Comment by scsouthw** [comment]
I got a prototype working last weekend. There are a lot of changes in the v15 release, I'll put it in a feature branch later today. Look forward to any suggestions/feedback :D

**Comment by scsouthw** [comment]
The code for this is here: https://github.com/Microsoft/ApplicationInsights-node.js/blob/feature/v15-schema-and-auto-collection/AutoCollection/Performance.ts

**Comment by mrmckeb** [comment]
Thanks, that's pretty exciting! I'll check it out ASAP.

**Comment by scsouthw** [comment]
This has been added in the 0.15 release. Let me know what you think :)
