### ISSUE TITLE
Offline mode does not persist endpoint with file, leading to data being sent to wrong endpoints

### ISSUE THREAD

**Issue by KevinMehlhaff** [Microsoft/ApplicationInsights-node.js#202]
Currently offline mode saves all files into %temp%\appInsights-node folder.

We have two clients each configured with a different URL endpoint.  The URL endpoint is not saved in the offline file.

When AppInsights goes back online, the client sends the first file in the offline folder to whichever URL endpoint the client happened to be configured with. This can be different than the original endpoint intended for the data.

If this different endpoint rejects the data, then AI will re-save the file and try later.  However, if the endpoint accepts the data, then AI will delete this file and fail to deliver the offline packet to the correct endpoint.

We also see a problem with all Node.JS AppInsights apps sharing the same folder.  If an endpoint in an active client rejects an offline packet stored by a different app, then this can stop the chain of re-sending packets from this client, event though that client's packets would successfully be sent.

.NET AppInsights in contrast saves entire HTTP request in an applicationKey-specific folder when it is offline.  This solves the problem both about URL and about delivery of offline packets.

**Comment by PavelUstinovMS** [comment]
I think aligning format of the files with .NET implementation is a good idea.
1. It will allow to solve problems which Kevin mentioned.
2. It will allow .NET based applications, which use the same appKey send data on behalf of the Node.js.
