### ISSUE TITLE
Question: Would like example of how to start normal collection & log a custom metric

### ISSUE THREAD

**Issue by khowling** [Microsoft/ApplicationInsights-node.js#206]
I'm not clear how I initiate the SDK for automatic performance collection, and also log custom metrics
I need to pass in the ikey twice?, once for .setup() & once for .getClient()?

appInsights.setup(ikey).setAutoCollectRequests(false).start()
aiclient = appInsights.getClient(ikey)

Also, with this in the code, my program never terminates (its event triggered), is there a .stop() ?

**Comment by KamilSzostak** [comment]
No, you don't need to pass it twice. `setup` calls `getClient` internally and initializes it with a default set of parameters (e.g. enable request auto-collection). Something like this will work: 

```
var appInsights = require("applicationinsights");

appInsights.setup("<your-ikey>").start();

appInsights.client.trackException(new Error("exception"));
appInsights.client.trackEvent("test");
appInsights.client.trackTrace("test");
```

The SDK doesn't support `stop()`. You can turn off specific auto-collectors (for instance `setAutoCollectRequests(false)`), but you don't have to stop the whole SDK.
