### ISSUE TITLE
ApplicationInsights:Sender - EACCES Exception

### ISSUE THREAD

**Issue by andrewhathaway** [Microsoft/ApplicationInsights-node.js#207]
Every day, our application is going down due to ApplicationInsights:Sender throwing an `EACCES` error. I've seen a couple of issues related to this, but no `EACCES` error-types. 

Running version: `0.18.0` of this package.

```
ApplicationInsights:Sender [ { [Error: connect EACCES 40.114.241.141:443 - Local (undefined:undefined)]
    code: 'EACCES',
    errno: 'EACCES',
    syscall: 'connect',
    address: '40.114.241.141',
    port: 443 } ]
```

Thanks.

**Comment by KamilSzostak** [comment]
The SDK should not crash on `EACCES` error.

**Comment by OsvaldoRosado** [comment]
Can you verify the SDK causes this crash? Do you have a stack trace? Getting a console log like this means the SDK successfully caught the error (and hopefully should have handled it!). It would be good to identify what function is failing

**Comment by OsvaldoRosado** [comment]
Could you also let us know if you're enabling "offline mode" to save failed telemetry to disk? It would help rule out certain code paths. Thanks!

**Comment by AlexBulankou** [comment]
We would need a repro confirming SDK is causing the crash, we believe the we should be handling the error and not letting app to crash. Please reactivate with repro.
