### ISSUE TITLE
Track* methods should accept tagOverrides and contextObjects

### ISSUE THREAD

**Issue by christopheranderson** [Microsoft/ApplicationInsights-node.js#209]
Using the custom `track*` methods from a Node.js application with lots of async code can be a headache since I currently have to set the operation id on the client context which might be called out of order. I can use the  `track` method to do this per track call, but then I lose the easy of use of the other `track*` commands. 

I'm working on a PR for this.

**Comment by KamilSzostak** [comment]
👍
