### ISSUE TITLE
How to perform queries ?

### ISSUE THREAD

**Issue by navneetccna** [Microsoft/ApplicationInsights-node.js#216]
I want to get json data as explain in rest api doc https://dev.applicationinsights.io/documentation/overview

customEvents 
 	 | where customDimensions.teamId == '8bcb0466-8227-4de4-b001-b70381b9cd04' 

As the rest api have limit of 15 call per min and 1500 per day  as doc https://dev.applicationinsights.io/documentation/Authorization/Rate-limits says to use Azure API and Azure Active Directory but there is no example available for that. This is possible in this SDK

**Comment by SergeyKanzhelev** [comment]
I think this is how you do it: https://docs.microsoft.com/en-us/rest/api/index (example is for the different Azure API, but authentication part should apply). 

Also please vote/comment at [user voice](https://visualstudio.uservoice.com/forums/357324-application-insights/suggestions/17365018-enable-higher-rate-limits-for-the-data-access-rest).

CC: @DaleKoetke

**Comment by SergeyKanzhelev** [comment]
Please open a separate issue at https://github.com/Microsoft/ApplicationInsights-Home/issues. This repo is for node.js SDK questions and bugs. Thanks for using Application Insights!
