### ISSUE TITLE
TypeScript Definition File

### ISSUE THREAD

**Issue by Cecildt** [Microsoft/ApplicationInsights-node.js#22]
Hi,

Thanks for this module. Can I please request a TypeScript definition file that is added to the DefinitelyTyped library?

https://github.com/borisyankov/DefinitelyTyped

Thanks.

**Comment by scsouthw** [comment]
I've added a pull request https://github.com/borisyankov/DefinitelyTyped/pull/4281

Thanks!
Scott

**Comment by Cecildt** [comment]
Thanks!
