### ISSUE TITLE
AppInsights prevents Node process to exit

### ISSUE THREAD

**Issue by beth-panx** [Microsoft/ApplicationInsights-node.js#220]
I implemented Application Insights in [Office Add-in validator](https://github.com/OfficeDev/office-addin-validator) and [Yo Office](https://github.com/OfficeDev/generator-office) using custom tracking. It takes a long time for Node process to end. Sometimes user has to ctrl+c to manually stop process.

Found out this is related to AppInsights by adding process.exit() at the end of the program. All other functions run successfully but no data is logged to AppInsights.

Any way to improve performance in such situations?

**Comment by KamilSzostak** [comment]
Could you share a sample code to reproduce this issue?

**Comment by OsvaldoRosado** [comment]
Closing to merge with #54
