### ISSUE TITLE
Support Typings Definitions for latest versions

### ISSUE THREAD

**Issue by myunggeun-song** [Microsoft/ApplicationInsights-node.js#227]
We are using Application Insights with TypeScript and are using Typings as well. But I found there is only 0.15.12 version's definition in the registry of Typings. Would you add Typescript definitions of each version including latest to the registry?

* Registry: https://api.typings.org/entries/dt/applicationinsights/versions
* Application Insights 0.15.12 Definition: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/253e456e3c0bf4bd34afaceb7dcbae282da14066/applicationinsights/index.d.ts

FYI, we are using 0.18.0 and the interfaces of 0.15.12 are not the same as it, so we are using it with workaround.

**Comment by OsvaldoRosado** [comment]
I believe the latest source correctly generates ts types embedded in the npm package, making this just work (at least for TS 2.0+).

I'll verify with a generated package, but copying latest build output directly to my node_modules folder seems to show correct types in vscode.
