### ISSUE TITLE
Error: connect ETIMEDOUT for ApplicationSender

### ISSUE THREAD

**Issue by chrwend** [Microsoft/ApplicationInsights-node.js#230]
Hi,

we are using the ApplicationInsights-node.js SDK in one of our projects. Sometimes we get the following error at random times (e.g. 04/21/2017, ~10:31-10:33 pm):

```warn: ApplicationInsights:Sender [ [ { Error: connect ETIMEDOUT 40.84.189.107:443```

I'm pretty sure those errors were thrown due to long API response times. However, I was wondering if data gets lost or if the SDK tries to resend it. Furthermore, do you provide any status page?

Thank you!

**Comment by OsvaldoRosado** [comment]
The SDK should resend this data if you enable offline mode to persist failed telemetry to disk for later retry.

The setting to enable this is `appInsights.setOfflineMode(true)` for the default client, or `client.channel.setOfflineMode(true)` for any additional clients. There is an optional second parameter to change the retry interval.

**Comment by OsvaldoRosado** [comment]
For service status, Application Insights is on the Azure status dashboard: https://azure.microsoft.com/status/

There is also a service status blog with detailed information: https://blogs.msdn.microsoft.com/applicationinsights-status/

**Comment by chrwend** [comment]
@OsvaldoRosado Thank you!

**Comment by chrwend** [comment]
Unfortunately, the status pages don't show slow response times. I'm got timeouts for the following machine:

* 52.167.221.184:443 (4/25/2017 1:16:06 PM UTC)

Do you see any issues?

**Comment by OsvaldoRosado** [comment]
I'm not aware of any issues with the service taking too long to respond for any significant number of requests. Transient errors may occur from time to time, of course (either taking too long to respond or any other number of issues). As long as the SDK is configured to retry, your data should still make it to the service.
