### ISSUE TITLE
Add support for tunneling data through a proxy

### ISSUE THREAD

**Issue by OsvaldoRosado** [Microsoft/ApplicationInsights-node.js#246]
We can do this by adding support for a configurable Agent (https://nodejs.org/api/http.html#http_class_http_agent) that the Sender uses

**Comment by JasonJJFS** [comment]
Hi all any ETA on this issue? Or is there a mitigation for running behind a corporate proxy.

**Comment by OsvaldoRosado** [comment]
No ETA for this yet. The workaround right now is to add exceptions to your firewall for the IPs listed at https://docs.microsoft.com/azure/application-insights/app-insights-ip-addresses

Depending on how your proxy works, you may also be able to manually forward to it by changing the `endpointUrl` address in the `Config` object.

**Comment by JasonJJFS** [comment]
Yes we've done that and now works as expected. Many thanks.
