### ISSUE TITLE
Console monkey patching

### ISSUE THREAD

**Issue by eamodio** [Microsoft/ApplicationInsights-node.js#249]
Is there any way to disable the `Console` monkey patching other than setting this environment variable APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL? Is there a configuration setting or anything for it?

I'm using application insights in a vscode extension, and I don't want the `Console` monkey patching -- especially since it hijacks it, rather than just capturing the info. With it on, it steals all console output which makes debugging far more difficult.

FYI using `setAutoCollectConsole` doesn't seem to do anything -- it still steals all the console output.

**Comment by OsvaldoRosado** [comment]
I've filed a bug to track autocollection of console objects being broken in vscode (https://github.com/Microsoft/node-diagnostic-channel/issues/22) and an enhancement request to disable diagnostic source publishers on particular items (#250). 

As a mitigation, `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` is your only option I believe. To avoid altering the environment for other extensions, I believe you can use something like:

```
var diagChannelState = process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'];
process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = true;
var appInsights = require('applicationinsights');
process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = diagChannelState;
```

**Comment by eamodio** [comment]
Thanks -- I will try that out

**Comment by eamodio** [comment]
Seems to have worked -- though certainly wish it was a setting rather than an env variable.

**Comment by OsvaldoRosado** [comment]
Glad that worked for you! I'll close this issue but feel free to re-open if necessary. We'll be shipping a new version very soon that will fix this problem so you won't need to turn it off if you don't want to. As for why it's an env variable - we have to patch methods before they're require'd by other code, making most config setting options too late to stop the process. I understand this is somewhat awkward to use as an env variable, but it satisfies the goal of being available before anything else is loaded and can be read entirely synchronously on our construction. Alternative ideas for how it can be disabled are certainly welcome!
