### ISSUE TITLE
trackRequestSync(req, context.res..) throws type error exception "url" must be a string, not undefined 

### ISSUE THREAD

**Issue by globysdz** [Microsoft/ApplicationInsights-node.js#253]
I am using Azure functions and integrated with appinsight, my code looks like following:

**Comment by SergeyKanzhelev** [comment]
@globysdz please paste the code you planned to

**Comment by SergeyKanzhelev** [comment]
CC: @christopheranderson for visibility in case it is some kind of docs bug

**Comment by globysdz** [comment]
`
const appInsights = require("applicationinsights");
const ai = appInsights.getClient();
module.exports = function (context, req) {
    context.log(req); // req.url === 'undefined'
    ...
    ai.trackRequestSync(req, context.res, (new Date() - start));  // this throws exception
};
`

if i replace 
module.exports = function (context, req) 
with 
exports.run = function(context, req)

then the req.url is defined

**Comment by OsvaldoRosado** [comment]
Azure Functions documentation at https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook states:

> For Node.js functions, the Functions runtime provides the request body instead of the request object.

This will not be what trackRequest is expecting. You may have to wait for #148 to become a feature to use trackRequest in Functions. As a workaround you can use trackEvent to fire a custom event for each request.

Did you follow a code snippet from somewhere? @SergeyKanzhelev mentioned the possibility of this being a docs bug

**Comment by OsvaldoRosado** [comment]
Dug deeper and found the bit about the request object being the body instead is only true for webhooks. The root issue here is that the req object from Functions is not a standard Node request object. You _may_ be able to work around this with something as simple as `context.req.url = context.req.originalUrl` and then pass `context.req` to `trackRequest`.

**Comment by OsvaldoRosado** [comment]
Closing as the SDK works correctly when given the data type it expects as per type definition.
