### ISSUE TITLE
setAutoCollectPerfarmance to false keeps sending performance metrics

### ISSUE THREAD

**Issue by msternik** [Microsoft/ApplicationInsights-node.js#259]
I disabled the collection of performance metrics, however I can still see the data in the dashboard. Is this method setAutoCollectPerformance(false) meant to switch the performance data off?

**Comment by OsvaldoRosado** [comment]
`setAutoCollectPerformance(false)` is indeed intended to disable autocollection of performance counters when used like so:
```
appInsights.setup("<instrumentation_key>")
    .setAutoCollectPerformance(false)
    .start();
```

Is this what your code looks like?

To clarify, you're seeing new performance counter data show up in Application Insights even after setting this flag and re-deploying/restarting your app?

**Comment by OsvaldoRosado** [comment]
Closing this issue. Please feel free to open it again if you're still experiencing this!

**Comment by msternik** [comment]
Many thanks, this helped!
