### ISSUE TITLE
How to send telemetry before process exit

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/ApplicationInsights-node.js#261]
In my application I have an uncaught exception handler. In that handler, I would like to send the uncaught exception telemetry to the portal, and then exit the process. My code looks something like this:
```
const client = appInsights.getClient(INSTRUMENTATION_KEY);

process.on('uncaughtException', (error) => {
        error.message = `Uncaught exception: ${error.message}`;
        client.trackException(error);

        client.sendPendingData(() => {
            process.exit(1);
        });
    });
```
However, it doesn't seem to work - the exception telemetry doesn't get send to the server. Am I doing anything incorrectly?

**Comment by OsvaldoRosado** [comment]
Are you able to verify your exception handler is being called?

The callback object given to `sendPendingData` is given an argument that's the response from the AI backend. Could you try echoing this out? That will let us see if data is being sent.

Ex:
```
client.sendPendingData((resp) => {
   console.log(resp);
   process.exit(1);
});
```

Note: We do have this functionality built into the SDK. It has an uncaughtException handler which saves the trace to disk, and attempts to send the telemetry when the app is started back up. You'll have to use `appInsights.setOfflineMode(true)` to enable this and you cannot be using `appInsights.setAutoCollectExceptions(false)`

**Comment by irakliy81** [comment]
The output from logging the response looks like this:
```
{
  "itemsReceived": 2,
  "itemsAccepted": 2,
  "errors":[]
}
```
However, seems like errors are making it to the server now. Maybe updating the library to the latest version fixed it. I think this issue can be closed.

PS: I don't really rely on any auto-collect features - but that's for the suggestion!

**Comment by bigman73** [comment]
sendPendingData doesn't seem to exist in newer versions
I have a CLI application that when using process.exit() doesn't send the current buffer.
Flushing the buffer with: 
```
 appInsights.defaultClient.flush();
```

Clears the internal buffer but doesn't send it to the app insights server.
Is there any way to force the node library to send the data?
