### ISSUE TITLE
Invalid method signature leads to implicit 'any' type

### ISSUE THREAD

**Issue by rstropek** [Microsoft/ApplicationInsights-node.js#264]
I found three method signatures that seem to be incorrect:

* [Channel.ts](https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Channel.ts#L89)
* [Client.ts](https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Client.ts#L239)
* [Sender.ts](https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Sender.ts#L42)

In all three locations, a parameter `callback` is used with the following type declaration: `(string) => void`. It looks like the author wants the callback to receive a parameter of type `string`. However, this TypeScript syntax leads to a parameter called `string` with type `any`. In my understanding, the callback's type should be something like `(msg: string) => void`.

The reason why this is important is TypeScript's TS7006 error: *Parameter '...' implicitly has an 'any' type'*. I want to compile my Node.js application with the TypeScript compiler setting `noImplicitAny`. In that case, the method signature mentioned above leads to an error and I cannot use `noImplicitAny`.

**Comment by OsvaldoRosado** [comment]
Great catch! Marking this for the next release.

Thanks!

**Comment by OsvaldoRosado** [comment]
Fixed with #272
