### ISSUE TITLE
Upgrading to 0.20.1 seems to break socket.io-redis module

### ISSUE THREAD

**Issue by irakliy81** [Microsoft/ApplicationInsights-node.js#268]
I've upgraded the library to version 0.20.1 (from 0.19.0) and after that socket.io-redis module throws errors. I've included a fragment of the stack trace below. Downgrading back to 0.19.0 fixes the problem.
```
TypeError: Cannot read property 'pubsubBound' of undefined
    at RedisClient.originalRedis.RedisClient.internal_send_command (C:\Projects\credo.api\node_modules\diagnostic-channel-publishers\.dist\src\redis.pub.js:12:22)
    at RedisClient.publish (C:\Projects\credo.api\node_modules\redis\lib\commands.js:62:25)
    at Redis.broadcast (C:\Projects\credo.api\node_modules\socket.io-redis\index.js:400:13)
    at Namespace.emit (C:\Projects\credo.api\node_modules\socket.io\lib\namespace.js:222:18)
```

In my code, I don't really rely on any of the auto-collect features. Is possible to load the module (or even just the Client class) without any monkey-patching and auto-collect features turned on?

**Comment by MSLaguana** [comment]
You can disable the monkey patching of redis by setting the `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` environment variable to a truthy value, or by setting the `process.env["APPLICATION_INSIGHTS_NO_PATCH_MODULES"] = "redis"`. Note that this will likely break correlation between events and requests in some circumstances, but it will stop the error that you see there.

Looks like it should be a fairly simple fix on our end, but I'm not sure when we'll get a release co-ordinated: https://github.com/Microsoft/node-diagnostic-channel/pull/29

**Comment by OsvaldoRosado** [comment]
>  Is possible to load the module (or even just the Client class) without any monkey-patching and auto-collect features turned on

To achieve this, you'll also need to use the snippet below before calling `start()` (if you are - if you don't use start() none of the settings in this snippet would have been enabled anyway).

```
appInsights.setup("<instrumentation_key>")
    .setAutoDependencyCorrelation(false)
    .setAutoCollectRequests(false)
    .setAutoCollectPerformance(false)
    .setAutoCollectExceptions(false)
    .setAutoCollectDependencies(false)
    .setAutoCollectConsole(false)
    .start();
```

If you aren't using `start()`, you should already be getting the Client class directly (via `appInsights.getClient("<instrumentation key>")`). If this is the case, only the settings described by @MSLaguana are necessary

**Comment by irakliy81** [comment]
@MSLaguana @OsvaldoRosado - thank you very much for the quick replies! I'll disable monkey-patching as you've recommended over the weekend and will let you know if I run into any issues.

A somewhat related question: is it possible to pass operation ID or something like that directly to functions on the Client class to correlate events manually? For example, something like:

```JavaScript
client.trackEvent("my custom event", {
    operationId: "some guid"
});
```

**Comment by MSLaguana** [comment]
One quick comment: When setting the environment variables, make sure that you set them before you `require('applicationinsights')`, since it's at that point that we configure the monkey patches.

**Comment by OsvaldoRosado** [comment]
The tagOverrides parameter should do what you want. Something like

`client.trackEvent("evtName", null, null, {"ai.operation.id": "some guid"});`

**Comment by OsvaldoRosado** [comment]
You can also use a telemetry processor to inject these (see the README file for a good example of using a telemetry processor). These are typically preferred, but tagOverrides may be easier to use if you don't have our correlation context tracking enabled

**Comment by OsvaldoRosado** [comment]
This should be fixed with the new version diagnostic-channel-publishers referenced in #276
