### ISSUE TITLE
Insights cookies not sent with tracking functions

### ISSUE THREAD

**Issue by kthayer424** [Microsoft/ApplicationInsights-node.js#27]
It appears that the `trackEvent` function (as well as others) are not sending the session cookies to App Insights with the event.

Ex. I have a App Insights configured on the browser of a webpage served up by node. The client side script creates the ai_session and ai_user cookies. When I post that form, I get those cookies back in the form post on the server, but the event tracking isn't identifying those cookies automatically like when I use the C# package for App Insights. 

Is there another way to send the App Insights cookies through the `trackEvent` function so that I can tie my end user's page view and server telemetry together? Should it be set as metadata?

**Comment by MaxShehovtsov** [comment]
In C# we set sessionid/anonimous user id of telemetry item (e.g. request) to values we get from cookies. Is that something you want to have in nodejs sdk automatically too?

**Comment by kthayer424** [comment]
Yeah, that would be sweet. I'm using Express, so I assume it would read off the request object's cookies parameter for those values?

**Comment by MaxShehovtsov** [comment]
I think the problem is that when you do manual trackXXX we don't have a request object representing the current request and holding cookies. (On the other hand for request *auto collection* we do collect sessions and users).

You could create wrappers around trackXXX that would pass these tags as the last parameter, and the implementation of getSessionId() and getUserId() is on you.
```javascript 
 MyTrackXXX = function() {
    var tags = {"ai.session.id": getSessionId(), "ai.user.id": getUserId()}
    appInsights.trackXXX(..., tags)
  }
```

And then implement getSessionId and getUserId reusing AppInsights public helpers - see example here https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/AutoCollection/Requests.ts#L215

**Comment by kthayer424** [comment]
Right, so just to understand what's going on here, if I just add `ai.session.id` and `ai.user.id` to the meta data field of trackxxx, App Insights will know to read those differently than other meta data on the same meta data object?

**Comment by kthayer424** [comment]
Nevermind, it looks like that didn't work. Here's my code:

`log.trackEvent('test event', { 'ai.session.id': 'randomsessionid', 'ai.user.id': 'randomuserid'});`

And result:

![](https://i.gyazo.com/8ceaa6063316cdec9a6d2ded3768ab7b.png)

Is there a different field that session id and user id need to be used with?

**Comment by MaxShehovtsov** [comment]
Yeah, it's more complicated than I thought - trackXXX treats second parameter as *custom* properties where I was looking at internal track() which takes "tag overrides".
I think at this point the easiest way - even though error prone - would be this:

```javascript
	appInsights.client.context.tags["ai.session.id"] ="92222222-2222-2222-2222-222222222222";
	appInsights.client.trackEvent("your node event");
```

where you still need to get the session id from cookies somehow. Also it looks like there's a bug in how session id is attached for requests - it doesn't parse the guid out of the string and shows something like GUID|date1|date2 (date1 and date2 shoud not be sent)

**Comment by kthayer424** [comment]
Cool, well this will work in the short term. I might make a middleware that pulls those cookies off each request and primes the client or something before each Track.
Thanks
