### ISSUE TITLE
Enhance npm documentation

### ISSUE THREAD

**Issue by nicolehaugen79** [Microsoft/ApplicationInsights-node.js#282]
Consider the following improvements to the package documentation to help appeal to node.js devs:

1.) The "Getting Started" section points the dev to a general [purpose walk-through](https://azure.microsoft.com/documentation/articles/app-insights-create-new-resource/) for configuring AI; instead, there is a node.js specific one available that seems like it would be better to point devs to: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs.

2.) The Node.js MSFT doc mentioned above does a really good job of emphasizing the value props of using AI in the first paragraph - the npm package documentation should do the same.  

In particular, since node.js devs looking at this package may likely have their app hosted using a different cloud platform, an important point that the npm package documentation should emphasize is that "AI can be used for Node.js services hosted anywhere...even other public clouds".  This helps to make it clear that our technologies are pluggable.

3.) To help with discoverability, the package tags should be revisited - for example, "tracing" and "telemetry" may be other keywords that would be beneficial to include.

**Comment by OsvaldoRosado** [comment]
Great observations! Thanks for the feedback!
