### ISSUE TITLE
How to get the Dependency calls in Application Insights using NodeJS Web application

### ISSUE THREAD

**Issue by sateesh1988** [Microsoft/ApplicationInsights-node.js#283]
I have developed a NodeJS web application, which I published it into azure web app and configured the application insights for that. Up to now every thing was working properly, one thing is when I go to application insights I am able to see only requests, events and exceptions but I am not getting any SQL dependency calls in AI, even though I am getting the data from Azure SQL Database.

I just followed the below link to configure the application insights for my NodeJS web application.
[](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs)

Can you please tell me how to resolve the above issue as soon as possible?

**Comment by OsvaldoRosado** [comment]
This SDK doesn't yet support automatic collection of SQL dependencies. Currently, automatic dependency collection is limited to HTTP(S) calls and calls from these libraries: bunyan, console, mongodb, mongodb-core, mysql and redis.

You can use the trackDependency method provided by this SDK to manually instrument your Azure SQL calls.

**Comment by OsvaldoRosado** [comment]
Closing this for now. Feel free to re-open if the above didn't solve your issue!
