### ISSUE TITLE
Multi-component application maps require cloud_RoleName

### ISSUE THREAD

**Issue by sheepcount** [Microsoft/ApplicationInsights-node.js#284]
The multi-component application map (preview) requires `cloud_RoleName` to be set.

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-multi-role-apps

Currently (v0.21.0), this does not seem to be the case, so Node.js-based components show up as "Unknown" in the application map.

**Comment by OsvaldoRosado** [comment]
It is possible to set cloud_RoleName manually with `appInsights.client.context.tags["ai.cloud.role"] = "ROLENAME"` but a quick look at how this feature works shows me this won't be enough to get the application map preview to work.

It looks like we have to also set the value of the current role name in the outgoing Request-Context header (with the key `roleName`) and on incoming requests, check for that header and add it to the Source field, and on headers returned from dependencies, add it to the target field (https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/db53106c5d85546a2508ecb9dcd6bf1106fb29fa/Src/DependencyCollector/Shared/Implementation/HttpProcessing.cs#L373) This is similar to what we do for appIds currently.

I'm assigning this to a future milestone. Thanks for bringing this up!
