### ISSUE TITLE
Auto collected client request missing GET/POST from dependency name

### ISSUE THREAD

**Issue by tirish** [Microsoft/ApplicationInsights-node.js#295]
How our auto-collected HTTP dependencies from our node app are showing up:
[![Screenshot from Gyazo](https://gyazo.com/7bb426935d7f334d33b35a576ead7555/raw)](https://gyazo.com/7bb426935d7f334d33b35a576ead7555)

Notably missing: The `GET` in the dependency name
Less notably missing: The port at the very top of the blade, the path in dependency name

Good example from auto collected client-side AJAX dependency:
[![Screenshot from Gyazo](https://gyazo.com/18665fd47183f7df375f3c28553cf186/raw)](https://gyazo.com/18665fd47183f7df375f3c28553cf186)

**Comment by OsvaldoRosado** [comment]
@KamilSzostak @SergeyKanzhelev 

JS SDK may be incorrect in giving you telemetry formatted this way. Here's a screenshot from the latest .NET SDK which Node.js should be replicating.

![image](https://user-images.githubusercontent.com/4926351/29334670-1521ffa6-81bd-11e7-8e54-97a8287e56ca.png)

**Comment by tirish** [comment]
Ah, I am also seeing that from our .NET applications as well. I guess it is working as intended, I just wish there were some indication of HTTP method. Do you know if that information is available in some not-obvious way from the portal?

**Comment by OsvaldoRosado** [comment]
This seems to be an accidental regression to me when we changed how we format our telemetry. I'm not seeing it available in any fields. @SergeyKanzhelev should be able to say what the intended output is here.

**Comment by OsvaldoRosado** [comment]
Investigated further - this was actually caused by an error in our backend ingestion service. When the fix is deployed out future telemetry should have the following form for a dependency to http://test.com/page

Name: GET /page
Target: test.com
Data: http://test.com/page

**Comment by tirish** [comment]
Thanks @OsvaldoRosado !
