### ISSUE TITLE
Refactor track* API

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-node.js#302]
Before we ship stable SDK I would like to refactor track API:

1. To make track* functions more consistent between themselves. 
2. To allow specifying timestamp
3. To address some reported bugs such as inability to specify result code for dependencies #286 and not being able to track requests without request object #148 
4. To make names consistent with property names in Portal and Analytics
5. To make API consistent with [.NET API](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/f3f43d0f2159ac34023af8e8c7b5afe2da782400/src/Microsoft.ApplicationInsights/Managed/Shared/TelemetryClient.cs)
6. To reduce the number of positional argument to the ones required, while keeping the others in TrackOptions bag.

This is the proposal:
```JavaScript

interface TrackOptions
{
    timestamp?: Date;
    properties?: { [key: string]: string; }
    measurements?:{ [key: string]: number; }
    contextObjects?: {[name: string]: any;}
    tagOverrides?: { [key: string]: string; }
}

void trackDependency(
     dependencyTypeName: string,
     target: string,
     dependencyName: string,
     data: string,
     duration: number,
     resultCode: string
     success: bool
     trackOptions: TrackOptions);

void trackEvent(
     eventName: string,
     trackOptions: TrackOptions);

void trackTrace(
     message: string,
     severityLevel: SeverityLevel
     trackOptions: TrackOptions);

void trackMetric(
     metricName: string,
     metricValue: number
     trackOptions: TrackOptions);

void trackException(
     exception: Error,
     trackOptions: TrackOptions);

void trackRequest(
     name: string,
     duration: number,
     resultCode: string
     success: bool
     trackOptions: TrackOptions);
```

@OsvaldoRosado @SergeyKanzhelev @KamilSzostak

**Comment by OsvaldoRosado** [comment]
What does `trackRequest` do in this proposal? Currently our `trackRequest` doesn't allow creation of a manual request - only autocreation from `req` and `res` objects. 

I think I would like to see `trackRequest` be purely manual, and we can have a separate extensions/helpers API that can perform the current actions of `trackRequest`/`trackRequestSync`/`trackDependencyRequest`.

Keeping these helpers is important as they enable cross-component correlation to work even in manually instrumented applications

**Comment by OsvaldoRosado** [comment]
Not part of track*, but we should also refactor the root API methods. For example, `getClient` is endlessly confusing.

**Comment by AlexBulankou** [comment]
@OsvaldoRosado, the intention of the trackRequest proposal above is to do exactly this: allow creating requests without req and res object. 

To make transition simpler we could also make:

- trackRequestFromRequestResponse
- trackDependencyFromClientRequest

Thoughts on these helpers?

**Comment by OsvaldoRosado** [comment]
These helpers could work. If you take the object args approach I added above, we could also simply allow overloaded methods. Eg:

```
interface ManualRequestArgs extends TrackOptions {
   name: string,
   duration: string,
   resultCode: string,
   success: bool
}

interface ReqResRequestArgs extends TrackOptions {
   req: Http.Request,
   res: Http.Response
}

void trackRequest(args: ManualRequestArgs | ReqResRequestArgs);
```

**Comment by OsvaldoRosado** [comment]
As part of this, should we also expose a way to trigger creation of a correlation context? Similar to `new Activity` / `startOperation` on .NET? Today the only way to get a correlation context is through our http server wrapper, there is no manual way.

**Comment by AlexBulankou** [comment]
@OsvaldoRosado, are you proposing that every track* method should have overloaded version that takes single CustomTrackOptions (extending from TrackOptions) argument?   
I like this, but I am not sure if we should allow it *in addition to* regular multi-argument track* API that I listed above OR *instead of* ?    

Regarding your other comment, we should but adding new API can easily be done past stable release. I wanted to focus on breaking changes here as those will be much harder to do post-stable. So I think it shouldn't be part of it. ``getClient()`` on the other hand should

**Comment by OsvaldoRosado** [comment]
@AlexBulankou I am, and I'm suggesting instead of. Having essentially no positional arguments grants us great API flexibility in the future as we can add and remove without worrying about ordering of properties. It's also a lot easier to implement overloaded methods, as you can compare object types (JS doesn't natively support overloaded fns).

It also, arguably, allows for cleaner code when funcs are called like `trackRequest({name: 'name', duration: 200})`, you don't need to read docs to see what these arguments are.

**Comment by AlexBulankou** [comment]
I like it. The only  issue with single positional argument alone, is that it doesn't provide immediately obvious guidance on what properties I must specify, vs. those that are optional. Positional arguments provide this clarity, but it comes with big downside with making it hard to do any changes in the future. Let me draft the argument signatures based on single options approach.

**Comment by AlexBulankou** [comment]
Updated with Osvaldo's suggestion:

```TypeScript

interface TrackOptions
{
    timestamp?: Date;
    properties?: { [key: string]: string; };
    measurements?:{ [key: string]: number; };
    contextObjects?: {[name: string]: any;};
    tagOverrides?: { [key: string]: string; };
}

interface DependencyTrackOptions extends TrackOptions
{
     dependencyTypeName: string;
     target: string;
     dependencyName: string;
     data: string;
     duration: number;
     resultCode: string;
     success: bool;
}

interface HttpDependencyTrackOptions extends TrackOptions
{
   requestOptions: string | http.RequestOptions | https.RequestOptions;
   request: http.ClientRequest;
}

interface EventTrackOption extends TrackOptions
{
     eventName: string
}

interface TraceTrackOptions extends TrackOptions
{
     message: string;
     severityLevel: SeverityLevel;
}

interface ExceptionTrackOptions extends TrackOptions
{
     exception: Error;
     severityLevel: SeverityLevel;
}

interface MetricTrackOptions extends TrackOptions
{
     metricName: string;
     metricValue: number;
}

interface RequestTrackOptions extends TrackOptions
{
     name: string;
     duration: number;
     resultCode: string;
     success: bool;
}

interface HttpRequestTrackOptions extends TrackOptions
{
     request:http.ServerRequest;
     response:http.ServerResponse;
     logBeforeRequestComplete: bool
}

void trackDependency(trackOptions: DependencyTrackOptions | HttpDependencyTrackOptions);
void trackTrace(trackOptions: TraceTrackOptions);
void trackMetric(trackOptions: MetricTrackOptions);
void trackException(trackOptions: ExceptionTrackOptions);
void trackRequest(trackOptions: RequestTrackOptions | HttpRequestTrackOptions);
void trackEvent(trackOptions: EventTrackOptions);

```

**Comment by SergeyKanzhelev** [comment]
- Call `trackOptions` an `envelope`? Ideally I do not want to introduce this concept if possible and let either create an entire envelope or pass arguments to the `track*` method.
- What is `contextObjects`?
- What is `tagOverrides`?
- Let's not mix an envelope in public contract with the types like `ClientRequest`. Those types are only needed to be passed in telemetry initializers for additional data extraction. So should be a separate argument
- Also `logBeforeRequestComplete` is another example of mixing data/schema with collection behavior

Ideal case it that we have an API layer that is shared with JS SDK. It may have extensibility to pass some runtime platform specific types, but it should be clearly decoupled.

**Comment by AlexBulankou** [comment]
Discussed with Sergey and decided to do 2 changes:
1. Rename *TrackOptions-> *Telemetry for consistency with .NET and also not to introduce additional concept:
- RequestTelemetry
- DependencyTelemetry
- MetricTelemetry
- ExceptionTelemetry
- EventTelemetry
- TraceTelemetry
2. Don't expose domain specific objects, such as http, https, http.RequestOptions in the Client API. This way API remains clean and can be easier shared with JS later on. Instead create helpers to create RequestTelemetry from req/res and DependencyTelemetry from ClientRequest
With this API becomes:

```TypeScript
class Util
{
 public createDependencyTelemetryFromClientRequest(clientRequest:http.ClientRequest|https.ClientRequest, requestOptions: http.RequestOptions|https.RequestOptions): DependencyTelemetry;
 public createRequestTelemetryFromHttpRequestAsync(httpRequest: http.Request | https.Request, httpResponse: http.Response | https.Response, onRequestComplete:()=>RequestTelemetry): void;
 public createRequestTelemetryFromHttpRequest(httpRequest: http.Request | https.Request, httpResponse: http.Response | https.Response, duration: number): RequestTelemetry;
}

interface Telemetry
{
    timestamp?: Date;
    properties?: { [key: string]: string; };
    measurements?:{ [key: string]: number; };
    contextObjects?: {[name: string]: any;};
    tagOverrides?: { [key: string]: string; };
}

interface DependencyTelemetry extends Telemetry
{
     dependencyTypeName: string;
     target: string;
     dependencyName: string;
     data: string;
     duration: number;
     resultCode: string;
     success: bool;
}

interface EventTelemetry extends Telemetry
{
     eventName: string
}

interface TraceTelemetry extends Telemetry
{
     message: string;
     severityLevel: SeverityLevel;
}

interface ExceptionTelemetry extends Telemetry
{
     exception: Error;
}

interface MetricTelemetry extends Telemetry
{
     name: string;
     value: number;
     count: number;
     min: number;
     max: number;
     stdDev: number;
}

interface RequestTelemetry extends Telemetry
{
     name: string;
     duration: number;
     resultCode: string;
     success: bool;
}

public class Client
{
  public void trackDependency(telemetry: DependencyTelemetry);
  public void trackTrace(telemetry: TraceTelemetry); 
  public void trackMetric(telemetry: MetricTelemetry);
  public void trackException(telemetry: ExceptionTelemetry);
  public void trackRequest(telemetry: RequestTelemetry);
  public void trackEvent(telemetry: EventTelemetry);
}
```

**Comment by irakliy81** [comment]
These improvements look great! I have one quick question: if I wanted to pass an operation ID with each track* request - would that be done via `tagOverrides` (e.g. `{"ai.operation.id": "myid"}`? Or would it be possible to make operation ID a separate property in the Telemetry interface?

**Comment by OsvaldoRosado** [comment]
@irakliy81  My understanding is `tagOverrides` would indeed be the place to do this if for some reason you cannot use automatic dependency correlation and `appInsights.getCorrelationContext().operation.id`

@AlexBulankou and @SergeyKanzhelev thoughts on a `NodeClient` that inherits from `Client` to have domain-specific objects rather than hiding them in Utils? Seeing that the domain they are specific to is built in to node, it's strange to hide them in the Node SDK. Separating a Node client and Base client in this way still leaves it reusable

**Comment by AlexBulankou** [comment]
>> thoughts on a NodeClient that inherits from Client to have domain-specific objects rather than hiding them in Utils .  

@OsvaldoRosado, I agree with this approach, this is how I'm doing it: https://github.com/Microsoft/ApplicationInsights-node.js/blob/albulank/trapi/Library/NodeClient.ts
