### ISSUE TITLE
Userid is not autocollected from the cookies

### ISSUE THREAD

**Issue by MaxShehovtsov** [Microsoft/ApplicationInsights-node.js#31]
JSSDK sets ai_user cookie which should be associated with the request. NodeSDK does parse ai_session cookie but doesn't look at ai_user.

**Comment by gzepeda** [comment]
As a proposal to solve this issue the RequestDataHelper class needs to be modified:

- Add a method like _getUser() similar to the _getSessionId() present in this class that retrieves that information. 
- Add a call to the previous method on the getRequestTags function to populate the tag corresponding to the user retrieved from the previous method. 

Let us now. 
@georgejolema
@AlexBulankou 
@oscargarciacolon

**Comment by kamilszostak** [comment]
@gzepeda looks good to me :) Thanks for fixing this issue!
