### ISSUE TITLE
AI does not properly fail fast when a bad ikey is given

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/ApplicationInsights-node.js#310]
If a bad ikey is given (either as an argument to `.setup()` or through environment variable), after running `.start()`, the script will never terminate. I looked through the code a bit and it looked like the CorrelationIdManager may be causing the issue, but forcing that request to timeout didn't solve anything, so I would need to look deeper to see what the actual fix is.

```js
const ai = require('applicationinsights');
console.log('before setup')
ai.setup('doesntexist').start();
console.log('before track')
ai.client.trackTrace('hello');
console.log('after track');
```

*Expected*: three messages are logged and then the script exits.
*Actual*: three messages are logged and then the script hangs indefinitely.

**Comment by OsvaldoRosado** [comment]
Here do you mean bad ikey as in not a string, or a string that happens to not have a record in our backend?

**Comment by OsvaldoRosado** [comment]
I believe the correct behavior here is to error on incorrect type, but not error on an ikey that the backend says is invalid, as that state can change at any time and is not worth crashing the app over.

As for the script staying running (different than fail fast), those traces aren't sent out yet. The script should terminate with a call to `sendPendingData`

**Comment by jackhorton** [comment]
In the cases I looked at, I was using strings like "none" and "doesntexist". I just tried with numbers and it looks like it throw with a TypeError because `iKey.replace()` is used.

**Comment by OsvaldoRosado** [comment]
Is there something particular to this scenario that requires an ikey that doesn't exist? It seems like this is #54 .

**Comment by jackhorton** [comment]
You're right, this looks like the same issue. Sorry about that!

The use case was that I am looking at a website that wants to run in a Jenkins CI without sending any telemetry during testing, and right now, theyre mocking out the methods they need as no-ops. I was trying to see if I could eliminate that mock, and if so, what would happen.

**Comment by jackhorton** [comment]
Would the preferred route here be to set sampling to 0 or use the "offline mode" as suggested in the other issue?

**Comment by OsvaldoRosado** [comment]
In the `Config` object there is a property `disableAppInsights`, it should remove all network calls. I think that will work for the CI scenario

**Comment by jackhorton** [comment]
Awesome. So, since there isn't even an ikey available in the CI environment at all, I suppose I can just give a random non-empty string as the ikey, in this case?

**Comment by OsvaldoRosado** [comment]
Yep! A random ikey should work just fine
