### ISSUE TITLE
Custom Metric Check for Use by Scale Set

### ISSUE THREAD

**Issue by jsevedge** [Microsoft/ApplicationInsights-node.js#313]
Thanks to this wonderful SDK it is very simple to include custom perf data in Application Insights, i do not see however if there is currently an option to perform a check to see if that custom metric is available for consumption (by a scale set as an autoscaling rule metric for example).  

It appears to typically takes a couple minutes for a newly create custom metric to propagate and be available for use.  Within an ARM template deployment though that may cause a raise condition if the VM scale set is created (each member starts sending the custom perf data via a custom metric name that never existed prior) and then an autoscale profile is applied referencing that custom metric that was just created by the members if it isn't quite available for use yet.

Any thoughts on how to resolve this?  Creating a "getMetric" method (or something similar) would resolve this fairly simply i would think.

**Comment by OsvaldoRosado** [comment]
If I'm understanding correctly, this sounds similar to #293. If that's the case, a `getMetric` method that checks for existing telemetry is currently out of scope for this SDK, which is for collection of server telemetry rather than retrieval of stored telemetry.

You should be able to easily accomplish seeing if data under your metric is available using our REST API. You can learn more about it at https://dev.applicationinsights.io/

**Comment by jsevedge** [comment]
@OsvaldoRosado Got it, thanks.  I spent some time getting familiar with this and rest api seems fairly straightforward when getting api key from portal.  My primary issue now is it doesn't appear possible yet to create (and retrieve?) an API key via an ARM template (as opposed to the GUI).  I assume this will be supported at some point?

**Comment by jsevedge** [comment]
Additional thought... it could simplify this scenario if the instrumentation key (which ostensibly has read/write access to App Insights) could be used as an "API Key".  Then checking via REST api as suggested after creating custom metric could be done via the same "object" as opposed to juggling instrumentation key and separate API key.

**Comment by OsvaldoRosado** [comment]
This assumption here isn't correct:
>  the instrumentation key (which ostensibly has read/write access to App Insights

Instrumentation Keys only have write access, as they can be made public (client-side JavaScript SDK usage for example). A separate API Key is indeed required for REST API usage.

**Comment by jsevedge** [comment]
Bummer, was afraid that was the response i would get but it makes sense i suppose.  Any insight you could give into when the ability to create/view API keys from within an ARM template would occur?  Or some other mechanism to fulfill this use case via an ARM deployment?

**Comment by OsvaldoRosado** [comment]
@jjjordanmsft Do you know the answer to this?

**Comment by OsvaldoRosado** [comment]
Actually, from a quick docs check.

Here are two approaches:
- Create an API Key using an ARM query: https://dev.applicationinsights.io/documentation/Authorization/API-key-and-App-ID
- Use Azure API format with Azure Active Directory instead to avoid needing an API key: https://dev.applicationinsights.io/documentation/Overview/URL-formats

**Comment by jsevedge** [comment]
@OsvaldoRosado Thanks for the info, I did however run across both of those links yesterday when looking at the docs and dont believe they will work in my context.  The example to create api key via ARM query uses Powershell with a specific set of PowerShell Modules making calls to the Azure Rest API as far as i can tell which won't work for me based on VM's being deployed.  The example using Azure API format with Azure AD assumes that you are logged in via CLI (example again is powershell).

Additional Context: The VM's in the scale set being created by the ARM template are linux based and dont have the azure cli installed so currently limited to Node SDK and simple rest calls via curl, etc.. which has not been a problem thus far.

**Comment by OsvaldoRosado** [comment]
How are you triggering your ARM template deployment? The code that is able to do this, should be able to use the ARM query to generate an API Key with essentially a pure REST call, as it's already authenticated. The powershell usage in both examples is for convenience and not necessary for use.

**Comment by jsevedge** [comment]
The ARM deployment is consumed/triggered by a customer from their machine that is deploying via the Azure CLI or the Azure portal yes, but the deployment itself within the ARM template is then self-contained and is not run from the same context as it was triggered.  Basically a single ARM template is the entirety of the "solution" a customer is deploying so pre or post prep work from that machine unfortunately is not an option.

**Comment by jsevedge** [comment]
Resolved by virtue of azure-arm-appinsights node sdk support added to create/delete api keys.

Thanks for the assistance with this.
