### ISSUE TITLE
Exclude specific requests from sending data?

### ISSUE THREAD

**Issue by luismendozamx** [Microsoft/ApplicationInsights-node.js#325]
I've looked through the docs and can't find a way to ignore certain requests. I was wondering if this can be done?

My use case is services that have a `GET /health-check` which is constantly called. The data generated by these endpoint throws off all our metrics making our response times and success rates different from what they actually are.

**Comment by OsvaldoRosado** [comment]
This is the perfect scenario to use a telemetry processor. Telemetry processors are run right before telemetry is sent to our backend and allow you to craft custom rules for whether or not they should get sent. A processor like this should work for you:
```
appInsights.defaultClient.addTelemetryProcessor((envelope, contextObjects) => {
    // Is this a request?
    // RequestData should be available as a constant in appInsights.Contracts, but it's missing in 0.22
    if (envelope.data.baseType === "RequestData") {
        // Instanceof check is optional. Provides type hinting for baseData
        const reqData = envelope.data.baseData;
        if (reqData instanceof appInsights.Contracts.RequestData && reqData.url === "GET /health-check") {
            return false; // Stop telemetry from being sent
        }
    }
    return true; // Allow telemetry to be sent
});
```

**Comment by luismendozamx** [comment]
Awesome! Thank you so much for the answer @OsvaldoRosado

**Comment by OsvaldoRosado** [comment]
You're welcome!
