### ISSUE TITLE
Integration with a system that has existing correlation semantics

### ISSUE THREAD

**Issue by GavinOsborn** [Microsoft/ApplicationInsights-node.js#327]
**Scenario**
You are looking to adopt application insights to an existing API.
This API already has a mechanism for providing correlation with other services.
This could be:
 - An arbitrary header `x-correlation-id`
 - contained within the inbound Bearer token
 - ... etc

**Question**
1) Is it possible to integrate the existing correlation mechanism with application insights?
2) If yes, should we? Is there a good reason not to.

Thanks in advance

**Comment by OsvaldoRosado** [comment]
I think this is something @SergeyKanzhelev has been looking into

**Comment by SergeyKanzhelev** [comment]
@GavinOsborn correlation in Application Insights is defined by data model, automatic context propagation and UI on top of it. 

Generally we recommend to rely on Application Insights correlation as it will enable correlation across multiple services/languages and with different azure resources going forward. We are trying to make it no-op for you to get correlation enabled.

If you have your own correlation mechanism you have two options:
1. Add those correlation parameters as custom properties so default correlation will be provided by Application Insights. But you'd always have extra information that will allow to correlate based on your own properties.
2. Replace fields in data model with your custom correlation fields. This way your own correlation identifiers will be used and natively shown in UI. However you'd need to make sure it's consistent across all your services.

Hope it answers your question.

CC: @lmolkova, @qubitron

**Comment by GavinOsborn** [comment]
To close this off - @SergeyKanzhelev thanks for your update.
We went down the custom parameter approach - worked like a charm. :-)
