### ISSUE TITLE
Bunyan logger cannot send logs back to app insights

### ISSUE THREAD

**Issue by MichaelTsengLZ** [Microsoft/ApplicationInsights-node.js#338]
Hello. I'm using bunyan logger in a project and the documentation said that:
`Note that by default setAutoCollectConsole is configured to exclude calls to console.log (and other console methods). By default, only calls to supported third-party loggers (e.g. winston, bunyan) will be collected. You can change this behavior to include calls to console methods by using setAutoCollectConsole(true, true).`
But I bunyan logger cannot sent log back to app insights. Do you  have any documentation about that? Thank you so much.

**Comment by MichaelTsengLZ** [comment]
It turns out that the sequence of require app insights and bunyan matters. 
`
var appInsights = require('applicationinsights');
var bunyan = require('bunyan');
`
This solve my problem.

**Comment by DaveA-W** [comment]
> It turns out that the sequence of require app insights and bunyan matters.
> 
> ```
> var appInsights = require('applicationinsights');
> var bunyan = require('bunyan');
> ```
> This solve my problem.

Hi @MichaelTsengLZ is your bunyan stream for App Insights something you'd be willing to publish a gist on?  (or package / open source..)

**Comment by brianpham93** [comment]
> just wanted to mention that @MichaelTsengLZ finding also applies for winston.

Yay this works! I spent several days to find out why winston logs were not collected while still worked in another project with same appinsights configurations

**Comment by diwakersurya** [comment]
Also check the version of the dependency you are trying to integrate see more here https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel-publishers/README.md
