### ISSUE TITLE
Track Metric doesn't accept properties

### ISSUE THREAD

**Issue by kthayer424** [Microsoft/ApplicationInsights-node.js#34]
I think we should be able to add meta data to the metrics we track similar to the C# library.

**Comment by scsouthw** [comment]
Thanks, @kthayer424. I think this was a point-in-time back-end limitation. We'll try to get this into the next release.

**Comment by kthayer424** [comment]
:+1:

**Comment by kamilszostak** [comment]
`TrackMetric` takes properties now - https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Client.ts#L111
