### ISSUE TITLE
Dependency calls over HTTPS are not detected on Node 8.x

### ISSUE THREAD

**Issue by benc-uk** [Microsoft/ApplicationInsights-node.js#352]
Seems like any dependency call that goes over HTTPS is not tracked. 

For example I have a demo app which makes two backend API calls to different REST APIs, only the HTTP one is appearing in App Insights. Anything over HTTP is not getting picked up. See screenshot

In addition any Cosmos DB calls are not detected either, which naturally go over HTTPS

This is with Node 8.9.1 running in a Azure App Service

![image](https://user-images.githubusercontent.com/14982936/33184020-800bb47a-d072-11e7-8ec3-52553237b184.png)
 
## EDIT: This seems to be a problem with Node 8.x. I've switched my app to run on Node 6.9.1 and the HTTPS dependencies started coming through! :)

**Comment by OsvaldoRosado** [comment]
This is interesting. It sounds like there's something special going on in the `request` library.

The following short snippet shows dependencies generated for native https calls)
```
var appInsights = require("applicationinsights");
appInsights.setup("IKEY").start();
appInsights.defaultClient.channel.send = console.log; // Send telemetry to console rather than AI

var https = require("https");
https.get("https://google.com");
```

**Comment by benc-uk** [comment]
Interesting. However I'm not sure it is related to the `request` library, as none of my Cosmos DB calls were detected until I switched to Node 6.9.1. Looking in the Cosmos DB client library source code, they don't use `request`, they use the native `https` method

**Comment by OsvaldoRosado** [comment]
This was due to internal changes in node on 8.9. If you update your SDK to 1.0.1 you should be able to use Node 8.9 and still retain autocollection.

Please feel free to reopen if you're still experiencing this!
