### ISSUE TITLE
Logging setting

### ISSUE THREAD

**Issue by v-geberr** [Microsoft/ApplicationInsights-node.js#359]
Is there a public method to turn on logging? I turned it on with Logging.enableDebug = true; in .\Library\Logging.js but it would be nice to see logging without touching something inside node_modules.

**Comment by OsvaldoRosado** [comment]
You can use `appInsights.setInternalLogging(true, true)` to enable logging. The first argument enables/disables debug logging, the second enables/disables warning

**Comment by OsvaldoRosado** [comment]
It depends which version of this SDK you're using. In 0.22 as well as all stable releases (1.0+) this method is `setInternalLogging`, in releases before that there are two methods: `enableVerboseLogging` and `disableVerboseLogging`

**Comment by v-geberr** [comment]
In case someone comes looking for this, here is what worked for me: appInsights.Configuration.setInternalLogging(true,true);
