### ISSUE TITLE
Session information are missing 

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/ApplicationInsights-node.js#36]
The node sdk used to report a session object that contains an Id. It's not the case any more. Is this by design?

**Comment by scsouthw** [comment]
Session Id is only captured / set in request auto collection. I don't think there's a clear definition of sessions otherwise. However, the data contracts support the field for any scenario. You can manually assign session Id for a client like this:

```javascript
// get a client with default instrumentation key
var ApplicationInsights = require("applicationinsights");
var client = ApplicationInsights.getClient();

// assign a session Id for the client
var sessionKey = client.context.keys.sessionId;
client.context.tags[sessionKey] = 'sessionId';

// all telemetry tracked with this client will have the session Id set
client.trackEvent('event with session');
```

You could also set the session Id for the default instance (which is used for all auto-collection) like this:

```javascript
// assign a session Id for the default client
ApplicationInsights.client.context.tags[sessionKey] = 'sessionId';
```

**Comment by mrmckeb** [comment]
@scsouthw I have two questions on this one... 

I understand that I'd need a new client for each request, but then I'd also need to be able to pass that new client into my other modules/controllers/routes that referenced Application Insights. Currently I import the exposed client to those modules from a util (as below), but do you have a suggested clean way of doing this a client per request?
```
AppInsights
    .setup(appInsightsKey)
    .setAutoCollectRequests(false)
    .start();

export default AppInsights.client;
```

On the topic of the `sessionId` itself, is the most efficient way to use the same `sessionId` as the client (JavaScript SDK) to grab it from the cookie at the start of the request? Or is that already available on the Application Insights client somewhere when auto collect is disabled?

**Comment by scsouthw** [comment]
Sorry for the late response. I'm not sure if there's a good way to accomplish this. You could try caching clients based on the session ID from the JS SDK but that could lead to other issues. 

It's worth noting this SDK attempts to extract sessionID set by the JS SDK here:  https://github.com/Microsoft/ApplicationInsights-node.js/blob/1fab950e65dfa4d3a5c09a1df4e7c33a4e6e23c3/AutoCollection/RequestDataHelper.ts#L119-L129

So, if you are using this in conjunction with the browser SDK it should already be setting session ID automatically. If it's not that would be a bug. 

If you're not using the JS SDK but want this behavior just set a cookie with ai_session on your first response to the client and subsequent requests should hit the session ID code above. Would that work?

**Comment by mrmckeb** [comment]
Thanks, that makes a lot of sense. I'm working cross-domain, so I'll need to play around some more as browsers like Safari block third-party cookies (which is a headache) - that should be solvable I think.
