### ISSUE TITLE
Cannot see node exception stack trace in the portal

### ISSUE THREAD

**Issue by amitbend** [Microsoft/ApplicationInsights-node.js#363]
Hey, I'm using this library on a node.js bot framework chatbot.

I'm trying to send a full stack trace for exceptions, but all I can see in the portal are Exceptions with the title: `Microsoft.Bot.Schema.BotTimeoutException`
And with a body of  `POST to <botname> timed out after 15s`

This is the configuration on the bot:
```
    const appInsights = require("applicationinsights");
    const appInsightKey =<key>;
    appInsights.setup(appInsightKey)
        .setAutoCollectRequests(false)
        .setAutoCollectPerformance(false)
        .setAutoCollectExceptions(true)
        .setAutoCollectDependencies(false)
        .setAutoCollectConsole(true,true)
        .start();
```
Am I doing something wrong?

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this! Are you able to see the full details of these exceptions in Analytics? It's possible these details are being sent but not presented in the Portal UI - or that the SDK is mistakenly placing the details in the wrong field.

**Comment by amitbend** [comment]
Hey @OsvaldoRosado.
I looked at the details, I cannot locate the stack trace. 

I can see data about the conversation like `Conversation ID,Bot ID` under `customDimensions`
Under `parsedStack` I can see `method` with the value  `Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext` and similar values in the other fields (nothing looks like Node)

**Comment by OsvaldoRosado** [comment]
That doesn't look like an exception collected by this SDK (seems like .NET to me!). Can you share a snippet of your calls to `trackException`?

**Comment by amitbend** [comment]
I do not call `trackException`, i set the `.setAutoCollectExceptions(true)` so it will be sent automatically.
In botframework settings there is a part for the application insights. it might be the one who is overriding the node stack traces?
![image](https://user-images.githubusercontent.com/11259265/34639735-2e4f35be-f2ee-11e7-9a43-80e71a625e11.png)

**Comment by OsvaldoRosado** [comment]
In general ‘autoCollectExceptions’, collects only unhandled exceptions. I don’t believe your stack traces are being overridden, but rather the telemetry is coming from outside your application code and from the bot framework service itself, explaining why it would have a C# stack trace. 

To verify, you could comment out the lines you use to setup this Node.js SDK - while still keeping that enabled in bot framework settings. I would expect you would still get these exceptions in your telemetry even though your application code would have had no way to send it.

If this guess is right, you should use ‘trackException’ within your own code in places where you want to collect Node.js stack traces.

**Comment by amitbend** [comment]
@OsvaldoRosado I will test it, and post results later.
Thanks.

**Comment by amitbend** [comment]
Ok, so now it seems I'm getting both node exceptions and the underlying system exceptions.
By default, i would like to eliminate the second, as it doesn't give me much info to work with.

Closing for now,
Thanks for the help @OsvaldoRosado
