### ISSUE TITLE
Disable IP address collection

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/ApplicationInsights-node.js#364]
I'm using app insights to add telemetry to our VS Code extensions. Things work really well, but there is one issue:

How can I disable the collection of the Client IP address per event? And I guess I'd really also like to not collect City and "State or province". I already have a filter running that I added via ``addTelemetryProcessor``, but the envelope I get there doesn't have those fields, they must be added at some later point in the pipeline.

I don't want to collect that information because it potentially is user-identifying (because it would give away the client machine IP address where someone is running VS Code), so from a privacy point of view I don't want that data, plus we also really don't need it.

**Comment by OsvaldoRosado** [comment]
A telemetry processor is the correct way to disable collection of "user" IPs from a traditional server point of view. This breaks down a bit when the service is actually the user itself as I believe we fallback to the "server" IP address (eg. whatever talked to our telemetry ingestion endpoint) and add that IP into the telemetry at the time of ingestion on our own service side.

I'm not sure if there's a way to disable this, although IP address is sanitized during processing on our service side to not be personally identifiable within your telemetry. @Dmitry-Matveev if I recall, you were looking at potentially user-identifying data like IP address. Do you know where this stands today?

**Comment by davidanthoff** [comment]
Ah, actually, now that I look at the IP address that gets recorded for my own system, it ends with ``.0``, whereas it actually is a real number. Is that what is happening, i.e. the last part is replaced by ``.0`` always? I think that would be ok for now, although it would still be nice if we could disable collection of that information entirely.

**Comment by OsvaldoRosado** [comment]
>  Is that what is happening, i.e. the last part is replaced by .0 always?

That's correct, in IPv4 the last octet is always removed. Similar rules are applied for IPv6 data (though with many more segments removed due to IPv6 potentially being more identifiable). 

@Dmitry-Matveev Do you know if this is becoming more aggressive for further protection or if there's a way for users to disable this collection done by our backend?

**Comment by Dmitry-Matveev** [comment]
@davidanthoff , the last octet of IPv4 (and IPv6) is currently removed for privacy reasons. City and Country/Region are identified on AI endpoint from IP and it's immediately anonymized as the next step.

If IP is not submitted from SDK, then the IP of the sender is taken, which in case of VS Code will be client IP address. To avoid this you can make SDK submit dummy IP like "0.0.0.0" with telemetry processor/initializer, then AI Endpoint will take that value over the sender IP (this will lead, however, to inability to extract City and other location info from such address).

There is a discussion to remove IP from the storage at all (not only the last octet) and keep only City and Country/Region, this has not landed yet as of my knowledge.

**Comment by OsvaldoRosado** [comment]
Closing this, as IP is now always sanitized to 0.0.0.0 at ingestion time (although after City/Location is extracted). Forcing a dummy IP like @Dmitry-Matveev described will disable City/Location as well.
