### ISSUE TITLE
MongoDB automatic integration not working

### ISSUE THREAD

**Issue by rogeralsing** [Microsoft/ApplicationInsights-node.js#366]
I might be doing something wrong here.
But I'm using MongoDB 2.2.33 which is within the range of supported MongoDB libs.

I'm seeing my frontend, my backend and remote HTTP services appear in the ApplicationInsights graph.

But I'm not seeing anything related to MongoDB.
Am I supposed to activate this somehow or configure anything?
I'm just doing 

```javascript
appInsights
  .setup("my-i-key")
  .setInternalLogging(true, true)
  .setAutoDependencyCorrelation(true)
  .setAutoCollectRequests(true)
  .setAutoCollectPerformance(true)
  .setAutoCollectExceptions(true)
  .setAutoCollectDependencies(true)
  .setAutoCollectConsole(true, true)
  .setUseDiskRetryCaching(true)
  .start();
```

**Comment by OsvaldoRosado** [comment]
As a quick first thing to check, are you doing `require('applicationinsights')` as the first require in your application? This SDK has to be required before anything else in order to patch libraries like `mongodb` correctly.

**Comment by OsvaldoRosado** [comment]
Closing for now. Please feel free to re-open if the reordering suggestion didn't solve the problem for you!

**Comment by ydogandjiev** [comment]
@OsvaldoRosado, I am also running into this issue.

This is what my Application map looks like:
![image](https://user-images.githubusercontent.com/3357245/40904660-4637116c-6790-11e8-8040-2ef17a31a1b7.png)

You can see all of the code in my project here:
https://github.com/ydogandjiev/taskmeow

These are the relevant packages I'm using:
```
applicationinsights@1.0.3
mongodb@3.0.6
mongoose@5.0.14
```

I am using an Azure CosmosDB via its MongoDB API. Any idea why the ApplicationInsights library is failing to track DB dependency?

**Comment by eegabeeva** [comment]
@ydogandjiev did you find an answer? I was wondering if `applicationinsights` would instrument `mongoose` or if for this to work I must use `mongodb` directly.

**Comment by markwolff** [comment]
@ydogandjiev @eegabeeva It should work for mongoose as of latest applicationinsights version `1.2.0`. This version adds support for mongodb 3.x, which mongoose takes a dependency on.
