### ISSUE TITLE
TypeError: this._handle.unref is not a function

### ISSUE THREAD

**Issue by alyssonlopes** [Microsoft/ApplicationInsights-node.js#367]
I get this exception just starting the Node.js appInsight v1.0.1:

```
node_modules/applicationinsights/out/AutoCollection…:28 Uncaught TypeError: this._handle.unref is not a function
    at AutoCollectPerformance.enable (/node_modules/applicationinsights/out/AutoCollection…:28)
    at Function.start (/node_modules/applicationinsights/out/applicationins…:68)
    at edebelix.js:6
AutoCollectPerformance.enable @ /node_modules/applicationinsights/out/AutoCollection…:28
start @ /node_modules/applicationinsights/out/applicationins…:68
(anonymous) @ edebelix.js:6
```
Js Code:

```
var appInsights = require("applicationinsights");
appInsights.setup(MY_KEY)
            .start();
```
I'm trying to use the SDK in a electron App.

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this? Which version of Node.js are you running? Docs seem to indicate unref should exist since 0.9.1 https://nodejs.org/api/timers.html#timers_timeout_unref

**Comment by OsvaldoRosado** [comment]
Just saw the update about electron. Are you trying to reference this from the frontend HTML rendering? If so, you'll want to use https://github.com/Microsoft/ApplicationInsights-js instead.

**Comment by alyssonlopes** [comment]
Thanks for your reply.
So i can't use the Node.js version in electron renderer, right?
In this case, how can I use some functions from the Node.js version, like trackNodeHttpRequest?

**Comment by OsvaldoRosado** [comment]
I think you have two options here.

1) You can treat this like a typical webpage + server setup and instrument them separately. Requests on the server side, page views on the client side, and using our server and client side SDKs.

2) You can use only the Node.js SDK for server-side instrumentation, and manually expose its track methods to your frontend. This lets you use only one SDK, but you'll lose the things we've written in our client side js SDK (like automatic AJAX collection and page load performance).

**Comment by OsvaldoRosado** [comment]
Pinging @KamilSzostak in case he's seen any suggested guidance for this before from the JS side

**Comment by alyssonlopes** [comment]
Thank you so much for your help @OsvaldoRosado.

**Comment by Tyriar** [comment]
FYI we're still hitting this in VS Code where we run the module in an Electron window. https://github.com/microsoft/vscode/issues/151109

Even though it doesn't look like you specifically target web, you can prevent this exception by supporting both environments like so:

```ts
const x = setTimeout(...) as number | NodeJS.Timeout;
if (typeof x !== 'number') {
  x.unref();
}
```
