### ISSUE TITLE
Requests and Traces aren't related in Application Insights

### ISSUE THREAD

**Issue by mrmckeb** [Microsoft/ApplicationInsights-node.js#37]
This could be something I'm doing wrong, but the following results in a request and a trace being logged in Application Insights - but for neither of those to be related to the other (not showing in 'Related Items').
```
appInsights.trackRequest(req, res);
appInsights.trackTrace(JSON.stringify(trace));
```

**Comment by scsouthw** [comment]
The 'Related Items' UI is driven by the `operationId` field in the context tags. If you are manually tracking telemetry and want to have several items show as 'Related' in the UI, you can set the operation ID for the client before making a set of calls or create a new client and assign operation ID if your grouping spans async boundaries.

Here is an example setting the operation ID on the default client:
```javascript
// get the default client
var ApplicationInsights = require("applicationinsights");
var defaultClient = ApplicationInsights.client;

// update the operation ID
var operationIdKey= client.context.keys.operationId;
defaultClient .context.tags[operationIdKey] = 'some operation identifier (could be a guid)';

// track telemetry
defaultClient.trackRequest(req, res);
defaultClient.trackTrace(JSON.stringify(trace));
```

Here is an example of how to create a new client (note: in this case context and config are not shared with the default instance)
```javascript
// get a client with default instrumentation key
var ApplicationInsights = require("applicationinsights");
var client = ApplicationInsights.getClient();

// assign an operation Id for the client
var operationIdKey= client.context.keys.operationId;
client.context.tags[operationIdKey] = 'some operation identifier (could be a guid)';

// all telemetry tracked with this operation ID will show as related
client.trackRequest(req, res);
client.trackTrace(JSON.stringify(trace));
```

**Comment by mrmckeb** [comment]
Sorry, I thought I'd replied to this - very poor form. This was exactly what I was looking for, thanks again!

This is a really helpful project, so thanks for all of your hard work on it.
