### ISSUE TITLE
Nested metadata from winston logger shows as [object Object]

### ISSUE THREAD

**Issue by ThomasKruegl** [Microsoft/ApplicationInsights-node.js#371]
We are using the winston logger in a node.js application. We are also using the library express-winston to log our requests. This library utilizes the metadata of winston for request and response details, which are complex objects. From my understanding in this case the following code of winston.sub.ts converts the metadata to properties for AI:
```
client.trackTrace(
            {
                message: event.data.message,
                severity: AIlevel,
                properties: event.data.meta
            });
```

edit: To be precise, it is not a problem of the winston subscription, it is also not possible to log nested metadata directly, using trackTrace(). The conversion actually happens in Util.validateStringMap.

But the type for properties has an index signature, values get typed to string. This causes nested objects to be converted to strings, resulting in [object Object]. Is it possible to change this? I can imagine several possible solutions, but i do not know if there are some limitations in the insights API, or the library. I can imagine:
- Change the type to 'any' (would have to check how this gets serialized and shows up in insights then)
- use util.inspect or JSON.stringify, may need some checks when to apply that.

We are also investigating how we can solve this on our side, finding a way around this in express-winston, or not using express-winston, but i wanted to open the issue, since it is a general problem with nested metadata objects.

regards,
Thomas

**Comment by willmorgan** [comment]
Just a thought, if you're using Winston, have you considered using https://github.com/bragma/winston-azure-application-insights?

**Comment by ThomasKruegl** [comment]
Thanks for the hint :) I think i had seen that library, but had forgotten about it.
If i understand it correctly, we could disable the AutoCollection for the winston console transport (or do not use a console transport, but we want that additionally), and instead use the AI transport provided there.
From a first glance, i guess we would have the same problem though, because that library is at some point just calling
```
this.client.trackTrace(msg, aiLevel, meta);
```
And this will run into exactly the same problem as described above, since it also does not check or convert the metadata before (only some changes for errors).

**Comment by willmorgan** [comment]
I now maintain the library and I'm actually working on logging for my own app this afternoon.

Out of interest, can you paste a few traces from AI here so I can get a bit more of an idea on what you're seeing?

How do you have console logging switched on? Is it `true` or `true, true`?

**Comment by ThomasKruegl** [comment]
We are using the defaults, which is only true, ignoring "console.log".
Here is the relevant code:
https://gist.github.com/ThomasKruegl/7d69cc57157d5e9a5023fd13a36c7524

I am aware that it does not make sense to just send one object as log message and metadata at the same time, it's just to test, and replicate the problem.

What i see in Azure is:
![insights_objobj](https://user-images.githubusercontent.com/22393196/36794975-19127818-1ca2-11e8-943a-825acac7169c.png)

**Comment by willmorgan** [comment]
Hmm that looks interesting, I have a feeling that it might be the console transport of Winston that's causing the issue but I will take a look and get back to you.

**Comment by ThomasKruegl** [comment]
Well i took some time investigating, pretty sure it is not winston. The meta data is showing with full data on the console :)

I just tested a workaround, looks good. I am using a rewriter for winston, we are on version 2.x. Updated gist:
https://gist.github.com/ThomasKruegl/7d69cc57157d5e9a5023fd13a36c7524/026bb086700eaebdabf840003b8190edbcc9f748

**Comment by willmorgan** [comment]
@OsvaldoRosado Looks like [this does some modification of nested objects](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Util.ts#L134-L160) (according to above linked issue) - any chance this could get swapped/changed?

**Comment by OsvaldoRosado** [comment]
Good catch! We can probably do something here to format nested objects in a sensible way before serializing it into the telemetry payload. Labeling as bug to track.

From a quick look, changing the `property.toString()` to `JSON.stringify(property)` may be all that's needed.

**Comment by OsvaldoRosado** [comment]
This should now work correctly in 1.0.6
