### ISSUE TITLE
How to call TemetryClient API in Azure Function App

### ISSUE THREAD

**Issue by pratapprashant** [Microsoft/ApplicationInsights-node.js#372]
To enable AI logging in Azure Function App, I added appsetting key (APPINSIGHTS_INSTRUMENTATIONKEY) as suggested here 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#existing-function-app

To add custom trace, I created AI client (client = appInsights.defaultClient; ) as suggested here
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs#telemetryclient-api
 
None of my custom trace/event/metric are showing up in the Azure Application Insights portal. There are no errors in my Azure Function App. As soon as I remove the appsetting  key (APPINSIGHTS_INSTRUMENTATIONKEY), I can see my custom events in the AI portal but it doesn’t log any Azure Function App specific events. When I add appsetting key back again, I can see Azure Function App events but it doesn’t log any of my custom events.

**How do I log my custom events along with Azure Function App events?**

Similar issue : https://github.com/Microsoft/ApplicationInsights-node.js/issues/346 

Here is my complete code:
```
//const appInsights = require("applicationinsights");
//appInsights.setup();
//const client = appInsights.defaultClient;

let appInsights = require("applicationinsights");
//appInsights.setup("my AI key").start();
//let client = appInsights.defaultClient;

if (!appInsights.defaultClient) {
   appInsights.setup("my AI key ").start();
}
let client = appInsights.defaultClient;
// var client = appInsights.getClient();


module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');


client.trackEvent({name: "1 my custom event", properties: {customProperty: "custom property value"}});
client.trackException({exception: new Error("1 handled exceptions can be logged with this method")});
client.trackMetric({name: "1 custom metric", value: 3});
client.trackTrace({message: "1 trace message"});
client.trackDependency({target:"http://dbname", name:"1 select customers proc", data:"SELECT * FROM Customers", duration:231, resultCode:0, success: true, dependencyTypeName: "ZSQL"});
client.trackRequest({name:"1 GET /customers", url:"http://myserver/customers", duration:309, resultCode:200, success:true});
 
 context.log('ai done.2');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};
```

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this! Which version of the applicationinsights package are you using? We recently released 1.0.2 to resolve some conflicts in the Azure Functions environment.

If you enable full internal logging on this SDK (‘.setup(...).setInternalLogging(true, true)’) do you get any errors in your console log?

**Comment by pratapprashant** [comment]
I am using 1.0.2.
I added this below line and removed the appsetting key, I can see my custom logs but nothing from Function Runtime (example : no logs from context.log() )

if (!appInsights.defaultClient) {
   appInsights.setup("my key").setInternalLogging(true,true);
}

**Comment by OsvaldoRosado** [comment]
The Azure Functions telemetry will only work with that app setting in place, so you should definitely place it back.

I’m curious if we will get information from this SDK with its internal logging as to why it’s not sending your custom telemetry when that App setting is present.

Also, as an FYI, when you place back the app setting you no longer need to specify the key as an argument to setup. You can use ‘setup()’ and it will find the app setting value.

**Comment by pratapprashant** [comment]
Here is my latest code and still doesn't captures my custom logs
(I can see the context.log() but not the traceEvent)

``
    let appInsights = require("applicationinsights");
if (!appInsights.defaultClient) {
   appInsights.setup().setInternalLogging(true,true).start();
}
let client = appInsights.defaultClient;

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
client.trackEvent({name: "1 my custom event", properties: {customProperty: "custom property value"}});
``

**Comment by OsvaldoRosado** [comment]
I can reproduce sporadic (or perhaps just slow) sending of track event with that code sample. assuming `context.done` is directly after.

The problem is that the function finishes execution before telemetry has a chance to be sent. These alternative code samples send the trackEvent as expected for me:
```
// Trigger sending of telemetry immediately and wait for it to finish (safest)
let appInsights = require("applicationinsights");
if (!appInsights.defaultClient) {
   appInsights.setup().setInternalLogging(true,true).start();
}
let client = appInsights.defaultClient;

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    client.trackEvent({name: "Flush quick", properties: {customProperty: "custom property value"}});
    client.flush(callback: () => {
        context.done();
    });
};
```

```
// Trigger sending of telemetry immediately but don't wait for it to finish (fastest)
let appInsights = require("applicationinsights");
if (!appInsights.defaultClient) {
   appInsights.setup().setInternalLogging(true,true).start();
}
let client = appInsights.defaultClient;

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    client.trackEvent({name: "Flush quick", properties: {customProperty: "custom property value"}});
    client.flush();
    context.done();
};
```

These events do live alongside Azure Functions telemetry as expected:

<img width="559" alt="screen shot 2018-03-06 at 8 51 56 am" src="https://user-images.githubusercontent.com/4926351/37045821-aa817cea-211b-11e8-9d98-df47199ccabc.png">

**Comment by landondavidson** [comment]
I am having a similar problem with the events.  The flush seems to fix the issue, but I am not seeing Dependency and Requests get logged.  

I tried the code with the initial report above and added the flush and I see everything shop up in application insights except Request and Dependency calls.  Is there something else that needs to happen to get those to work?

**Comment by OsvaldoRosado** [comment]
@landondavidson 
In Azure Functions, request telemetry is logged by Azure Functions itself. Make sure your Function App has Application Insights enabled and your Instrumentation Key is in the App Setting named `APPINSIGHTS_INSTRUMENTATIONKEY`.

As for dependencies, are you using `trackDependency` or are you trying to use autocollection?

**Comment by landondavidson** [comment]
I do have the `APPINSIGHTS_INSTRUMENTATIONKEY` set and I am using `trackDependency`.

**Comment by OsvaldoRosado** [comment]
@landondavidson 

Which version of this SDK are you using? With the following sample Azure Function, I'm able to get all expected telemetry reported:

```
let appInsights = require("applicationinsights");
if (!appInsights.defaultClient) {
   appInsights.setup().setInternalLogging(true,true).start();
}
let client = appInsights.defaultClient;

module.exports = function (context, req) {
    client.trackDependency({target:"target", name:"name", data:"data", duration:200, resultCode:200, success: true, dependencyTypeName: "type"});
    client.trackRequest({name:"name", url:"url", duration:200, resultCode:200, success:true});
    client.flush({callback: ()=>{
        context.done();
    }});
};
```

![image](https://user-images.githubusercontent.com/4926351/37496846-291f2068-2872-11e8-910a-57100f4ffd52.png)

**Comment by landondavidson** [comment]
1.0.1  I'll give 1.0.2 a shot and see if that fixes my issue.

**Comment by landondavidson** [comment]
upgrading to 1.0.2 fixed it for me.  Thanks!
