### ISSUE TITLE
Support for Massivejs / Pg-promise - Not Collecting SQL Calls

### ISSUE THREAD

**Issue by gpierrick** [Microsoft/ApplicationInsights-node.js#376]
Initial discussion here https://github.com/Microsoft/node-diagnostic-channel/issues/42#issuecomment-373763633

MassiveJS uses pg-promise - application insights doesn't seem to be tracking the SQL Calls

pg-promise uses pg internally

https://github.com/brianc/node-postgres (pg)

https://github.com/vitaly-t/pg-promise/blob/master/package.json (pg-promise)

**Comment by OsvaldoRosado** [comment]
As a workaround while this isn't supported, using `trackDependency` manually would be the way to go here. Depending on how many direct calls you have to MassiveJS there's a few approaches you could do.

- If there aren't too many separate places for it to be painful, simply place `trackDependency` wherever you use massive.
- If there are too many separate places:
  - Wrap your use of MassiveJS in a helper function rather than using it directly. Call `trackDependency` from this helper
  - Create a monkeypatch for MassiveJS (or its internal pg-promise / pg) similar to what this SDK would be doing, so all calls to the library inherently call `trackDependency`
  - Call `trackDependency` from any hooks or logging bits already exposed in the MassiveJS API (I couldn't find any from a quick look, but maybe they exist)

**Comment by gpierrick** [comment]
Thanks @OsvaldoRosado 

As an example this is how my db files access massivejs

```
return new Promise((resolve, reject) => {
            return postgres.db.users.find({ uid: data }).then((res) => {
                return resolve(res[0]);
            }).catch((err) => {
                logger.error(err);
                return reject(err);
            });
        });
```

Could you explain how I would use `trackDependency` here?

What would a monkey patch look like?

**Comment by OsvaldoRosado** [comment]
*Note:* All snippets were written without testing - but should be the right idea.

Using `trackDependency` here would look like the snippet below. It could be cleaned up with some helper methods, but it's a good example of the basics.
```
let client = appInsights.defaultClient;
...
return new Promise((resolve, reject) => {
    let startTime = new Date();
    return postgres.db.users.find({ uid: data }).then((res) => {
        client.trackDependency({ target: 'mydatabase', data: JSON.stringify({uid: data}), name: JSON.stringify({uid: data}),
            duration: new Date().getTime() - startTime.getTime(), success: true, resultCode: "1", dependencyTypeName: "postgres"});
        return resolve(res[0]);
    }).catch((err) => {
        client.trackDependency({ target: 'mydatabase', data: JSON.stringify({uid: data}), name: JSON.stringify({uid: data}),
            duration: new Date().getTime() - startTime.getTime(), success: false, resultCode: "0", dependencyTypeName: "postgres"});
        logger.error(err);
        return reject(err);
    });
});
```

As for a monkeypatch example, you can see the existing one for pg here: https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel-publishers/src/pg.pub.ts If you were to include in your code an updated copy of this for the newer version of pg used by massive, this SDK should automatically pick up the diagnostic-channel events published by it, and do `trackDependency` by itself.

As a simpler example, here's a non-diagnostic-channel monkeypatch that would handle just this particular method from massive and call `trackDependency`.
```
let origFind = postgres.db.users.find;
postgres.db.users.find = (arg) => {
    let startTime = new Date();
    let track = (success) => {
        client.trackDependency({ target: 'mydatabase', data: JSON.stringify(arg), name: JSON.stringify(arg),
            duration: new Date().getTime() - startTime.getTime(), success: success, resultCode: success ? "1" : "0", dependencyTypeName: "postgres"});
    }
    return origFind(arg).then((res) => {
        track(true);
        return res;
    }).catch((err) => {
        track(false);
        throw err; 
    });
};
```

**Comment by MSLaguana** [comment]
One caveat to the above: correlation between incoming HTTP requests and dependency calls may be broken if the `pg` module uses certain code parterns. The events will still exist in AI, but they may not be associated as you expect.

**Comment by OsvaldoRosado** [comment]
Great point @MSLaguana!

The `appInsights.wrapWithCorrelationContext` method can be used to overcome this.

**Comment by gpierrick** [comment]
I am little lost on what to do so I may have to wait for a fix and go to production without app insights

**Comment by vitaly-t** [comment]
SQL calls are collected via [pg-monitor](https://github.com/vitaly-t/pg-monitor), which Massive.js allows you to use.
