### ISSUE TITLE
Add way to force sending batched messages

### ISSUE THREAD

**Issue by dzek69** [Microsoft/ApplicationInsights-node.js#379]
If I'd like to send something just before app exit (with `process.exit(1)` for example) - It won't be send, because this library is batching requests (I'm guessing from reading sources that messages will be really send when there is 250 of them batched or 15 seconds passes).

So I'd have to wait over 15 seconds just to be sure everything is sent or send over 250 messages, which is crazy too.

Is there any way or can you add it to force messages sending?

**Comment by OsvaldoRosado** [comment]
You can use the `flush` method for this. For example:

```
let appInsights = require("applicationinsights");
appInsights.setup().start();

appInsights.defaultClient.trackDependency({target:"target", name:"name", data:"data", duration:200, resultCode:200, success: true, dependencyTypeName: "type"});
appInsights.defaultClient.flush({callback: ()=>{
    process.exit(1);
}});
```

**Comment by dzek69** [comment]
Thanks. This should really go into README.md I think.
