### ISSUE TITLE
The envelope properties init order is not compatible with Xpert (Microsoft Inside)

### ISSUE THREAD

**Issue by XiaoliangHuang** [microsoft/ApplicationInsights-node.js#383]
# Issue
we use this sdk to collect node.js logs, and want to sent this data to [xpert](https://xpert/), and then encountered some problems that the order or envelope properties are not supported.

# Root cause
The requirement is that 'data', 'tags' or 'ext' (part B/C) should appear before name, time, ikey... (part A).
the detailed rule can be find in the following section:

[Http Request Format using JSON](https://osgwiki.com/wiki/Vortex/ClientProtocol):
Although we accept JSON, Vortex requires an order to the fields in the JSON payload. See the [Vortex/EventQuality](https://osgwiki.com/wiki/Vortex/EventQuality) page for details on exactly what you have to do. the rule "FieldsOutOfOrder"

In other strongly typed language like  C#,  new a instance will allocate memories for all the properties as it defined, but in JS,  the memory allocation is based on the order fields added, then when it converted to string (Json.Stringify()), the order will different from its declaration.

# Fix
see the pull request https://github.com/Microsoft/ApplicationInsights-node.js/pull/384

**Comment by hectorhdzg** [comment]
@XiaoliangHuang let us know if this is still relevant, xpert documentation doesn't include any details about JSON format anymore.
