### ISSUE TITLE
Auto collected CPU metric is rejected by app insights endpoint

### ISSUE THREAD

**Issue by lmillott** [Microsoft/ApplicationInsights-node.js#39]
The CPU metrics being sent by the node sdk are being rejected by the app insights endpoint.
If you enable verbose logging you can see this response from the endpoint:
WaWorkerHost.exe Information: 0 : ApplicationInsights:Sender [ '{"itemsRecieved":58,"itemsAccepted":42,"errors":[{"index":0,"statusCode":400,"message":"Metric at index[0] \'% cpu[0] user\' name contains invalid character \'[\'"},{"index":1,"statusCode":400,"message":"Metric at index[0] \'% cpu[1] user\' name contains invalid character \'[\'"},{"index":2,"statusCode":400,"message":"Metric at index[0] \'% cpu[2] user\' name contains invalid character \'[\'"},{"index":3,"statusCode":400,"message":"Metric at index[0] \'% cpu[3] user\' name contains invalid character \'[\'"},{"index":4,"statusCode":400,"message":"Metric at index[0] \'% cpu[4] user\' name contains invalid character \'[\'"},{"index":5,"statusCode":400,"message":"Metric at index[0] \'% cpu[5] user\' name contains invalid character \'[\'"},{"index":6,"statusCode":400,"message":"Metric at index[0] \'% cpu[6] user\' name contains invalid character \'[\'"},{"index":7,"statusCode":400,"message":"Metric at index[0] \'% cpu[7] user\' name contains invalid character \'[\'"},{"index":29,"statusCode":400,"message":"Metric at index[0] \'% cpu[0] user\' name contains invalid character \'[\'"},{"index":30,"statusCode":400,"message":"Metric at index[0] \'% cpu[1] user\' name contains invalid character \'[\'"},{"index":31,"statusCode":400,"message":"Metric at index[0] \'% cpu[2] user\' name contains invalid character \'[\'"},{"index":32,"statusCode":400,"message":"Metric at index[0] \'% cpu[3] user\' name contains invalid character \'[\'"},{"index":33,"statusCode":400,"message":"Metric at index[0] \'% cpu[4] user\' name contains invalid character \'[\'"},{"index":34,"statusCode":400,"message":"Metric at index[0] \'% cpu[5] user\' name contains invalid character \'[\'"},{"index":35,"statusCode":400,"message":"Metric at index[0] \'% cpu[6] user\' name contains invalid character \'[\'"},{"index":36,"statusCode":400,"message":"Metric at index[0] \'% cpu[7] user\' name contains invalid character \'[\'"}]}' ]

**Comment by scsouthw** [comment]
The CPU stuff was always kind of weird because the back-end had some very-specific-to-iis logic for handling system metrics like CPU. If the back-end changed this processing I would guess there are a collection of similar bugs. @BogdanBe @lmillott @BretGrinslade do any of you know if something changed or if there is a way for non-windows platforms to send CPU/network/memory data to App insights without formatting like windows perfmon data?

I think this is the offending line of code: https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/AutoCollection/Performance.ts#L175

For reference here is the error message with formatting:
``` json
{
  "itemsRecieved": 58,
  "itemsAccepted": 42,
  "errors": [
    {
      "index": 0,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[0] user' name contains invalid character '['"
    },
    {
      "index": 1,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[1] user' name contains invalid character '['"
    },
    {
      "index": 2,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[2] user' name contains invalid character '['"
    },
    {
      "index": 3,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[3] user' name contains invalid character '['"
    },
    {
      "index": 4,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[4] user' name contains invalid character '['"
    },
    {
      "index": 5,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[5] user' name contains invalid character '['"
    },
    {
      "index": 6,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[6] user' name contains invalid character '['"
    },
    {
      "index": 7,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[7] user' name contains invalid character '['"
    },
    {
      "index": 29,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[0] user' name contains invalid character '['"
    },
    {
      "index": 30,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[1] user' name contains invalid character '['"
    },
    {
      "index": 31,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[2] user' name contains invalid character '['"
    },
    {
      "index": 32,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[3] user' name contains invalid character '['"
    },
    {
      "index": 33,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[4] user' name contains invalid character '['"
    },
    {
      "index": 34,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[5] user' name contains invalid character '['"
    },
    {
      "index": 35,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[6] user' name contains invalid character '['"
    },
    {
      "index": 36,
      "statusCode": 400,
      "message": "Metric at index[0] '% cpu[7] user' name contains invalid character '['"
    }
  ]
}
```

**Comment by lmillott** [comment]
The backend has a some characters that are not allowed in metric and event names. I think previously there may have been a bug that it was not enforcing the ban for some time, and then started enforcing it again. These are apparently the list of allowed characters:
(symbol >= '0' && symbol <= '9')
                    || (symbol >= 'a' && symbol <= 'z')
                    || (symbol >= 'A' && symbol <= 'Z')
                    || (symbol == '.')
                    || (symbol == '-')
                    || (symbol == '_')
                    || (symbol == '(')
                    || (symbol == ')')
                    || (symbol == '\\')
                    || (symbol == '/')
                    || (symbol == ' ')
                    || (symbol == '#')
                    || (symbol == '%'))

Any other characters would cause this error.
