### ISSUE TITLE
Is it possible to specify the timestamp of a trackMetric call? 

### ISSUE THREAD

**Issue by qimyi** [Microsoft/ApplicationInsights-node.js#391]
Can trackMetric be called with a `timestamp` property so that the timestamp on the envelope be overwritten, instead of using current time?

I have an application where trackMetric will be called in batches and not in real time.

**Comment by OsvaldoRosado** [comment]
You should be able to use the `time` property on all `trackX` calls.

Does doing something like: `client.trackMetric({name: "custom metric", value: 3, time: new Date("December 20, 2018 05:30:00")});` work for you?

**Comment by qimyi** [comment]
That worked. I was using the wrong property name before (`timestamp`). 

I've also got it to work using an `addTelemetryProcessor` method to overwrite `envelope.time` but this is better. 

Thanks @OsvaldoRosado
