### ISSUE TITLE
Connection Leak

### ISSUE THREAD

**Issue by jdadojr** [Microsoft/ApplicationInsights-node.js#402]
I am baffled when I see very high tcp connections in my azure app services using nodejs.
I experimented a bit by removing all http outbound requests , until its just my redis cache getting outside data but the tcp connection is still climbing slowly but surely until it reaches more than 1920 tcp connections in a day.  

Then I  commented out just these
/*
const appInsights = require("applicationinsights");
appInsights.setup(process.env.APPINSIGHTS_INSTRUMENTATIONKEY);
appInsights.start();
const clnInsights = appInsights.defaultClient;
*/
also I don't have any other logging using the clnInsights declared above.

Then I bring back all of my outside http requests and walla, the tcp connections count are stable.

So, why the connection leak?

// "applicationinsights": "^1.0.1",

**Comment by OsvaldoRosado** [comment]
Can you verify you're pulling the latest package version (1.0.3) in your node_modules folder?

To help debug this, can you reproduce the problem when `start()` isn't called (eg. disabling all autocollection)?

If it does still reproduce, does it stop if you set the environment variable `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` to `true`?

If possible, a functioning code sample that demonstrates the problem with the minimum amount of code necessary would be great!

Thanks!

**Comment by jdadojr** [comment]
Yep, the 1.0.3 fixes it. Now tcp connections are low and stable.
Thanks A Bunch
