### ISSUE TITLE
node.js collapse when setup appInsights with error "ReferenceError: Zone is not defined"

### ISSUE THREAD

**Issue by Adidi** [Microsoft/ApplicationInsights-node.js#403]
Full Error:
```

ReferenceError: Zone is not defined
    at Function.CorrelationContextManager.getCurrentContext (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:17:9)
    at Function.EnvelopeFactory.getTags (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:183:88)
    at Function.EnvelopeFactory.createEnvelope (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:70:30)
    at NodeClient.TelemetryClient.track (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/TelemetryClient.js:102:44)
    at NodeClient.TelemetryClient.trackException (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/TelemetryClient.js:55:14)
    at AutoCollectExceptions.handle (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:30:35)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at processEmit [as emit] (/home/adidi/code/AxonizeAdminWeb/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (bootstrap_node.js:378:26)
```

usage is the basic from the docs:
```
const appInsights = require('applicationinsights');
appInsights.setup('MY_KEY').start();
```

applicationinsights: 1.0.3
node: 8.11.2

Thanks

**Comment by OsvaldoRosado** [comment]
Can you verify that npm install installed the zone package?

Is anything put in the console if you change your code to `setup('MY_KEY').setInternalLogging(true,true).start();`

Can you also confirm that this library is your first require?

**Comment by Adidi** [comment]
`cat node_modules/zone.js/package.json`
zone.js package is installed in version `0.7.6`

`const appInsights = require('applicationinsights')` is the first require in my node.js application

running `setup('MY_KEY').setInternalLogging(true,true).start();` gives me this output before the error:
```
ApplicationInsights:CorrelationIdManager [ { method: 'GET', disableAppInsightsAutoCollection: true } ]
ApplicationInsights:CorrelationIdManager [ '152bcc8d-63c9-4c03-b706-1d0f8a75bb7f' ]
```
and After
```
applicationinsights/out/AutoCollection/CorrelationContextManager.js:17        
return Zone.current.get("context");
ReferenceError: Zone is not defined
    at Function.CorrelationContextManager.getCurrentContext (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:17:9)
    at Function.EnvelopeFactory.getTags (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:183:88)
    at Function.EnvelopeFactory.createEnvelope (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/EnvelopeFactory.js:70:30)
    at NodeClient.TelemetryClient.track (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/TelemetryClient.js:102:44)
    at NodeClient.TelemetryClient.trackException (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/Library/TelemetryClient.js:55:14)
    at AutoCollectExceptions.handle (/home/adidi/code/AxonizeAdminWeb/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:30:35)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at processEmit [as emit] (/home/adidi/code/AxonizeAdminWeb/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (bootstrap_node.js:378:26)
```

Thanks

**Comment by OsvaldoRosado** [comment]
Can you please provide a complete minimum-necessary sample that reproduces this issue? I've tried the following script on Windows and macOS with the same version of Node (8.11.2) and this library (1.0.3) and couldn't reproduce the issue.

```
const appInsights = require("applicationinsights");
appInsights.setup("ikey").start();

console.log("Start!");
appInsights.defaultClient.trackException({exception: new Error("test")});
appInsights.defaultClient.flush({callback: () => {
    console.log("Done!");
}});
```

**Comment by Adidi** [comment]
Oh. I run in on Centos 7. I have it on my personal computer and on different servers of mine. All collapse with the same problem.
So can it be concern to linux ? 
```
cat /etc/*release*
CentOS Linux release 7.2.1511 (Core) 
Derived from Red Hat Enterprise Linux 7.2 (Source)
```

**Comment by OsvaldoRosado** [comment]
This seems to work for me within a CentOS container (although perhaps a container isn't sufficient and a full VM is needed?):
<img width="387" alt="image" src="https://user-images.githubusercontent.com/4926351/41651107-978f7b98-7434-11e8-8232-fd4ea5d088b5.png">

In this example the entire contents of `index.js` is the code snippet I provided in the previous reply. Do you get a different result with the same file?

**Comment by OsvaldoRosado** [comment]
If you're able to pinpoint what it is and provide a minimum-necessary sample to reproduce the error, that would be great to help address this!

If not, it might be possible to figure it out just from the list of other NPM packages you reference - but that's much less sure than code that contains a solid repro.

**Comment by OsvaldoRosado** [comment]
@nwabdou85 are you able to provide a sample script that reproduces the problem? Does the script provided above also **not** reproduce the problem for you?

Thanks!

**Comment by nwabdou85** [comment]
@OsvaldoRosado it throw me "ApplicationInsights:Failed to require zone.js "

Is that enough to find the problem?

**Comment by OsvaldoRosado** [comment]
@nwabdou85  Unfortunately it isn't. As far as I can tell so far, this error is specific to a way a project is set up. At least if the cause is the same as @Adidi has where the script at https://github.com/Microsoft/ApplicationInsights-node.js/issues/403#issuecomment-398576919 does not make this error happen, but it happens within his own code.

If you could verify that the script at that comment linked above **does** work for you with no error, it sounds like it's the same situation and we need to figure out what's special about both of your projects that causes this error.

Without a sample script that can make this exception get thrown, it's going to be really hard to make a bug fix.

**Comment by OsvaldoRosado** [comment]
Quick note that you can workaround this problem by using `.setAutoDependencyCorrelation(false)` after `setup()`. This will disable correlation of dependencies/exceptions/events to requests, but will avoid the Zone library.

Of course this is only a workaround. We should still find a way to reproduce this problem and actually fix it so you can use all the features of this SDK.

**Comment by nwabdou85** [comment]
when I change the code to setup('MY_KEY').setInternalLogging(true,true).start();
I ve this error on terminal : ReferenceError: setup is not defined
I use my code on server side;

**Comment by OsvaldoRosado** [comment]
I think you're forgetting to reference the library. 

Working code should look like:
```
const appInsights = require("applicationinsights");
appInsights.setup('MY_KEY').setInternalLogging(true,true).start();
```

**Comment by nwabdou85** [comment]
@OsvaldoRosado 
additional log if it can helps


W20180627-20:03:46.980(2)? (STDERR) in the root directory of your application.
W20180627-20:03:47.492(2)? (STDERR) ApplicationInsights:Failed to require zone.js []
W20180627-20:03:47.535(2)? (STDERR) ApplicationInsights:CorrelationIdManager [ { [Error:  dc.services.visualstudio.com:443]
W20180627-20:03:47.536(2)? (STDERR)     code: 'EAI_AGAIN',
W20180627-20:03:47.537(2)? (STDERR)     errno: 'EAI_AGAIN',
W20180627-20:03:47.538(2)? (STDERR)     syscall: 'getaddrinfo',
W20180627-20:03:47.539(2)? (STDERR)     hostname: 'dc.services.visualstudio.com',
W20180627-20:03:47.540(2)? (STDERR)     host: 'dc.services.visualstudio.com',
W20180627-20:03:47.541(2)? (STDERR)     port: 443,
W20180627-20:03:47.543(2)? (STDERR)     message: ' dc.services.visualstudio.com:443' } ]

**Comment by OsvaldoRosado** [comment]
@nwabdou85 Can you provide which other dependencies you have in your package.json?

As for the additional log, that looks like an unrelated networking error to me. The SDK will retry on these kinds of errors, so it's nothing to be concerned about.

**Comment by nwabdou85** [comment]
theses are the dependencies I ve:

 "dependencies": {
    "@babel/runtime": "^7.0.0-beta.40",
    "applicationinsights": "^1.0.3",
    "babel-runtime": "^6.26.0",
    "bcrypt-nodejs": "0.0.3",
    "chart.js": "^2.7.1",
    "firebase": "^3.5.2",
    "imports": "^1.0.0",
    "intl": "^1.2.5",
    "intl-locales-supported": "^1.0.0",
    "material-ui": "^0.16.3",
    "meteor-node-stubs": "^0.2.11",
    "moment": "^2.20.1",
    "node-opensignal-api": "0.0.3",
    "prop-types": "^15.6.2",
    "react": "^15.6.2",
    "react-addons-pure-render-mixin": "^15.6.2",
    "react-bootstrap": "^0.30.10",
    "react-chartjs-2": "^2.7.0",
    "react-contenteditable": "^2.0.5",
    "react-dom": "^15.6.2",
    "react-firebase-file-uploader": "^2.4.1",
    "react-loadable": "^5.3.1",
    "react-native-listener": "^1.0.2",
    "react-router": "^2.8.1",
    "react-select": "^1.2.1",
    "react-tap-event-plugin": "^2.0.1",
    "reactour": "^1.6.5",
    "zone.js": "^0.8.26"
  }

**Comment by OsvaldoRosado** [comment]
Thanks @nwabdou85 !

What's immediately pointing out to me is your dependency on zone.js. This SDK depends on it as well, but a different version (`0.7.6`). Perhaps both versions are incompatible?

@Adidi do you depend on zone.js as well?

**Comment by nwabdou85** [comment]
@OsvaldoRosado 

For the zone package in the list, I just added it to verfiy if the error remains or goes; it does not make part of my list and I should remove it.

yeah it's a nodejs project; meteor(backend framwork based on nodejs) + reactjs (frontend)

**Comment by nwabdou85** [comment]
And I put the config code in the top of my server file.

**Comment by OsvaldoRosado** [comment]
@nwabdou85 I was able to reproduce the issue you found inside a Meteor project. It looks like the root cause is this bug in `zone.js`: https://github.com/angular/zone.js/issues/850

This bug has been worked around in later versions of `zone.js`, but this library hasn't been updated to be compatible with newer versions yet.

I believe this is not actually the same issue originally reported by @Adidi (as he did not get the `ApplicationInsights:Failed to require zone.js []` message). Because of this, I'm splitting this into two issues. You can follow the meteor related issue (and related analysis + workaround) at: https://github.com/Microsoft/ApplicationInsights-node.js/issues/408

Thanks for the report!

**Comment by nwabdou85** [comment]
@OsvaldoRosado  I thinks it works perfectly. thank's a lot
