### ISSUE TITLE
not detecting cosmos db dependancy

### ISSUE THREAD

**Issue by dinushadev** [Microsoft/ApplicationInsights-node.js#404]
I integrated the app insights with my node js application hosted in app service in azure. It is connect with few dependancies such as key vault, b2c, graph api, web serivce and  cosmos db. but unfotunatly it detect all other dependance except Cosmos Db. 

my configuration. 

appInsights.setup(config.app_insightkey)
.setAutoDependencyCorrelation(true)
.setAutoCollectRequests(true)
.setAutoCollectPerformance(true)
.setAutoCollectExceptions(true)
.setAutoCollectDependencies(true)
.setAutoCollectConsole(true)
.start();

**Comment by OsvaldoRosado** [comment]
Closing this for now. Feel free to reopen if the comments above weren't helpful!

**Comment by hanvyj** [comment]
Does it not track it through the HTTP requests?

**Comment by markwolff** [comment]
@hanvyj That is one avenue, yes. You can also communicate with a cosmosdb via `mongoose`/`mongodb`. Are you seeing it as not working in some scenario?

**Comment by hanvyj** [comment]
I thought the @azure/cosmos library communicated via HTTP (they haven't implemented TCP yet) so expected it to start tracking by default.

Does the auto tracking only work with the default client?

I'm creating one manually with `new TelemetryClient(key)`

**Comment by OsvaldoRosado** [comment]
Automatic tracking is indeed only with the default client. It's important to note that it won't start collection until you configure the default client with `.setup()` and start collection with `.start()`

**Comment by hanvyj** [comment]
Hmm, Changed it from `new TelemetryClient(key)` to:

        appInsights
            .setup(key)
            .setAutoDependencyCorrelation(true)
            .setAutoCollectRequests(true)
            .setAutoCollectPerformance(false)
            .setAutoCollectExceptions(true)
            .setAutoCollectDependencies(true)
            .setAutoCollectConsole(false)
            .start();

Which is called prior to the cosmos usage. I'm still only seeing my explicitly fired events.

**Comment by markwolff** [comment]
Another thing to check is if `.setup()` and `.start()` is called before you require in cosmos (and `http`/`https`) in your app. If either of these modules are required in before app insights, the autocollection probably won't work.
