### ISSUE TITLE
Proper way to flush() before process.exit(1)?

### ISSUE THREAD

**Issue by iandvt** [Microsoft/ApplicationInsights-node.js#405]
What is the proper way to handle flushing telemetry events before exiting a process? I want to be able to track the failed events and exceptions associated to the process not starting successfully. The code snippet below never successfully logs to Application Insights. 

Using applicationinsights": "^1.0.0"
``` ts

process.env.APPINSIGHTS_INSTRUMENTATIONKEY = '';
ai
  .setup()
  .start();

const telemetryClient: ai.TelemetryClient = new ai.TelemetryClient();
telemetryClient.trackEvent({ /* Insert Event */ });
telemetryClient.flush({
  isAppCrashing: true,
  callback: () => {
    process.exit(1);
  }
});
```

**Comment by OsvaldoRosado** [comment]
Telemetry is sent to disk if you use `isAppCrashing: true`, if you disable the flag, your code sample should work correctly.

The idea behind `isAppCrashing` is you use it if you know the app is about to fail and you won't be able to get telemetry out over the network - so its synchronously stored to disk instead. When the app restarts and runs again, the telemetry will be retrieved from disk and sent out to Application Insights alongside the first piece of telemetry sent by that run of the app.

**Comment by iandvt** [comment]
Worked like a charm! Thanks @OsvaldoRosado
