### ISSUE TITLE
ENOTFOUND, ECONNREFUSED, ETIMEDOUT  errors from ApplicationInsights:Sender

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/ApplicationInsights-node.js#413]
As described in https://github.com/Microsoft/vscode/issues/55417, there are instances when we see ENOTFOUND, ECONNREFUSED and ETIMEDOUT errors from ApplicationInsights.

Assuming that these are network issues, what is the recommendation for the consumers of this module on how to deal with it?

We use the `setup` and `getClient` methods on applnsights module
We use the `trackEvent` and `sendPendingData` methods on the appInsights client

Try catching on each of the above doesnt help. The error is bubbling up from ApplicationInsights.Sender in some other way.

We are using 0.18.0 version of the appInsights module.

**Comment by OsvaldoRosado** [comment]
There shouldn't be anything to catch, as the SDK has already caught this error. For these errors, the message in the console is purely informational. You can disable error logging if you're not interested in these messages.

However, if possible, I would _highly_ suggest upgrading to 1.0.3 for this class of issues. This version introduces more advanced logic on console logging for network errors beyond just always and never, with the default only showing errors in the console when the SDK determines it is unlikely to recover from the error (disk retries are disabled or many consecutive retries failed).

**Comment by ramya-rao-a** [comment]
Thanks

**Comment by ramya-rao-a** [comment]
@OsvaldoRosado When using 1.0.3, how do we change the default such that the errors are never shown in the console?

**Comment by OsvaldoRosado** [comment]
@ramya-rao-a You can use the following setup option to disable all SDK error logging. This should hide all network errors.

`.setInternalLogging(false, false)`

**Comment by ramya-rao-a** [comment]
Thanks @OsvaldoRosado, that works.
