### ISSUE TITLE
pg v7 support

### ISSUE THREAD

**Issue by csuich2** [Microsoft/ApplicationInsights-node.js#415]
Per https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel-publishers/README.md, only pg v6 is supported by the diagnostic channel, which means we can't get auto dependency collection for pg v7. pg v6 is now over a year old. Is there any timeline for supporting newer versions of pg?

Although I don't use it, I suspect some folks may like to see pg-pool v2 supported as well since the update to pg-pool v1 was in June of 2017.

**Comment by OsvaldoRosado** [comment]
There's no timeline for supporting newer versions at the moment, but this is a great enhancement to track!

I'd encourage you to open a similar feature request against the node-diagnostic-channel repo, since we'll be able to gain support in the Application Insights SDK when a publisher is available within `diagnostic-channel`.

**Comment by csuich2** [comment]
Will do. Thanks!

**Comment by marty2bell** [comment]
Is there any update on this......we have just hit this whereby we are not getting any telemetry from application insights for our Postgres databases using version 7 which as previously commented, has been released for well over a year!!

**Comment by OsvaldoRosado** [comment]
@marty2bell Nothing new yet. I'm sure PRs to `diagnostic-channel-publishers` for this would be welcome!

In the meantime, `trackDependency` is the way to go, whether through direct calls where you call `pg`, making a helper method that calls `trackDependency` and `pg`, or monkeypatching the relevant `pg` methods (just like `diagnostic-channel-publishers` would have done)
