### ISSUE TITLE
Is winston 3.0 supported?

### ISSUE THREAD

**Issue by wy193777** [Microsoft/ApplicationInsights-node.js#417]
I tried this with winston 3.0, but cannot get any trace event on application insight.

**Comment by OsvaldoRosado** [comment]
Only winston 2.x is supported currently. You can see the support matrix for third-party libraries at https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel-publishers/README.md

**Comment by OsvaldoRosado** [comment]
There's no current timeline to share, but I expect a PR adding the proper monkeypatches into diagnostic-channel-publishers would be welcome!

**Comment by markwolff** [comment]
@wy193777 Updating this thread to mention that winston 3.x is now supported in latest version `1.2.0`

**Comment by wy193777** [comment]
Thanks for sharing!
