### ISSUE TITLE
How to avoid all monkey patches?

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/ApplicationInsights-node.js#425]
We use the `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` env variable to avoid the monkey patching of third party libraries as suggested in https://github.com/Microsoft/ApplicationInsights-node.js#automatic-third-party-instrumentation

But even after doing this, we see that the `require` package itself is monkey patched in the [diagnostic-channel](https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel/src/patchRequire.ts) module.

We use the default settings, i.e we dont use any of the AutoDependencyCorrelation, AutoCollectRequests, AutoCollectPerformance, AutoCollectExceptions, setAutoCollectDependencies, setAutoCollectConsole features.

Given this, is there any way we can avoid all monkey patching altogether?

This is related to https://github.com/Microsoft/vscode-extension-telemetry/issues/16 and is stopping us from upgrading the app insights module in VS Code

**Comment by OsvaldoRosado** [comment]
Can you expand more on using the default settings? The default settings has all of those autocollectors on, so you'll need to be in a non-default state to disable them - or simply don't call the start method.

Here's an example that disables all monkey patching for me, are you able to reproduce this behavior?

```
// Must be before requiring applicationinsights
process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = true;

// Store require to verify it hasn't changed
const originalRequire = require;

// Initialize applicationinsights
const appInsights = require('applicationinsights');
appInsights.setup('ikey'); // Don't call start! or alternatively call false on all of the setAuto methods

// Test using applicationinsights
appInsights.defaultClient.trackEvent({name: 'test'});
appInsights.defaultClient.flush();

// Verify originalRequire is still === require
console.log("require is not tampered: ", originalRequire === require);
```

**Comment by MSLaguana** [comment]
For a workaround, if you are able to run `global.diagnosticsSource = {}` prior to loading application insights then that should make diagnostic-channel believe that require has already been patched, and avoid patching require.

In the longer term this is something that should probably be supported properly in diagnostic-channel.

**Comment by MSLaguana** [comment]
Ah, just read your comment and saw that you already suggested an equivalent workaround. as well :)

**Comment by ramya-rao-a** [comment]
@OsvaldoRosado 

> Can you expand more on using the default settings? The default settings has all of those autocollectors on, so you'll need to be in a non-default state to disable them - or simply don't call the start method.

Yes, we set all of those to false. See https://github.com/Microsoft/vscode-extension-telemetry/blob/6ea39e70f0eef767a02c2d15f0a27c6cc7a1cc7a/src/telemetryReporter.ts#L50-L65

> We could potentially avoid this by avoiding requiring diagnostic-channel entirely when we see this environment variable - or diagnostic-channel could be updated to not patch require if there's no subscribers present.

I do see a TODO statement for the same at https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel/src/channel.ts#L128-L137

> For a workaround, if you are able to run global.diagnosticsSource = {} prior to loading application insights then that should make diagnostic-channel believe that require has already been patched, and avoid patching require.

Are there any other potential pitfalls of doing this?

**Comment by MSLaguana** [comment]
The only problem with `global.diagnosticsSource = {}` is if someone else wanted to enable diagnostic channel. Even if they `require('diagnostic-channel')` again it will be detected as already-run by node, and so it wouldn't initialize itself and would remain essentially disabled.

**Comment by OsvaldoRosado** [comment]
The pitfall is a bit worse than remaining disabled. Diagnostic channel will look enabled to code that knows how to use it and will crash when access is attempted (try the code sample above but add `.start()` after `.setup()`

I would highly suggest saving the initial contents of `global.diagnosticsSource`, and the `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` environment variable and setting them back after you've initialized the AI SDK - avoiding this problem for other code that you don't control (which I presume is potentially any VSCode extension).

You don't need them set beyond initialization anyway to prevent your own use of the AI SDK from being starting patching. You should be able to restore these variables as soon as you finish running `require("applicationinsights")`

**Comment by OsvaldoRosado** [comment]
Closing as the workarounds discussed here no longer are necessary as of v1.0.5
