### ISSUE TITLE
Add TrackAvailability method

### ISSUE THREAD

**Issue by Orekhov** [microsoft/ApplicationInsights-node.js#429]
[TrackAvailability](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient.trackavailability?view=azure-dotnet) method is very useful in cases when availability tests feature can't be used. It is available in the .NET package, but is missing in node.js.

This method is very valuable to have in node.js as this platform is used a lot for writing tests. (We already have a few cases, where it is required)

**Comment by devaradhanm** [comment]
@OsvaldoRosado , is there any update on this issue?
