### ISSUE TITLE
HttpDependencyParser.ts uses non-compliant `url.parse()` instead of `url.URL()`

### ISSUE THREAD

**Issue by avoidwork** [microsoft/ApplicationInsights-node.js#432]
Hi,

`HttpDependencyParser.ts` should be using `new URL()` to generate a correctly parsed URL object, specifically the `pathname`. The root issue is `url.parse()` is very flawed, and was replaced quite awhile ago by the WHATWG compliant `url.URL` constructor.

Example (purposefully flawed URL results in flawed parsing):

![screen shot 2018-10-04 at 6 31 51 am](https://user-images.githubusercontent.com/369698/46468756-5daac400-c79f-11e8-922d-0c68e4eaedcd.png)

**Comment by OsvaldoRosado** [comment]
This will probably need special casing, since this SDK has backcompat to Node 0.10, and if I'm reading documentation correctly the URL constructor was introduced in Node 7.

In case anyone is looking to contribute a PR, `url.parse` is also used in at least `HttpRequestParser.ts`, `TelemetryClient.ts`, and `Util.ts`

**Comment by avoidwork** [comment]
Hi,

As someone who authors a few things... I can honestly say that trying to support 0.10 today is going to hurt the project. You should be targeting current LTS and when one loses support that'd be a chance for an LTS branch on this project.

Anyone running old node in production or on a dev machine today is either a masochist or not the target audience. ;)

**Comment by OsvaldoRosado** [comment]
I wouldn't be very surprised if we reduced the version support in our next major release, but this would need special casing regardless. I anticipate Node 6 would still fall into support by this SDK as it's a maintained LTS line until well into 2019 :smile:

**Comment by avoidwork** [comment]
nice.
