### ISSUE TITLE
Type Error in NodeHttpRequestTelemetry.d.ts

### ISSUE THREAD

**Issue by Bene-Graham** [Microsoft/ApplicationInsights-node.js#433]
TSC is giving the following error `[ts] Namespace '"http"' has no exported member 'ServerRequest'.` in  `/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpRequestTelemetry.d.ts`

``` ts
export interface NodeHttpRequestTelemetry extends Telemetry {
//....

    request: http.ServerRequest; //<-- Error is here

//....
}
```

Application Insights Version: 1.0.5
NodeJS Version: 10.10.0

**Comment by OsvaldoRosado** [comment]
Do you have the node types package `@types/node` installed?

**Comment by Bene-Graham** [comment]
Yes I do `"@types/node": "10.11.5"`

**Comment by OsvaldoRosado** [comment]
It looks like the name for this type changed to `http.IncomingMessage` at some point. In previous node types, `http.ServerRequest` continued to be defined. See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8fcdf2d62c222fd34f27d5bc3f1321aa2eecc6da/types/node/v9/index.d.ts#L1115 where it was available in types up to Node 9.

As a workaround until we publish an update that won't have tsc complain with Node 10 types, you can define the ServerRequest interface manually and map it directly to IncomingMessage (they're compatible for our purposes). Alternatively you can use Node 9 types.

Here's an example where the ServerRequest interface is defined manually that properly compiles with Node 10 types. You could do it in code like this or in a separate d.ts file.

```
import * as appInsights from "applicationinsights";
import * as http from "http";

appInsights.setup("ikey");

declare module "http" {
    export class ServerRequest extends http.IncomingMessage {}
}

const server = http.createServer((req, res) => {
    appInsights.defaultClient.trackNodeHttpRequest({
        request: req,
        response: res
    });
    res.end("Hello!");
});

server.listen(1337);
```

**Comment by OsvaldoRosado** [comment]
Another workaround is to not attempt to compile the SDK's internal d.ts files. You can do this by specifying the following in your tsconfig.json:
```
{
    "compilerOptions": {
...
        "skipLibCheck": true
    }
}
```
