### ISSUE TITLE
Application insights not logging requests with long urls

### ISSUE THREAD

**Issue by chuckwatson87** [Microsoft/ApplicationInsights-node.js#436]
I am attempting to log all http requests that come through our expressjs application, and have been mostly successful.  But I noticed that for one route, there are no requests being logged in App Insights.  I have a hunch that it is because the URL is too long,  but I haven't been able to totally confirm that.  The URL in question includes a SAML token and ends up being about 5500 characters long.  

I see [here](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-data-model-request-telemetry#url) that url has a maxlength of 2048 characters.  So I have a few questions on that, that I am hoping I can find out:  

1. Is that the url that would be getting logged?  
2. If this URL is too long, is there a way I can increase the maxlength, or another workaround that I could do to be able to log these requests in App insights?
3. Is there a way in Application Insights to view errors/issues that the Insights App may have, and not the app I am tracking.( I realize this question may be outside of the scope of this repo).

**Comment by OsvaldoRosado** [comment]
For 1 and 2, this is the field for the URL that is to be logged. You cannot increase the maximum length as this is enforced by our backend. As a workaround you could truncate the field using a telemetry processor (perhaps this SDK should also be doing this for you). If you'd like to keep the whole field still somewhere in telemetry, you could report the full URL in a trace telemetry item, which has a [max length of 32,768 chars][0].

Could you expand more on 3? Do you mean view errors the SDK itself throws?


[0]: https://docs.microsoft.com/en-us/azure/application-insights/application-insights-data-model-trace-telemetry?toc=/azure/azure-monitor/toc.json

**Comment by chuckwatson87** [comment]
Thanks for the suggestions on 1 and 2.  For number 3, yes the errors the SDK itself throws.  

Like in my example, I was just assuming that the URL was too long, but is there anywhere that actually tells me that?

**Comment by OsvaldoRosado** [comment]
Out of the box this error is silent, but you can see it in your console if you enable verbose logging with `setInternalLogging(true, true)`.

Going further than that, you can forward the verbose log (along with other console log output) to Application Insights with `setAutoCollectConsole(true, true)`.

For example, this code:
```
let appInsights = require("applicationinsights");

appInsights.setup("ikey")
    .setInternalLogging(true, true)
    .setAutoCollectConsole(true, true)
    .start();

// Generate long Url
let url = "http://reallylongurl.com/";
for (let i=0; i<5000; i++) {
    url += 'a';
}

appInsights.defaultClient.trackRequest({
    name: "Test long request",
    duration: 200,
    resultCode: 200,
    success: true,
    url: url
});
```

Results in this telemetry: 
![image](https://user-images.githubusercontent.com/4926351/46983221-626f5200-d094-11e8-8e9e-328246334644.png)


As an alternative for this particular case. `client.flush` takes an optional callback argument where you can get and parse the success / failure response from the backend and fire telemetry about it as you wish.

**Comment by chuckwatson87** [comment]
Thanks for the information.  With  .setInternalLogging(true, true) and  .setAutoCollectConsole(true, true), I was able to see exactly what the issue was, and put together a processor.  In our case we don't have to see the entire url in Application Insights.  Just need to log the request.  So, I was able to do the following to truncate the request.  

```javascript

const instrumentationKey = 'XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX'

let client;
appInsights.setup(instrumentationKey)
.start();
client = appInsights.defaultClient;
client.addTelemetryProcessor(truncateRequest);

function truncateRequest(envelope, context) {
    let instrumentationKeyNoDashes = instrumentationKey.replace(/-/g, '');
    if (envelope.name == `Microsoft.ApplicationInsights.${instrumentationKeyNoDashes}.Request`) {
        if (Object.keys(envelope.tags).includes('ai.operation.name')  &&  envelope.tags['ai.operation.name'].length > 1024) {
            let operationName = envelope.tags['ai.operation.name']
            envelope.tags['ai.operation.name'] = operationName.substring(0, 1000)
        }
        let requestName = envelope.data.baseData.name;
        envelope.data.baseData.name = requestName.substring(0,1000);
        let requestUrl = envelope.data.baseData.url;
        envelope.data.baseData.url = requestUrl.substring(0,1000);
    }
    
    return true;
}
```
