### ISSUE TITLE
Custom data question

### ISSUE THREAD

**Issue by leemm** [Microsoft/ApplicationInsights-node.js#448]
Hi,

I'm hoping for a little help here.  I've got an hapijs api running and i'm trying to track each key value pair from the querystring, and add them as custom data.  I just can't figure out how to do this.  I'm currently trying traceTrace but nothing appears to show.  I can see the common property showing up.

Second quick question: if i use client in this way do I need to use trackNodeHttpRequest?

```
appInsights.setup(this.config.insights.key);
appInsights.start();
appInsights.defaultClient.commonProperties = {
    environment: process.env.NODE_ENV || 'development'
};

let client = appInsights.defaultClient;

server.ext('onPreResponse', (request, h) => {
    client.trackTrace( request.query );
    client.trackNodeHttpRequest({ request: request.raw.req, response: request.raw.res });
});
```

I want to show up here.

![alt text](http://i.imgur.com/LBjIHDP.png "Insights")

Thanks in advance.

**Comment by leemm** [comment]
Thanks so much, I'll try it out and see what happens tomorrow.

**Comment by leemm** [comment]
@OsvaldoRosado This works very well thank you.  However, is it possible to use a similar method for payload data.  i.e. get Hapi's POST/PUT body and add properties to the baseData as keys.?

It appears the context parameter doesn't include this in any of the properties.

Thanks again.

**Comment by OsvaldoRosado** [comment]
@leemm To put POST parameters from the body into custom dimensions instead of from the querystring you can just slightly modify the example telemetry processor to read the proper fields from the `context['http.ServerRequest']` object.

This is slightly tricky since you'll have to re-parse the request body inside the telemetry processor. To avoid duplicating the work hapi does for you, you can export the field during your hapi request handler. Eg:
```
server.route({
    method: 'POST',
    path: '/',
    handler: (req)=> {
        req.raw.req.payload = req.payload;
        return 'Hello world!';
    }
});
```

If you do this, the payload parameters will be in your telemetry processor at `context['http.ServerRequest'].payload`

**Comment by leemm** [comment]
@OsvaldoRosado I can confirm this has worked.  Thanks for all your help.

**Comment by guisouto** [comment]
Hi @OsvaldoRosado! Can you help me solve a problem?
As you posted on 6 Nov 2018, I'm using the example to capture the payload of POST requests. But, I need to capture the responses body. Is there any way I can achieve this?
Follow my code snippet used to capture the payload:

`appInsights.defaultClient.addTelemetryProcessor((envelope, context) => {
      const httpRequest = context['http.ServerRequest'];
      const baseData = envelope.data.baseData;
      if (httpRequest && appInsights.Contracts.domainSupportsProperties(baseData)) {
        if(httpRequest.method === 'POST') {
          baseData.properties['bodyRequest'] =  JSON.stringify(httpRequest.body);
        } else {
          const url = URL.parse(httpRequest.url);
          if (url.query) {
              const pairs = url.query.split('&').map(x => x.split('='));
              pairs.forEach(pair => {
                  baseData.properties[pair[0]] = pair[1] || '<empty>';
              });
          }
        }
      }

      return true;
    });`

Another scenario in which I need help is when I get the ['http.ClientRequest'] context, I can't access the body property, like in the example above. The property is undefined. You do know why?

Thank you! I appreciate your help.
