### ISSUE TITLE
Performance metric - RAM usage should be of process

### ISSUE THREAD

**Issue by Spragalas** [Microsoft/ApplicationInsights-node.js#449]
Performance tracker for 'Private Bytes' tracks os ram usage, but it should be process ram usage.
```
 private _trackMemory() {
        var totalMem = os.totalmem();
        var freeMem = os.freemem();
        var usedMem = totalMem - freeMem;
        var percentUsedMem = usedMem / (totalMem || 1);
        var percentAvailableMem = freeMem / (totalMem || 1);
        this._client.trackMetric({name:"\\Process(??APP_WIN32_PROC??)\\Private Bytes", value: usedMem});
        this._client.trackMetric({name: "\\Memory\\Available Bytes", value: freeMem});
    }
```
With current implementation on Application Insights metrics view it shows os ram usage. This is bad if my App Service is running on Shared Resource Group on Azure.

Used memory should be tracked like this:
`var usedMem = process.memoryUsage().heapTotal`

**Comment by Spragalas** [comment]
@OsvaldoRosado when can we expect new build ?

**Comment by OsvaldoRosado** [comment]
@Spragalas There isn't a set date, but I'd expect a new release within a week.

**Comment by Spragalas** [comment]
@OsvaldoRosado Thanks!
