### ISSUE TITLE
Question: can application insights write telemetry via rest based call?

### ISSUE THREAD

**Issue by mandeveloper2** [Microsoft/ApplicationInsights-node.js#454]
We are using oracle mcs node js server for hosting node api and would like to leverage application insights telemetry. Issue is oracle mcs has port open only to rest or soap based calls. For any calls made through application insights to instrument are getting blocked as its not rest/soap based. Is there a way app insight can make calls rest based?

**Comment by OsvaldoRosado** [comment]
@mandeveloper2 Can you provide more details?

If the question is if this SDK sends telemetry using a RESTful interface, the answer is yes and the protocol is defined here: https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/ENDPOINT-PROTOCOL.md

If the question is what IP and ports are used to open spots in your firewall, this is described here: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-ip-addresses
