### ISSUE TITLE
new Buffer() is deprecated

### ISSUE THREAD

**Issue by bpasero** [Microsoft/ApplicationInsights-node.js#458]
Used here: https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Channel.ts#L95

Please see https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor

VSCode will soon update to Electron 3.0.x that ships with a node.js version where this prints a deprecation warning on the console so it would be great to get this fixed.

**Comment by OsvaldoRosado** [comment]
Thanks for spotting this! This will probably need special casing for us to use old and new depending on what's available at runtime, since it looks like `Buffer.from(array)` was only introduced in Node 5.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by bpasero** [comment]
@OsvaldoRosado can we get a release with this fix?

**Comment by markwolff** [comment]
hey @bpasero We will be releasing v1.0.8 tomorrow. I'll update this thread once we release

**Comment by markwolff** [comment]
@bpasero published 1.0.8
https://www.npmjs.com/package/applicationinsights/v/1.0.8
