### ISSUE TITLE
trackMetric not working

### ISSUE THREAD

**Issue by FerdinandvHagen** [Microsoft/ApplicationInsights-node.js#46]
For some reason I can't get trackMetric to work.
My code is something like
```javascript
var appInsights = require("applicationinsights");
appInsights.setup("<id>").start();

appInsights.client.trackEvent("Hello World");        
appInsights.client.trackMetric("RegisteredPushChannels", Math.random * 1000);
````

The event Hello World shows up but I cannot find anywhere RegisteredPushChannels in the Metrics Explorer.

Any ideas?

Best regards

Ferdinand

**Comment by scsouthw** [comment]
I think this might be related to #39, are you still seeing the issue since version 0.15.7 was published?

**Comment by FerdinandvHagen** [comment]
Just updated to 0.15.7. I have a line
appInsights.client.trackMetric("OpenChannels", Object.keys(timer).length);

But I can't find OpenChannels anywhere in the Metrics Explorer. If I track it alongside of an event I can find it?!

**Comment by jeffwilcox** [comment]
Track Metric working great now; given these comments are from 2015, should this issue be closed by a maintainer?
