### ISSUE TITLE
Memory leaks detected

### ISSUE THREAD

**Issue by simpliciti-238** [Microsoft/ApplicationInsights-node.js#463]
We have implemented the ApplicationInsights package and it works like we expect, however my gulp test-all is coming back with a memory leak:

The following leaks were detected:diagnosticsSource, __zone_symbol__Promise, __zone_symbol__Error, Zone, __zone_symbol__setTimeout, __zone_symbol__clearTimeout, __zone_symbol__setInterval, __zone_symbol__clearInterval, __zone_symbol__setImmediate, __zone_symbol__clearImmediate

Any ideas what could be the problem or how to get around this? Example implementation below:

`const applicationInsights = require('applicationinsights')

applicationInsights.setup(env.APPINSIGHTS_INSTRUMENTATIONKEY)
applicationInsights.defaultClient.context.tags[env.APPINSIGHTS_KEY] = env.APPINSIGHTS_ROLENAME
applicationInsights.start()

const client = applicationInsights.defaultClient

function appInsightsLogger (message, exception) {
  if (exception != null) {
    client.trackException({exception: new Error(message)})
  }
  client.trackEvent({name: 'My Custom Event', properties: {customProperty: message}})
}
`

**Comment by OsvaldoRosado** [comment]
I'm not sure how gulp determines what is or is not a memory leak, but my first guess given that its reporting from `setTimeout` (and related fns) is that this is from the background loops used for resending failed telemetry or collecting performance counters. AFAIK they don't leak in that they increase memory consumption over time, but they do - by design - persist in the background.

You can try `.setUseDiskRetryCaching(false).setAutoCollectPerformance(false)` before `start()` to see if this guess was right.

**Comment by simpliciti-238** [comment]
> I'm not sure how gulp determines what is or is not a memory leak, but my first guess given that its reporting from `setTimeout` (and related fns) is that this is from the background loops used for resending failed telemetry or collecting performance counters. AFAIK they don't leak in that they increase memory consumption over time, but they do - by design - persist in the background.
> 
> You can try `.setUseDiskRetryCaching(false).setAutoCollectPerformance(false)` before `start()` to see if this guess was right.

Thanks, I managed to do away with some of the errors by setting .setAutoCollects to false, will just see which ones we need and which ones we don't. I am now left with **detected:diagnosticsSource** and this seems to be coming from **const applicationInsights = require('applicationinsights')** if I put the require in a function then no leaks are detected but it looks very unusual having a require within a function and I have seen a few articles suggesting not to do that with good reason.

Any other thoughts to get rid of the last issue?

**Comment by OsvaldoRosado** [comment]
The last one sounds like its our use of diagnostic-channel to patch the `require` method (and subsequently use that to patch popular libraries and record telemetry about them).

You can try adding `process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = true;` to the top of your file to disable diagnostic-channel patching.

**Comment by simpliciti-238** [comment]
Many thanks, that's done it for me.

**Comment by markwolff** [comment]
@simpliciti-238 
Just updating this thread to mention that this issue may have been fixed by https://github.com/Microsoft/ApplicationInsights-node.js/pull/478, so a workaround might not be necessary anymore.
