### ISSUE TITLE
Using trackEvent or trackException causes error

### ISSUE THREAD

**Issue by dfenske** [Microsoft/ApplicationInsights-node.js#482]
I'm using v1.1.0 of this package (looks like it was just released yesterday?). I have gotten set up with the basics, but when I try to add a trackEvent or trackException in my JavaScript code, I get an error:

```
import * as appinsights from 'applicationinsights';
appinsights.setup(appInsightsId);
appinsights.start();
....
appinsights.trackException({
    exception: new Error("handled exceptions can be logged with this method")
})
```

results in 

```
These dependencies were not found:

* async_hooks in ./node_modules/cls-hooked/context.js
* child_process in ./node_modules/applicationinsights/out/Library/Sender.js, ./node_modules/
async-listener/index.js
* console in ./node_modules/diagnostic-channel-publishers/dist/src/console.pub.js
* dns in ./node_modules/async-listener/index.js
* fs in ./node_modules/applicationinsights/out/Library/Context.js, ./node_modules/applicatio
ninsights/out/Library/Sender.js and 1 other
* module in ./node_modules/diagnostic-channel/dist/src/channel.js, ./node_modules/diagnostic
-channel/dist/src/patchRequire.js
* net in ./node_modules/async-listener/index.js

To install them, you can run: npm install --save async_hooks child_process console dns fs module net
TypeError: applicationinsights__WEBPACK_IMPORT
ED_MODULE_0__.trackException is not a function
```

I tried installing the packages it suggests installing but that di not fix the problem. Any ideas on how to fix this? I also tried reverting to v1.0.8 to see if that fixed the problem but still got a similar error.

**Comment by OsvaldoRosado** [comment]
Which version of Node.js are you using? I'm noticing webpack in your error which would suggest client-side JS rather than Node. Is this an Electron or Meteor environment?

**Comment by OsvaldoRosado** [comment]
`async_hooks`, `child_process`, `console`, `dns`, `fs`, `module`, and `net` are all part of Node as built-in modules. 

Is there a way in NextJS to instruct webpack that these modules are inherently part of the server system? It is of course important to ensure that this code isn't used on the client side. (If you need to use Application Insights there we have a separate client-side SDK for that)

**Comment by dfenske** [comment]
I'm not sure how I would tell NextJS that the module is part of Node... I am not using the code on the client-side though. I am using the client-side SDK on the client side, and this package on the server-side. It seems weird that it looks like it's looking for those modules in my `node_modules` folder. Is there any chance this is a bug on your side and happening for other people as well?

**Comment by OsvaldoRosado** [comment]
I think this problem is specific to NextJS limitations on only supporting APIs that are available in both the server and client. It seems to relate to https://github.com/zeit/next.js/issues/173 and https://github.com/zeit/next.js/issues/4552#issuecomment-395519758

Here's a workaround you can do - though I'm not sure how particularly stable it is.

Have the following in next.config.js:
```
module.exports = {
    webpack: (config) => {
        config.node = {
            console: false,
            child_process: 'empty',
            dns: 'empty',
            fs: 'empty',
            module: 'empty',
            net: 'empty'
        };
        config.externals = {
            "async_hooks": "async_hooks",
            "console": "console"
        };
        return config
    }
};
```

In your code file, use this SDK in the following way:
```
const isServer = typeof window === 'undefined';
if (isServer) {
    try {
        const appInsights = require("applicationinsights");
        appInsights.setup('ikey').start();
        appinsights.defaultClient.trackException({ exception: new Error("Exception!") });
    } catch (e) {
        // Ignore client-side processing
    }
}
```

Another workaround I saw was to use a separate server (or supply Next with a custom one: https://github.com/zeit/next.js/#custom-server-and-routing) to perform Node.js-specific operations.

**Comment by dfenske** [comment]
Got it - thank you for your thorough response! I will check these options out.

**Comment by markwolff** [comment]
Are you seeing other telemetry from this package in the portal at all?

**Comment by dfenske** [comment]
I see all the automatic stuff that comes with running appinsights.start(), yes. Just not any of the custom telemetry I'm trying to send.

**Comment by OsvaldoRosado** [comment]
Some things to try here. When setting up the SDK, add `setInternalLogging(true, true)` to enable debug logging. Then after `trackException`, add `appinsights.defaultClient.flush()` to avoid having to wait for batching.

You should also provide an Error object to `trackException`, rather than a string.

One extra note, you might not need the `isServer` and try/catch stuff if you've moved this code directly to an express server.

**Comment by markwolff** [comment]
Your setup looks correct to me. You can try adding `.setInternalLogging(true, true)` and see if anything comes out. You can also try setting the batching interval to 0 (`appinsights.defaultClient.config.maxBatchIntervalMs = 0`), or calling `appinsights.defaultClient.flush()` after each manual track.

**Comment by OsvaldoRosado** [comment]
Can you console.log the value of `appinsights` and `appinsights.defaultClient`? Are they available?

**Comment by dfenske** [comment]
Oh! Nevermind! The exceptions showed up - I just wasn't seeing them before. I see them now! I think the main fix was the fact that I needed to send an 'Error' type object instead of a string. Thank you so much!

**Comment by dfenske** [comment]
Actually it might also be that the .flush() worked, because now I see all the custom events and exceptions I was trying to send earlier... with the timestamps from like, an hour ago. So somehow they all started making it into Azure? Maybe .flush() was what it needed to actually send them? Do you know if that's possible?

**Comment by OsvaldoRosado** [comment]
`flush()` simply speeds up the process. By default, telemetry is sent every 15 seconds (or after 250 telemetry items are waiting to send. If your app was terminating faster than that, the telemetry may have been saved to disk to try sending later.

Do note that even after telemetry is sent from your app, it will take several minutes to appear in the Azure Portal as your telemetry makes its way through our backend ingestion pipeline. Typically ingestion latency is under 10 minutes.

**Comment by dfenske** [comment]
Ok. Thanks for all your help!
