### ISSUE TITLE
mongodb v3.x.x 

### ISSUE THREAD

**Issue by ma-ha** [Microsoft/ApplicationInsights-node.js#483]
Support for mongodb v3.x.x would be great. 

Currently only v2.0.0 -> v2.3.0 are supported :-(

**Comment by markwolff** [comment]
Supprt for 3.x is current in the works (https://github.com/Microsoft/node-diagnostic-channel/pull/50). I don't have an ETA when it will hit stable, but if you'd be able to trial a beta version I can get it to you a bit earlier

**Comment by markwolff** [comment]
Hi @ma-ha, you can upgrade to `1.2.0`, where it now supports mongodb 3.x
