### ISSUE TITLE
Winston 2.4.4 not working on NodeJS 8 but Console does

### ISSUE THREAD

**Issue by Jonlondon** [Microsoft/ApplicationInsights-node.js#485]
Using Winston 2.4.4 and AppInsights 1.1.0, winston logging doesn't send any data to AppInsights while console.log does. I used the same sample in your documentation 

```
let winston = require('winston');
winston.log('info', "test %s", 'info');
```

I added console.log in nodules_modules locally and nothing shows in winston.sub.js subscriber function.

Thanks.

**Comment by markwolff** [comment]
Hi @Jonlondon, just wondering if you tried to repro this in a standalone test app, or are you seeing this in a built out one?

**Comment by Jonlondon** [comment]
Hi @markwolff, it occurs in a built out one. Let me try in a standalone app.

**Comment by Jonlondon** [comment]
Hi @markwolff.
OK I found why. It works on standalone app, I just forgot to declare appInsights module before my logger module.
