### ISSUE TITLE
Use node-uuid NPM library

### ISSUE THREAD

**Issue by sergey-shandar** [Microsoft/ApplicationInsights-node.js#49]
Consider to use https://github.com/broofa/node-uuid instead of Util.NewGuid() function.

**Comment by jeffwilcox** [comment]
Note that `node-uuid` has been deprecated and they now recommend using the `uuid` package - though it's based on the same bits, just a package rename mostly.

**Comment by OsvaldoRosado** [comment]
Thanks for the suggestion. Closing this as there's little benefit to move off of our already functioning method vs the effort to onboard to a third party dependency (and keep updating from time to time). It doesn't seem worthwhile for one method.
