### ISSUE TITLE
Impossible to change RoleName for autoCollection Request/dependencies

### ISSUE THREAD

**Issue by valereColleville** [Microsoft/ApplicationInsights-node.js#490]
**version : applicationinsights@1.2.0**  
My goal is to monitor a full serverless application with multiple function apps. To have the aplication-map part working and readable into azure-portal i need to separate all function-app role.

Application map is really an interesting things to keep an eyes on everythings very quickly and i really want to have this working!

Actually all auto-collection metrics are seen on azure with the label "Web". I have tried : 

```javascript
appInsights.defaultClient.context.tags['ai.cloud.role'] = 'named-fa';
```
and also:
```javascript
appInsights.defaultClient.addTelemetryProcessor(envelope => {
    envelope.tags["ai.cloud.role"] = "named-fa";
});
```
But in my azure app-map dashboard everythings still showing under "Web" label.
What'is the correct methode to have a named role in app-isight application-map view?

My init : 
```javascript
const appInsights = require('applicationinsights');
if (!appInsights.defaultClient) {
    appInsights.setup().setInternalLogging(true, true).start();
}
appInsights.defaultClient.context.tags['ai.cloud.role'] = 'named-fa';
```
![github_issue_appinsights_js_sdk](https://user-images.githubusercontent.com/6152371/53156416-a7197580-35bf-11e9-9311-5c0ec8f1f6d0.png)

**Comment by valereColleville** [comment]
Ok my bad... i have search for a half day yesterday and just found the solution in the readme today...don't know why i missed it yesterday...

For other bad readers like me solution is:
```javascript
appInsights.defaultClient.context.tags[appInsights.defaultClient.context.keys.cloudRole] = 'named-fa';
```
I think that appInsights.defaultClient.context.keys.cloudRole wich is equals to 'ai.cloud.role' is an object reference in tags array so jsute the string is not enought.

**Comment by elahekaramzade** [comment]
> Ok my bad... i have search for a half day yesterday and just found the solution in the readme today...don't know why i missed it yesterday...
> 
> For other bad readers like me solution is:
> 
> ```js
> appInsights.defaultClient.context.tags[appInsights.defaultClient.context.keys.cloudRole] = 'named-fa';
> ```
> 
> I think that appInsights.defaultClient.context.keys.cloudRole wich is equals to 'ai.cloud.role' is an object reference in tags array so jsute the string is not enought.

I used this approach but still is unknown_service, 
any idea why it could be unknown ?
