### ISSUE TITLE
StartOperation<DependencyTelemetry>("OperationName") issues

### ISSUE THREAD

**Issue by colindooley11** [Microsoft/ApplicationInsights-node.js#491]
Hi, 

Using the following: 
_.Net Framework 4.6.1
System.Net HTTP 4.2.0.0 (HttpClient) 
Microsoft.ApplicationInsights 2.8.1
Microsoft.ApplicationInsights.DependencyCollector 2.8.1_ 

I have a block of code I want to execute which I want all of the related dependency telemetry to be logged with the same operation_Name.   

This "_kind of works_"  **BUT** I am getting interleaved results with **operation_Name** _remaining the same for the next execution_ of this code path  (which is, in effect, the next handling of a message) 

For example I have the following code, which handles a message (An NServiceBus message in this instance)

When it is first handled the operation name should be
PROCESSED: 1 

and the next time 
PROCESSED: 2   
and so on 

It takes a message, does some work and calls off to various external dependencies (Cosmos and Http (via HttpClient))

The logger is registered as singleton

2 different HttpClients are registered as singletons. One is used for _Call 2_ and _3_, and the other for _4_
The HttpClients point to different resources and the first is registered with a delegating handler to add some authentication headers  (this isn't needed for call 4 as this is a different external resource not requiring authentication) 

```
public async Task Handle(MyMessageType message, IMessageHandlerContext context)
{
           using (this.Logger.StartOperation($" PROCESSED: {message.Reference} ))
            {
                // DO SOME WORK 

               // Call Cosmos (http call 1)
              //  Http Call 2
              //  Http Call 3

              //  Http Call 4
           }
     }

```

I get  the log lines I expect, plus some log lines which should have a different operation_Name.  Querying the application insights dependencies collection via:

`dependencies | where operation_Name = "PROCESSED: 1"`

Produces something like:

2019-02-21 | \|jy2Qy6/gJpg=.f0b42cd6_1. | https://cosmos| HTTP | POST |  PROCESSED :1
2019-02-21 | \|jy2Qy6/gJpg=.f0b42cd6_2. | https://httpCall2 | HTTP | POST | PROCESSED :1
2019-02-21 |  \|jy2Qy6/gJpg=.f0b42cd6_3. | https://httpCall3| HTTP | POST | PROCESSED :1 
2019-02-21 | \|jy2Qy6/gJpg=.f0b42cd6_4. | https://httpCall4| HTTP | POST | PROCESSED :1
**2019-02-21 | \|DIFFERENT_OperationId_1. | https://cosmos| HTTP | POST | _PROCESSED :1_**

**NOTE**:  The last line should NOT be included here its operation name **should be PROCESSED: 2**

The operation Ids and parent operation Ids seem to be have reconciled properly,  the operation name is being retained somewhere.  

I'd hazard a guess the underlying ``Activity`` (used in Start operation and taken from a thread local variable?)  is not having its operation_Name correctly set and reset? 

Can someone help, this is driving me to insanity.

**Comment by markwolff** [comment]
Hey @colindooley11, is this a .NET app? You can repost this issue over at https://github.com/Microsoft/ApplicationInsights-dotnet-server and they can try to answer your question

**Comment by colindooley11** [comment]
Hi Really, sorry for the life of me I didn't see the node.js part of the title!
