### ISSUE TITLE
 How to use Developer Mode in Azure Application Insights for node.js

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-node.js#496]
As I know, for c#, it can use this line of code: `TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = true;`

Then in node.js, how to use Developer Mode in Application Insights?

Thanks.

**Comment by markwolff** [comment]
You can use `setInternalLogging`
```ts
const appInsights = require("applicationinsights");
appInsights.setup("<instrumentation_key>").setInternalLogging(true, true);
appInsights.start();
```
https://github.com/Microsoft/ApplicationInsights-node.js/blob/bf66555ad51f2e312866088cd1e006a73f04ee06/applicationinsights.ts#L243-L254
