### ISSUE TITLE
Cannot set the error type when sending trackException

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/ApplicationInsights-node.js#499]
Summarised in this [Stackoverflow Question](https://stackoverflow.com/questions/55307986/how-do-i-set-the-exception-type-in-application-insights-when-raising-an-error-us/55308132#55308132)

The source seems to suggest that the error type which is logged in Application Insights is taken from the exception `.name` property, however setting this does not affect what is logged in the portal. Errors are always logged as 'Error' type.

Is there some other way to distinguish error types?

**Comment by markwolff** [comment]
Thanks for the repro. I've been able to get it to show up in the portal correct with your snippet.
![image](https://user-images.githubusercontent.com/5515583/54874826-17c6d400-4db0-11e9-8f92-808c5d7005fa.png)

Posting my snippet below. If possible, could you let me know if `typeName` is set after `TelemetryClient.js:102` in your example?
![image](https://user-images.githubusercontent.com/5515583/54874838-5d839c80-4db0-11e9-8bdb-36bc35ac9f93.png)

```js
const appInsights = require('applicationinsights');
appInsights.setup('ikey')
  .setInternalLogging(true, true)
  .start();
appInsights.defaultClient.config.maxBatchSize = 1;

class MyError extends Error {
  constructor (msg) {
    super(msg)
    this.name = 'MyError'
  }
}

const error = new MyError('some message')

appInsights.defaultClient.trackException({ exception: error });
```

**Comment by brendanarnold** [comment]
OK, after trying again it seems like ApplicationInsights is now logging the correct exception type - I'm not sure what has changed which is puzzling.

In these situations I would guess that it must be something like I hadn't restarted the app after code changes however I had been working on this for most of the afternoon so that would be surprising.

In any case I'm happy to close and I will continue to monitor.
