### ISSUE TITLE
Question: Azure Functions + node-fetch + SPFetchClient (pnpjs)

### ISSUE THREAD

**Issue by eirikb** [Microsoft/ApplicationInsights-node.js#503]
Is it possible to automatically log every request made using [SPFetchClient](https://pnp.github.io/pnpjs/nodejs/docs/sp-fetch-client/) which I think uses [node-fetch](https://www.npmjs.com/package/node-fetch)?

Based on some other issues I've seen here I made this attempt: https://gist.github.com/eirikb/002a745d5b0b545c83edb883f102c2a4 but I have no idea if this is the best approach.  
It would also be nice if simply all calls done with `node-fetch` in Azure Functions (v2) would be automatically logged to AI, as it already does this with exceptions and `context.log`.

**Comment by OsvaldoRosado** [comment]
From a quick glance at the code of `node-fetch`, it looks like it uses Node's standard http/https objects under the hood (see https://github.com/bitinn/node-fetch/blob/5367fe6a978e01745e4264384a91140dc99a4bf8/src/index.js#L49 )

If this is the case, collection of calls should work automatically out-of-the-box, as long as `applicationinsights` is required before any libraries that reference `node-fetch`. Request autocollection needs to be enabled as well, which is the default case.

Are you finding this doesn't work?

**Comment by eirikb** [comment]
You are right!  
I thought it was my custom code doing it, but all I need is this:
```JavaScript
const appInsights = require('applicationinsights');
if (!appInsights.defaultClient) {
  appInsights.setup().start();
}
```
I tried only doing `require('applicationinsights')` but it didn't seem to be enough.  
Note that `context.log` will write to Application Insights even without `applicationinsights` being added as dependency to the project.

**Comment by OsvaldoRosado** [comment]
This is currently expected. Azure Functions magically handles piping `context.log` for you, as well as generating request telemetry. But for anything Azure Functions doesn't handle itself, you need this SDK loaded up.

Glad fetch collection is now working for you!
