### ISSUE TITLE
Adding Request Headers to Application Insights Events 

### ISSUE THREAD

**Issue by ohall** [Microsoft/ApplicationInsights-node.js#507]
I'd like my request headers for my Hapi app to be included in the events in the Application Insights portal.  It doesn't seem like they are included in the default configuration.  
Do I need to do some customization for this?  Thanks.

**Comment by ohall** [comment]
You can add a custom Telemetry Processor to do this https://github.com/Microsoft/ApplicationInsights-node.js/blob/44330896f58d4e6c2b6c4fec821430f7e1067138/README.md#preprocess-data-with-telemetry-processors

Here's an example:
```
const logHTTPheaders = (envelope, context) => {
  const httpRequest = context['http.ServerRequest'];
  if (httpRequest && appInsights.Contracts.domainSupportsProperties(envelope.data.baseData)) {
    _.forOwn(httpRequest.headers, (headerValue, headerName) => {
      _.set(envelope, `data.baseData.properties.[header-${headerName}]`, headerValue);
    });
  }
  return true;
};

// Telemetry processor to record HTTP request header
appInsights.defaultClient.addTelemetryProcessor(logHTTPheaders);
```

**Comment by OsvaldoRosado** [comment]
For others interested, there's more examples of how to do this with other parts of the data stream from Hapi in #448
