### ISSUE TITLE
Unable to contact qps endpoint, dropping this Live Metrics packet

### ISSUE THREAD

**Issue by KrishnaPravin** [microsoft/ApplicationInsights-node.js#510]
I am using ApplicationInsights-node.js version 1.3.1.
I am using it in express node server, with liveMetrics enabled. `appInsights.setup(_ikey_).setSendLiveMetrics(true).start()`

For couple of minutes live metrics is working fine, but after that I am getting ECONNRESET error.
I restarted the express server several times, the same problem comes again.

I guess [https://rt.services.visualstudio.com/QuickPulseService.svc/post?ikey=_ikey_](https://rt.services.visualstudio.com/QuickPulseService.svc/post?ikey=_ikey_) is closing the connection/dropping the request after a specific time.

This is the error I am getting:
```
ApplicationInsights:Unable to contact qps endpoint, dropping this Live Metrics packet [ { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } ]
```

**Comment by markwolff** [comment]
Hey @KrishnaPravin I expect with this error that the SDK is able to leave the error state after some time. Are you seeing this as not the case after a few minutes? In the meantime I'll look into if the underlying can be resolved

**Comment by OsvaldoRosado** [comment]
@markwolff If this error isn't critical, perhaps the message should be suppressed until it happens a couple of times in a row? (Unless verbose logging is enabled)

Like was done for the ingestion channel in https://github.com/Microsoft/ApplicationInsights-node.js/issues/180#issuecomment-394025939

**Comment by markwolff** [comment]
@OsvaldoRosado agreed. I'm also considering not showing it unless it is actually POSTing data

**Comment by KrishnaPravin** [comment]
> Hey @KrishnaPravin I expect with this error that the SDK is able to leave the error state after some time. Are you seeing this as not the case after a few minutes? In the meantime I'll look into if the underlying can be resolved

For first few minutes after connection reset error, I didn't see any data in the portal. But after few minutes, the error was still logging in my local console but in parallel some data was showing up in the live metrics portal. Another thing to note is, the number of online servers count in the live metrics portal was 0.

**Comment by KrishnaPravin** [comment]
> @markwolff If this error isn't critical, perhaps the message should be suppressed until it happens a couple of times in a row? (Unless verbose logging is enabled)
> 
> Like was done for the ingestion channel in [#180 (comment)](https://github.com/Microsoft/ApplicationInsights-node.js/issues/180#issuecomment-394025939)

In my case the error was getting logged for each second, until I stop the server.

**Comment by ferantivero** [comment]
@markwolff same here. What I'm observing is that my server(s) disconnect and re-connect like every couple of seconds while I'm at the Live Metrics Stream blade.

I think I haven't experienced something like this neither with ASP.NET Core or JAVA SDK live metrics support.

**Comment by markwolff** [comment]
@ferantivero this is likely due to how we are handling communication errors currently. When entering an error state, the SDK will disconnect your server from the live metrics stream and reconnect after a few seconds. Behavior of other SDKs is to essentially ignore the errors and remain in the current state. I most likely update this behavior to match other SDKs in the next update

**Comment by markwolff** [comment]
Changed the logging behavior and ping/post state change behavior in 1.4.0. If connectivity is lost with the live metrics server for an extended period of time, it should take ~2 minutes for your server to appear again due to expected timing fallback logic.
