### ISSUE TITLE
Unable to obtain request metrics

### ISSUE THREAD

**Issue by isabellachen** [microsoft/ApplicationInsights-node.js#514]
I have set up application insights in a middleware in my node app (it's a Strapi backend). I am getting trace logs with this code, but for the life of me, under 'requests', there are no results found. I am using the default setup which I understand is .setAutoCollectRequests(true), so it should be collecting requests as I send them.

```js
const appInsights = require('applicationinsights');

module.exports = () => {
  let isInit = false;
  return {
    initialize: function(cb) {
      strapi.app.use(async (ctx, next) => {
        if (!isInit) {
          appInsights.setup().start();
          var client = appInsights.defaultClient;
          client.trackTrace({ message: 'trace message' });
          console.log('app insights setup');
          isInit = true;
        }
        await next();
        appInsights.defaultClient.trackNodeHttpRequest({
          request: ctx.request,
          response: ctx.response
        });
        console.log('track node http request');
      });
      cb();
    }
  };
};
```

![image](https://user-images.githubusercontent.com/9280665/57447878-575e5800-7258-11e9-8cf4-3000ea98cf6f.png)
![image](https://user-images.githubusercontent.com/9280665/57447895-6fce7280-7258-11e9-8cde-6b2fb4db44be.png)

**Comment by markwolff** [comment]
Hey @isabellachen. To get request telemetry, you will need to add Application Insights to your function via the Azure Portal.

**Comment by devaradhanm** [comment]
@markwolff , I am facing this issue as well. I am running app insights under task of batch pool created with user subscription vm pool. 

```
appInsights
            .setup()
            .setAutoCollectConsole(true)
            .setAutoCollectExceptions(true)
            .setAutoCollectRequests(true)
            .setAutoCollectDependencies(true)
            .setAutoDependencyCorrelation(true);
```
Am able to see traces, exceptions, dependencies. But, I don't see requests logged.

**Comment by isabellachen** [comment]
In the end it was working. For some reason the calls were not logged under request but some other metric. I still don't know why they weren't logged under request, but its a something from Nuxt and not App Insights. At least I think it is...

**Comment by michaelaird** [comment]
@isabellachen / @devaradhanm , we're running into this same issue. AppInsights is showing data in all areas except Requests. How did you resolve this?

(thanks in advance!)

**Comment by markwolff** [comment]
@michaelaird What sort of environment are you running in? Some managed API services and Azure Functions (FaaS) abstract away the request from the node.js runtime, and so this SDK isn't able to autocollect them without some sort of manual instrumentation.
