### ISSUE TITLE
Session and User Id blank for cross domain requests

### ISSUE THREAD

**Issue by lworkman** [microsoft/ApplicationInsights-node.js#518]
I have an angular front-end communicating with my node API running on a different domain. I've successfully managed to get the context headers sending between the two pieces and have the `ai.operation.parentId` property recording correctly. However, both `ai.user.id` and `ai.session.id` are not being set to anything.

Are those expected to be set by the correlation headers? Or am I expected to manage those values myself?

My setup is as follows: 
```
appInsights
  .start()
  .setAutoDependencyCorrelation(true)
  .setAutoCollectRequests(true)
  .setAutoCollectPerformance(true)
  .setAutoCollectExceptions(true)
  .setAutoCollectDependencies(true)
  .setAutoCollectConsole(true);
```

**Comment by markwolff** [comment]
The angular front-end communicating with a node service should have a "Cookie" header in it, which this SDK should parse. Is this header present on your front-end's outgoing requests?
![image](https://user-images.githubusercontent.com/5515583/57814602-0acbbe80-7729-11e9-81e4-e93f3d464c13.png)

**Comment by lworkman** [comment]
The angular front-end is using the latest version of `@microsoft/applicationinsights-web` (2.0.0-rc5) which sends along a `Request-Context` and `Request-Id` header. Should it be sending the `Cookie` header in addition to those two?

**Comment by markwolff** [comment]
Yes it should be sending that header as well. If you see `Provisional headers are shown`, then record a session with `chrome://net-export/` and see if it is in there?

**Comment by markwolff** [comment]
I was able to repro this last week, but it seems to have resolved itself when I tried it today. Are you experiencing the same thing? I am thinking it could have been a chrome or (server) cache issue?

**Comment by lworkman** [comment]
Still not showing up. However, it sounds like this probably an issue with the web implementation. I'll open an issue in that repo.
