### ISSUE TITLE
Unable to properly setup App Insight logging to Azure Portal

### ISSUE THREAD

**Issue by erikschlegel** [Microsoft/ApplicationInsights-node.js#52]
I have a Node app running on my localhost, and I'm receiving the following error when I invoke my trackEvent method. Not sure if there's a limitation with using app insight via browserify, as Im able to write logs to my instance when I run the same code below in my server.js script. 

Fetch API cannot load http://dc.services.visualstudio.com/v2/track. Request header field content-encoding is not allowed by Access-Control-Allow-Headers in preflight response.
index.debug.js:1245 ApplicationInsights:Sender [TypeError: Failed to fetch
    at TypeError (native)]0: TypeError: Failed to fetch
    at TypeError (native)length: 1__proto__: Array[0]

Here's my code. 

import appInsights from 'applicationinsights';
import env_properties from '../../config';

  setupLogging(){
    appInsights.setup(env_properties.APPINSIGHTS_INSTRUMENTATIONKEY).start();
    appInsights.client.trackEvent("login", {message: "Logging worked"});
  },

Here's the outputted request header from verbose logging
headers: Object
Content-Encoding: "gzip"
Content-Length: 473
Content-Type: "application/x-json-stream"

**Comment by SergeyKanzhelev** [comment]
See resolution of https://github.com/Microsoft/ApplicationInsights-node.js/issues/133#issuecomment-260601362
