### ISSUE TITLE
Source maps is missed in npm package

### ISSUE THREAD

**Issue by asvishnyakov** [microsoft/ApplicationInsights-node.js#523]
Every `*.js` file in npm package has `//# sourceMappingURL=*.js.map` at the end, but there is no one `*.map` file in npm package. Because of that I receive a lot of similar warnings from webpack:

> WARNING in ./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/winston.sub.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'winston.sub.js.map': Error: Can't resolve './winston.sub.js.map' in 'E:\my-theme\node_modules\applicationinsights\out\AutoCollection\diagnostic-channel'
 @ ./node_modules/applicationinsights/out/AutoCollection/Console.js 15:12-55
 @ ./node_modules/applicationinsights/out/applicationinsights.js
 @ ./server.ts

**Comment by markwolff** [comment]
Source maps are now included in 1.4.0

**Comment by asvishnyakov** [comment]
microsoft/ApplicationInsights-node.js-native-metrics#2
microsoft/node-diagnostic-channel#60
