### ISSUE TITLE
Node.js process response too late when setAutoCollectDependencies set to true

### ISSUE THREAD

**Issue by asvishnyakov** [microsoft/ApplicationInsights-node.js#524]
It respond ~15 sec instead of usual ~3 sec. If I do setAutoCollectDependencies(false) then all is ok.

**Comment by OsvaldoRosado** [comment]
15 seconds sounds like you’re running into the default batching interval.

If you’re using this SDK in an app that isn’t a typical long-running server and need it to close quickly, consider calling `client.flush()` or setting the batching interval to 0 (through the configuration described in the readme).

Possibly related: #495, #475, #390, #379

**Comment by asvishnyakov** [comment]
Yay! Seems to be truth. Thank you @OsvaldoRosado!
