### ISSUE TITLE
Question: How to send up properties on metrics such that I can split on them in the portal

### ISSUE THREAD

**Issue by SamJarmanPP** [microsoft/ApplicationInsights-node.js#535]
Hey Team,

I'm doing something pretty simple in code:
```
        client.trackMetric({
            name: 'complete_time',
            value: endTime.valueOf() - startTime.valueOf(),
            properties: { notificationServiceEventType: type }, // `type` is a string based enum with 3 possible values
        });
```

However, in the portal, I dont see how to split on this?
![Screen Shot 2019-06-27 at 4 23 21 PM](https://user-images.githubusercontent.com/50305305/60234321-e6522d00-98f7-11e9-9429-2c40cae7ad0a.png)

Is there something I'm doing wrong, or is this not possible?

Thanks,
Sam

**Comment by markwolff** [comment]
Hey @SamJarmanPP for this to work I believe you will need to enable custom metrics dimension alerting. It will only work on dimensions that are ingested after you checked the checkbox.
![metrics](https://user-images.githubusercontent.com/5515583/60288820-dc193a00-98c9-11e9-9d9c-ab9ad4201942.png)

**Comment by SamJarmanPP** [comment]
That did it, thanks! :)
