### ISSUE TITLE
Create React App + Application Insights does not work

### ISSUE THREAD

**Issue by navneet-g** [microsoft/ApplicationInsights-node.js#537]
Hi,

I created a React app using Create React App and then added Application Insights using 
```
yarn add application insights
```

In App.js I use 
```
import * as appInsights from 'applicationinsights';

appInsights.setup("<key>").start();
const client = appInsights.defaultClient;
```

Now when I build the code using
```
yarn build
```

I get following error

yarn run v1.16.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

.\node_modules\cls-hooked\context.js
**Cannot find module: 'async_hooks'. Make sure this package is installed.**

You can install this package by running: yarn add async_hooks.
Following are the version of Node and Npm and Yarn

```
node -v v10.16.0
npm -v 6.9.0
yarn -v 1.16.0
```

**Comment by markwolff** [comment]
Hey @navneet-g this is the Node.js library. Please see [here](https://github.com/microsoft/applicationinsights-js) for the browser compatible SDK for Application Insights
