### ISSUE TITLE
App hangs after trackEvent is called

### ISSUE THREAD

**Issue by peterj** [Microsoft/ApplicationInsights-node.js#54]
Run the code below and the app won't exit after console.log()

``` javascript
var appInsights = require("applicationinsights");

var c = appInsights.getClient("key");
c.trackEvent('some event', {'version': 'foo'});
console.log('All done'); 
```

**Comment by bragma** [comment]
I suspect this is because it is waiting to send messages in background. If you force termination with "process.exit()", the messages will not be delivered.

**Comment by scsouthw** [comment]
Thanks @bragma that sounds correct. @PeterJausovec your use case sounds similar to @SofianHn's. We added a flag to the sender for "offline mode" which causes data to be written to disk in some cases instead of sent to the server. Enabling this might resolve your issue. 

https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Sender.ts#L35

**Comment by PeterJausovec** [comment]
I chatted with @BogdanBe a week or so ago and he mentioned the issue was a timer that was not being disposed, hence not ending the process. 

The workaround for me was to call `setAutoCollectPerformance(false);`.

**Comment by bragma** [comment]
@PeterJausovec  This is similar to a problem with calling "dispose" manually (which I use in my tests). But I'll open another issue for that.

**Comment by OsvaldoRosado** [comment]
The app seems to be able to close if `client.sendPendingData();` is called. This seems to be in line with the suspicion over waiting for sending.

**Comment by AlexBulankou** [comment]
I've verified that using `sendPendingData` addresses the OP's problem.
```
    var c = appInsights.getClient("key");
    c.trackEvent('some event', { 'version': 'foo' });
    c.sendPendingData();
    console.log('All done');
```
