### ISSUE TITLE
session_id and user_id is not populating in AppInsight

### ISSUE THREAD

**Issue by vivek1may** [microsoft/ApplicationInsights-node.js#549]
Sorry if this is not valid .. !
When I tried to log in AppInsight, the session_id and user_id is populating as empty.

for example,
```
appInsights.setup(process.env.MicrosoftApplicationInsightsInstrumentationKey).start();
const appInsightsClient = appInsights.defaultClient;
appInsightsClient.trackEvent({name: "LuisCall"});
```

Is there any configuration needs to be done. I can't find any relevant samples with node.js. 

Thanks in advance.

**Comment by markwolff** [comment]
I don't believe this SDK will start a new session and user server-side, but rather depends on a client-side SDK (e.g. https://github.com/microsoft/applicationinsights-js) to (automatically) propagate the cookie information over to this SDK. Do you have a front-end with your app which is instrumented with the client side SDK? If so, this should all work out-of-the-box, assuming its not CORS.
