### ISSUE TITLE
How to get severity level values

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-node.js#55]
Hi,
I'm working on a transport for Winston logger and I'd like to map Winston log levels to AI's trace levels. I've seen an enumeration of supported levels in the "Contracts" module, but I am not sure on how to extract those values for using in my code. What's the suggested way?
Thanks!

**Comment by scsouthw** [comment]
Not sure I'm understanding the question, but you can set severity by passing it to the trackTrace method of the client: https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Client.ts#L70-L71

I'm not sure what the best way to extract the enum for use in your code would be. It should be possible to import the contracts module after it is installed via npm but the reference path would be messy. I doubt these will change so you could redeclare the enum in your code as a workaround.

**Comment by bragma** [comment]
@scsouthw  sorry, I've not described well what I'm trying to do. As part of my Winston transport, I have to map default Winston's log levels (strings) to App Insight's levels (numbers). 

```js
	var levels = {
...
		crit: 4,	// AI 'Critical' 
		error: 3,	// AI 'Error' 
		warning: 2,	// AI 'Warning' 
...
	};
```

Instead of inserting the numeric values corresponding to AI's levels, I'd like to reference the enum values from the Contracts file, something like this:

```js
	var levels = {
...
		crit: AppInsights.Contracts.SeverityLevel.Critical,
...
	};
```

As you suggest I could import the contracts module, but it's messy. What about making them accessible directly from the ApplicationInsights class? It seems to me that's the only exported symbol from the module.
