### ISSUE TITLE
AI doesn't _seem_ to properly honor the response 'aborted' event

### ISSUE THREAD

**Issue by nulltoken** [microsoft/ApplicationInsights-node.js#550]
Hello,

We're seeing some intermittent issues from one of our dependencies.
It's reported as an exception in LogAnalytics by [@hapijs/wreck](https://github.com/hapijs/wreck) that complains that "Payload stream closed prematurely".

- Googling around (eg. https://github.com/nodejs/node/issues/18756) seems to indicate
that `aborted` is emitted when the socket is prematurely closed.

However, the dependency is reported as a successful call by AI. Which is... well... surprising ;-)

- https://nodejs.org/api/http.html#http_class_http_clientrequest states that _"Unlike the request object, if the response closes prematurely, the response object does not emit an 'error' event but instead emits the 'aborted' event."_

It's entirely possible that I'm reading the code wrong, but I can't find any place where the code subscribes to that event.

Thoughts?

https://github.com/microsoft/ApplicationInsights-node.js/blob/c8fa5b8de5c34a4f50f64fa904aaaa8aa8002fae/AutoCollection/HttpDependencies.ts#L182-L206

**Comment by markwolff** [comment]
> * https://nodejs.org/api/http.html#http_class_http_clientrequest states that _"Unlike the request object, if the response closes prematurely, the response object does not emit an 'error' event but instead emits the 'aborted' event."_

Since this is the case, this is probably a bug on our end. I'll take a look and get it in to the next release. 

Just curious, how would you expect the telemetry to look like on your end for an aborted event? Would it be similar how we are handling the `error` event?

If an abort event occurs, I'm assuming neither the `response` nor `error` events occur? But since you stated that the telemetry is appearing as a success on your end, it makes me think that at least `response` is being emitted?

**Comment by nulltoken** [comment]
@markwolff Thanks for the feedback!

>Just curious, how would you expect the telemetry to look like on your end for an aborted event? 

From an logAnalytics standpoint, I'd very much like the dependency to not be reported with `success=True` even when the reported status code is 200. Driving a bit down that road, I'd even in favor to not report the status code (as the response hasn't been completely sent). That would put under the light that something wrong happened with that dependency.

>Would it be similar how we are handling the error event?

That would seem like a good fit: no resultCode, success=false, and a customDimensions.error property. I wonder if adding to `customDimensions.error` a hint about the kind of event that caused the issue would be interesting.

>If an abort event occurs, I'm assuming neither the response nor error events occur? But since you stated that the telemetry is appearing as a success on your end, it makes me think that at least response is being emitted?

It looks like so. Sorry, I haven't locally repro'd the issue in a dev environment. I went straight from the LogInsights results to AInode.sdk in order to understand how the telemetry was processed.

**Comment by nulltoken** [comment]
@markwolff Hey! Has this been triaged yet?

**Comment by nulltoken** [comment]
@markwolff Hello again 😄 

Any news on that topic?

**Comment by nulltoken** [comment]
@markwolff Hello. Any feedback?

**Comment by markwolff** [comment]
Hi @nulltoken I've stubbed out a PR for this, but I haven't had the cycles to create an environment where an `abort` event will take place. Do you have a repro that I would be able to try my changes on?

**Comment by nulltoken** [comment]
>Do you have a repro that I would be able to try my changes on?

@markwolff Thanks for getting back. Unfortunately, I haven't any repro at hand. As described in the initial comment this has been discovered by analyzing logs and reading the code of AInode.js.

**Comment by nulltoken** [comment]
@markwolff How should we proceed in order to move further?

**Comment by nulltoken** [comment]
@markwolff Kind bump?

**Comment by nulltoken** [comment]
@hectorhdzg It looks like @markwolff is not answering. Would you know someone that could help moving this forward?

**Comment by hectorhdzg** [comment]
@nulltoken sorry about the delay, we do have this item in our backlog and also there is is similar issue #741 raised recently, we will include this work in our next iteration, we need to sync with other SDKs to determine what is the correct way to set the dependency in this case and hopefully is a simple change in our side

**Comment by nulltoken** [comment]
@hectorhdzg Thanks a lot for the feedback!
