### ISSUE TITLE
Does the node sdk have the same concept of telemetry channels as does the dotnet sdk? 

### ISSUE THREAD

**Issue by xtianus79** [microsoft/ApplicationInsights-node.js#556]
As noted here in the [dotnet documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels) telemetry channels handle buffering and transmission of telemetry to the insights service. Is the same principal applied to the node sdk?

**Comment by markwolff** [comment]
Yes this SDK has a Channel and Sender class which handles all of the batching, retries, etc. for telemetry transmission.
