### ISSUE TITLE
Does the node sdk have telemetry initializers as the dotnet sdk has them?  

### ISSUE THREAD

**Issue by xtianus79** [microsoft/ApplicationInsights-node.js#557]
I found this in the source code

/**
 * Application Insights telemetry client provides interface to track telemetry items, register telemetry initializers and
 * and manually trigger immediate sending (flushing)
 */

**Comment by markwolff** [comment]
Yes this would fall under telemetry processors
https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors

**Comment by xtianus79** [comment]
@markwolff it's not the same but you could do the same things with them?  Just wanted to verify that.

**Comment by markwolff** [comment]
Yes you can do the same things with them for the most part. For 99.9% of scenarios, using either definition would suffice.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#itelemetryprocessor-and-itelemetryinitializer
