### ISSUE TITLE
Typo in readme.md, develop branch

### ISSUE THREAD

**Issue by keithfree** [microsoft/ApplicationInsights-node.js#568]
https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/README.md

There is a small typo in a method name in a code snippet within the configuration section. Method setDistributedTracingMode is written incorrectly as setDistributedTracing**Tracing**Mode.

**Comment by salmanmkc** [comment]
Fixed, thanks.

**Comment by markwolff** [comment]
Fixed by #567
