### ISSUE TITLE
patchedRequire failing in Ubuntu terminal

### ISSUE THREAD

**Issue by munozemilio** [microsoft/ApplicationInsights-node.js#573]
Botframework CLI uses app insights to track the usage of the tools.
We got a bug opened related to patchedRequire failing in the following settings:
```
OS: Windows 10 Enterprise and Ubuntu's terminal downloaded from Microsoft Store to use the CLI. The current version of Ubuntu is:
$ lsb_release -a
No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 18.04.2 LTS Release: 18.04 Codename: bionic
```

There is a repro in this [bug](https://github.com/microsoft/botframework-cli/issues/373).

**Comment by markwolff** [comment]
Closing this since referencing issue was also closed
