### ISSUE TITLE
Is there a way to send events after > 24 hours of network connectivity loss?

### ISSUE THREAD

**Issue by alyssaong1** [microsoft/ApplicationInsights-node.js#574]
From my understanding of this issue https://github.com/microsoft/ApplicationInsights-node.js/issues/556, like the .NET SDK, the NodeJS SDK implements retries should there be network connectivity loss. 

However, in [this documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#does-the-application-insights-channel-guarantee-telemetry-delivery-if-not-what-are-the-scenarios-in-which-telemetry-can-be-lost), it mentions that items older than 24 hours are discarded. Is this true for the NodeJS SDK as well? Or is this actually a limitation imposed by App Insights itself?

**Comment by markwolff** [comment]
Yes this is an intended limitation of the ingestion server to prevent stale telemetry from being collected. The behavior will be the same across SDKs.

**Comment by alyssaong1** [comment]
Got it, thank you.
