### ISSUE TITLE
AppInsights doesn't flush logs from CLI on process.exit()

### ISSUE THREAD

**Issue by jordanlevy96** [microsoft/ApplicationInsights-node.js#580]
I am running a commandline utility in NodeJS that sends its logs to Azure App Insights. We need to use a `process.exit()` at the end of the program with different codes for our own analytics, but it seems that quitting the program this way prevents the App Insights module from sending its buffer to Azure, since the logs are cut off (i.e., if we had 10 logs in our local console, only 7 of them appear in App Insights). We have even tried manually calling `flush()` to force the propagation, but it has not changed the behavior.

Here is some sample code:

```
const appInsights = require('applicationinsights');
...
console.log('some log message');
...
console.log('last log message');
appInsights.defaultClient.flush();
process.exit();
```
On App Insights, we would only see the first log ("some log message") appear. However, removing the `process.exit()` call makes both appear.

This appears similar to a previous issue, unable to end node process #331. We tried the `dispose()` function to force the propagation after calling `flush()`, but again, no results.

**Comment by bigman73** [comment]
The only workaround I found was to use 
```
process.exitCode = 1; // or any other value
```

I think the expected behavior for flush() is to flush and force sending the data to the AppInsights server.

**Comment by OsvaldoRosado** [comment]
Flush is an asynchronous operation, did you try exiting inside the callback to flush? eg:

```
client.flush({callback: () => process.exit()});
```

In general I would expect there's no opportunity for this SDK to send out telemetry if you call process.exit without flush, since process.exit is an immediate termination operation

**Comment by asklar** [comment]
dang it, I got bit by this too :(
@markwolff @OsvaldoRosado could we please add a note in the readme or somewhere in the doc, that says `process.exit()` will prevent events from being flushed? And in parallel investigate if the sdk can be resilient to process.exit

**Comment by JacksonWeber** [comment]
The callback can be used with flush - solution applies to the latest version.
