### ISSUE TITLE
[BUG] AutoCollectExceptions.enable re-throws an uncaught exception into the ether which can crash the process with status 7

### ISSUE THREAD

**Issue by avoidwork** [microsoft/ApplicationInsights-node.js#584]
**Description/Screenshot**
The `redis` package `retry_strategy` handler appears to have a problem with this feature of the `applicationinsights` package, such that a retry never happens due to this extra throw.

<img width="992" alt="Screen Shot 2020-01-20 at 1 56 42 PM" src="https://user-images.githubusercontent.com/369698/72753496-16626580-3b93-11ea-8f22-025b5940c659.png">

The screenshot above has an event registered for `uncaughtException` but it doesn't execute due to the process exiting with status 7; the trigger of the exception is node.js > net.js > client which is utilized for a `redis` client.

The screenshot below is proper behavior as coded in my app:

<img width="1032" alt="Screen Shot 2020-01-20 at 2 45 57 PM" src="https://user-images.githubusercontent.com/369698/72753723-adc7b880-3b93-11ea-9c03-3ae8dfca06ef.png">

The `uncaughtException` event handler in my code would do some ops, then `process.exit(1)` to trigger a restart with a revised configuration; because this never runs I had processes restart with the same config in production:

<img width="1100" alt="Screen Shot 2020-01-20 at 1 55 41 PM" src="https://user-images.githubusercontent.com/369698/72753626-64776900-3b93-11ea-9469-440c8389c150.png">

**Steps to Reproduce**
1. (with app insights active) using latest redis package connect to a server with a retry strategy defined for the client
2. stop redis, or disconnect the client uncleanly

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**
Application error is logged, application continues to run (no exit 7 status)

**Additional context**
Application is utilizing `tenso` for API server functionality, but that does not handle `uncaughtException` events.

**Comment by markwolff** [comment]
In terms of best practices, when something throws it is meant to convey that your app is in an undefined state and should be restarted, if possible. For this reason, the way this SDK handles uncaught exceptions is that it rethrows them which crashes your app. Even if you have another uncaught exception handler that would swallow them, which seems to be what `retry_strategy` is doing.

What you can do instead is keep autoexception tracking disabled and add your own uncaught error handler yourself to only rethrow if it isn't an exception that `retry_strategy` should be handling. To send telemetry you only need to call `trackException`.
https://github.com/microsoft/ApplicationInsights-node.js/blob/34a23fc9c869ecdd3b800d7748cf5ee81db6411f/AutoCollection/Exceptions.ts#L41-L49

**Comment by avoidwork** [comment]
@markwolff i think there's a fundamental flaw here; the event handlers are arrays of functions, so app-insights handler registers first because it's a dependency, and then mine registers; so 2 event handlers.

The "re-throw" goes no where; it's not the same event that my handler will receives, it's a new event and because it cannot be disabled by config, it crashes node with a status 7 - the redis package & my code cannot get around this because app-insights loads first.

The re-throw is the bug.

**Comment by avoidwork** [comment]
@markwolff the ideal amendment would be to allow me to override the event handler that is generated in code via a second parameter for the `instance.setAutoCollectExceptions(true[, fn]);` method; since your handler has no value it's ideal for me to remove it from the app.

**Comment by avoidwork** [comment]
@markwolff from the node.js docs: https://nodejs.org/api/process.html ... very bottom of the page is the exit codes:

7 Internal Exception Handler Run-Time Failure: There was an uncaught exception, and the internal fatal exception handler function itself threw an error while attempting to handle it. **This can happen, for example, if an 'uncaughtException' or domain.on('error') handler throws an error.**

**Comment by avoidwork** [comment]
@markwolff the test for this feature is absent... https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Tests/AutoCollection/Exceptions.tests.ts ... you're counting registered handlers which is a function of EventEmitter, you're not validating that the system doesn't crash if your code runs.

**Comment by markwolff** [comment]
I don't expect app insights rethrows to be caught by other error handlers you are adding. We rethrow to maintain the default node.js behavior where no error handlers exist. Does the following not solve your problem?

```js
appInsights.setup()
  .setAutoCollectExceptions(false)
  .start();
process.on('uncaughtException', (err) => {
  appInsights.trackException({ exception: err });
});
```

**Comment by avoidwork** [comment]
@markwolff that's not the default behavior. your re-throw is a bug, because node.js itself will crash because the re-throw happens in a function executed on the 'uncaughtExeception' event. Please delete your throw, your tests aren't even proving your assumption.

The alternative is I take it out of my @adobe product stack & replace it with an APM that won't crash the platform I produce.

![Screen Shot 2020-01-27 at 8 12 06 PM](https://user-images.githubusercontent.com/369698/73227354-54d2c400-4141-11ea-8a4f-39bdf12c83fa.png)

**Comment by avoidwork** [comment]
Details are here https://nodejs.org/api/process.html#process_exit_codes

**Comment by avoidwork** [comment]
Elsewhere on that same page:

"The 'uncaughtException' event is emitted when an uncaught JavaScript exception bubbles all the way back to the event loop. By default, Node.js handles such exceptions by printing the stack trace to stderr and exiting with code 1, overriding any previously set process.exitCode."

So as I mentioned, that re-throw is not default behavior because it can only result in status 7 exit due to the documented behavior of a throw inside of an 'uncaughtException' handler.

**Comment by OsvaldoRosado** [comment]
Both rethrowing and not rethrowing seem to induce non-default behavior.

An app that throws an unhandled exception **without** any registered unhandled exception handlers will crash.

An app that throws and unhandled exception **with** an unhandled exception handler will not crash.

Adding this SDK, with unhandled exception tracking enabled, will change the behavior of one of these - the question I suppose is which to mirror by default. 

I'm not sure if there's a good way to detect which state the monitored application is in ( Perhaps check `process.listenerCount("unhandledException") > 1` inside this SDK's exception handler to determine if rethrow is appropriate?) An alternative of course is to ask the user, much like you proposed @avoidwork with an optional parameter to `setAutoCollectExceptions` that can disable rethrowing.

**Comment by OsvaldoRosado** [comment]
Actually looking at the documentation, perhaps this SDK shouldn't even have an unhandledException listener...

```
It is possible to monitor 'uncaughtException' events without overriding the default behavior to exit the process by installing a 'uncaughtExceptionMonitor' listener.
```

**Comment by avoidwork** [comment]
@OsvaldoRosado i disagree about the default behavior; crashing with status 1 when no handler is registered is expected on current versions, and going backwards it used to log a few years ago.

An app that doesn't exit when an 'uncaughtException' happens is flawed; not concerned with this case.

My concern is sourced solely to the rethrow which triggers a status 7 and blocks my handler from doing it's job; the only short term fix is to disable the feature, which creates a reporting gap (not ideal, can't do this long term). If the re-throw didn't exist everything would happen as everyone expected.

**Comment by avoidwork** [comment]
A second bandaid is I register my handler, then load app-insights ... but you always want the APM first.

**Comment by OsvaldoRosado** [comment]
@avoidwork, @markwolff What do you think of this approach? Apps seem to maintain behavior regardless of `hasSDK` (simulating the enabling/disabling of exception autocollection) or `hasOwnHandler` (simulating apps with existing handlers)

```
let hasSDK = true;
let hasOwnHandler = false;

if (hasSDK) {
    process.on("uncaughtException", (err) => {
        console.log("AI SDK handler");
        if (process.listenerCount("uncaughtException") === 1) {
            console.log(err);
            process.exit(1);
        }
    });
}

if (hasOwnHandler) {
    process.on("uncaughtException", (err) => {
        console.log("My app's handler");
    });
}

setTimeout(() => console.log("App is still running"), 0);
throw new Error("My error!");

```

**Comment by avoidwork** [comment]
@OsvaldoRosado lets step back and look at the code in production right now. it expects to catch the re-throw, but that's technically impossible and the test for that module doesn't test the methods it only counts the event handlers.

The problem it's aimed at isn't real, nor is the 'to crash or not to crash' question for app-insights to consider or answer - that's not it's role... it reports.

The fact that the module changes programs based on if it's loaded or not is a significant design flaw that should be reconsidered.

**Comment by avoidwork** [comment]
To explain further, i'd expect app-insights to log a warning when NODE_ENV is not 'production' that it'll change default behavior and block a crash. That'd be ideal, & people can write tests around it.

This behavior would align with more of the ecosystem.

**Comment by OsvaldoRosado** [comment]
>The problem it's aimed at isn't real, nor is the 'to crash or not to crash' question for app-insights to consider or answer - that's not it's role... it reports.

Absolutely agree here. In Node 13.7+, this is simple. I think this SDK should listen to `uncaughtExceptionMonitor` and be out of this business of managing crash state entirely.

Unfortunately in older versions, the only API we have forces us into this question. We should only report, but the only API available to us to report on unhandled exceptions changes program behavior just by listening to it.

Rethrowing was definitely a bug in all cases - as you pointed out there's behavior change in the status code. My intent in the sample snippet is to keep the default behavior in the Node documentation maintained:

>By default, Node.js handles such exceptions by printing the stack trace to stderr and exiting with code 1, overriding any previously set process.exitCode. Adding a handler for the 'uncaughtException' event overrides this default behavior.

https://nodejs.org/api/process.html#process_event_uncaughtexception

So with the technique in my sample snippet, the AI SDK would track the exception, print it out (example is console log but it should go to stderr), and then exit with code 1. If another handler is found, just like Node default, the printing and exit behavior is skipped - allowing the user's own handler to define behavior.

It's important that merely using the SDK doesn't change app behavior - that's how this bug with rethrows was caught after all! Apps that crash without this SDK should always crash with it. By not having any handling to retain default Node exit behavior, I could easily see consumers using this SDK in non-server scenarios (examples here are CLI scripts and desktop programs like VS Code) ending in really unexpected states.

Would the proposed solution in my sample resolve your use case? I believe it should allow your existing handlers to operate as if this SDK were not even on the box

**Comment by avoidwork** [comment]
@OsvaldoRosado Yeah, the proposed solution is fine imo.
