### ISSUE TITLE
How to set dummy IP via telemetry processor?

### ISSUE THREAD

**Issue by makap0120** [microsoft/ApplicationInsights-node.js#587]
I'm trying to disable geolocation data collection and I've stumbled upon this git issue - #364 and it seem I can achieve it by predefining a tag on context param received in telemetry processor. And the question following: 
How exactly should I add dummy IP address as context tag in `addTelemetryProcessor` function? 
My attempts so far (none gave desired result):
```
client.addTelemetryProcessor((envelope, context) => {
    context.locationIp = "0.0.0.0";
    // i've also tried - context.tags.locationIp = "0.0.0.0";
    return true;
});
```

**Comment by markwolff** [comment]
It would be `envelope.tags["context.tags.<whatever tag key name you want>"] = "0.0.0.0"`. Note that I am pretty sure setting custom IPs in this way won't work anymore at ingestion due to gdpr requirements. You can set one in a custom property though.
https://techcommunity.microsoft.com/t5/Azure-Monitor-Status/bg-p/AzureMonitorStatusBlog2018/02/01/all-octets-of-ip-address-will-be-set-to-zero/

**Comment by makap0120** [comment]
@markwolff 
have i got you right - there's no way to disable ip/geolocation data collection from SDK? 

The link you reference adress the opposite issue and there's mentioned "disableIpMasking" property field, which is not even listed in application insight properties list - https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components#ApplicationInsightsComponentProperties 
Is there some generic properties fields for some of azure resource? would be nice if you could link them if there's such.

**Comment by markwolff** [comment]
We do not store the IP address. At the ingestion level, we look from where the telemetry came from (IP address) and use it to determine geolocation and then discard the IP address altogether. Could you provide more context to what you are trying to accomplish? Do you also want to disable the described behavior?

https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection#storing-ip-address-data

**Comment by OsvaldoRosado** [comment]
To clarify about geolocation - the example code mark gave (using `envelope.tags`) will disable geolocation in addition to the general IP masking already applied by Application Insights.

**Comment by makap0120** [comment]
@markwolff basically i need 'city', 'state' and 'country' fields to be empty when i view telemetry e2e transaction details in azure portal. 
![image](https://user-images.githubusercontent.com/25979355/73437479-19104800-4355-11ea-9a87-10194130f771.png)

**Comment by makap0120** [comment]
@OsvaldoRosado , @markwolff i believe this one i should've mention earlier - im using telemetryClient to track my events. In this case overriding envelope tags is not my case, am i right?

**Comment by markwolff** [comment]
Overriding envelope tags will still work if you are using your own telemetryClient as long as you are adding the telemetry processor to that client. The sample you provided at the top should be disabling geolocation on our end (setting the `ai.location.ip` to `"0.0.0.0"`).

**Comment by makap0120** [comment]
@markwolff and it works :^). 
I guess i've been screwing up somewhere in my modules building sequence.

Appreciate the support, thanks.
