### ISSUE TITLE
Device Id is always node

### ISSUE THREAD

**Issue by seanzer** [Microsoft/ApplicationInsights-node.js#59]
It would be nice if Device Id could identify instances of the application running from the same device. "node" is not unique enough to group events coming from multiple instances running on different devices.

**Comment by seanzer** [comment]
It also looks like deviceMachineName is not available on the Azure portal, even though it is set in the Context to os.hostname() -- which would also be an acceptable solution for this scenario

**Comment by bragma** [comment]
I'm using this on an IoT device, we have an HW DeviceId and I'd like to use that instead of "node".

**Comment by scsouthw** [comment]
I don’t remember if there was a good reason to always set the device id to “node” here: https://github.com/Microsoft/ApplicationInsights-node.js/blob/1fab950e65dfa4d3a5c09a1df4e7c33a4e6e23c3/Library/Context.ts#L50

This might be a bug, I'll check with the processing team about it.

As a workaround the value can be set to anything you find useful. Here is an example of how to set the device ID to ```os.hostname()```. @bragma you could do something similar for your HW DeviceID.
```javascript
// get the default client
var ApplicationInsights = require("applicationinsights");
var defaultClient = ApplicationInsights.client;

// update the device ID
var deviceIdKey= client.context.keys.deviceId;
defaultClient.context.tags[deviceIdKey] = os.hostname();
```

**Comment by bragma** [comment]
@scsouthw that's exactly what I do. :-)
It should be nice to set it directly  during configuration.

**Comment by jeffwilcox** [comment]
Hi,
Any updates on whether the default `node` value was a necessary one, @southwood ?

**Comment by southwood** [comment]
@BogdanBe might have an answer. It would be good to get some documentation published around the semantics of these fields. Part of the problem is that a node process might be a server but could also be a device - but I think processing / rendering treats data from the nodejs SDK as always coming from a web server.

**Comment by kamilszostak** [comment]
`device.id` was used for filtering on UI to separate client and server telemetry before we switched to `device.type`. The `id` field is no longer used and we should leave it blank - #102. Users can set the value to anything, but AFAIK the UI doesn't allow filtering based on `device.id`.

Node.js SDK sends `device.type = PC` (#98). This means that telemetry is coming from a server side. Application Insights also accepts `device.type = Browser` which should be used for client side telemetry. 

If you want to identify an instance of the app you can use `ai.device.roleInstance` tag. 

```javascript
appInsights.client.context.tags[client.context.keys.deviceRoleInstance] = "App 1";
```

![image](https://cloud.githubusercontent.com/assets/12164228/16498151/366646ba-3eaf-11e6-8dc7-47fe2964408e.png)
