### ISSUE TITLE
Question: How to manually send performance counters

### ISSUE THREAD

**Issue by jcbit** [microsoft/ApplicationInsights-node.js#599]
Hi,

I had performance counters enabled by default but the amount of data is considerable for me (cost wise) and I don't need that level of granularity (every second). Is there a way to change it for it to be sent every x amount of time (I am fine with hourly or an hourly average for example). Thanks!

**Comment by jcbit** [comment]
And thought about enabling sampling but I have custom metrics I wish to receive 100% of them. Guessing those get affected by reducing the % of samples?

**Comment by markwolff** [comment]
Metrics are not affected by sampling rates -- they are always sent and sampled in. By default we collect several metrics every 1 minute.

I'd imagine you could override this by turning off the default autocollector when you setup the SDK `.setAutoCollectPerformance(false)` and then create your own via this constructor
https://github.com/microsoft/ApplicationInsights-node.js/blob/4a242f60e1e185442752d784da229a7412068b0d/AutoCollection/Performance.ts#L40-L44

**Comment by hectorhdzg** [comment]
@jcbit let us know if you are still having issues with this after Mark's suggestion
