### ISSUE TITLE
[NestJS] Tracking outgoing http request does not work

### ISSUE THREAD

**Issue by golfyos** [microsoft/ApplicationInsights-node.js#602]
Hi,
In the portal azure, I have tried to track the outgoing HTTP requests.

**Example**
Node **A** (Started appinsight)
Node **B** (Started appinsight)

**A** calls **B**
but portal.azure (Application map menu) shows **A** calls something that isn't started appinsight. Like this
![image](https://user-images.githubusercontent.com/21194352/76304028-3f7eb700-62f5-11ea-8ba0-ee3b6dba6f6a.png)

Expected should be:
![image](https://user-images.githubusercontent.com/21194352/76304143-72c14600-62f5-11ea-9a43-153ba323e0ff.png)

In **_Koa_** framework,
I just added `trackNodeHttpRequest({request, response})` at global middleware, It's work.

Please help me,
Thank you.

**FYI**:
-     "applicationinsights": "^1.7.2"
-     node version: 8.12

**Comment by soulcruelz** [comment]
I have this issue also. I have been trying to set up following official documentation but feature autocorrelation does not work.

**Comment by markwolff** [comment]
Are these HTTP calls not automatically tracked for you (with app insights SDK being loaded/started before everything else in your app)?

**Comment by golfyos** [comment]
Outgoing requests were tracked but endpoint(with started app insights) that called is shown as application that's not started app insights following **figure 1**.

Actually, I started app insights of the endpoint that called already following **figure 2**. But the node in application map doesn't link together.

1.
![image](https://user-images.githubusercontent.com/21194352/76591036-ae405800-6521-11ea-9efd-6176d4f5ddad.png)

2. 
![image](https://user-images.githubusercontent.com/21194352/76591251-6110b600-6522-11ea-92e5-e9edb22aef0e.png)
