### ISSUE TITLE
Support for metric dimensions

### ISSUE THREAD

**Issue by henryju** [microsoft/ApplicationInsights-node.js#610]
Comparing the SDK MetricTelemetry.ts and the REST API documentation, it seems there is a mismatch. I can't find any reference to `stdDev` attribute, and all multi-dimensions feature is missing.

Are there any plan to fix that? Would you accept a PR?

**Comment by hectorhdzg** [comment]
@henryju can you provide more details about which REST API documentation you are referring?

**Comment by henryju** [comment]
Sorry, I moved away from this topic, and I can't remember exactly what it was about. Feel free to close this issue.
