### ISSUE TITLE
[Bug] Cannot get operation_Id from this.appInsights.context.tags[this.appInsights.context.keys.operationId]

### ISSUE THREAD

**Issue by ZhimaoLin** [microsoft/ApplicationInsights-node.js#611]
Hi,

## Actual Behavior
I am using Node.js backend with the Node.js version of `applicationinsights@1.7.3`. 
I have initialized `appInsights` with `appInsights.setup("<instrumentation_key>").start();`. However, I cannot get the `operation_Id` through 
```
let operationId = this.appInsights.context.tags[this.appInsights.context.keys.operationId]
```
![image](https://user-images.githubusercontent.com/22060375/78721412-c0c16d80-78e4-11ea-8804-c8acfa0d184d.png)

## Expected Behavior
I am expecting that `this.appInsights.context.tags[this.client.context.keys.operationId]` returns the `operation_Id` after I initialize `appInights` with `appInsights.setup("<instrumentation_key>").start();`

## Environment
Node.js: 12.13.1
applicationinsights: 1.7.3 (Node.js version)
Windows 10 Enterprise OS Build 18363.720
Chrome: Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by markwolff** [comment]
I might be missing some context here. An operation id is started when the SDK handles a request. I would not expect there to be an operation id in the global scope. Where are you trying to grab this? To see the operation id of a handled request, you can view it inside a telemetry processor.

**Comment by ZhimaoLin** [comment]
Hi @markwolff,

I was trying to grab this in a get controller:
```javascript
app.get("/", (req, res, next) => {
  let operationId = this.appInsights.context.tags[this.appInsights.context.keys.operationId];
  res.send("Node Test Rest API")
});
```

When I use Postman to call this get controller, I think App Insights is handling the request. So, I expect to get `operation_Id` through `this.appInsights.context.tags[this.appInsights.context.keys.operationId]`. If not, how can I get the id through telemetry processor?

Thanks!

**Comment by markwolff** [comment]
You can either import in CorrelationContextManager to grab the context from within your handler `CorrelationContextMananager.getCurrentContext()` or access the tags field of the envelope inside a telemetry processor. The telemetry processor would be defined outside your request handler and could not be accessed from within the handler.
