### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by leidegre** [microsoft/ApplicationInsights-node.js#612]
I've noticed a suspicious memory leak issue as of late. I've been using app insights to investigate but I'm starting to think that app insights is the cause of the memory leak, which I find somewhat ironic.

![image](https://user-images.githubusercontent.com/63085/78898729-91da0180-7a74-11ea-9307-448c5fddf1bf.png)

To the best of my ability, `_documents` seem to grow indefinitely. Can anyone help explain why this would be the case. All I can see is that my heap is growing for each snapshot and that the `_documents` array grows with it.

I did some further digging, and it looks like this leak happens because live metrics is not enabled? I'm I right in assuming that the `QuickPulseStateManager` manage live metrics? If live metrics is not enabled why does it retain so much data?

**Comment by markwolff** [comment]
I think the bug here is that calling `setSendLiveMetrics(false)` inadvertently creates a client. If you omit this line altogether, the client won't be created.

**Comment by leidegre** [comment]
Thanks for the quick response.
