### ISSUE TITLE
TelemetryProcessors are not applied for LiveMetrics

### ISSUE THREAD

**Issue by lippinio** [microsoft/ApplicationInsights-node.js#617]
I would like to filter out HealthChecks in an Express Node WebApp so that they are not in the Logs. I added a TelemetryProcessor where I check the URL and drop the healthcheck requests. Everything fine in the search. There this requests are not visible. But in live metrics the healthtest request still flood the stream.

**Comment by cs-ananda-ramos** [comment]
Same here. I tried to add:

```
function removeStackTraces (envelope, context) {
  const data = envelope.data.baseData
  console.log(envelope)
  return !(data.url && data.url.includes('/health'))
}
applicationInsights.defaultClient.addTelemetryProcessor(removeStackTraces)
```

to my code but no success :/

**Comment by lippinio** [comment]
Any Updates here?
