### ISSUE TITLE
Device.Id in metrics

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-node.js#62]
Hi,
I've added a tag to my client context for setting my custom device id. It works well on traces, but I don't see the device id as a grouping criteria in metrics. Is it supported and correctly sent in metrics?
Thanks!

**Comment by SergeyKanzhelev** [comment]
Our latest recommendation is to start using device roleInstance instead of device id. You should be able to group metrics by roleInstance.

Device ID is used in devices monitoring and can be quite high cardinality. Think of every phone having unique ID. So we do not allow to group by it

**Comment by bragma** [comment]
That's in fact what I wanted to do, group metrics by single device. But as you pointed out, this would be impractical in case of a large number of devices.
Thanks.
