### ISSUE TITLE
Configure React + Node application with Application Insights in Azure

### ISSUE THREAD

**Issue by pankajingle** [microsoft/ApplicationInsights-node.js#625]
Hi Team,

I want to configure my React.js + Node application with application insights.
Please guide me what chnages i should require on Application side.
I have created the application insights in azure portal and i got the instrumentationKey.

Pankaj

**Comment by markwolff** [comment]
To onboard you will need to instrument your front-end / back-end with the appropriate Application Insights SDKs
https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs
