### ISSUE TITLE
Appinsights breaks node's http.createServer function

### ISSUE THREAD

**Issue by Pixelatex** [microsoft/ApplicationInsights-node.js#628]
So after a lot of digging and an [issue](https://github.com/nodejs/node/issues/33245) at the node repo, I was pointed here.

The culprit are these lines:

https://github.com/microsoft/ApplicationInsights-node.js/blob/44a0e7f6454a859a15f31b43c448513e92d01855/AutoCollection/HttpRequests.ts#L150-L155

Node should have an option for the HTTP create server as well. disabling app insights from my code proves that it works.

**Comment by Pixelatex** [comment]
I opened a PR to add the missing options parameter

**Comment by DevRCRun** [comment]
We're currently looking at trialling appinsights and I think this would cause an issue for us too. I note the PR is still outstanding. Anyone at MS able to provide an update / eta?

**Comment by hectorhdzg** [comment]
Fixed #629
