### ISSUE TITLE
Could not find module QuickPulseTelemetry

### ISSUE THREAD

**Issue by alex-p-mai** [microsoft/ApplicationInsights-node.js#631]
Hi, we are facing an issue that is crashing our server hosted on Microsoft Azure. When we install the applicationinsights SDK for nodejs on our local machine, everything seems to be working fine. However, when our server does an npm install, it is looking for a file that does not exist.

```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './QuickPulseTelemetryProcessor'
Require stack:
- D:\home\site\wwwroot\node_modules\applicationinsights\out\TelemetryProcessors\index.js
- D:\home\site\wwwroot\node_modules\applicationinsights\out\Library\TelemetryClient.js
- D:\home\site\wwwroot\node_modules\applicationinsights\out\Library\NodeClient.js
- D:\home\site\wwwroot\node_modules\applicationinsights\out\applicationinsights.js
- D:\home\site\wwwroot\dist\src\index.js
- D:\Program Files\iisnode\interceptor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\applicationinsights\out\TelemetryProcessors\index.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

This is what's inside the `node_modules/applicationinsights/out/TelemetryProcessor` folder:
![image](https://user-images.githubusercontent.com/51252887/81601693-4c716280-9399-11ea-8049-8b7fdf3ef634.png)

And inside the index.d.ts file, the code is:
```js
export * from "./SamplingTelemetryProcessor";
export * from "./QuickPulseTelemetryProcessor";
```

As you can see, the code that eventually ends up on our server looks for QuickPulseTelemetryProcessor file. However, that does not exist in the directory from the npm package. In fact, our local servers and playgrounds that I've spun up have this in index.d.ts file:
```js
export * from "./SamplingTelemetryProcessor";
export * from "./PerformanceMetricsTelemetryProcessor";
```

Every time we run our deployment pipeline, npm install runs, and our compiled files get written over, so a temporary change to the file directory change isn't a permanent solution. How do we go about getting the index file to point to PerformanceMetricsTelemetryProcessor instead of QuickPulseTelemetryProcessor?

**Comment by markwolff** [comment]
@alex-p-mai Can you check which version of the SDK you are using in your server? I don't see any reference to `QuickPulseTelemetryProcessor` in the latest version when installing it in a test app. Could you have a lockfile difference between your local and production environments?
