### ISSUE TITLE
Type definition file does not know about baseData

### ISSUE THREAD

**Issue by Tyriar** [microsoft/ApplicationInsights-node.js#632]
When the example in the readme is used such that type information is implicit in the function definition, it errors out in TS due to `baseData` not existing under `data`:

![image](https://user-images.githubusercontent.com/2193314/81721252-71ff7a00-9434-11ea-8362-b5529460647b.png)

`data` is of type `Base`:

![image](https://user-images.githubusercontent.com/2193314/81721306-89d6fe00-9434-11ea-905e-2b7fe03b1e7a.png)

Using applicationinsights@1.7.5

**Comment by bm77525-kr** [comment]
Still present in 1.8.8. This is a small annoyance, but would be nice to be able to use the actual type instead of defining my own more generic signature as `(envelope: { [name: string]: any }): boolean`.
