### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by asos-VasilisKortsimelidis** [microsoft/ApplicationInsights-node.js#634]
Hi App insights team, 

I'm trying to identify a memory leak in one of our apps. 

Please see the below screenshot

![Screenshot 2020-05-22 at 16 21 04](https://user-images.githubusercontent.com/35957481/82684104-fd091d00-9c49-11ea-94f5-1280f087c890.png)

Comparing the two memory dumps, seems that there are many closures being added to the memory from this line of code.

https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Sender.ts#L138

```
setTimeout(() => this._sendFirstFileOnDisk(), this._resendInterval).unref();
```

Quickly commenting out that line of code seems to fix the problem.

What are your thoughts about this? 

Thanks!

**Comment by markwolff** [comment]
I think the current behavior is to create a new timer each time telemetry is accepted by the backend. By default, Only 4 of these timers should be created per minute (default batch interval is 15 seconds), and they should be cleared every `_resendInterval`, which is 1 minute. If you turn off batching, I would imagine they would pile up for each send and disappear after the minute passes.

All of the extra timers are redundant after the 1st one, and so I will make a change to not create new ones after the 1st

**Comment by asos-VasilisKortsimelidis** [comment]
@markwolff Thanks for the quick response and your commit! I'm going to test it now!
