### ISSUE TITLE
Duplicate telemetry for traces and dependencies

### ISSUE THREAD

**Issue by tomlagier** [microsoft/ApplicationInsights-node.js#645]
I've gone through what I think is a standard Node.js Application Insights setup. We're getting `console` traces reported twice, and dependencies for our Postgres DB reported 3x. I stepped through the code and found that the `TelemetryClient.trackTrace` and `TelemetryClient.trackDependency` were only getting called once, so I suspect it's a setup/environment issue rather than the package misbehaving.

Here's our setup:

```
appInsights
    .setup(appInsightsKey)
    .setAutoDependencyCorrelation(true, true)
    .setAutoCollectRequests(true)
    .setAutoCollectPerformance(true, true)
    .setAutoCollectExceptions(true)
    .setAutoCollectDependencies(true)
    .setAutoCollectConsole(true, true)
    .setUseDiskRetryCaching(true)
    .setSendLiveMetrics(false)
    .setDistributedTracingMode(appInsights.DistributedTracingModes.AI)
    .start();
```

This happens once, right at the start of our app.

This is our Azure App Service portal:

<img width="595" alt="Screen Shot 2020-06-02 at 11 47 06 AM" src="https://user-images.githubusercontent.com/3165151/83557635-d8713880-a4c6-11ea-90a0-701991b2b860.png">

My suspicion is that there is some duplication happening because of the out-of-the-box in-process monitoring and the manual `applicationinsights` setup, but I'm not sure. I can't find any documentation about how to configure or disable the in-process monitoring.

Here are the environment variables that Azure instrumented our app with when we turned Application Insights on:

<img width="695" alt="Screen Shot 2020-06-02 at 11 49 26 AM" src="https://user-images.githubusercontent.com/3165151/83557812-25eda580-a4c7-11ea-9e09-f05e026c8194.png">

We do use this Express middleware for fixing correlation with Postgres as we use Knex. The duplication was happening before we added the `wrapWithCorrelationContext`, but I'm including it just in case.

```
async function dbMiddleware(req, _, next) {
    if (postgresEnabled) {
      const requestKnex = knex.withUserParams();
      requestKnex.client.query = appInsights.wrapWithCorrelationContext(
        originalKnexQuery
      );
      req.db.knex = requestKnex;
      req.models = await getModelsWithKnexObject(requestKnex, models);
    }

    next();
  };
```

Here's an example of the duplicate data:

<img width="845" alt="Screen Shot 2020-06-02 at 11 52 22 AM" src="https://user-images.githubusercontent.com/3165151/83558254-98f71c00-a4c7-11ea-93b1-08d3218f5239.png">
<img width="533" alt="Screen Shot 2020-06-02 at 11 52 31 AM" src="https://user-images.githubusercontent.com/3165151/83558263-9c8aa300-a4c7-11ea-9c15-08f11df31f5c.png">

At a loss here and would love to get this fixed so we're not over-paying for data. Any pointers are greatly appreciated!

**Comment by markwolff** [comment]
Enabling application insights via the Portal also instruments your app with app insights. It includes a basic attempt to see if you've manually instrumented, but it is not guaranteed to work for all project setups. You can try disabling it through the Portal, or removing your coded version.

As an aside, I would only expect to see 2x telemetry, not 3x. If you drill into the duped telemetry, you will see which version of the SDK is sending it via the `sdkVersion` property. If it looks something like `ad_node:1.6.0`, it is coming from the Portal enabled version. If it looks like `node:1.6.0`, then it is from your coded version.

**Comment by tomlagier** [comment]
Thanks for the response Mark,

To disable the automatic telemetry it in the App Service portal, just toggle "enabled"? That won't do anything to the existing App Insights resource?

Checked the duplicate telemetry, _all_ of the entries have `ad_node:1.7.5`.

Once you confirm that disabling the toggle in App Services isn't destructive, I'll let you know how it behaves with it off.

**Comment by markwolff** [comment]
Yes feel free to toggle it on the Portal. It will not touch the underlying app insights resource, only the codeless instrumentation will be disabled.

**Comment by tomlagier** [comment]
OK, after disabling the App Service AI integration, it I see no duplicates and events with an `sdkVersion` of `node:1.7.5`. Closing this out, thanks for your help!

**Comment by MuhamedSalihSeyedIbrahim** [comment]
> Yes feel free to toggle it on the Portal. It will not touch the underlying app insights resource, only the codeless instrumentation will be disabled.

1. How to disable using toggle option to disable?
Note:
 when I tried to toggle it to disable it reset automatically,
unless I delete app insight keys I cant able to disable application insight codeless instrumentation in azure function.

2. removing appinsight instrumentation key disable codeless application insight log collection but also found the actual log generated by the appInsight Nodejs sdk also not sent to application insight?
