### ISSUE TITLE
Redis cache does not appear in Application Map

### ISSUE THREAD

**Issue by lszomoru** [microsoft/ApplicationInsights-node.js#648]
We are using `applicationinsights` version `1.7.6`, and `redis` version `2.8.0` but even though we are initializing the client using all the default settings we are not seeing Redis in the application map. We are seeing the Azure App Services, and CosmosDB but not Redis. Are there any known issues with Redis dependency collection? Any suggestions on how to debug the missing dependency telemetry? Thanks!

**Comment by markwolff** [comment]
Hi @lszomoru, since it seems this is running in a vscode environment, I would recommend seeing if this issue https://github.com/microsoft/ApplicationInsights-node.js/issues/560#issuecomment-546114796 is related to your use case.

**Comment by lszomoru** [comment]
Thanks @markwolff for getting back to me.
The behavior that we are seeing is not in a vscode environment but it it one of our test applications that is running on Azure.

**Comment by markwolff** [comment]
Got it. I also recommend making sure that you are calling `.setup(...).start()` before importing redis. This SDK patches modules by patching them when you initially `require` them. If they are already in the require cache when this SDK is started, then they can't be patched

**Comment by lszomoru** [comment]
Interesting. Do you have a sample by any chance that I can take a closer look? I have looked at our code and we call `.setup(...).start()` in our `server.ts` before we call `createApp()` which then creates a new instance of `RedisCache`.

**Comment by markwolff** [comment]
You would need to call `.setup(...).start()` before you *import* `./createApp.js` (assuming that is the file name).

**Comment by lszomoru** [comment]
We are using TypeScript but I will take a look at your example and try to sort it out. Thanks!

**Comment by lszomoru** [comment]
@markwolff, does the SDK also do any "patching" of the `express` module?
Should requests served by `express` contain the `traceparent` header if the following is set?
```
setDistributedTracingMode(appInsights.DistributedTracingModes.AI_AND_W3C)
```

**Comment by markwolff** [comment]
This SDK does patching on `http` and `https` which will cover most `express` scenarios.

If W3C mode is enabled, this SDK will parse incoming `traceparent` headers and include it in all outgoing HTTP requests.

**Comment by lszomoru** [comment]
Thanks again @markwolff. I can confirm that after refactoring our code, now we can see Redis in the application map.

If W3C mode is enable should the `traceparent` header be included in the response that is sent to the browser? Looking at the response headers, I am only seeing the `request-context` header. Essentially we want to display a correlation id to the client in case of an error so that we can use that to correlate the error with the backend telemetry. Thanks!

**Comment by markwolff** [comment]
I would only expect to see w3c headers in incoming/outgoing request headers and not in any response headers
