### ISSUE TITLE
What is new/different about the v2 beta release?

### ISSUE THREAD

**Issue by cliffkoh** [microsoft/ApplicationInsights-node.js#657]
Hi,

I am struggling to find more information about the 2.x release. Are there any wikis or documentation to learn more about the new v2 release?

Thanks!

**Comment by markwolff** [comment]
Hi you can find an overview section here. It is a WIP migration to replace existing SDK components with the respective OpenTelemtry equivalents. As more components of OpenTelemtry become stable this year (Metrics / Logs), the 2.x release will be updated to include those as well. Today, 2.x sends Metrics / Logs via the existing SDK components, and autocollects distributed tracing via OpenTelemetry.

https://github.com/microsoft/ApplicationInsights-node.js#migrating-to-applicationinsights200-beta

**Comment by cliffkoh** [comment]
Thank you so much!
