### ISSUE TITLE
Question - Electron app and web app - which to use?

### ISSUE THREAD

**Issue by whyld4900** [microsoft/ApplicationInsights-node.js#658]
I have an electron app that can be accessed by url in browser too.

Can I use this or https://github.com/microsoft/ApplicationInsights-JS ?
Or should I use both and bundle whichever one (electron or webapp) I build for?

I want to just use one, is there a problem with that? Will I be missing things if I load one appInsights over another?

Thanks!

**Comment by markwolff** [comment]
The browser SDK will autoinstrument things found in the browser and use browser APIs to manage itself, whereas this SDK uses the corresponding node.js APIs (e.g. for making http requests, persisting telemetry to disk, auto-catching errors, etc).  I think either way, there might be some gaps in autocollection and so you would be using the manual track APIs to cover the gaps.

I'm aware of several users using this SDK in their electron apps (e.g. VSCode), as well as some using this SDK within a webpack bundled app.
