### ISSUE TITLE
Allow the use of startOperation for non-HTTP functions or expose CorrelationContextManager

### ISSUE THREAD

**Issue by bm77525-kr** [microsoft/ApplicationInsights-node.js#665]
SDK version: 1.8.4

I would like to correlate custom traces and custom events in my function app, as currently they all show up in AI with no correlation, with the exception of when I use `context.log` instead of `trackTrace` or `trackEvent`, etc. I've attempted several suggestions from past issues and docs with no real luck. The docs [here](https://github.com/microsoft/ApplicationInsights-node.js#setting-up-auto-correlation-for-azure-functions) suggest using the `wrapWithCorrelationContext` and `startOperation` methods. `startOperation` looks almost exactly like what I need: take the function context and start an AI opertaion based off its data and pass it along, but it must also be passed  an`HttpRequest`. A simplified example of my function using a Kafka trigger:

```
appInsights
    .setup(process.env.APPINSIGHTS_INSTRUMENTATIONKEY)
    .setDistributedTracingMode(appInsights.DistributedTracingModes.AI_AND_W3C)
    .setAutoDependencyCorrelation(true)
    .setAutoCollectRequests(true)
    .setAutoCollectPerformance(true, true)
    .setAutoCollectExceptions(true)
    .setAutoCollectDependencies(true)
    .setAutoCollectConsole(true)
    .setUseDiskRetryCaching(true)
    .setSendLiveMetrics(true)
    .start();
const telemetryClient = appInsights.defaultClient;

const kafkaTrigger: AzureFunction = async (context: Context, event: Buffer): Promise<void> => {
    const correlationContext = appInsights.getCorrelationContext(); // <- null
    
    context.log.info('Incoming event (context log)'); // Shows up in overall function trace in AI
    context.log.info('Another context log'); // Shows up in the same correlated trace as the above message in AI

    // Shows up in its own trace in AI
    telemetryClient.trackTrace({
            message: `Incoming event (trackTrace)`,
            severity: appInsights.Contracts.SeverityLevel.Information,
        });

    // Shows up in its own trace in AI
    telemetryClient.trackTrace({
            message: `Another trace (trackTrace)`,
            severity: appInsights.Contracts.SeverityLevel.Information,
        });
};
```

The correlation context above is `null` from the start of the function. Then the suggested use of `wrapWithCorrelationContext` falls apart:

```
// Default export wrapped with Application Insights FaaS context propagation
export default async function contextPropagatingTrigger(context: Context, event: Buffer): Promise<void> {
    // Start an AI Correlation Context using the provided Function context
    const correlationContext = appInsights.getCorrelationContext(); // <- Still null.

    // Wrap the Function runtime with correlationContext
    return appInsights.wrapWithCorrelationContext(async () => {
        appInsights.startOperation(context); // <- Can't event use this because I don't have an HttpRequest or IncomingMessage

        await kafkaTrigger(context, event);
    }, correlationContext)();
}
```

The issue [here](https://github.com/Microsoft/ApplicationInsights-node.js/issues/401) is basically exactly what I'm trying to solve, and the suggested solution was to set the override tag for operation ID to the invocation ID from the function context, but that was in 2018 and that's not what all other auto-collected traces and `context.log` messages appear to be using anymore. 

The doc [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#version-2x-and-later-3) suggests setting the override tag for operation ID to `context.traceContext.traceparent`, but that value appears to be in the format of `00-<operation ID>-<parent ID>-00`. _Almost_ what I need. The operation ID and parent ID within that string _are_ what the auto-collected traces are using. I suppose I could manually parse that myself, but it seems like bad practice since it's guesswork on my part, it could change, and it's essentially what the innards of `CorrelationContextManager.startOperation` (by way of using the `Traceparent` class) is doing anyway. If I can at least re-use the existing logic for parsing `traceparent` to access operation ID and parent ID, that would be very helpful.

Is there some other way that I'm missing to get non-HTTP trigger events and traces correlated?

**Comment by rnarayana** [comment]
Same issue for me on a kubernetes cron job
