### ISSUE TITLE
How to filter out cancelled requests?

### ISSUE THREAD

**Issue by dufia** [microsoft/ApplicationInsights-node.js#668]
Hey, my app is cancelling a lot of requests, they reach the Application Insights with status code 0, is there a way to filter out cancelled requests?

**Comment by markwolff** [comment]
Yes this is possible with [telemetry processors](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors). I've provided a sample (untested) below with the general idea. Note: for incoming requests we use `responseCode` and for outgoing requests we use `resultCode`. 

```ts
appInsights.defaultClient.addTelemetryProcessor((envelope) = {
  // if false, the envelope is dropped
  return envelope.data.baseData.resultCode === 0;
})
```
