### ISSUE TITLE
Processor\% Processor Time shows 100%

### ISSUE THREAD

**Issue by lszomoru** [microsoft/ApplicationInsights-node.js#669]
We have a Nodejs application that is running in App Services on Linux being. Periodically, we see that the `Processor\% Processor Time` performance counter shows 100% for some of the App Service instances. `Process\% Processor Time` shows a much lower value which looks more realistic.

Can the value of `Processor\% Processor Time` performance counter be trusted with App Services on Linux? Thanks!

**Comment by markwolff** [comment]
Hey you can view how we calculate these 2 metrics here, where we calculate some timing deltas from `process.cpuUsage` and `os.cpus`. Some caveats are that they are not normalized w.r.t cores, and so periods of >100% are possible. Also, processor time includes any time spent by the system on other os related tasks, whereas process time is closer to the resource consumption of only your application.

https://github.com/microsoft/ApplicationInsights-node.js/blob/0d3e908d6814e3c24c8aa1a91559487c89c49d11/AutoCollection/Performance.ts#L218-L219

**Comment by lszomoru** [comment]
Thanks for the pointer. The fact that processor time includes any time spent by the system on other OS related tasks makes perfect sense. One thing I was wondering if whether having processor time consistently >100% could indicate an error condition (ex: system issue, noisy neighbor, etc.) that is outside of our control.
