### ISSUE TITLE
Question: How to set context in dependency log on a per request basis?

### ISSUE THREAD

**Issue by thoo1** [microsoft/ApplicationInsights-node.js#670]
Version: "applicationinsights": "1.3.1"

I'm using the automatic fetch and xhr logging provided by app insights sdk. However I want to add some context to be logged on a per request basis. Is there a way to accomplish something like that?

One thing I was thinking of was to have a map of {id: Context} and in telemetryInitializer, read the id of the telemetry object, and look up the Context in the map, and then add this Context

To do this however, we'd need to know what the id of the telemetry object will be when we make a fetch/xhr request
I know there is "Request-Id" request header that will be added which is the id of the telemetry object.
However I think there are some requests that don't get this Request-Id header attached, in this case what is the value of the id?

Let me know if anything here is unclear
Thanks!

**Comment by markwolff** [comment]
Is this for a node.js application? You can get the current context (at request time, not telemetry time!) via `getCorrelationContext()` and then you can grab all of the `id` related fields so that you can setup your map.

**Comment by thoo1** [comment]
sorry this is for a frontend js application

**Comment by markwolff** [comment]
Which SDK are you using?

**Comment by thoo1** [comment]
"applicationinsights": "1.3.1"

**Comment by markwolff** [comment]
Are you running this SDK in the browser? Or is this an electron app? `applicationinsights` is the node.js version of application insights.

If so, you can grab the current context via `getCorrelationContext()`. If you are running in the browser using XHR/Fetch, it seems straightforward to bake your own request-id symbol on the fetch/xhr prototype/instance and grab it when you need it in your custom telemetry processor

**Comment by thoo1** [comment]
oh! sorry that's my mistake, we're actually using "@microsoft/applicationinsights-web": "2.4.0"

**Comment by markwolff** [comment]
Yes seems sound to me. I think your use-case is simpler in the browser since you can directly modify eaech xhr object.

**Comment by thoo1** [comment]
thanks, closing
