### ISSUE TITLE
Trace messages are not filtered according to host.json in Azure Function apps

### ISSUE THREAD

**Issue by bm77525-kr** [microsoft/ApplicationInsights-node.js#680]
SDK Version: 1.8.5

When attempting to adjust the log levels for our function app, it appears that any trace messages sent via the SDK are not filtered according to the settings in `host.json`. Our log settings:

```
"logging": {
        "fileLoggingMode": "never",
        "logLevel": {
            "Microsoft.AspNetCore.Mvc.StatusCodeResult": "Warning",
            "default": "Error",
            "Host.Results": "Information",
            "Host.Executor": "Information",
            "Host.General": "Warning",
            "Host.Controllers.Admin": "Warning",
            "Host.Aggregator": "Information",
            "Host.Startup": "Information"
        },
        "console": {
            "isEnabled": "false"
        }
    }
```

All other logs generated by the function host are abiding by the log levels specified, but no matter the log level specified for either "default" or for the specific function category (i.e. Function.myFunctionName) we always see all levels of traces from the SDK.

Observations:
- Trace messages generated by the host have a `LogLevel` and `Category` property in their "custom properties". Traces sent with the SDK don't.
- Manually adding those custom properties via the SDK does not fix the issue.
- Non-trace messages logged with the function's context logger (e.g. `context.log.info`) are properly filtered.

**Comment by markwolff** [comment]
This SDK does not parse `host.json` at all. For custom filtering, I would recommend taking a look at adding your own [telemetry processor](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors) to your `defaultClient`
