### ISSUE TITLE
How does correlation work from a Http Trigger to a service bus trigger

### ISSUE THREAD

**Issue by MohammedFoysal** [microsoft/ApplicationInsights-node.js#685]
Hey, we're having trouble with getting correlation working between a http trigger and a service bus and had some questions.

Within the same function app, we have a http trigger that puts a message onto the queue and a service bus trigger that consumes the message. The logs from each of the functions are separate, in their own operation. But we were hoping app insights would correlate the two. The dependency of the service bus is also not showing up on the app insights application map. 

After the service bus trigger has processed the message, it is added to a second queue, a timer trigger consumes multiple messages from the second queue. Is there a way we can correlate the logs from the individual messages from the timer trigger to the original http trigger? 

We have tried wrapping the two functions in a context propagating http and service bus trigger. We have also tried setting the correlationId of the service bus message to the operationId of the first function (http function). Neither has helped correlate the two logs.

sender http trigger:
```
await this.queue.send({
	body: {
		...queueRecord,
		operationId: getOperationId(context)
	}
	correlationId: getOperationId(context),
});
```

Are we missing anything here? how does a service bus message handle correlation internally and why don't they show up in app insights map? Thanks @markwolff

**Comment by markwolff** [comment]
Automatic Service Bus (and Functions) integration isn't something that is supported right now, and so it will need to be done manually.

https://github.com/microsoft/ApplicationInsights-node.js#azure-functions

You can use this SDK's `startOperation` fn to start an AI context from your Function, and then you will need to inject/extract the trace context to/from the body of your messages

**Comment by hectorhdzg** [comment]
@MohammedFoysal let us know if you still have issues with this after adding code Mark shared
