### ISSUE TITLE
Winston log both to AppInsights and Log Stream

### ISSUE THREAD

**Issue by kirill-reva** [microsoft/ApplicationInsights-node.js#686]
We have App Service on Azure and we use Winston (https://github.com/winstonjs/winston) for logging, the flow is:

1. Application logic just calls log.info("stuff")
2. Logs are captured in AppInsight and can be seen from Azure admin panel
3. Logs are NOT printed to runtime console (Log Stream)

When we disable AppInsights logs can be seen in Log Stream, however when we enable AppInsights logs can only be seen in AppInsights.
The problem is that we want logs to be in 2 places: AppInsight and Log Stream.

Is there any AppInsight configuration value so that it still consumes console/other logs but doesn't suppress them?

**Comment by markwolff** [comment]
You will need to add your own Console Transport to your Winston logger. This SDK's autocollection works by adding our own AppInsightsTransport; current winston behavior is to disable their "default" console transport if another transport is added. By explicitly adding your own console transport, both log streams should be enabled

**Comment by kirill-reva** [comment]
HI, 

I explicitly added my own console transport by just copying and slightly modifying the code of default winston console transport.
However Azure Log Stream still empty if AppInsights is enabled.
If AppInsights is disabled Log Stream has double entries (which is expected). 

`const os = require('os')
const { LEVEL, MESSAGE } = require('triple-beam')
const TransportStream = require('winston-transport')

//
// Inherit from `winston-transport` so you can take advantage
// of the base functionality and `.exceptions.handle()`.
//
export class CustomConsoleTransport extends TransportStream {
    // @ts-ignore
    constructor(options) {
        super(options);
        // @ts-ignore
        this.name = options.name || 'faro-console';
        // @ts-ignore
        this.stderrLevels = this._stringArrayToSet(options.stderrLevels);
        // @ts-ignore
        this.consoleWarnLevels = this._stringArrayToSet(options.consoleWarnLevels);
        // @ts-ignore
        this.eol = options.eol || os.EOL;

        this.setMaxListeners(30);
    }

    // @ts-ignore
    log(info, callback) {
        setImmediate(() => this.emit('logged', info));

        // Remark: what if there is no raw...?
        if (this.stderrLevels[info[LEVEL]]) {
            // @ts-ignore
            if (console._stderr) {
                // Node.js maps `process.stderr` to `console._stderr`.
                // @ts-ignore
                console._stderr.write(`${info[MESSAGE]}${this.eol}`);
            } else {
                // console.error adds a newline
                console.error(info[MESSAGE]);
            }

            if (callback) {
                callback(); // eslint-disable-line callback-return
            }
            return;
        } else if (this.consoleWarnLevels[info[LEVEL]]) {
            // @ts-ignore
            if (console._stderr) {
                // Node.js maps `process.stderr` to `console._stderr`.
                // in Node.js console.warn is an alias for console.error
                // @ts-ignore
                console._stderr.write(`${info[MESSAGE]}${this.eol}`);
            } else {
                // console.warn adds a newline
                console.warn(info[MESSAGE]);
            }

            if (callback) {
                callback(); // eslint-disable-line callback-return
            }
            return;
        }
        // @ts-ignore
        if (console._stdout) {
            // Node.js maps `process.stdout` to `console._stdout`.
            // @ts-ignore
            console._stdout.write(`${info[MESSAGE]}${this.eol}`);
        } else {
            // console.log adds a newline.
            console.log(info[MESSAGE]);
        }

        if (callback) {
            callback(); // eslint-disable-line callback-return
        }
    }

    // @ts-ignore
    _stringArrayToSet(strArray, errMsg) {
        if (!strArray)
            return {};

        errMsg = errMsg || 'Cannot make set from type other than Array of string elements';

        if (!Array.isArray(strArray)) {
            throw new Error(errMsg);
        }

        return strArray.reduce((set, el) =>  {
            if (typeof el !== 'string') {
                throw new Error(errMsg);
            }
            set[el] = true;

            return set;
        }, {});
    }
}
`

then I configured winston 
`
        winston.configure({
            transports: [
                new transports.Console(),
                new CustomConsoleTransport({})
            ],
        })
`

**Comment by markwolff** [comment]
Thanks for the code sample. I'll take a look locally and see whats happening

**Comment by kirill-reva** [comment]
Hi @markwolff did you have a chance to check?

**Comment by priyath** [comment]
Can't you just use the Console transport for winston and and then set `setAutoCollectConsole(true, true)`  when initializing application insights?

Initializing application insights (notice the multiple `true` parameters for `setAutoCollectConsole`
```
appInsights.setup(appConfigs.app.instrumentationKey)
  .setAutoDependencyCorrelation(true)
  .setAutoCollectRequests(true)
  .setAutoCollectPerformance(true, true)
  .setAutoCollectExceptions(true)
  .setAutoCollectDependencies(true)
  .setAutoCollectConsole(true, true)
  .setUseDiskRetryCaching(true)
  .setSendLiveMetrics(false)
  .setDistributedTracingMode(appInsights.DistributedTracingModes.AI)
  .start();
  ```
  Initialize winston like you would normally without custom transporters:
```
winston.configure({
 ...
  [
    new winston.transports.Console(),
 ],
});
```
