### ISSUE TITLE
Automatic dependency correlation does not work with Node js + express

### ISSUE THREAD

**Issue by moubAde** [microsoft/ApplicationInsights-node.js#687]
I'm trying to run a test program to view the logs on App insights. I think I have followed the necessary configuration and have activated automatic dependency management. I received the logs, but without correlation between the initial request and the dependencies. Attached is the program I am using.

index.js
`
const express = require("express");
const app = express();
const app2 = express();
const portHttp = 3000;
const portHttp2 = 3001;
const bodyParser = require("body-parser");
const appInsights = require("applicationinsights");
const axios = require("axios");

///////////////////////////////////////////////app
app.use(bodyParser.json());

app.use((req, res, next) => {
  let config = {
    applicationInsightsKey: "key",
  };

  appInsights
    .setup(config.applicationInsightsKey)
    .setAutoDependencyCorrelation(true)
    .setAutoCollectRequests(true)
    .setAutoCollectPerformance(true, true)
    .setAutoCollectExceptions(true)
    .setAutoCollectDependencies(true)
    .setAutoCollectConsole(true)
    .setUseDiskRetryCaching(true)
    .setSendLiveMetrics(true)
    .setDistributedTracingMode(appInsights.DistributedTracingModes.AI);

  let client = appInsights.defaultClient;
  client.trackNodeHttpRequest({ request: req, response: res });
  appInsights.start();
  next();
});

app.listen(portHttp, (err) => {
  if (err) {
    return console.log("something bad happened", err);
  }
  console.log(`server is listening on ${portHttp}`);
});

app.post("/test", async (req, res, next) => {
  const ret = await axios({
    method: "post",
    url: "http://127.0.0.1:3001/r1",
    data: {
      firstName: "f r1",
      lastName: "l r1",
    },
  });
  const ret2 = await axios({
    method: "post",
    url: "http://127.0.0.1:3001/r2",
    data: {
      firstName: "f r2",
      lastName: "l r2",
    },
  });
  res.status(200).json();
});

app.post("/r1", (req, res) => {
  res.status(200).json({ r1: 0 });
});

app.post("/r2", (req, res) => {
  res.status(200).json({ r2: 0 });
});

////////////////////////////////////////////////app2
app2.use(bodyParser.json());

app2.listen(portHttp2, (err) => {
  if (err) {
    return console.log("something bad happened", err);
  }
  console.log(`server is listening on ${portHttp2}`);
});

app2.post("/test2", (req, res) => {
  res.send("ok2");
});

app2.post("/r1", (req, res) => {
  res.status(200).json({ r1: 0 });
});

app2.post("/r2", (req, res) => {
  res.status(200).json({ r2: 0 });
});
`
Calling the '/ test' route on the app server triggers two calls on the app2 server

![img2](https://user-images.githubusercontent.com/35049431/97020406-cebd9f80-1551-11eb-8f4c-940749c9c3b8.jpeg)

**Comment by markwolff** [comment]
Hi @moubAde App Insights needs to be setup first in your application, else we won't be able to properly patch the internal HTTP module. By moving your `require` and `.setup.(...).start(...)` earlier, this will resolve itself

https://github.com/microsoft/ApplicationInsights-node.js#basic-usage
