### ISSUE TITLE
trackMetric does not support setting custom properties

### ISSUE THREAD

**Issue by phmiller** [Microsoft/ApplicationInsights-node.js#69]
Unlike the .NET (or browser JavaScript) library, this library does not allow you to pass in additional properties to the .trackMetric function.

You can do it for the other types of telemetry like events and dependencies, but not metrics.

ContractsModule.Contracts.MetricData object has a spot for properties, so doesn't seem like it would break the model.

**Comment by lmillott** [comment]
I just submitted a PR to fix this: https://github.com/Microsoft/ApplicationInsights-node.js/pull/71
