### ISSUE TITLE
problem when upgrading appinsights

### ISSUE THREAD

**Issue by htorjmen** [microsoft/ApplicationInsights-node.js#691]
Hello, 

Lately i upgraded appinsights from 1.7.6 to 1.8.7 and since then when i run package:bundle i get this errors:

`WARNING in ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js 49:44-89
Module not found: Error: Can't resolve 'applicationinsights-native-metrics' in 'C:\query-api\node_modules\applicationinsights\out\AutoCollection'
 @ ./node_modules/applicationinsights/out/applicationinsights.js 13:26-71
 @ ./dist/common/backend/app-insights-helper.js 4:20-50
 @ ./dist/query-api/src/app.js 7:30-76`

and i can't run my integration tests from database.

does anyone have the solution ?

**Comment by hectorhdzg** [comment]
@htorjmen are you still having this issue?, if you do can you provide more details on how to reproduce.

**Comment by hectorhdzg** [comment]
Please let us know if this is still an issue in your side
