### ISSUE TITLE
Can't remove a single processor

### ISSUE THREAD

**Issue by asklar** [microsoft/ApplicationInsights-node.js#700]
I want to write some tests to verify that my [exception] processor works properly. To test it, my plan was going to be to add a second processor and validate that the exception it gets is of the form that my first processor would leave it in.
However, there is only `addTelemetryProcessor` and `clearTelemetryProcessors`, no remove or get.

**Comment by hectorhdzg** [comment]
@asklar there is a plan for this SDK to fully support [Open Telemetry](https://github.com/open-telemetry/opentelemetry-js) next semester and telemetry processors are not available and similar functionalities are achieved differently, using [Resources SDK] (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md) and [SpanProcessors](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor).

**Comment by asklar** [comment]
@jonthysell fyi
