### ISSUE TITLE
Angular Universal: undefined correlation id

### ISSUE THREAD

**Issue by mac2000** [microsoft/ApplicationInsights-node.js#704]
**Steps to reproduce:**

- Create the simplest possible angular application with help of `ng new demo`
- On a home component add code to query and display results from any API
- Enable SSR with help of `ng add @nguniversal/express-engine`
- Add and configure Application Insights to generated `server.ts`
- Run app (does not matter in dev or prod mode)

**Actual results:**

Application Insights successfully collects requests to the app itself and requests being sent to an API from within the app (remote dependency)

But, somehow both request and remote dependency has  `undefined` as `context.correlation.id` so it is not possible to correlate dependencies with requests

**Comment by xiao-lix** [comment]
@mac2000 can you please share how you setup your demo app and how did you make the request? 
I tried locally that it works fine. 
On client side, I send a GET request to server.ts `httpClient.get('http://localhost:4200/test2')`, and `/test2` is defined in server.ts as: 
```
server.get('/test', (req, res) => {
    res.send('random');
  });

server.get('/test2', (req, res) => {
    res.send(https.get('https://localhost:4200/test'));
  });
```
It makes a dependency and a request. On portal, they are correlated correctly with the same operation id: 
![image](https://user-images.githubusercontent.com/20292261/102289471-9acc7e00-3ef3-11eb-8ade-ff3532ab2da9.png)

**Comment by mac2000** [comment]
@xiao-lix here you go: https://github.com/mac2000/ai-704

your sample works because you are sending requests right from your express js app, it works fine, the problem begins whenever requests are sent from withing angular while it renders the page on the server-side

btw, while I had a chance also tried to connect appinsights before zone.js but it does not help also

to run it do something like:

```bash
git clone https://github.com/mac2000/ai-704
cd ai-704
npm install
export APPINSIGHTS_INSTRUMENTATIONKEY=your-instumentation-key # <- do not forget that
npm run dev:ssr
open localhost:4200
```

hopefully you will be able to reproduce it also

if you will need some more tests and help feel free to ask, we have a demo repo so it will be much easier

**Comment by mac2000** [comment]
And you wont belive, still does not understand how it is possible

I was making some additional checks, e.g.:

- calling https from server
- calling xhr2 from server

and noticed following - when you wrap render function in server side with https call - everything starts to work, little bit laggy but working

![image](https://user-images.githubusercontent.com/88868/103232264-b21f5880-4942-11eb-85d6-9c680ae512c2.png)

![image](https://user-images.githubusercontent.com/88868/103232294-c4999200-4942-11eb-9ba1-7c977a35f68c.png)

on screenshot you can see main requests and two dependencies one made from server side (screen before) and another from within app component in angular

also can confirm that deep inside angular uses xhr2 lib which uses https, you can found sources here: `node_modules/xhr2/lib/xhr2.js`

**Comment by xiao-lix** [comment]
@mac2000 Did you solve the issue by wrapping the render method? I tried to reproduce the issue but still I can see correlation ids correctly. For the demo you linked : 
1. The SDK should be started first - can you move the node sdk on top in `server.ts` file before importing other stuff? 
2. Where exactly do you see the correlation id undefined? Do you see them in code or through portal? Do you have a screenshot? 
3. Do you make request from server.ts also? I'm confused why don't you add web sdk on Angular? Without the web sdk, the dependency sent from front end is not captured. Unless you are sending dependency from the server then to the server itself?

I have my demo app setup like this: 

In `app.component.ts` file: 
Import web sdk on top and set it up before class.

```
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

const appInsights = new ApplicationInsights({ config: {
  instrumentationKey: 'ikey'
  /* ...Other Configuration Options... */
} });
appInsights.loadAppInsights();
appInsights.trackPageView();
@Component({
  ...
})
export class AppComponent {
  ...
  public sendGetRequest(){
    console.log('sendGetRequest gets called');
    this.httpClient.get('http://localhost:4200/test').subscribe(value => {
      this.response = JSON.stringify(value);
    });
  }
}

```
In `server.ts` file, import node sdk on top and receive `/test`: 
```
const appInsights = require('applicationinsights');
appInsights.setup('63969e7a-c5f7-4494-96f8-a33184d0fe30').start();

...

export function app(): express.Express {
  const server = express();

  ...

  server.get('/test', (req, res) => {
    res.send('<p>some html</p>');
  });

  ...

  return server;
}

export * from './src/main.server';
```
I tested both with same ikey and different ikey, I can see dependency and request events with same operation id / correlation id: 

![image](https://user-images.githubusercontent.com/20292261/104062621-ad16a080-51af-11eb-847c-55702044ecc0.png)

**Comment by mac2000** [comment]
@xiao-lix I have pushed a [minor change](https://github.com/mac2000/ai-704/commit/3d83c40fa7816eaa5b2fb46494a7c09dbc5698fc) which hopefully will show you what I meant

the key point here is that we are not looking at browser, in my experiment after starting angular I just run

```bash
curl localhost:4200
```

I have added the following logs:

- in server.ts to see incoming requests
- in app.component.ts to see internal requests which are required for angular to render home page
- custom processing handler to log whatever being send to application insights

![image](https://user-images.githubusercontent.com/88868/104094601-88e3be00-529a-11eb-926d-bd4a37095847.png)

as you can see from the screenshot we are printing both requests (one for express and the second for angular) but somehow correlation context for remote dependency is null

and as for my last message, yes, if I wrap server rendering function into one more call everything suddenly starts to work

![image](https://user-images.githubusercontent.com/88868/104094639-cba59600-529a-11eb-9a3e-075cf904cc29.png)

**Comment by xiao-lix** [comment]
hi @mac2000 , thanks for the details and sorry for the late reply. I happened to find that the correlation context populates values with Angular 11, and the demo you are using Angular 9. Can you update it to 11? The dependencies my test uses is: 
```
"dependencies": {
    "@angular/animations": "~11.0.6",
    "@angular/common": "~11.0.6",
    "@angular/compiler": "~11.0.6",
    "@angular/core": "~11.0.6",
    "@angular/forms": "~11.0.6",
    "@angular/platform-browser": "~11.0.6",
    "@angular/platform-browser-dynamic": "~11.0.6",
    "@angular/platform-server": "~11.0.6",
    "@angular/router": "~11.0.6",
    "@nguniversal/express-engine": "^11.0.1",
    "applicationinsights": "^1.8.9",
    "express": "^4.15.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.6",
    "@angular/cli": "~11.0.6",
    "@angular/compiler-cli": "~11.0.6",
    "@nguniversal/builders": "^11.0.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
```

**Comment by mac2000** [comment]
@xiao-lix I have [upgraded](https://github.com/mac2000/ai-704/blob/main/package.json) every dependency to the latest version

But unfortunately, the issue is still reproducible

**Comment by xiao-lix** [comment]
Hi @mac2000 , sorry for late reply. I tried multiple things and had a couple debug sessions. The reason behind this is there's a timing issue caused by either the old version of Angular, or the SSR. If you console.log the envelope inside the telemetry processor you'll see that the dependency happens before the request. This causes the issue. Because the context doesn't exist yet when dependency happens ---  the context is created when receiving the request which happens later in this particular scenario. That is to say, the `res.render` method makes the dependency faster than our SDK creates the context. We have no way to fix this on our side. 
I'm not sure why you still see the issue with newer version of Angular, I couldn't reproduce it with Angular 11, but do see it with Angular 9. 
To fix this, you could either upgrade Angular version. Unfortunately it doesn't work for you. Or as what you did, to delay the render method. I tried to simply use `setTimeOut` to delay it, and it works too.
