### ISSUE TITLE
Envelope property values lose type information

### ISSUE THREAD

**Issue by asklar** [microsoft/ApplicationInsights-node.js#708]
`client.trackException({ exception: e, properties: { foo: 42 } })`

If I set up a telemetry processor, the value of `envelope.data.properties.foo` is `'42'`, not `42`.

**Comment by hectorhdzg** [comment]
Properties must be strings in ApplicationInsights, backend will reject other types
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#properties
