### ISSUE TITLE
Base type inside envelope always equals to request data.

### ISSUE THREAD

**Issue by goto1** [microsoft/ApplicationInsights-node.js#713]
Hello,

I would like to be able to exclude specific requests based on the `evenlope.data.baseType`.

Currently, I have the following setup:

```js
appInsights.setup().setSendLiveMetrics(true).start()

appInsights.defaultClient.addTelemetryProcessor(
  (envelope, context) => {
    const telemetryTypes = {
      Request: appInsights.Contracts.TelemetryTypeString.Request,
      Exception: appInsights.Contracts.TelemetryTypeString.Exception,
    }
    const isOfTelemetryType = (telemetryType) => envelope.data.baseType === telemetryType

    const isExceptionTelemetry = isOfTelemetryType(telemetryTypes.Exception)
    const isRequestTelemetry = isOfTelemetryType(telemetryTypes.Request)

    if (isExceptionTelemetry) return true
    if (isRequestTelemetry && process.env.NODE_ENV !== "development") return true

    return false
  }
)
```

However, it appears that `evenlope.data.baseType` always comes back as `RequestData` and I am never seeing any other types, such as `ExceptionData`, as specified in the [example](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors) from the documentation,

```js
const baseType = envelope.data.baseType // RequestData
```

This is true when I manually try to trigger an exception in one of my middleware functions,

```js
// express middleware
app.use((req, res, next) => {
  appInsights.defaultClient.trackException({ exception: new Error("Hello World") })
  next()
})
```

I've looked at this issue #325, which suggests to look at the value of `envelope.data.baseType` to determine whether to send the telemetry or not, but I am always getting `RequestData` for `baseType`.

In the Azure portal, however, I am seeing those exceptions being logged no problem, so technically they should be getting processed through my custom telemetry processor.

Any tips would be greatly appreciated, thank you!

---

Setup information:

- `node v14.15.1`
- `applicationinsights v1.8.8`

**Comment by hectorhdzg** [comment]
@goto1 I tried code snippet you added and telemetry processor works as expected, I can see "ExceptionData" as envelope.data.baseType, is it possible another telemetry processor was added and is modifying the envelope? if you are seeing correct events in Azure this could means there is some issue in your local environment, is also possible multiple telemetry events are triggered in your middleware function please validate all of them while debugging.

**Comment by goto1** [comment]
@hectorhdzg thank you for your response, I re-installed my project dependencies and that seemed to fix the issue, thanks!

---

Also, if I can may ask about something else, would you happen to know if there's a way to populate the `client_Browser` field, similarly to setting [`deviceOSVersion`](https://github.com/microsoft/ApplicationInsights-node.js/blob/f843973866b6966e96ad884bca746a99930eec91/Declarations/Contracts/Generated/ContextTagKeys.ts#L135) and [`userId`](https://github.com/microsoft/ApplicationInsights-node.js/blob/f843973866b6966e96ad884bca746a99930eec91/Declarations/Contracts/Generated/ContextTagKeys.ts#L146) context keys?

Currently I am using a custom field to store this information but don't always have the ability to filter my logs by custom field values.

```js
appInsights.defaultClient.addTelemetryProcessor(
  (envelope, context) => {
    const getContextKey = (key) => appInsights.defaultClient.context.keys[key]
    const setContextKey = (key, value) => {
      envelope.tags[key] = value
    }
   
    const requestContext = appInsights.getCorrelationContext().requestContext // custom request context
    const data = envelope.data.baseData

    const { userId, os, browser } = requestContext

    // this is what I would like to do for `client_Browser`
    setContextKey(getContextKey("deviceOSVersion"), os)
    setContextKey(getContextKey("userId"), userId)

    // setting a custom property, but this doesn't populate the `client_Browser` field
    data.properties.browser = browser 

    return true
  }
)
```

Any help would be greatly appreciated, thanks!

**Comment by hectorhdzg** [comment]
Glad it works now, you could use envelope.tags["ai.device.browser"]
