### ISSUE TITLE
Custom data question - Node.js

### ISSUE THREAD

**Issue by guisouto** [microsoft/ApplicationInsights-node.js#716]
Hi! I'm hoping for a little help here.

Based on this post [https://github.com/microsoft/ApplicationInsights-node.js/issues/448](url), I'm using this example to capture the payload of POST requests in a Node.js Project. But, I need to capture the responses body. Is there any way I can achieve this?
Follow my code snippet used to capture the payload:

```
appInsights.defaultClient.addTelemetryProcessor((envelope, context) => {
      const httpRequest = context['http.ServerRequest'];
      const baseData = envelope.data.baseData;
      if (httpRequest && appInsights.Contracts.domainSupportsProperties(baseData)) {
        if(httpRequest.method === 'POST') {
          baseData.properties['bodyRequest'] =  JSON.stringify(httpRequest.body);
        } else {
          const url = URL.parse(httpRequest.url);
          if (url.query) {
              const pairs = url.query.split('&').map(x => x.split('='));
              pairs.forEach(pair => {
                  baseData.properties[pair[0]] = pair[1] || '<empty>';
              });
          }
        }
      }
      return true;
    });
```

Another scenario in which I need help is when I get the ['http.ClientRequest'] context, I can't access the body property, like in the example above. The property is undefined. You do know why?

Thanks in advance.

**Comment by goto1** [comment]
If there’s something missing from the `http.ClientRequest` that you’d like to have access to I’d suggest storing this information in a custom request context inside the `getCorrelationContext()` object, then you can grab that information inside your custom telemetry processor and save it however you need.

I posted my solution on [StackOverflow](https://stackoverflow.com/a/65252309/5862900) so have a look to get an idea on how you could do this.

**Comment by hectorhdzg** [comment]
@guisouto the  ['http.ClientRequest'] context will include a reference to the response object [http.ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse) in this case a Writable Stream  more info about streams [here](https://nodejs.org/api/stream.html)

**Comment by guisouto** [comment]
Tks @goto1 and @hectorhdzg! I appreciate for your help.

We found another solution to capture the response data. My colleague create a middleware to intercept response data. 
Here's the solution:

`
insights() {
      let capturedRes = {};

      // Middleware to intercept response data
      this.server.use((req, res, next) => {
        const originalSend = res.send;
        res.send = data => {
          capturedRes = data;
          res.send = originalSend;
          return res.send(data);
        };
        next();
      });

      // Run with default settings
      appInsights.setup().start();

      // Adds custom properties
      appInsights.defaultClient.addTelemetryProcessor((envelope, context) => {
        const { baseData } = envelope.data;
        const supportsProperties = appInsights.Contracts.domainSupportsProperties(
          baseData
        );

        if (
          context &&
          context['http.ServerRequest'] &&
          context['http.ServerRequest'].body &&
          supportsProperties
        ) {
          baseData.properties.requestBody = JSON.stringify(
            context['http.ServerRequest'].body
          );
          baseData.properties.responseBody = capturedRes;
        }

        return true;
      });
    }`
