### ISSUE TITLE
support TrackPageView()?

### ISSUE THREAD

**Issue by haocs** [Microsoft/ApplicationInsights-node.js#72]
Hi, 
I am using the library in my client side node.js project and I need to track the pageview data. However, I found this function is not implemented in the latest version('0.15.11') yet. 
Wondering if there is a plan to implement this function? Is there a workaround for the current version?

**Comment by kamilszostak** [comment]
Hi,
sorry for the delay. Could you explain your scenario a bit better? What do you mean by client side Node.js? 

The SDK with autocollection enabled will log a Request for every server side HTTP request ([docs](https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#track-request)). 

Page views should be logged by a client application. If you use a web browser as your client, you can use JavaScript SDK to log PageViews. If you use Node.js as a client, I see a value in adding `trackPageView` functionality.

**Comment by timotheeguerin** [comment]
I do think this would be worth adding for electron application. We have one right now and use the nodejs sdk and don't really want to have both JS and nodejs libraries.
