### ISSUE TITLE
Seems some http dependencies aren't tracked

### ISSUE THREAD

**Issue by nulltoken** [microsoft/ApplicationInsights-node.js#722]
Hello,

https://github.com/nulltoken/applicationinsights-jose-repro-case puts under the light a use case where a http dependency call isn't intercepted by applicationinsights.

In order to ease the troubleshooting I've repro'd this through a test which output can be seen in the GitHub action workflow https://github.com/nulltoken/applicationinsights-jose-repro-case/runs/1770198720?check_suite_focus=true

The test does sets up application-insights and issues 3 GET HTTP requests
1. Directly, through Axios => https://httpbin.org/status/200
2. Indirectly, through [panva/jose](https://github.com/panva/jose/) => https://nexus.passport.com/public/partner/discovery/key
3. Directly, through Axios => https://httpbin.org/status/201

A debug addTelemetryProcessor is set up to output to the console log what dependencies are processed.

Only the calls to Axios are seen. However, although not intercepted, one can see that the remote key is properly loaded over https.

From my understanding, `panva/jose` internally [leverages](https://github.com/panva/jose/blob/main/src/runtime/node/fetch.ts) `https.get` to issue the request.

Is this a bug in application-insights?
Would that be the case, is there something I can do on my side to work around it?

/cc @panva

**Comment by hectorhdzg** [comment]
Hard to tell what is happening because I don't understand how the package you are using works, we don't support automatic dependency tracking for this package like you said we do support http/https native modules but anything could be happening here, I recommend you to manually call the trackDependency API for these kind of calls.

**Comment by nulltoken** [comment]
@hectorhdzg Thanks for the feedback.

>Hard to tell what is happening because I don't understand how the package you are using works

That makes a lot of sense. I've pushed a dumbed down version of the repro case (into which I've copied/pasted relevant parts of source code of @panva 's jose library. This helped to eventually (more or less) understand where the problem occurs

See here https://github.com/nulltoken/applicationinsights-jose-repro-case/blob/main/src/fetch.ts#L20-L35

Basically the code is 

```
import { get } from 'https'

...(snipped)...

// /!\ This seems to be the source of the issue.
const localGet = get;
const opts = {}

// Dumbed down from https://github.com/panva/jose/blob/main/src/runtime/node/fetch.ts#L1-L2

export const joseFetch = async (url: URL) => {
  if (url.protocol !== "https:") {
    throw new TypeError('Unsupported URL protocol.')
  }
  return new Promise((resolve, reject) => {
    // /!\ If here rather than calling `localGet`, we directly invoke `get`, application insights
    // properly intercepts the call.
    localGet(url.href, opts, async (response) => {
      if (response.statusCode !== 200) {
        reject(new Error('Expected 200 OK from the JSON Web Key Set HTTP response'))
      } else {
        const parts = []
        // eslint-disable-next-line no-restricted-syntax

...(snipped)...
```

A pointer to `https.get` function is stored in a local variable (`localGet`). Later on, that local variable is used to eventually perform the call.

If the final call isn't done through the local variable, but directly through `get`, AppInsights properly intercepts the call.

>I recommend you to manually call the trackDependency API for these kind of calls.

That's an option. However, would there be a recommended way to properly "capture" the `get` function so that AI interception works, I'd rather try an open a PullRequest in @panva's jose repository.

Would you be able to help me how the `get` function should be handled so that it can be locally stored in a variable and still be compatible with the monkey patching happening at https://github.com/microsoft/ApplicationInsights-node.js/blob/c8fa5b8de5c34a4f50f64fa904aaaa8aa8002fae/AutoCollection/HttpDependencies.ts#L78-L102 ?

**Comment by panva** [comment]
@nulltoken can't you just require the instrumentation before requiring `jose` which pulls in the local function reference?

**Comment by nulltoken** [comment]
@panva Let me see what I can come up with.

**Comment by nulltoken** [comment]
@panva :clap: That was the right call. I've managed to leverage the `jose` library and see calls to jwks uri intercepted by AI by deferring the import through an await import call once AI is set up (eg. `const {default: createRemoteJWKSet } = await import("jose/jwks/remote");`).

@hectorhdzg Don't you think this kind of workaround may be handy in a troubleshooting section of the README?

**Comment by hectorhdzg** [comment]
@nulltoken sorry for late reply, we do mention Application Insights SDK need to be imported and setup before importing other libraries [here](https://github.com/microsoft/ApplicationInsights-node.js#basic-usage), same for official Azure [docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/nodejs#basic-usage), let me know if you have any feedback
