### ISSUE TITLE
how to trackPageView()

### ISSUE THREAD

**Issue by prafull3313** [microsoft/ApplicationInsights-node.js#725]
How can I call the trackPageView() or add my analytics under pageViews table?
trackPageView() is available in JS SDK here >>
[https://github.com/microsoft/ApplicationInsights-JS#connection-string-setup](https://github.com/microsoft/ApplicationInsights-JS#connection-string-setup)
On above link, last line of snippet.

**Comment by hectorhdzg** [comment]
@prafull3313 trackPageView API is only available in Application Insights Web SDK not in node.js SDK, to have that kind of telemetry you will need to include the Web SDK code as well in your Web App

**Comment by prafull3313** [comment]
Thanks @hectorhdzg
