### ISSUE TITLE
Database calls are not correlated with a function app that makes them in the Application Map

### ISSUE THREAD

**Issue by maximivanov** [microsoft/ApplicationInsights-node.js#726]
I'm not sure this is the right repo to open the issue, let me know if there's a better place for this.

For some reason calls to a Postgresql database that my function app makes originate from a "Web" instance.
Function app is the only application connected to the Application Insights instance, there's nothing Web/frontend in the stack.

<img width="944" alt="Screen Shot 2021-02-08 at 12 40 59" src="https://user-images.githubusercontent.com/1759643/107222502-e9d2f300-6a0c-11eb-9885-d2926b680874.png">

Function App Hosting Plan: Elastic Premium EP1
Application Insights Application Type: Node.JS
applicationinsights npm package version: 1.8.8

Code I use to start tracking:
```js
import * as appInsights from 'applicationinsights'
if (process.env.APPINSIGHTS_INSTRUMENTATIONKEY) {
  appInsights.setup().start()
}
```

Let me know if I can help with anything. Thanks!

**Comment by hectorhdzg** [comment]
"Web" is the actual default role name in the Application Insights SDK https://github.com/microsoft/ApplicationInsights-node.js#multiple-roles-for-multi-component-applications, you must be able to configure it in your Azure function code to unblock you, this is something we need to investigate further to have a better integration with Azure functions.

**Comment by maximivanov** [comment]
Thanks @hectorhdzg  setting the role name explicitly seems to have worked.

I've added a new App Setting to the function app and updated the code from what I posted above to:

```js
import * as appInsights from 'applicationinsights'
if (process.env.APPINSIGHTS_INSTRUMENTATIONKEY) {
  appInsights.setup()
  if (process.env.FUNCTION_APP_NAME) {
    appInsights.defaultClient.context.tags[
      appInsights.defaultClient.context.keys.cloudRole
    ] = process.env.FUNCTION_APP_NAME
  }
  appInsights.start()
}
```

That's not intuitive though and I wish it figured the environment (the function app) it runs within automatically. I guess there's just nothing provided by the platform for the APM library to "know" the environment it belongs to?
