### ISSUE TITLE
Library blocks express server from response

### ISSUE THREAD

**Issue by rsouthgate** [microsoft/ApplicationInsights-node.js#735]
Seems very similar to #390 but I'm not clear on whether the solution is as described there - not calling start() or whether this is actually undesired behaviour.

Basically an express server where appinsights.start() called before express server started and listening. Any routes captured by express will, according to the logs be done in a few milliseconds. But the actual response isn't flushed to the client for about 15 seconds (or whatever maxBatchIntervalMs is set to).

Is this expected? I would have thought the background job collecting stuff shouldn't interfere with express sending it's response.

**Comment by hectorhdzg** [comment]
@rsouthgate the SDK must not delay the actual response of the server request, is it possible to get a repro of this issue so we can investigate further?

**Comment by rsouthgate** [comment]
Sorry for the delay in responding. I've been trying to put a minimal repro together that showcases the issue but there is something more complicated going on and it probably means this library is not to blame (though the issue is definitely mitigated by the use of a short batch interval). In the project that shows the issue there is a combination of webpack loaders bundling for node, native node modules bundled vai node-loader and an emulated xmlHttpRequest object via xhr2 (https://www.npmjs.com/package/xhr2) - some combination of these with express is causing node to lock until that batch interval is reached. I wonder @hectorhdzg if you can think of a likely culprit there? I'll keep going trying to narrow down the actual culprit but I'll also close this as it's not this libraries fault!
