### ISSUE TITLE
Blob storage, Service Bus Queue and other call with sdk are not  auto monitored or tracked

### ISSUE THREAD

**Issue by MuhamedSalihSeyedIbrahim** [microsoft/ApplicationInsights-node.js#738]
Hi Team,
We are trying to use application insight to track http ,cosmos db calls and all external calls.
But in case of blob storage , service bus queue and other calls with azure sdk are not tracked automatically.

Trigger which use blob storage is  only available in application map.
But triggers like cosmos and service bus queue is not monitored.
 
1. Any Suggestions for about scenarios?

2. May I know Nodejs Application insight latest version auto tracking app list? in other words does AI sdk latestversion in nodejs does it support tracking for blob , SB queue , other service sdk call tracking automatically?

3. codeless azure function AI instrumentation - what all it can automatically track (like http call and blob triggers)?

4. durable function nodejs correlationand end to end support needed(w3c traceparent support)

Node v12
all other azure sdk LTS version/ latest version

Thanks in advance

**Comment by hectorhdzg** [comment]
Application Insights currently support automatic tracking for several Azure SDKs more details [here](https://github.com/microsoft/ApplicationInsights-node.js#automatic-third-party-instrumentation), are you currently having issues after installing @opentelemetry/tracing?

**Comment by MuhamedSalihSeyedIbrahim** [comment]
No, we have not installed/use @opentelemetry/tracing. We are using application insight latest version.

Nodejs Azure SDK of application insight not automatically tracking SDK of blob storage , server bus queue , cosmos dB.
and also it not able to correlate the trigger's trace parent with orchestrator client and activity clients's context.

**Comment by hectorhdzg** [comment]
@MuhamedSalihSeyedIbrahim you need to install @opentelemetry/tracing to enable automatic tracing of Azure SDKs with Application Insights SDK, the specific section explaining this is the link I shared with you. 

"Automatic instrumentation for several Azure SDKs is also available, you must manually install @opentelemetry/tracing to enable this automatic tracing. No additional configuration is required Currently Cognitive Search, Communication Common and Cosmos DB SDKs are not supported. Javascript Azure SDKs"

We are working on enabling this without customers explicitly adding the @opentelemetry/tracing package and hopefully will be part of next release.

We will need more details about the correlation issue you are having, w3c tracing is currently supported in the SDK, if you are using Azure functions please take a look at the following
https://github.com/microsoft/ApplicationInsights-node.js#azure-functions

**Comment by MuhamedSalihSeyedIbrahim** [comment]
Ok i shall try installing open telemetry and try in sdk correlations and check if it solve my issue 
thanks🙂. 

The scenario is this
We use http triggered function push message to service bus queue
Then its picked by sb trigger and it starts orchestrator and activity of durable function 

Here in above flow i have w3c trace context in http function then i managed to propagate it via service bus to service bus queue durable function trigger but after it 
the durable orchestrator and activity have different w3c trace context than the trigger 

it may lead us to miss the flow while we try to trace end to end logs

**Comment by James-Firth** [comment]
@hectorhdzg Does import order between `@opentelemetry/tracing` and `applicationinsights` matter when trying to get automatic tracing for service bus?

I'm attempting to call `sendMessage` and would like to be able to track the call from Node and then have the message consumer also track that same id (operationId and parent_operationId I believe?)

Should `sendMessages` be automatically tracked as a `dependency` in app insights?

**Comment by hectorhdzg** [comment]
@James-Firth you don't need to import @opentelemetry/tracing to have auto collection of Azure SDKs to work, just need to install it so code is available and Application Insights can hook into it, if you are actually using the @opentelemetry package then ensure Application Insights code is imported first before any other package, yes I can see sendMessages in @azure/service-bus is creating telemetry

**Comment by mabecth** [comment]
@hectorhdzg I did exactly that but it still does not work for me with blob storage upload. I still get disconnected components in application map and transaction details. Why is that?

**Comment by James-Firth** [comment]
@hectorhdzg Hm, I've installed that and still don't see Service Bus showing up on the application map nor as a dependency metric.

`require('applicationinsights')` is the very first line of my `index.js`, followed by a console log then `appInsights.setup(process.env.APPINSIGHTS_CONNECTIONSTRING).setSendLiveMetrics(true).start()`

My other dependencies (postgresql) shows up fine though.

Here is a snippet from my package.json:

```
    "@azure/service-bus": "^7.0.3"
    // .. other packages
    "@opentelemetry/tracing": "^0.18.2",
    "applicationinsights": "^1.8.10"
```

And my `yarn.lock` shows those exact versions are the resolved ones

**Comment by MuhamedSalihSeyedIbrahim** [comment]
@hectorhdzg ,  I am still facing the issue of broken component link in application map.
the operation id / trace parent is successfully passed via diagnostic id  from send message to service bus trigger but still its not tracked in app insights

as you have said I have tried application using latest version of appinsight NodeJS and service bus sdk with the recommended @opentelemetry/tracing lib with all its peer dependencies but still I am facing the issue.

any suggestion or idea in it?

**Comment by ephesusit-nz** [comment]
Hi @MuhamedSalihSeyedIbrahim
You need to pass a tracingOptions per https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-service-bus/7.0.0-preview.1/interfaces/sender.html#send and https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-service-bus/7.0.0-preview.1/interfaces/operationoptions.html#tracingoptions.

It only supports passing OpenTelemetry SpanOptions.
