### ISSUE TITLE
opentelemetry package duplication leading to broken tracing

### ISSUE THREAD

**Issue by jameyg42** [microsoft/ApplicationInsights-node.js#742]
it's unclear what versions of opentelemetry packages should be installed or what the compatibility matrix is for applicationinsights, opentelemetry, and azure-sdk.

`azure-sdk core-tracing@1.0.0-preview.10 `depends on `@opentelemetry/api@0.10.2`
`diagnostic-channel-publishers@0.4.4` depends (devDep) on `@opentelemetry/api@0.16.0`

manually installing `@opentelemetry/tracing` that matches the devDep (0.16.0) leads to package duplication of opentelemetry/api - the tracer registered by diagnostic-channel-publishers registers into the 0.16.0 version of ot/api, but core-tracing is using its local 0.10.2 ot/api version (which is a different symbol for the global tracer).  The result is that core-tracing is always using the NoOp tracer from the 0.10.2 api.

installing ot/packages@0.10.2 avoids package duplication but fails because the API doesn't have a `setSpan()` function.

i'm not trying anything elaborate - just trying to get a "basic usage" setup to trace @azure/event-hubs publishers.

**Comment by jameyg42** [comment]
after playing around a bit, i'm now getting a different behavior when using ot@0.16.0.  Previously these two lines in azure-core.pub were returning a NoOp tracer

        new tracing.BasicTracerProvider().register(tracerConfig);
        var tracer = api_1.trace.getTracer("applicationinsights tracer");

because `api_1` was the 0.10.2 version.  I can no longer recreate that and i do now see that core-tracing is caching the tracer itself vs. using the OT global tracer (the similar function names confused me).

i'm now having a different issue, but it also smells like a duplicate package / version mismatch one.  For the following

    at getSpanContext (\event-hub-debug\node_modules\@opentelemetry\api\build\src\context\context.js:71:76)
    at getParent (\event-hub-debug\node_modules\@opentelemetry\tracing\build\src\Tracer.js:100:16)
    at Tracer.startSpan (\event-hub-debug\node_modules\@opentelemetry\tracing\build\src\Tracer.js:50:31)
    at Tracer.tracer.startSpan (\event-hub-debug\node_modules\diagnostic-channel-publishers\dist\src\azure-coretracing.pub.js:52:44)
    at createMessageSpan (\event-hub-debug\node_modules\@azure\event-hubs\dist\index.js:3639:25)
    at EventDataBatchImpl.tryAdd (\event-hub-debug\node_modules\@azure\event-hubs\dist\index.js:3788:33)

it fails because `_a.context()` is undefined (_a is defined, but doesn't have a context function).   The context itself here is the AI context from HttpRequests (i.e. my test setup is an ExpressJS app calling event-hubs) which i don't believe is an OT span.

above may be a completely different problem, but i don't want to close this particular issue just yet because my original question still stands - what OT packages packages need to be installed and where for a working example.

**Comment by hectorhdzg** [comment]
@jameyg42 sorry about the inconvenience, we actually adding the direct dependency to @opentelemetry packages in this repo and we will sync dependencies with diagnostic-channel and Azure SDK as well, we are expecting OpenTelemetry stable version at least the API to be published soon, once this is available we don't expect any breaking changes in OpenTelemetry and all dependencies involved here could be pointing to latest release .

**Comment by hectorhdzg** [comment]
This is fixed in version 2.0.0
