### ISSUE TITLE
Enrich Dependency telemetry with optional request/response logging

### ISSUE THREAD

**Issue by przemos** [microsoft/ApplicationInsights-node.js#750]
Hi,

what we have found missing and would be absolutely useful to have is the ability to opt-in for logging request/response of the egress requests on demand (by means of some configuration switch). Logging request/response is an essential feature when debugging your distributed systems and Dependency telemetry makes a perfect home for that. Request and response as strings could be homed under dedicated properties of customDimensions. 
I am cognizant it is most useful for text payloads, so it could apply only to selected content types such as application/json, or application/xml. Still, knowing those two cover quite a lot of the "integration market", the value proposition seems to be very compelling.

**Comment by hectorhdzg** [comment]
@przemos we store the request and response objects and are available in [Telemetry Processors](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors) inside context parameter, you must be able to add your telemetry processor, read the context values and store whatever property is useful for you in the telemetry event.

**Comment by przemos** [comment]
The problem is though reading those streams are asynchronous, so you cannot make them onto Dependency Telemetry since these callbacks are unrelated
