### ISSUE TITLE
@types/node required for Azure Functions using TypeScript

### ISSUE THREAD

**Issue by coreyroth** [microsoft/ApplicationInsights-node.js#760]
It took me a while to figure this one out after adding the SDK 2.0.0 to my Azure Function using TypeScript.  You'll get errors such as cannot find type definition for "node" or cannot find module "https".  I resolved this by running the following:

`npm install @types/node --save-dev`

I recommend including this in the getting started page with your Azure Function example.

**Comment by hectorhdzg** [comment]
@coreyroth @types/node is a dev dependency for applicationinsights package, so typescript must not complain about node types while building the SDK code, can you share more details about your Typescript version and tsconfig? some errors you were getting would be useful as well

**Comment by coreyroth** [comment]
Hi @hectorhdzg, here is a repo which demonstrates the errors: 
[Repo](https://github.com/microsoft/ApplicationInsights-node.js/issues/760)

It's an OOTB Azure Function wrapped with contextPropegatingHttpTrigger using TypeScript 4.0.0

Here are the errors, you receive from tsc:


node_modules/applicationinsights/out/applicationinsights.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/applicationinsights/out/applicationinsights.d.ts:4:33 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

4 import { IncomingMessage } from "http";
                                  ~~~~~~

node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.d.ts:2:25 - error TS2307: Cannot find module 'events' or its corresponding type declarations.

2 import events = require("events");
                          ~~~~~~~~

node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.d.ts:4:23 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

4 import * as http from "http";
                        ~~~~~~

node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpDependencyTelemetry.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpDependencyTelemetry.d.ts:3:23 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

3 import http = require("http");
                        ~~~~~~

node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpDependencyTelemetry.d.ts:4:24 - error TS2307: Cannot find module 'https' or its corresponding type declarations.

4 import https = require("https");
                         ~~~~~~~

node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpRequestTelemetry.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/NodeHttpRequestTelemetry.d.ts:3:23 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

3 import http = require("http");
                        ~~~~~~

node_modules/applicationinsights/out/Library/Config.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/applicationinsights/out/Library/Config.d.ts:2:23 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

2 import http = require('http');
                        ~~~~~~

node_modules/applicationinsights/out/Library/Config.d.ts:3:24 - error TS2307: Cannot find module 'https' or its corresponding type declarations.

3 import https = require('https');


Resolved by installing @types/node as mentioned aboe.

**Comment by hectorhdzg** [comment]
Thank you @coreyroth, looks like link to the repo is wrong, can you share it again?.

**Comment by coreyroth** [comment]
My apologies. I updated it.
https://github.com/coreyroth/AzureFunctionApplicationInsightsTypeScript
