### ISSUE TITLE
upgrade to 2.x peer dependencies missing

### ISSUE THREAD

**Issue by automaticdreams** [microsoft/ApplicationInsights-node.js#761]
On upgrading from 1.8.10 => 2.0.0, I get a warning
npm WARN @opentelemetry/tracing@0.19.0 requires a peer of @opentelemetry/api@^1.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @opentelemetry/core@0.19.0 requires a peer of @opentelemetry/api@^1.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @opentelemetry/resources@0.19.0 requires a peer of @opentelemetry/api@^1.0.0-rc.0 but none is installed. You must install peer dependencies yourself.

**Comment by Sebs030** [comment]
Not sure if related, but i also noticed that the installation hangs when trying to install v2.0.0 recently: 
`npm verb cli   'i',
npm verb cli   '--save',
npm verb cli   'applicationinsights',
npm verb cli   '-verbose'
npm verb cli ]
npm info using npm@7.13.0
npm info using node@v16.2.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\SebastianSchuman\AppData\Roaming\nvm\v16.2.0\node_modules\npm\npmrc Completed in 0ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\SebastianSchuman\Documents\5i\Apps\5i-Microservices\New_Ticket_Service\.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:C:\Users\SebastianSchuman\.npmrc Completed in 1ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:C:\Users\SebastianSchuman\AppData\Roaming\nvm\v16.2.0\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 2ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 12ms
npm timing npm:load:configload Completed in 12ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 2ms
npm timing npm:load Completed in 60ms
npm timing config:load:flatten Completed in 5ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 322ms
npm timing idealTree:userRequests Completed in 3ms
npm timing arborist:ctor Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/applicationinsights 734ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pre-commit 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/continuation-local-storage 37ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/cross-spawn 38ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@opentelemetry%2fapi 439ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/diagnostic-channel 456ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cls-hooked 462ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/diagnostic-channel-publishers 470ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/spawn-sync 481ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@opentelemetry%2ftracing 493ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/which 500ms (from cache)
npm timing idealTree:#root Completed in 1272ms
npm http fetch GET 304 https://registry.npmjs.org/emitter-listener 473ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/async-listener 483ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/async-hook-jl 505ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@opentelemetry%2fresources 516ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@opentelemetry%2fcore 532ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@opentelemetry%2fsemantic-conventions 535ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.merge 545ms (from cache)
npm timing idealTree:node_modules/applicationinsights Completed in 576ms
npm http fetch GET 304 https://registry.npmjs.org/semver 542ms (from cache)
npm timing idealTree:node_modules/@opentelemetry/tracing Completed in 559ms
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 4ms (from cache)
npm timing idealTree:node_modules/@opentelemetry/core Completed in 8ms
npm timing idealTree:node_modules/@opentelemetry/resources Completed in 0ms
npm timing idealTree:node_modules/@opentelemetry/semantic-conventions Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/stack-chain 44ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/shimmer 498ms (from cache)
npm timing idealTree:node_modules/cls-hooked Completed in 505ms
npm timing idealTree:node_modules/async-hook-jl Completed in 2ms
npm timing idealTree:node_modules/continuation-local-storage Completed in 3ms
npm timing idealTree:node_modules/async-listener Completed in 1ms
npm timing idealTree:node_modules/diagnostic-channel Completed in 0ms
npm timing idealTree:node_modules/diagnostic-channel-publishers Completed in 0ms
npm timing idealTree:node_modules/emitter-listener Completed in 0ms
npm timing idealTree:node_modules/lodash.merge Completed in 0ms
npm http fetch GET 304 https://registry.npmjs.org/shebang-command 68ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/os-shim 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/concat-stream 130ms (from cache)
npm timing idealTree:node_modules/pre-commit Completed in 142ms
npm http fetch GET 304 https://registry.npmjs.org/pseudomap 467ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 471ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/shebang-regex 477ms (from cache)
npm timing idealTree:node_modules/cross-spawn Completed in 486ms
npm timing idealTree:node_modules/lru-cache Completed in 2ms
npm timing idealTree:node_modules/pseudomap Completed in 0ms
npm timing idealTree:node_modules/shebang-command Completed in 1ms
npm timing idealTree:node_modules/shebang-regex Completed in 0ms
npm timing idealTree:node_modules/shimmer Completed in 0ms
npm http fetch GET 200 https://registry.npmjs.org/buffer-from 10ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/typedarray 48ms (from cache)
npm timing idealTree:node_modules/spawn-sync Completed in 56ms
npm timing idealTree:node_modules/concat-stream Completed in 5ms
npm timing idealTree:node_modules/buffer-from Completed in 0ms
npm timing idealTree:node_modules/os-shim Completed in 0ms
npm timing idealTree:node_modules/stack-chain Completed in 0ms
npm timing idealTree:node_modules/typedarray Completed in 0ms
npm timing idealTree:node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/@opentelemetry/core/node_modules/semver Completed in 2ms
npm timing idealTree:node_modules/@opentelemetry/core/node_modules/lru-cache Completed in 3ms
npm timing idealTree:node_modules/@opentelemetry/core/node_modules/yallist Completed in 0ms
npm timing idealTree:node_modules/applicationinsights/node_modules/@opentelemetry/api Completed in 0ms
npm timing idealTree:node_modules/pre-commit/node_modules/which Completed in 0ms
npm timing idealTree:buildDeps Completed in 3667ms
npm timing idealTree:fixDepFlags Completed in 12ms
npm timing idealTree Completed in 4027ms
npm timing reify:loadTrees Completed in 4029ms
npm timing reify:diffTrees Completed in 30ms
npm timing reify:retireShallow Completed in 1ms
[         .........] \ idealTree: timing reify:retireShallow Completed in 1ms`

So in the last installation hangs and needs to be aborted. Enviroment used: 
npm info using npm@7.13.0
npm info using node@v16.2.0
Win10
