### ISSUE TITLE
Add custom properties to RequestTelemetry while using AI SDK autocollection only

### ISSUE THREAD

**Issue by johnib** [microsoft/ApplicationInsights-node.js#769]
Hi,

I reviewed the code, and think that it's impossible to load the `baseTelemetry` object with `properties` object, containing custom properties **without instrumenting telemetry directly**.

I'm trying to avoid the manual/explicit instrumentation, and enjoy the great autocollection support that is already built into the nodejs SDK.

https://github.com/microsoft/ApplicationInsights-node.js/blob/b3e871b7a3f435880b3dafd418aac9167c97b0c0/AutoCollection/HttpRequestParser.ts#L103-L107

My suggestion is to allow loading a `properties` object into the `request/response` objects available in the middleware, for example:

```javascript
app.get("/ping", (req, res) => {
  req.properties = { "customProperty1": "customValue1" };
  req.res.status(200).send("pong");
});
```

Is that something that you'd be willing to add?

Thanks!

**Comment by hectorhdzg** [comment]
@johnib telemetry processors could be used for this scenario, more info [here](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors), HTTP/s requests and responses are available in there as well, so you must be able to add extra properties and read them in the telemetry processor
