### ISSUE TITLE
Does applicationInsights SDK support send batch event synchronously

### ISSUE THREAD

**Issue by ruowan** [microsoft/ApplicationInsights-node.js#770]
**Is your feature request related to a problem? Please describe.**
Here is my service scenario. Worker service subscribe Azure eventhub, process events from eventhub and output result to ApplicationInsights.  As I know applicationInsights SDK process result and telemetry asynchronously.  But worker service seems applicationInsights process rate is slower than process events from eventhub. When there are high traffic event comming in, it cause many result items pipe up in applicationInsights SDK buffer and memory goes up to limit finally OOM.

I think maybe there is a bottleneck in applicationInsights. 

**Describe the solution you'd like**

I would like to make applicationInsights SDK process event synchronously. For example, worker service pull batch events from eventhub and output batch result to applicationInsights synchronoulsy. it means worker service will not pull next batch events from eventhub until the current batch is prccessed and applicationInsights SDK buffer is flushed.

I want applicationInsights support two features:

- expose current buffer length, so we could monitoring whether there are some data is block in applicationInsights buffer or queue.
- support explicitly send batch result or telemetry synchronously 

**Describe alternatives you've considered**

**Additional context**
Really apprecicate you could give some advice or some techincal detials. Thanks~

**Comment by hectorhdzg** [comment]
TelemetryClient [flush](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/TelemetryClient.ts#L130) method accepts a FlushOptions parameter where you can include a callback and wait until flush is done on your side. 
[channel](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/TelemetryClient.ts#L30) is available in TelemetryClient where you can read [_buffer ](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Channel.ts#L15) property to determine the number of envelopes in the buffer.

**Comment by hectorhdzg** [comment]
Please let us know if you still have issues with this.
