### ISSUE TITLE
What's the expected behavior if powershell doesn't work properly

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/ApplicationInsights-node.js#777]
We use applicationinsights@1.0.3 and we learned that it invokes powershell when caching telemetry data to disk. We recently have a customer issue complaining about it since they said they "disabled" powershell and when appinsights attempts to invoke the powershell command (getACL), the process crashes.

I highly suspect that the root cause is how they "disable" powershell. However, I wonder what is the expected behavior in your mind if powershell is disabled in a standard way or not working properly, e.g. disabled via group policy, returning an error, etc.

**Comment by hectorhdzg** [comment]
@JasonYeMSFT ask customer to upgrade to latest release of the SDK, that version is 3 years old and is possible there are unexpected issues in there, Application Insights must not crash if Powershell is disabled

**Comment by JasonYeMSFT** [comment]
OK, we will upgrade appinsights in our product asap and ask our customer how they messed up with powershell. If we run into any issue, I'll open a separate issue instead.
