### ISSUE TITLE
__Empty error after 2.1.2 upgrade

### ISSUE THREAD

**Issue by scare82** [microsoft/ApplicationInsights-node.js#782]
After upgrade applicationinsights package from 1.8.10 to 2.1.2, in Azure Failures page there are many and many errors __Empty

![immagine](https://user-images.githubusercontent.com/72262797/122518656-c4d13b00-d011-11eb-9443-8d985a941f21.png)
![immagine](https://user-images.githubusercontent.com/72262797/122518713-d9153800-d011-11eb-80dd-cc1a4ce2b744.png)

My service have 448K calls, the true errors are 268 but i see 404K __Empty error. When click the count link the result is No available results 
![immagine](https://user-images.githubusercontent.com/72262797/122518978-35785780-d012-11eb-9494-7a99b9cdaa3b.png)

My configuration is very simple:

    appInsights.setup();
    appInsights.defaultClient.context.tags[
        appInsights.defaultClient.context.keys.cloudRole
    ] = 'BeWrite';
    appInsights.start();

Sorry for my poor english and thanks for helps

Best regards, Filippo

Edit:

With 1.8.10 and 2.0.0 package i haven't __Empty errors. With 2.1.1 and 2.1.2 the errors appears. I haven't try with 2.1.0 package

**Comment by hectorhdzg** [comment]
@scare82 this is definitely unexpected, are you also seeing an increase in Exceptions?, is your server actually returning the empty responses now or is the issue regarding wrong telemetry?

**Comment by scare82** [comment]
@hectorhdzg . No, the "true" exceptions are approximately the same that i expect. I don't think my service returns empty responses (no reporting in 2 years). As you can see in picture with the 2.0 applicationinsights the __Empty error dissapears. Same code, only downgrade applicationinsights version (downgrade at 17:00). 

![immagine](https://user-images.githubusercontent.com/72262797/122633046-b39e3200-d0d6-11eb-889e-367a82f1ac4d.png)

**Comment by hectorhdzg** [comment]
You can see changes between 1.8.10 and 2.1.2 in [here](https://github.com/microsoft/ApplicationInsights-node.js/releases), biggest change is regarding node.js supported version, and only change that could affect automatic tracking of requests is #767, if you can provide some repro environment or steps we can investigate further in our side.

**Comment by DevRCRun** [comment]
We're experiencing this too in a new Appinsights environment containing two node projects (one express frontend, one express API). We have come directly in with version 2.1.2 for the setup of these.

As best as I can see, the errors are potentially occurring alongside actually successful requests to the frontend (in that there is an error % recorded against that component in the application map). Could be wrong about that though.

I've upgraded some other APIs in different Appinsights environments powered by express from 1.8.x to 2.x (haven't tried this in any frontends yet) and haven't had this issue.

We're currently on Windows server with node 12.x

Can be more specific about versions if necessary, mainly wanting to flag that it doesn't seem to be just scare82 having the issue...
