### ISSUE TITLE
no redirect handling when ingestionEndpoint changes

### ISSUE THREAD

**Issue by jameyg42** [microsoft/ApplicationInsights-node.js#787]
Recently, the ingestionEndpoints for all of our ConnectionStrings were changed w/out any apparent communication the change happened.  This caused all monitoring to stop working because the agent doesn't appear to handle redirects.  Issue #172 captures the same problem, but was apparently closed w/out any review or fix.

**Comment by hectorhdzg** [comment]
@jameyg42 we recently added redirect support and fixed some issues in there including handling of 307 and 308, please update to latest version of the SDK to get all updates, we will be updating to OT API 1.0.0 next release, we are waiting for Azure SDKs to release latest changes to avoid version mismatch issues

**Comment by jameyg42** [comment]
@hectorhdzg awesome news re: 1.0 - was waiting for this and the Azure SDKs to all line up before looking to upgrade anything.  Thanks for answer my question before i even asked it!
