### ISSUE TITLE
How to use the library with Nextjs?

### ISSUE THREAD

**Issue by netMaer** [microsoft/ApplicationInsights-node.js#808]
I have tried to use the lib in nextjs, but it seems like I cant Initialize the library early enough, and therefore are the logs not working as they should. Is it possible to use the lib with nextjs and how? is there a lazy load option?

const ApplicationInsightsServer = require('applicationinsights');
ApplicationInsightsServer.setup(process.env.NEXT_PUBLIC_APPINSIGHTS_INSTRUMENTATIONKEY)
    .setAutoCollectConsole(true, true)
    .setUseDiskRetryCaching(false) // Don't use disk retry cache since we'll have a read-only filesystem in Azure
    .setSendLiveMetrics(true);
ApplicationInsightsServer.defaultClient.setAutoPopulateAzureProperties(true);
ApplicationInsightsServer.start();

**Comment by hectorhdzg** [comment]
@netMaer can you add more details about what exactly is not working?, @xiao-lix created some basic nextjs app available [here](https://github.com/xiao-lix/next-app) that you could use as reference

**Comment by netMaer** [comment]
@hectorhdzg It is a nice example, but I can’t create a custom server, I must use the nextjs server, and when doing so, I can’t for example get request tracking to work, and all data is missing operation_id and parent. If I create a custom server as in the example, everything works as expected.
It seems like in the nextjs setup I can’t initialize the application library early enough.

**Comment by netMaer** [comment]
@denu5 It worked thx!!

**Comment by zmarty** [comment]
Thank you, this require trick helped guide us hopefully in the right direction. Still experimenting with it.

I did notice that for server side rendered pages App Insights logs show up like this: GET /_next/static/chunks/pages/page-name.js

Instead of showing up as a URL and having all query parameters in there.

Any chance we can get that too somehow?

**Comment by ashish-srivastava-dev** [comment]
@zmarty Were you able to show the server side rendered pages as URL?
Also for next.js integration with appInsights, Should we use client side libararies (like @microsoft/applicationinsights-react-js and @microsoft/applicationinsights-web) or server side libraries (applicationinsights)?
