### ISSUE TITLE
Provide a sync flush call

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/ApplicationInsights-node.js#81]
If an application immediately shuts down after logging an event, for example, it can happen that the events are dropped and never written to disk for later submission. It seems that there is a [sync implementation of it](https://github.com/Microsoft/ApplicationInsights-node.js/blob/4e0ac5bcfc52b8b76f6528c02557fc08218f8031/Library/Sender.ts#L172), but it is not exposed in the API.

If it were, we could always call that method when listening on process exit: `process.on('exit'...`

**Comment by seanmcbreen** [comment]
Hi,
I wanted to see if there was any update here - this is a key issue for us as it really impacts the consistency, accuracy and predictability of the data we can get.

**Comment by martincostello** [comment]
A similar use case is using Application Insights with an AWS lambda function. If the function gets low traffic, events can end up never being logged as the disk cache cannot always be read later.

**Comment by jeffwilcox** [comment]
We were previously calling `appInsightsClient.sendPendingData()`, but this is no longer working in newer SDK versions - there's an undefined `channel` inside this method that we often see when watching the errors stream through.

Our scenario is similar to the lambda one - we have a WebJob that runs, and if we call `process.exit(0)` at some point, we do tend to lose events, metrics as the process ends so quick.

**Comment by AlexBulankou** [comment]
@jeffwilcox, do you happen to have a repro of undefined `channel` when calling `sendPendingData`? I can see that otherwise this method works  as sync flush call.

**Comment by AlexBulankou** [comment]
With the updated API, sendPendingData was renamed to flush which provides a way set a flag indicating that app is crashing, so they payload needs to be saved on disk immediately: ``client.flush({isAppCrashing: true})`` .   

I'm going to close the issue for now. Please reactivate if there's a repro with SDK crashing with undefiend channel when flush() is called.
