### ISSUE TITLE
Application insight custom logging - custom properties serialization bug

### ISSUE THREAD

**Issue by MuhamedSalihSeyedIbrahim** [microsoft/ApplicationInsights-node.js#811]
Description - Upon assigning circular JSON to custom properties of app insight log methods like trackTrace , trackException, etc.., 
I experience a bug in the serialization and it's reflected in application insight blade table -> custom dimension column.

Runtime - NodeJSv12.18.3
lib version - applicationinsights@latest

Expected behavior - The JSON must be serialised (by removal of circular reference) and proper json is found in application insght blade table under column custom dimension

Actual behavior - 
I showing error in custom dimension PFA.

Attachment - [
![Capture](https://user-images.githubusercontent.com/30931525/129082359-d6440be4-7dbf-4ed0-9910-54b7cd52a74c.JPG)
](url)

**Comment by hectorhdzg** [comment]
Thanks for reporting the issue @MuhamedSalihSeyedIbrahim, all custom dimensions are send as strings by the SDK, not sure how we can fix this on SDK side, maybe a bug in UX because they are the ones trying to parse it as JSON, where specifically are you seeing this in the portal?, is it possible to validate the custom dimension is well formed on your side before sending it in the SDK?

**Comment by MuhamedSalihSeyedIbrahim** [comment]
I observed it exceptions table record in appinsights

when I spread the error obj of the axios in customproperties of track exception method

This is the code
log.trackException(axiosErrorInstance, {properties: {... axiosErrorInstance} });

My goal is to try manually the
proposal explained in issue [#809](https://github.com/microsoft/ApplicationInsights-node.js/issues/809#issue-966830473)

To capture addition information in error
Such as axios error object contain
Response , request ,config etc..,
Which is critical if stack doesn't provide enough detail. 

Yes if proper simple json is provided
From node side the expected result is achieved but in my case the axios exception have cyclic response object of tcpSocket

**Comment by JacksonWeber** [comment]
@MuhamedSalihSeyedIbrahim Please ensure that you're sending correctly JSON serializable. There are several 3rd party NPM packages that can help clean up JSON for serialization. Thank you.
