### ISSUE TITLE
Allow multiple instances running side-by-side

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/ApplicationInsights-node.js#82]
Currently [all instances of this module share the same cache directory](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Sender.ts#L17). This is a problem if several applications depend on it and run simultaneously.

cc @seanmcbreen

**Comment by jsheely** [comment]
See https://github.com/Microsoft/ApplicationInsights-node.js/pull/83

**Comment by OsvaldoRosado** [comment]
Related to #202
