### ISSUE TITLE
What's the Statsbeat design goal and benefit?

### ISSUE THREAD

**Issue by emmansun** [microsoft/ApplicationInsights-node.js#822]
Hi @hectorhdzg , What's the **Statsbeat** design goal and benefit? I can't find any document related it, could you kindly help to elaborate more detail?

BTW, the `ApplicationInsights:AzureVirtualMachine` hard code the AIMS_URI as "http://169.254.169.254/metadata/instance/compute", is it a temporary solution?

**Comment by mattmccleary** [comment]
Hi @emmansun, we are working on a new feature across all our langauges that will serve three benefits for Azure Monitor Application Insights customers:

1. Service Health (outside-in monitoring of ingestion endpoint)
2. Support Diagnostics (self-help insights and CSS Insights)
3. Product Improvement (insights for design optimizations)

We are working on detailed official documentation that should fill in any gaps. Let me know if you have further questions!

**Comment by emmansun** [comment]
Thx @mattmccleary, looking forward to the official documents!
