### ISSUE TITLE
ApplicationInsights:AzureVirtualMachine [   Error: connect EHOSTUNREACH 169.254.169.254:80

### ISSUE THREAD

**Issue by russosalv** [microsoft/ApplicationInsights-node.js#839]
I have strange exception message in Windows and also in WSL2

Windows:
`
ApplicationInsights:AzureVirtualMachine [
  Error: connect EHOSTUNREACH 169.254.169.254:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
      at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:131:14) {
    errno: -4073,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80
  }
]
`

in wsl2
`ApplicationInsights:AzureVirtualMachine [
  Error: connect EHOSTUNREACH 169.254.169.254:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:131:17) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80
  }
]
`

the code is very simple and it is:
`
import express from 'express';
import appInsights from 'applicationinsights'

const app = express();

appInsights.setup(process.env.APPLICATIONINSIGHTS_CONNECTION_STRING)
    // .setAutoDependencyCorrelation(true)
    // .setAutoCollectRequests(true)
    // .setAutoCollectPerformance(true, true)
    // .setAutoCollectExceptions(true)
    // .setAutoCollectDependencies(true)
    // .setAutoCollectConsole(true)
    // .setUseDiskRetryCaching(true)
    // .setSendLiveMetrics(false)
    // .setDistributedTracingMode(appInsights.DistributedTracingModes.AI)
    .start();

app.listen(3000, () => {
    console.log("Server running on port 3000");
})

app.get("/url", (req, res, next) => {
    res.json(["Tony","Lisa","Michael","Ginger","Food"]);
});
`

**Comment by PhakornKiong** [comment]
I'm getting the same error on `v2.1.6`

reverting to `v2.0.0` seems to solve the issue temporarily

**Comment by hectorhdzg** [comment]
@PhakornKiong this is by design we try to make a call to specific IP available in Azure environment to retrieve extra properties and add them in the telemetry, this must be a 1 time operation only and SDK must handle the error, let me know if this actually throwing or affecting the app in any way,

**Comment by russosalv** [comment]
@hectorhdzg thx for the explanation.
Honestly i didn't test this code inside Azure enviroment, in my scenario the application will be hosted in docker container and on premises server.
i had the error running code in WSL2 enviroment.
I think that use ApplicationInsigth, telemetry and trace also for application outside Azure is very usefull, and for this reason i added it on my dev enviroment.

Wich type of data you collect from external ip? 

maybe can be a good option do not throw on exception if this specific azure ip is not reachable but simply notify a warining.

**Comment by PhakornKiong** [comment]
> @PhakornKiong, @russosalv this is by design we try to make a call to specific IP available in Azure environment to retrieve extra properties and add them in the telemetry, this must be a 1 time operation only and SDK must handle the error, let me know if this actually throwing or affecting the app in any way,

The only problem i have with he current version is that the `liveMetrics` will go offline after that error. I'm not 100% sure If it is caused by that error, but downgrading to `v2.0.0` solved that problem.

Would be great if you could share more on which code is responsible for this, night be able to help debug.
