### ISSUE TITLE
appInsights.setup().start(); returns an error

### ISSUE THREAD

**Issue by exhaler** [microsoft/ApplicationInsights-node.js#846]
I'm using appInsights v2.1.4 in my NodeJs Azure Function.
The app key in provided by the APPINSIGHTS_INSTRUMENTATIONKEY variable in the function configuration.

I have setup a class as such
```js
const appInsights = require('applicationinsights');

class AppInsightsLog {
    error (context, eventName, error) {
        context.log.error(error);

        appInsights.setup().start();
        const client = appInsights.defaultClient;
        client.trackEvent({ name: `Catch error: ${eventName}`, properties: error });
    }

    info (context, eventName, extraInfo = null) {
        context.log.info(eventName);

        appInsights.setup().start();
        const client = appInsights.defaultClient;
        client.trackEvent({ name: `Log info: ${eventName}`, properties: extraInfo });
    }
}

module.exports = { AppInsightsLog };
```

And using it like so

```js
/* ... other imports before it ... */
const { AppInsightsLog } = require('../../../utils/AppInsightsLog');
const appInsightsLog = new AppInsightsLog();

class Post {
    async data (context, feedRow) {
        try {
            ...
            appInsightsLog.info(context, `processing feed: ${feedRow.feedtype}`);
            ....
        } catch (error) {
            appInsightsLog.error(context, 'ProcessRawDataQueue', error);
            return { statusCode: 500, body: error.message };
        }
    }
}
```
I'm getting this error:

> [Error] TypeError: api_1.createContextKey is not a functionat Object.<anonymous> (D:\home\site\wwwroot\node_modules\@opentelemetry\core\build\src\trace\suppress-tracing.js:20:36)at Module._compile (internal/modules/cjs/loader.js:999:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)at Module.load (internal/modules/cjs/loader.js:863:32)at Function.Module._load (internal/modules/cjs/loader.js:708:14)at Module.require (internal/modules/cjs/loader.js:887:19)at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:15:46)at require (internal/modules/cjs/helpers.js:74:18)at Object.<anonymous> (D:\home\site\wwwroot\node_modules\@opentelemetry\core\build\src\baggage\propagation\HttpBaggagePropagator.js:20:28)at Module._compile (internal/modules/cjs/loader.js:999:30)

Any ideas what is wrong?

**Comment by hectorhdzg** [comment]
@exhaler are you using any @azure or @opentelemetry packages as well in your project?, OpenTelemetry packages are currently being used to support automatic tracking of Azure SDK operations, we fixed several issues caused by mismatches of OpenTelemetry packages being used by this SDK and Azure SDKs, please give it a try using latest version for this SDK and other Azure SDKs you may be using.

**Comment by exhaler** [comment]
@hectorhdzg Thank you!! We were using an old version of @azure/storage-blob when I updated it everything worked 👍
