### ISSUE TITLE
Client#trackException is prone to leak PII

### ISSUE THREAD

**Issue by jrieken** [Microsoft/ApplicationInsights-node.js#85]
When encountering exceptions in VS Code we take measures remove any PII, esp. from stack traces. However, [Client#trackException](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Client.ts#L90) counters that effort by throwing new errors in case it doesn't understand the given one and thereby leaking stack traces that include PII.

**Comment by kamilszostak** [comment]
Yes, trackException is checking if an object is of type Error - [Util#isError](https://github.com/Microsoft/ApplicationInsights-node.js/blob/master/Library/Util.ts#L97). 

Do you have any fix in mind? Would adding a `DoNotLogStackTraces` switch to the configuration work? It will disable stack trace logging for the whole project and will be set to `false` by default.

**Comment by kamilszostak** [comment]
Sorry for a delay. I added an option to disable stack trace collection - #110. 
I'll include this change in the v0.15.19 release. 

Sample usage:

    AppInsights.setup("key")
        .setAutoCollectExceptions(true, false)
        .start();

**Comment by kamilszostak** [comment]
It is now possible to process all telemetry data (including exceptions) by adding a **Telemetry Processor** - see #111. 

I'll add this feature in the next release v0.15.19.
