### ISSUE TITLE
Could not find ICACLS in expected location! This is necessary to use disk retry mode on Windows.

### ISSUE THREAD

**Issue by vpetersen** [Microsoft/ApplicationInsights-node.js#852]
We are getting this error when trying to write custom logs to application insights. After some testing, it appears that the variable is case-sensitive. While it's not an issue with the Windows host it appears to be an issue within the code itself. Have anyone seen this behavior? I was also wondering what the scenario was that causes that error to appear. Is it only when it fails to connect successfully to application insights?

ApplicationInsights:Sender [
'Could not find ICACLS in expected location! This is necessary to use disk retry mode on Windows.'
]
ApplicationInsights:Sender [
'Ignoring request to enable disk retry mode. Sufficient file protection capabilities were not detected.'
]

**Comment by hectorhdzg** [comment]
@vpetersen disk retry will basically try to put telemetry in disk whenever Application Insights ingestion endpoint is not available, there is a check to make the file not accessible to other users in the machine, which version of Windows are you using?, SDK is [looking](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Sender.ts#L21) for icacls.exe in system32 folder, is that available in your machine?

**Comment by vpetersen** [comment]
> @vpetersen disk retry will basically try to put telemetry in disk whenever Application Insights ingestion endpoint is not available, there is a check to make the file not accessible to other users in the machine, which version of Windows are you using?, SDK is [looking](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/Sender.ts#L21) for icacls.exe in system32 folder, is that available in your machine?

It's an Azure Function running on a Windows app service plan. The application exists and I can run it through the KUDO console but the SDK is throwing this error.

**Comment by hectorhdzg** [comment]
@vpetersen you should be able to turn disk retry off to avoid noise using [setUseDiskRetryCaching](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/applicationinsights.ts#L329) method, I believe Azure Functions doesn't allow you to persist data to disk so most likely this feature will not work correctly in there, I will follow up with Azure Functions teams to see if this could achieved in different way.

**Comment by vpetersen** [comment]
> @vpetersen you should be able to turn disk retry off to avoid noise using [setUseDiskRetryCaching](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/applicationinsights.ts#L329) method, I believe Azure Functions doesn't allow you to persist data to disk so most likely this feature will not work correctly in there, I will follow up with Azure Functions teams to see if this could achieved in different way.

okay just to confirm, the only time we will see this issue if the sdk is unable to connect to application insights to send the data?
