### ISSUE TITLE
2.1.9 enabled verbose logging globally for azure libraries

### ISSUE THREAD

**Issue by SteveSheldonQ2** [microsoft/ApplicationInsights-node.js#872]
We have a nodejs program that uses @azure/storage-queue in addition to @azure/applicationinsights.   This is all running in a docker container using nodejs 16.  When we upgraded @azure/applicationinsights from 2.1.8 to 2.1.9, we started seeing verbose logging out of @azure/storage-queue package.   When running the docker container locally this is all going to the console, but we also noticed the Data ingestion on our application insights subscription shot from a few megs a day to gigabytes per day.

I dug through the changesets on the applicationinsights project, and noticed the addition of the @azure/logging package, along with this line:
`setLogLevel("verbose"); // Verbose so we can control log level in our side`

Unfortunately setLogLevel seems to also override the environment variable AZURE_LOG_LEVEL.

It's unclear from the code changes, or any documentation if there is a way to change this from applicationinsights settings.   I do not see any reason I would want verbose logging being sent to app insights.

**Comment by FlipABit** [comment]
I can confirm were seeing this in our azure functions as well after deploying 2.1.9. Were getting millions of traces from the node service bus library and the logs are categorized as`Host.Function.Console` with severity level `Information` and every line of every message is an individual log entry (not correlated). We should be able to use the function host setting to at least set the filter that category to a higher level for now
