### ISSUE TITLE
Azure Service Bus dependency messages have no context

### ISSUE THREAD

**Issue by bivas6** [microsoft/ApplicationInsights-node.js#883]
Hi,
We're using AI to track our app, and everything works as expected except service-bus messages.
We have http endpoint which receives a request, then sends a message on the service bus. 
All the logs in this function and http/s requests have the same context in the AI as the incoming http request, but the service-bus outgoing message looks like a stand-alone dependency without a parent and context. 

Should I add something manually to the `ServiceBusClient.send` call? Is it a bug? 
I can give you a small script to reproduce + screenshots from our AI UI.  (edit: code and screenshots attached)

Thanks!

**Comment by orgads** [comment]
@hectorhdzg ping

**Comment by bivas6** [comment]
Code example:

```
const appInsights = require('applicationinsights');
const express = require('express');
const axios = require('axios');
const {ServiceBusClient} = require('@azure/service-bus');
const WebSocket = require('ws');

appInsights.setup()
    .setAutoCollectConsole(true, true)
    .setSendLiveMetrics(true)
    .start();

const connectionString = "******";
const sender = new ServiceBusClient(connectionString, {webSocketOptions: { webSocket: WebSocket }}).createSender('bivas-test');
const app = express();
app.post('/sendMessage', async (_req, res) => {
    console.log('log');
    await axios.default.get('https://google.com');
    console.log('log 2');
    await sender.sendMessages({subject: 'subject', body: {key:'value'}});
    res.sendStatus(200);
});

app.listen(3080, '0.0.0.0', () => {console.log('started')});

```

This is a snippet from Azure portal if I clicked the 'get to Google' dependency:
![image](https://user-images.githubusercontent.com/40261105/149656638-4d1efa9c-c654-4ec3-873f-a76860d4ec54.png)

And this is what I see if I clicked the 'ServiceBus Message' dependency:
![image](https://user-images.githubusercontent.com/40261105/149656673-bc83a20d-13f3-4446-9ea3-0c33eff2d5bc.png)

Thanks.

**Comment by orgads** [comment]
Thank you @hectorhdzg. Do you plan to publish a new release soon?

**Comment by hectorhdzg** [comment]
@orgads we plan to release early next week

**Comment by bivas6** [comment]
Hi @hectorhdzg 

I tried to run the example app from above with your fix in it, and the rest request doesn't hold the service-bus message as dependency, In addition, now the service-bus messages not shown at all in the AI UI.

Can you check it? 

Thanks

cc: @orgads

**Comment by orgads** [comment]
@hectorhdzg 7.4.0

**Comment by hectorhdzg** [comment]
@bivas6, @orgads , I can see everything working fine with exact same code you shared and using @azure/service-bus 7.4.0, validated using a tarball generated from develop branch

![image](https://user-images.githubusercontent.com/39923391/151853023-2d728a5c-80c6-4393-a0f6-a02693ea56fb.png)

**Comment by orgads** [comment]
I just tried again now, and it doesn't work for me.

I tried Node 16.13 and 17.4, both on Windows.

That's what I get:
![image](https://user-images.githubusercontent.com/1246544/151867330-c519035d-6e17-4ad1-999d-eb4217738581.png)

**Comment by hectorhdzg** [comment]
@orgads do you have any OpenTelemetry package as dependency in your project?

**Comment by orgads** [comment]
No. I have only the packages that I `require` directly. What else should I install?

**Comment by orgads** [comment]
hmmm... I tried on Linux now with Node 17.4.0, and it does show the send message request, but it is still not connected to the http request:

![image](https://user-images.githubusercontent.com/1246544/151869797-21428f2c-4feb-493c-b4ab-1753abaa5e52.png)

**Comment by orgads** [comment]
Sorry, these tests on linux were with version 2.2.0. With latest develop it's the same as on Windows (no ServiceBus at all).

This is my package.json (I published my own package from develop):
```json
{
  "name": "servicebus",
  "version": "1.0.0",
  "main": "servicebus.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@azure/service-bus": "^7.4.0",
    "applicationinsights": "npm:@audc/applicationinsights@^2.3.0",
    "axios": "^0.25.0",
    "express": "^4.17.2",
    "ws": "^8.4.2"
  }
}
```

**Comment by orgads** [comment]
@hectorhdzg were you able to reproduce? Can I provide you any more information?

**Comment by hectorhdzg** [comment]
@orgads still no repro on my side, can you try with latest version of Application Insights SDK?, we published yesterday, can you turn logging and share the logs if you still have the problem?
