### ISSUE TITLE
AI events are not transmitted before app ends 

### ISSUE THREAD

**Issue by tschissler** [microsoft/ApplicationInsights-node.js#898]
I have a Node.js console app using the readline-sync which is waiting for user input.
If I track some events in my code, none of them are visible in the portal, only when the execution is completed fully, all of them are transmitted at once.

A simplified version of this problem is shown below. How could I transmit the name when input for the age is waiting for minutes or even hours?

```Javascript
const readline = require('readline-sync');
let appInsights = require("applicationinsights");

appInsights.setup(connectionString).setAutoCollectConsole(true).start(); 
let client = appInsights.defaultClient;
client.trackEvent({name: "my custom event", properties: {myProp: "custom property value 2"}});
client.flush();

var name = readline.question("What is your name? ");
client.trackEvent({name: "name entered", properties: {name: name}});
client.flush();

var age = readline.question("What is your age? ");
client.trackEvent({name: "age entered", properties: {age: age}});
```

**Comment by hectorhdzg** [comment]
@tschissler sorry I don't know how readline-sync works, not sure if this could be fixed in our side, looks like something is preventing the track and flush code to be executed. I would recommend you to provide a callback in flush [method](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/TelemetryClient.ts#L147), so you can block the execution after the telemetry was flushed.

**Comment by tschissler** [comment]
Thank you @hectorhdzg 
That did the trick. My code looks now like this and it works as expected.

```javascript
const readline = require('readline-sync');
let appInsights = require("applicationinsights");

function askName() {
    var name = readline.question("What is your name? ");
    client.trackEvent({name: "name entered", properties: {name: name}});
    client.flush({callback: askAge});
}

function askAge() {
    var age = readline.question("What is your age? ");
    client.trackEvent({name: "age entered", properties: {age: age}});    
}

appInsights.setup(connectionString).setAutoCollectConsole(true).start(); 
let client = appInsights.defaultClient;
client.trackEvent({name: "my custom event", properties: {myProp: "custom property value 2"}});
client.flush({callback: askName});
```
