### ISSUE TITLE
Question: how to access original telemetry event in memory 

### ISSUE THREAD

**Issue by link89** [microsoft/ApplicationInsights-node.js#907]
Hi, would like to use ApplicationInsights to monitor the outbound http(s) requests and keep those telemetry data in memory to analysis at the end of the script so that I can visualize those data to analysis the request/response times, etc.
I have read the document and find that maybe I can use the `appInsights.defaultClient.addTelemetryProcessor` for this purpose, but I am not sure if it is the right way or best way to do as there is few information about this topic in the document. Any suggestion will be appreciated. Thank you!

**Comment by hectorhdzg** [comment]
@link89 that is correct, telemetry processor will expose the telemetry envelope before is sent and it also have HTTP request and response, and error when applicable. You must be able to hook into that and store whatever you need in memory.
