### ISSUE TITLE
Application Insights can't be enabled from Azure Portal on App Service Linux + Node 16

### ISSUE THREAD

**Issue by danmana** [microsoft/ApplicationInsights-node.js#916]
The [Application Insights blade](https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-nodejs?tabs=linux#auto-instrumentation-through-azure-portal) is greyed out in Azure Portal for App Service.

Auto instrumentation should be possible, according to docs it is [GA ready](https://docs.microsoft.com/en-us/azure/azure-monitor/app/codeless-overview).

App Service OS: Linux
App: Node 16 LTS (express)

![image](https://user-images.githubusercontent.com/498419/155320794-81ac13ee-ca47-459a-ab24-4e69dd5a236b.png)

Env Configuration:
* `APPINSIGHTS_INSTRUMENTATIONKEY`
* `APPLICATIONINSIGHTSAGENT_EXTENSION_ENABLED=true`
* `APPLICATIONINSIGHTS_CONNECTION_STRING` - this was not preset by default, but nothing changed if I added it

If I remember correctly when I created the app I was able to add the Application Insights. Now it is disabled. (Also disabled for a newly created app service plan)

**Comment by JasonFreeberg** [comment]
Hi @danmana -- The UX will be enabled next week. 

Node 16 was released on App Service as an "Early Access" stack and was only recently built-in to the platform. Now that's out of Early Access, we're enabling the UX. 

More about Early Access on App Service: https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/early_access.md

**Comment by hectorhdzg** [comment]
Should be enabled now
