### ISSUE TITLE
Support live metrics stream

### ISSUE THREAD

**Issue by ramijarrar** [Microsoft/ApplicationInsights-node.js#92]
https://azure.microsoft.com/en-us/blog/live-metrics-stream/

**Comment by kamilszostak** [comment]
Thanks for opening this issue. Currently Live metrics are only supported for .NET web app SDK. We are looking into enabling it in other SDKs, but there is no timeline for it yet.

I'll keep you posted.

**Comment by stevenfollis** [comment]
Hello, any update or ETA on supporting Live Metrics Stream with Node applications? Thanks!

**Comment by JasonJJFS** [comment]
Hi any update on this, again for NodeJS. Thanks!

**Comment by OsvaldoRosado** [comment]
No update from @KamilSzostak's last reply. There's not yet a timeline for adding Live Metrics to the Node.js SDK.

**Comment by beckylino** [comment]
Thanks everyone for the feedback! If you could take a minute and up vote the user voice requests as well that'd be great :) 
https://feedback.azure.com/forums/357324-application-insights/suggestions/18622672-live-metrics-support-for-node-js

**Comment by benc-uk** [comment]
Hi, Is there any update? I'd heard rumours this was planned and being worked on, but no sign. Thanks!

**Comment by OsvaldoRosado** [comment]
No update beyond what was added in the user voice linked above in June. I've quoted below for convenience.

> The team is looking at the best way to enable this support. More info to come soon.

Please make sure to up vote the user voice linked above if this is important to you!

**Comment by markwolff** [comment]
Hey all, Live metrics support was added in latest version (`1.3.0`). It is currently disabled by default, so you will need to enable it when initializing the SDK with `setSendLiveMetrics(true)`.
