### ISSUE TITLE
Option to write console logs to stdout (while still capturing them)

### ISSUE THREAD

**Issue by devinrhode2** [microsoft/ApplicationInsights-node.js#928]
I'd like to capture console logs/warn/error and send them to ApplicationInsights, but, I'd also like to see those send to stdout like normal.

When simulating production locally, running `next start`, I was getting an error that port 3000 was already in use. But, ApplicationInsights was swallowing this error.

**Comment by devinrhode2** [comment]
Actually, it seems that all my stdout is being swallowed somehow, doing `.setAutoCollectConsole(false, false)` has no effect on the issue.

I am using `next-logger`. It can also capture console.log/warn/error. Seems that ALL the std output is being funneled into AI and it doesn't necessarily forward all the input to stdout.

**Comment by devinrhode2** [comment]
As I'm not sure this is an issue with ApplicationInsights sdk I'll close for now. Turn key integration with pino+next.js would be nice

**Comment by devinrhode2** [comment]
This WAS unrelated to this lib.

It may be interesting to have some option to transparently pipe all stderr/stdout BACK to the terminal, but I think applicationinsights may already be transparently collecting stdout/stderr.

It WOULD definitely be cool to have an option to see everything this lib is sending to azure in real time. The logs would be very excessive in a local terminal, but that's the point, here's EVERYTHING that's being collected and sent.

**Comment by hectorhdzg** [comment]
@devinrhode2  we provide extra internal logging to understand what the SDK is doing using enableInternalDebugLogging in the SDK [config](https://github.com/microsoft/ApplicationInsights-node.js#configuration), if you want to see the actual telemetry that is being sent in the console you could use a [Telemetry Processor](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors) to output the envelope before is sent
