### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by dhensby** [microsoft/ApplicationInsights-node.js#966]
It's a bit concerning to see patch releases like https://github.com/microsoft/ApplicationInsights-node.js/releases/tag/2.3.3 where we have seen the following changes:

👍 #961 - fixing a bug
👎 #960 - changing a method signature in a breaking way
👎 #950 - new feature
👎 #948 - new feature

Does this library intend to follow [semantic versioning](https://semver.org/)? Only one of these changes should be making it into a patch release and one of them should be in a new major version.

Lots of developers, like myself, rely on packages following this convention so we can upgrade packages with some confidence about comparability so it would be really great to see a package like this one follow semver.

**Comment by hectorhdzg** [comment]
@dhensby we try to follow semantic versioning best we can, breaking change is in internal functionality that no one is supposed to be using that is why we didn't consider major version bump, if you are using it we can talk about what you should be using instead, and new features are for Web Snippet injection that is a feature still in preview, 2.4.0 make more sense now that I think about it but this is still a manual process, I'm open to suggestions for some automated way of doing this.

**Comment by dhensby** [comment]
@hectorhdzg thanks for the prompt reply.

I'm not using any of these features that I can see, but I'm in the habit of checking the changelogs when I get a @dependabot PR to update my dependencies and so seeing this kinds of changes feel worrying in a patch release. I hadn't appreciated some of these methods were internal/private - I should have looked into that more before writing up this issue, apologies.

In terms of automating 😅  - that's always the dream, I do my releases manually and they typically involve looking through the changelog / diffs to see what's changed and then make a call on it. I'm sure there would be some way to automate this using some specific commit message format, but that can often be a pain for contributors.

The approach I use (for example in [node-mssql](https://github.com/tediousjs/node-mssql)) is to have a branch for each major version I'm maintaining, you can also do the same for minor versions and PRs then go against the appropriate branch depending on if they are bug fixes or new features - but this can be a bit of maintenance burden as those branches often need "merging up" to keep feature parity across release versions.

I'm happy to accept your judgement on this if you feel these were very low-risk changes and accept I may been overly reactive if that's the case.

**Comment by hectorhdzg** [comment]
Thanks @dhensby for the feedback and suggestions, I will try to improve this process for future releases, I'm thinking about using some kind of label in the PR to quickly identify features and bugs, prefer that instead of branches, as merging could get messy, also classify them in the release notes would be useful as well, we are doing big refactoring for next major version that hopefully will take care of internal stuff that people should not be using directly.
