### ISSUE TITLE
Application Insights request logs are not found with 2.3.3

### ISSUE THREAD

**Issue by varungbt** [microsoft/ApplicationInsights-node.js#970]
Request logs are not being pushed using the latest applicationinsights@2.3.3. 

We have the standard initialization logic and see a successful response of type `Configuration` after initialization.
However, the request log generation has stopped working with this version.

Can you pls share details if there is a known issue?
```

package.json
    "applicationinsights": "2.3.3",
    "applicationinsights-native-metrics": "0.0.7",
```

```
    appinsights.setup(AzureConfig.AI_INSTRUMENTATION_KEY)
       .setAutoDependencyCorrelation(true)
       .setAutoCollectRequests(true)
       .setAutoCollectPerformance(true, true)
       .setAutoCollectExceptions(true)
       .setAutoCollectDependencies(true)
       .setAutoCollectConsole(true)
       .setUseDiskRetryCaching(true, 30 * 1000, 104857600)
       .setDistributedTracingMode(appinsights.DistributedTracingModes.AI_AND_W3C);

     appinsights.defaultClient.context.tags[
        appinsights.defaultClient.context.keys.cloudRole] = 'dms';

     appinsights.start();
```

**Comment by hectorhdzg** [comment]
@varungbt can you double check applicationinsights is loaded first before native http modules? more info (here)[https://github.com/microsoft/ApplicationInsights-node.js#basic-usage]

**Comment by varungbt** [comment]
@hectorhdzg  thanks and I was able to fix this. We recently had introduced other imports and this resulted in appinsights telemetry loss

**Comment by hectorhdzg** [comment]
Closing this one, let us know if you any other issue
