### ISSUE TITLE
How to ensure PII doesn't make it into logs?

### ISSUE THREAD

**Issue by dfberry** [microsoft/ApplicationInsights-node.js#975]
There is probably a doc somewhere that discusses how to ensure PII isn't captured in logs but I can't find the doc. Is it linked in the package readme? 

FYI - @diberry

**Comment by hectorhdzg** [comment]
@dfberry can you elaborate on which PII data are you worried about?, you should be able to update the telemetry envelope and drop or update specific fields using telemetry processors more info [here](https://github.com/microsoft/ApplicationInsights-node.js#preprocess-data-with-telemetry-processors)

**Comment by dfberry** [comment]
@hectorhdzg Is there a processor already created, maintained, and provided to remove PII or do you mean I have to create it?

**Comment by hectorhdzg** [comment]
@dfberry closing this issue because like I mentioned before the SDK doesn't generate PII automatically, let us know if you have more questions.
