### ISSUE TITLE
Changes in bunyan error reporting causes traces loss

### ISSUE THREAD

**Issue by r0tc** [microsoft/ApplicationInsights-node.js#978]
Few months ago I encountered problem with bunyan and traces/exceptions reporting #914, thank you for fixing the issue.
Now I try to move to recent lib version after the fix, but I'm not able due to changes introduced. Let's consider log like 
`log.error({ err, otherProperty: value },  "Some error message...");`
In version 2.1.8 `otherProperty` will be logged to `traces` together with error and message. In recent version, the error will be reported as `exception` but there is no trace of `otherProperty` neither in exceptions or traces. That's due to [returning](https://github.com/microsoft/ApplicationInsights-node.js/blob/c4a613579eb54be3518368d499d066ed0343b180/AutoCollection/diagnostic-channel/bunyan.sub.ts#L34) after identifying the log contains error and reporting it as exception. Can you modify the behavior to also report errors as traces, so in my case I don't lose other important properties? Or add a flag so it can be optionally enabled?

**Comment by JacksonWeber** [comment]
Hi @r0tc, I'm wondering if you could give me some insight into the scenario for including other properties you want to have output as traces in your Bunyan error logging is. Thanks!

**Comment by r0tc** [comment]
hey @JacksonWeber , I don't work anymore on the project where I encountered this scenario and forgot the details, sorry.

**Comment by JacksonWeber** [comment]
Ok. Closing as the change is being made as a part of another issue. Thank you for letting me know!
