### ISSUE TITLE
How do I connect server requests and background jobs?

### ISSUE THREAD

**Issue by Burgov** [microsoft/ApplicationInsights-node.js#983]
I'm trying to achieve something like in this screenshot:

![image](https://user-images.githubusercontent.com/417674/175253628-8afc58d8-dfcb-4c42-b589-727e356fcc10.png)

So there is one request, and it triggers two background jobs.

What I've tried to far is when I create the job, I set the operation Id in the job's data like this:

```typescript
appInsights.getCorrelationContext()?.operation?.id
```

Then then in the processor I create a new contact using that operation Id as such:

```typescript
    const ctx = CorrelationContextManager.generateContextObject(job.data.correlationId);

    const wrap = appInsights.wrapWithCorrelationContext(async () => {
      const time = new Date();

      try {
        await callback();

        appInsights.defaultClient?.trackRequest({
          name: `Queue: ${job.queue.name}, Name: ${job.name}, ID: ${job.id}`,
          duration: new Date().getTime() - time.getTime(),
          time,
          success: true,
          resultCode: 200,
          properties: { data: job.data },
          url: '',
        });
      } catch (e) {
        appInsights.defaultClient?.trackRequest({
          name: `Queue: ${job.queue.name}, Name: ${job.name}, ID: ${job.id}`,
          duration: new Date().getTime() - time.getTime(),
          time,
          properties: { data: job.data },
          success: false,
          resultCode: 500,
          url: '',
        });

        throw e;
      }
    }, ctx);

    await wrap();
  }
```

But while the requests now do all show up in one pane, the dependencies are not organized by request, and it looks like one big mess:

![Screenshot 2022-06-23 at 10 37 09](https://user-images.githubusercontent.com/417674/175255720-f9c7d362-dca5-49a4-83c5-c4607acececc.png)

What can I do to make all the requests/jobs and their dependencies appear like in the first screenshot?

**Comment by johnib** [comment]
In general this is the structure/hierarchy:

All `requests` under the same `operation_Id` would be visible in the spans view that you showed:

```
- request 1
- request 2
- request 3
```

For a single `request`, `dependency` calls are associated and grouped, if the `request.id` equals the `dependency.operation_ParentId` (i.e. the `id` column of the `request` event equals the `operation_ParentId` of the `dependency` event)

You'd be able to validate that this condition doesn't hold true in your case by looking up the logs with a query similar to this:

```
union requests, dependencies
| where operation_Id == "<the operation ID>"
| project itemType, operation_Id, operation_ParentId, id
```

Next, to your background jobs:
- I assume they are not being tracked automatically, you are probably using the `StartOperation` function
- In that case, you should initialize it with the `traceparent` header being sent by the caller.
