### ISSUE TITLE
trackDependency not send duration

### ISSUE THREAD

**Issue by davidmssantander** [microsoft/ApplicationInsights-node.js#984]
Hello, I am using the following method.

client.trackDependency({target:"http://dbname", name:"select customers proc", data:"SELECT * FROM Customers", duration:231, resultCode:0, success: true, dependencyTypeName: "ZSQL"});

But in application insight it appears empty in the duration field.

![image](https://user-images.githubusercontent.com/105428595/175289742-74e742a7-2f13-4814-a78a-1d2f40e87979.png)

Can you review it?

I am use the last version to sdh 2.3.3.

regards

**Comment by Burgov** [comment]
you'll have to keep track of the duration yourself. AI has no way of knowing how long it too.

something like:

```typescript
const t = new Date();

await dependency();

client.trackDependency({duration: new Date().getTime() - t.getTime(), target:"http://dbname/", name:"select customers proc", data:"SELECT * FROM Customers", duration:231, resultCode:0, success: true, dependencyTypeName: "ZSQL"});
```

**Comment by davidmssantander** [comment]
Yes, we do that, what I mean is that we send the value, but in applicationInsights it always shows zero.

**Comment by hectorhdzg** [comment]
Can you double check an actual duration is being sent? code you shared is generating dependency with duration for me

![image](https://user-images.githubusercontent.com/39923391/177651663-fa180f8b-c443-44f6-a0df-0457c2dbe19e.png)

**Comment by hectorhdzg** [comment]
Closing as this is apparently not an issue, please create a new issue with more details if you are still having problems.
