### ISSUE TITLE
Log full transaction on failed request with sampling enabled

### ISSUE THREAD

**Issue by krystianolech** [microsoft/ApplicationInsights-node.js#990]
Hi,
I try to implement an approach where logging sampling is enabled but in case of failer, the whole request is logged.
Normally when I set sampling and request will be "nominated" to be skipped, then I will not get all logs even when the transaction had an error. 
To overcome that I added a custom telemetry processor that is ensuring a log is sent when a request fails. This however affects only root requests, but it does not work on related logs like traces, dependencies, etc. 

As telemetry processors are providing a synchronous response at the time when the log is triggered (so it might be before the end of the transaction) it is impossible to determine if the request will eventually fail or succeed. 

Is there any way to achieve that (ensuring all tansaction logs are stored  in case of failed root request with request sampling enabled)?

**Comment by hectorhdzg** [comment]
@krystianolech unfortunately we do not support that in the SDK, like you mentioned the root request could fail once all the other telemetry was already generated, we sample using a hash of the operationId that is used to identify the distributed trace, so when a request is sampled all the telemetry associated will be sampled as well, in your case with your telemetry processor your failed request could include the entire trace in some cases but not all the time.

**Comment by LitalReuveni** [comment]
@hectorhdzg Is it possible / there are plans to extend the SDK so it would support this scenario?

**Comment by hectorhdzg** [comment]
@LitalReuveni we are not adding support for full transaction logging for failed requests when sampling is enabled, that will require big changes on how the sampling works in this SDK and will add extra overhead of keeping failed requests trace ID information.
